= Field Level Encryption from the Java SDK
:page-topic-type: concept

[abstract]
Field Level Encryption is available in Couchbase Data Platform 5.5, from Java SDK version 2.6.0

[#package]
== Packaging

The Couchbase Java SDK uses the https://github.com/couchbase/java-couchbase-encryption[java-couchbase-encryption^] library to provide support for encryption and decryption of JSON fields.

The Couchbase Java Field Level Encryption (FLE) uses entity annotations/`JsonObject` methods to specify which field(s) to apply encryption and which algorithm to use.
Here’s an example POJO entity definition:

[source,java]
----
public static class Person {

    @Id
    public String id;

    @EncryptedField(provider = "AES")
    public String password;

    //The rest will be transported and stored unencrypted
    public String firstName;
    public String lastName;
    public String userName;
    public int age;
  }
----

[#encryption_configuration]
== Configuration

Create a configuration to connect to your Couchbase cluster and configure the crypto manager in the Couchbase environment with the encryption crypto algorithm and key store providers.

NOTE: The alias used for registering the provider should match the provider name string in the annotation/parameter.

[source,java]
----
JceksKeyStoreProvider kp = new JceksKeyStoreProvider("secret");
kp.storeKey("SecretKey", "mysecretkey".getBytes());
kp.storeKey("HMACsecret", "myauthsecret".getBytes());
kp.publicKeyName("secret_key");
kp.signingKeyName("hmac_key");
AES256CryptoProvider aes256CryptoProvider = new AES256CryptoProvider(kp);
CryptoManager cryptoManager = new CryptoManager();
cryptoManager.registerProvider("AES", aes256CryptoProvider);
CouchbaseEnvironment environment = DefaultCouchbaseEnvironment.builder().cryptoManager(cryptoManager).build();
----

To apply encryption to a repository entity, use the `EncryptedField` annotation with provider name as registered on the crypto manager.

[source,java]
----
@EncryptedField(provider = "AES")
public String password;
----

Encryption can also be applied to JsonObjects.

[source,java]
----
JsonObject.create().putAndEncrypt("foo", "bar", "AES");
----

[#decryption]
== Decryption

Encrypted fields in entities are decrypted based on the annotations.
To decrypt use fields in `JsonObject`, use `getAndDecrypt` methods.

[source,java]
----
JsonDocument stored = bucket.get("mydoc");
stored.content().getAndDecrypt("foo", "AES")
----
