= Failure Considerations for the Java SDK in Couchbase
:navtitle: Failure Considerations
:page-aliases: concept-docs:durability-replication-failure-considerations.adoc

include::6.0@sdk:shared:partial$env-errors.adoc[tag=failover_definition]

include::6.0@sdk:shared:partial$env-errors.adoc[tag=what_to_expect_in_application]

include::6.0@sdk:shared:partial$env-errors.adoc[tag=what_to_expect_during_failover]

include::6.0@sdk:shared:partial$env-errors.adoc[tag=missing-nodes]

include::6.0@sdk:shared:partial$env-errors.adoc[tag=timeouts]

include::6.0@sdk:shared:partial$env-errors.adoc[tag=network_failures]

[#devguide-replica-read]
== Reading from replicas

High-availability applications can read documents from replicas, exchanging consistency for availability.

If your bucket is configured for replication, then multiple replicas of each item exist within the cluster.
By default the client will attempt to access an item using its computed master or active node.
This returns the current and authoritative version of the item as it is stored within Couchbase.

In conditions where access to the active node is unavailable (for example, it is disconnected from the network), an application may be able to access a replica version of the item using the _get-from-replica_ operation which queries a replica node for a copy of the item.

NOTE: The item received from a replica node may be an older version.
It is possible a newer version exists in the active node, but did not manage to get replicated before the active node went offline.

[source,java]
----
static JsonDocument getOrGetReplica(Bucket bucket, String docId) {
  try {
    return bucket.get(docId);
  } catch (CouchbaseException e) {
    Iterator<JsonDocument> docs = bucket.getFromReplica(docId);
    return docs.hasNext() ? docs.next() : null;
  }
}
----

Note also the method `TransparentReplicaGetHelper.getFirstPrimaryOrReplica()`.
Currently experimental, this method comes in several overloaded flavors, which allow specification of timeouts, document-types, and more.
See the API for details.
A simple usage is as follows:

[source,java]
----
JsonDocument doc = new TransparentReplicaGetHelper()
  .getFirstPrimaryOrReplica(docId, JsonDocument.class, bucket)
  .toBlocking()
  .value();
----
