= Managing clusters using the Java SDK with Couchbase Server
:navtitle: Managing Clusters

include::5.1@sdk:shared:partial$flush-info-pars.adoc[tag=management-intro]

The Java SDK also comes with some convenience functionality for common Couchbase management requests.

Management operations in the Java SDK may be performed through several interfaces depending on the object:

* [.api]`ClusterManager` class (obtained via [.api]`Cluster#clusterManager(string, string)` with the administrative username and password).
* [.api]`BucketManager` class (obtained via [.api]`Bucket#bucketManager()`).

== Getting Information About the Cluster

When you call `ClusterManager#info()` it returns a `ClusterInfo` object that contains both raw and typed information on the overall cluster state.
In addition to the `ClusterInfo#raw()` method that provides direct access to everything returned by the server, the following methods are available:

* To find out the minimum version of all nodes in the cluster, you can use the `ClusterInfo#getMinVersion()` method.
For example, if you have 3 nodes running version 3.1 and one running version 3.0.3, it reports version 3.0.3.
* If you want to check if a certain feature is enabled on the cluster, you can use the `checkAvailable` method and pass in one of the``CouchbaseFeature`` enumerations.
It uses the minimum cluster version as a basis and then asserts it against the minimum version of the passed in feature.
The SDK uses this internally to determine if specific integration tests can be executed against the connected cluster, and so can you.
* The `getAllVersions` method returns the version number of all nodes in the cluster.

== Creating and Removing Buckets

The [.api]`ClusterManager` class may be used to create and delete buckets from the Couchbase cluster.
It is instantiated through the [.api]``Cluster``'s [.api]`clusterManager` method, providing the administrative username and password.

----
Cluster cluster = CouchbaseCluster.create("127.0.0.1");
ClusterManager clusterManager = cluster.clusterManager("Administrator", "123456");
----

To create a bucket, use the [.api]`ClusterManager#insertBucket(BucketSettings)` method.
The [.api]`BucketSettings` can be created via a builder, [.api]`DefaultBucketSettings.builder()`.
This class is also used to expose information about an existing bucket ([.api]`ClusterManager#getBucket(string)`) or to update an existing bucket ([.api]`ClusterManager#updateBucket(BucketSettings)`).

include::5.1@sdk:shared:partial$flush-info-pars.adoc[tag=update-bucket-warning]

Only [.param]`name` and [.param]`type` parameters are mandatory for the [.api]`BucketSettings`.
Here is the list of parameters available:

* [.param]`name`: The name of the bucket (mandatory to create one, cannot be updated).
* [.param]`type`: The type of the bucket (mandatory to create one, cannot be changed).
Defaults to `BucketType.COUCHBASE`, but can also be `BucketType.MEMCACHED` to create a cache bucket.
* [.param]`quota`: How much memory should each node use for the bucket.
This number is specified in megabytes.
* [.param]`password`: If specified, makes this bucket password protected, forcing future connects (using the [.api]`Bucket`) class to specify the [.param]`password` parameter.
* [.param]`enableFlush`: Enables the [.api]`BucketManager#flush()` operation to be performed on this bucket (see the <<flushing>> section below).
* [.param]`replicas`: The number of replicas to use for the bucket.
* [.param]`indexReplicas`: Wether or not to replicate indexes.
* [.param]`port`: The optional proxy port.

The following example updates an existing "hello" bucket (notice how all parameters are set):

----
BucketSettings bucketSettings = new DefaultBucketSettings.Builder()
    .type(BucketType.COUCHBASE)
    .name("hello")
    .password("")
    .quota(120) // megabytes
    .replicas(1)
    .indexReplicas(true)
    .enableFlush(true)
    .build();

manager.updateBucket(bucketSettings);
----

Once you no longer need to use the bucket, you may delete the bucket using the [.api]`ClusterManager#removeBucket(string)` method:

----
clusterManager.removeBucket("new_bucket");
----

[#flushing]
== Flushing Buckets

include::5.1@sdk:shared:partial$flush-info-pars.adoc[tag=flush-intro]

You may flush a bucket in the Java SDK by using the [.api]`BucketManager#flush()` method:

----
bucket.bucketManager().flush()
----

The [.api]`flush` operation may fail if the bucket does not have flush enabled:

....
com.couchbase.client.java.error.FlushDisabledException: Flush is disabled for this bucket.
    at com.couchbase.client.java.bucket.BucketFlusher$6.call(BucketFlusher.java:145)
    at com.couchbase.client.java.bucket.BucketFlusher$6.call(BucketFlusher.java:140)
    ...
....

== N1QL Index Management

include::5.1@sdk:shared:partial$flush-info-pars.adoc[tag=index-management]

You can manage indexes in the Java SDK using the [.api]`BucketManager` class, with its various N1QL related methods: [.api]`listN1qlIndexes()`, [.api]`+createN1qlIndex(...)+`, etc\...

The following example creates a N1QL secondary index named "fooBar" on the "test" bucket, indexing fields "foo" and "bar":

----
//shortcut for the purpose of this snippet only
BucketManager testManager = CouchbaseCluster.open("127.0.0.1").openBucket("test").bucketManager();

boolean ignoreIfExists = true; // if index exists, don't throw exception
boolean defer = false; // create the index immediately
testManager.createN1qlIndex("fooBar", ignoreIfExists, defer, "foo", "bar");
----

== View Management

include::5.1@sdk:shared:partial$flush-info-pars.adoc[tag=view-management]

In the Java SDK, design documents are represented by the `DesignDocument` class and `View` interface.
All operations on design documents are performed on a `BucketManager` instance.
Use the `DefaultView.create()` factory method to create a [.api]`View`.

To inspect design documents, you can either retrieve them by name (`bucketManager.getDesignDocument("landmarks")`) or iterate through a list of documents (`bucketManager.getDesignDocuments();`).

To create or update design documents, use the [.api]`insertDesignDocument(DesignDocument)` and [.api]`upsertDesignDocument(DesignDocument)` methods.
You can also publish a design document that is in development mode (that is, running only on a small fraction of the documents) to production mode by using the [.api]`publishDesignDocument(string)` method.

When you initialize the design document, you can also specify how often to trigger indexing on documents and replicas.
The following table lists the available options:

.`DesignDocument.create()` method `options` parameter
|===
| Option | Description

| `UPDATE_MIN_CHANGES`
| The minimum changes to perform on a design document before indexing is triggered.

| `REPLICA_UPDATE_MIN_CHANGES`
| The minimum changes to perform on a design document before replica indexing is triggered.
|===

The following example inserts a design document with two regular views and one spatial view into a bucket named `travel-sample`:

----
//shortcut for the purpose of this snippet only
BucketManager bucketManager = CouchbaseCluster.open("127.0.0.1").openBucket("travel-sample").bucketManager();

// Initialize design document
DesignDocument designDoc = DesignDocument.create(
    "landmarks",
    Arrays.asList(
        DefaultView.create("by_country",
            "function (doc, meta) { if (doc.type == 'landmark') { emit([doc.country, doc.city], null); } }"),
        DefaultView.create("by_activity",
            "function (doc, meta) { if (doc.type == 'landmark') { emit(doc.activity, null); } }",
            "_count"),
        SpatialView.create("by_coordinates",
            "function (doc, meta) { if (doc.type == 'landmark') { emit([doc.geo.lon, doc.geo.lat], null); } }")
    )
);
// Insert design document into the bucket
bucketManager.insertDesignDocument(designDoc);
----

include::5.1@sdk:shared:partial$flush-info-pars.adoc[tag=one-view-update-warning]

----
//(note: obtaining the bucketManager is omitted in this snippet)
// Get design document to be updated
DesignDocument designDoc = bucketManager.getDesignDocument("landmarks");

// Update the "by_country" view, adding a reduce
designDoc.views().add(
    DefaultView.create("by_country", //reuse same name
        "function (doc, meta) { if (doc.type == 'landmark') { emit([doc.country, doc.city], null); } }", //same map function
        "_count" //added reduce function
        )
    );

// Resend to server
bucketManager.upsertDesignDocument(designDoc);
----

To remove a design document from a bucket, pass its name to the `removeDesignDocument` method.
