= Couchbase Java SDK Release Notes and Archives
:navtitle: Release Notes
:page-aliases: relnotes-java-sdk,release-notes,download-links,project-docs:migrating-sdk-code-to-3.n,project-docs:sdk-release-notes

// tag::latest[]
== Installation

At least Java 7 is required for current releases; all newer, vendor supported Java versions are supported (and encouraged), up to and including java 11. 
See the xref:compatibility-versions-features.adoc[Compatibility] section for details.
Java 11 is recommended which has various enhancements like lambda local variable type inference, profiling tools and updated security features, starting from the release 2.7.2. For older releases, Java 8 is recommended. 

Version 2.6 and earlier support Java 6, though some transitive dependencies are no longer supported by those projects and have known security issues.

All stable releases of the Java SDK are primarily distributed through Maven. 
As a result the dependency can be included easily using your favorite package manager. For Maven itself, the current GA release's coordinates are:

[source,xml]
----
 <dependencies>
   <dependency>
     <groupId>com.couchbase.client</groupId>
     <artifactId>java-client</artifactId>
     <version>2.7.13</version>
   </dependency>
 </dependencies>
----

The java-client dependency will pull in two more transitive dependencies. One is called com.couchbase.client.core-io and is an internal dependency which performs all the underlying tasks like IO and cluster management. 
The other dependency is RxJava which is both used internally and exposed as a first-class API to the user in order to perform scalable and performant asynchronous, reactive operations.

== Version 2.7.13 (3rd March 2020)

Version 2.7.13 is the forteenth release of the 2.7 series, bringing bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.7.13/Couchbase-Java-Client-2.7.13.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.7.13/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.7.13/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.7.13**
* com.couchbase.client:**core-io:1.7.13**
* io.reactivex:**rxjava:1.3.8**
* io.opentracing:**opentracing-api:0.31.0**

=== Enhancements & New Features

* http://issues.couchbase.com/browse/JCBC-1594[JCBC-1594]: 
To provide better compatibility with cluster upgrades and with query prepared statements on Couchbase Server 6.5 and later, 
the SDK now transparently retries the 4040 reponse code in a similar way to with related error codes.

== Version 2.7.12 (4th February 2020)

Version 2.7.12 is the thirteenth release of the 2.7 series.

http://packages.couchbase.com/clients/java/2.7.12/Couchbase-Java-Client-2.7.12.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.7.12/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.7.12/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.7.12**
* com.couchbase.client:**core-io:1.7.12**
* io.reactivex:**rxjava:1.3.8**
* io.opentracing:**opentracing-api:0.31.0**

=== Enhancements & New Features

* http://issues.couchbase.com/browse/JCBC-1544[JCBC-1544]: 
Allow doc annotiations in meta-annotations.
* http://issues.couchbase.com/browse/JCBC-1574[JCBC-1574]: 
Add support for JsonObject/Array.put(String,Object) on Map or List.

=== Bug Fixes

* http://issues.couchbase.com/browse/JVMCBC-806[JVMCBC-806]: 
Fix an issue where hostname validation (introduced in 2.7.11) was not working correctly because hostname and port are not passed down to the SSL engine.
* http://issues.couchbase.com/browse/JVMCBC-807[JVMCBC-807]: 
Hostnames are now re-resolved on each socket connect attempt to catch DNS resolution changes from the hostname to another IP address.

== Version 2.7.11 (4th December 2019)

Version 2.7.11 is the twelfth release of the 2.7 series.

http://packages.couchbase.com/clients/java/2.7.11/Couchbase-Java-Client-2.7.11.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.7.11/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.7.11/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.7.11**
* com.couchbase.client:**core-io:1.7.11**
* io.reactivex:**rxjava:1.3.8**
* io.opentracing:**opentracing-api:0.31.0**

=== Enhancements & New Features

* http://issues.couchbase.com/browse/JVMCBC-759[JVMCBC-759]: 
Add support for optional TLS hostname verification if enabled on the `CouchbaseEnvironment`.
* http://issues.couchbase.com/browse/JVMCBC-780[JVMCBC-780]: 
Update the shaded jackson JSON dependency to 2.10.1.

== Version 2.7.10 (8th November 2019)

Version 2.7.10 is the eleventh release of the 2.7 series.

http://packages.couchbase.com/clients/java/2.7.10/Couchbase-Java-Client-2.7.10.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.7.10/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.7.10/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.7.10**
* com.couchbase.client:**core-io:1.7.10**
* io.reactivex:**rxjava:1.3.8**
* io.opentracing:**opentracing-api:0.31.0**

=== Enhancements & New Features

* http://issues.couchbase.com/browse/JVMCBC-756[JVMCBC-756]: 
Sent request queue warning over quota is now logged at WARN level.

=== Bug Fixes

* http://issues.couchbase.com/browse/JVMCBC-748[JVMCBC-748]: 
When the seed nodes are updated in the configuration manager, it should only include KeyValue nodes so that on subsequent bucket open attempts only the correct nodes are used for bootstrapping.
* Updated internal dependencies Disruptor (3.4.2) and Jackson (2.9.10.1) to their latest versions.

== Version 2.7.9 (6th August 2019)

Version 2.7.9 is the tenth release of the 2.7 series.
Note that this release is identical to the previous 2.7.8 release, but there had been a glitch with Maven Central publishing, so 2.7.8 is not downloadable through Maven.

http://packages.couchbase.com/clients/java/2.7.9/Couchbase-Java-Client-2.7.9.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.7.9/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.7.9/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.7.9**
* com.couchbase.client:**core-io:1.7.9**
* io.reactivex:**rxjava:1.3.8**
* io.opentracing:**opentracing-api:0.31.0**

== Version 2.7.8 (6th August 2019)

Version 2.7.8 is the ninth release of the 2.7 series, bringing bugfixes over the last stable release. 

http://packages.couchbase.com/clients/java/2.7.8/Couchbase-Java-Client-2.7.8.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.7.8/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.7.8/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.7.8**
* com.couchbase.client:**core-io:1.7.8**
* io.reactivex:**rxjava:1.3.8**
* io.opentracing:**opentracing-api:0.31.0**

**Please note**: You cannot use this version through Maven because of an upload glitch, please use the - otherwise identical - 2.7.9 version for this instead.

=== Enhancements & New Features

* http://issues.couchbase.com/browse/JCBC-1387[JCBC-1387]: 
It is now possible to select ephemeral ejection methods on the bucket manager, so ephemeral buckets can be created via the API.

=== Bug Fixes

* http://issues.couchbase.com/browse/JVMCBC-714[JVMCBC-714], http://issues.couchbase.com/browse/JVMCBC-713[JVMCBC-713], http://issues.couchbase.com/browse/JVMCBC-712[JVMCBC-712]:
Multiple regressions from 2.7.7 have been addressed, including timing out when opening multiple buckets at the same time.
* http://issues.couchbase.com/browse/JVMCBC-720[JVMCBC-720]: 
The repackaged Jackson dependency has been bumped to 2.9.9.3 to fix reported CVEs against it.
* http://issues.couchbase.com/browse/JVMCBC-687[JVMCBC-687]: 
An issue has been resolved which prevent the `ping` operation against the analytics service to succeed.
* http://issues.couchbase.com/browse/JVMCBC-715[JVMCBC-715]: 
The (continuous) keepalive operation against the analytics service now works properly again and is not reporting exceptions when executed.
* http://issues.couchbase.com/browse/JCBC-1381[JCBC-1381]: 
The client now properly closes the trace span of a `subdoc_mutate` op which will make it show up in the slowlog tracer or any externally attached tracer.

== Version 2.7.7 (6th June 2019)

*PLEASE NOTE*: 2.7.7 has known issues which have been addressed in 2.7.9. We recommend upgrading straight to 2.7.9 or later.

Version 2.7.7 is the eighth release of the 2.7 series, bringing bugfixes over the last stable release. 

http://packages.couchbase.com/clients/java/2.7.7/Couchbase-Java-Client-2.7.7.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.7.7/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.7.7/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.7.7**
* com.couchbase.client:**core-io:1.7.7**
* io.reactivex:**rxjava:1.3.8**
* io.opentracing:**opentracing-api:0.31.0**

=== Known Issues

* http://issues.couchbase.com/browse/JVMCBC-714[JVMCBC-714], http://issues.couchbase.com/browse/JVMCBC-713[JVMCBC-713], http://issues.couchbase.com/browse/JVMCBC-712[JVMCBC-712]:
The changes to not eagerly resolve network addresses has led to a regression that has been addressed in 2.7.8. Please go straight to this version.

=== Bug Fixes

* http://issues.couchbase.com/browse/JVMCBC-654[JVMCBC-654]: 
The Java SDK no longer eagerly resolves network addresses when parsing the cluster configuration. 
This makes sure that a setup works where the client SDK runs outside of Kubernetes, and the cluster inside (utilizing the "alternate address" feature of the cluster).
* http://issues.couchbase.com/browse/JVMCBC-677[JVMCBC-677]: 
Fixed a "division by 0" error in the core layer. 
Note, this only happened during shutdown, and was not perceived to have an impact on actual operations.

== Version 2.7.6 (21 May 2019)

Version 2.7.6 is the seventh release of the 2.7 series, bringing bugfixes over the last stable release. 

http://packages.couchbase.com/clients/java/2.7.6/Couchbase-Java-Client-2.7.6.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.7.6/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.7.6/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.7.6**
* com.couchbase.client:**core-io:1.7.6**
* io.reactivex:**rxjava:1.3.8**
* io.opentracing:**opentracing-api:0.31.0**

Note that 2.7.6 release is identical with 2.7.5, but there had been a glitch with maven central publishing, so 2.7.5 is not downloadable through maven. 
As a result, if you are using the jars from 2.7.5 directly it's fine, but if you want to grab it through maven you need to point the dependency to 2.7.6.

== Version 2.7.5 (17 May 2019)

Version 2.7.5 is the sixth release of the 2.7 series, bringing bugfixes over the last stable release. 

http://packages.couchbase.com/clients/java/2.7.5/Couchbase-Java-Client-2.7.5.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.7.5/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.7.5/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.7.5**
* com.couchbase.client:**core-io:1.7.5**
* io.reactivex:**rxjava:1.3.8**
* io.opentracing:**opentracing-api:0.31.0**

**Please note**: You cannot use this version through maven because of an upload glitch, please use the - otherwise identical - 2.7.6 version for this instead.

=== Bug Fixes

* http://issues.couchbase.com/browse/JVMCBC-657[JVMCBC-657]: 
Even when booted through HTTP, if a couchbase bucket is used the client now switches to the more efficient carrier publication mechanisms for config updates. 
This fixes a couple of issues associated with HTTP streaming connections when bootstrapping from non-kv nodes.
* http://issues.couchbase.com/browse/JVMCBC-656[JVMCBC-656]: 
When HTTP streaming must be used, it only falls back to the verbose config if the terse one returned with a 404, not on any error as before.
* http://issues.couchbase.com/browse/JCBC-1333[JCBC-1333]: 
Reflection triggered NoClassDefFoundError for CryptoManager. This has been resolved by inverting the dependencies. 
If you are using field level encryption, please upgrade to the 2.0 version there as well.
* http://issues.couchbase.com/browse/JCBC-1323[JCBC-1323]: 
A bug has been fixed where the Search engine returned an empty error block and as a result parsing would fail. 
The SDK is now more reslient to such a situation.
* http://issues.couchbase.com/browse/JVMCBC-656[JVMCBC-662]: 
As a precautionary defensive mechanism, internal KV ErrorMap parsing now is more resilient to unknown enum values.

== Version 2.7.4 (26 February 2019)

Version 2.7.4 is the fifth release of the 2.7 series, bringing new features, enhancements, and bugfixes over the last stable release. 

http://packages.couchbase.com/clients/java/2.7.4/Couchbase-Java-Client-2.7.4.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.7.4/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.7.4/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.7.4**
* com.couchbase.client:**core-io:1.7.4**
* io.reactivex:**rxjava:1.3.8**
* io.opentracing:**opentracing-api:0.31.0**

=== Bug Fixes

* http://issues.couchbase.com/browse/JCBC-1292[JCBC-1292]: 
A previous OSGi bundle change pulled core packages into the Java Client's jar.
This led to class path failures for the technologies which inspect classes (for example Spring Boot) and a bloated jar.
Now, only the Java Client packages for OSGi specific manifest generation are exported, and behaviour and jar size are back to expected.
* http://issues.couchbase.com/browse/JVMCBC-632[JVMCBC-632]: 
Export only core-io's package for the OSGi specific manifest generation.

== Version 2.7.3 (6 February 2019)

Version 2.7.3 is the fourth release of the 2.7 series, bringing new features, enhancements, and bugfixes over the last stable release. 

http://packages.couchbase.com/clients/java/2.7.3/Couchbase-Java-Client-2.7.3.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.7.3/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.7.3/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.7.3**
* com.couchbase.client:**core-io:1.7.3**
* io.reactivex:**rxjava:1.3.8**
* io.opentracing:**opentracing-api:0.31.0**

=== Enhancements & New Features

* http://issues.couchbase.com/browse/JCBC-1287[JCBC-1287], http://issues.couchbase.com/browse/JVMCBC-621[JVMCBC-621]: 
Added query statement information tag on the tracing spans, which could be useful while debugging.
* http://issues.couchbase.com/browse/JCBC-1239[JCBC-1239]: 
Optimized queue pop operation to use subdocument operation instead of full document operation. 
* http://issues.couchbase.com/browse/JCBC-1288[JCBC-1288]:  
Added a workaround for missing proxyPort parameter that may be removed in next server version. 
__This change may be a temporary one for internal use__.
* http://issues.couchbase.com/browse/JCBC-1276[JCBC-1276]: 
Core changes to redo DNS lookups on every new connection call -- if enabled through system property `com.couchbase.forceDnsLookupOnReconnect`. 
This is useful in containerized environments.


== Version 2.7.2 (5 December 2018)

Version 2.7.2 is the third release of the 2.7 series, bringing new features, enhancements, and bugfixes over the last stable release. 
As of this release, OpenJDK 11 and Oracle JDK 11 with HotSpot JVM is supported. 
See the xref:compatibility-versions-features.adoc[Compatibility] section for details.

http://packages.couchbase.com/clients/java/2.7.2/Couchbase-Java-Client-2.7.2.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.7.2/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.7.2/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.7.2**
* com.couchbase.client:**core-io:1.7.2**
* io.reactivex:**rxjava:1.3.8**
* io.opentracing:**opentracing-api:0.31.0**

=== Enhancements & New Features

* http://issues.couchbase.com/browse/JCBC-1254[JCBC-1254]: 
Adds experimental utility API to ingest Analytics query results back to KV layer.
* http://issues.couchbase.com/browse/JCBC-1258[JCBC-1258]: 
Adds experimental support for deferred Analytics query execution. 
This is useful for long running queries where the results can be fetched later.
* http://issues.couchbase.com/browse/JCBC-1171[JCBC-1171]: 
Allows to add hints for hash and nested loop joins in N1QL query DSL.
* http://issues.couchbase.com/browse/JCBC-1266[JCBC-1266]: 
You can now compile with Java 11, which contains minor javadoc fixes. 

=== Fixed Issues

* http://issues.couchbase.com/browse/JVMCBC-579[JVMCBC-579]: 
Fixes the Response Time Observability threshold logging to use descending order instead of ascending as mandated in the sdk-rfc.

== Version 2.7.1 (6 November 2018)

Version 2.7.1 is the second release of the 2.7 series, bringing new features, enhancements, and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.7.1/Couchbase-Java-Client-2.7.1.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.7.1/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.7.1/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.7.1**
* com.couchbase.client:**core-io:1.7.1**
* io.reactivex:**rxjava:1.3.8**
* io.opentracing:**opentracing-api:0.31.0**

A special note for this release, the Jackson databind dependency has been upgraded to version to 2.9.7 for security updates. 
As the newer Jackson dependency uses Java 7 language features and older Java 6 compatible versions are no longer maintained, the SDK is no longer compatible with Java 6. 
Couchbase prefers to make such platform changes in minor releases, but is applying the change here given the nature of the issue and that the https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api[semantic versioning standard does allow for a dependency update].

=== Enhancements & New Features

* http://issues.couchbase.com/browse/JCBC-1253[JCBC-1253]: 
Adds support for Sub-Document operation expansion of macro in extended attributes. This is intended for internal use for other dependent Couchbase libraries.
* http://issues.couchbase.com/browse/JCBC-1259[JCBC-1259]: Exposes async cluster interface from cluster similar to the bucket interface behavior.
* http://issues.couchbase.com/browse/JVMCBC-581[JVMCBC-581]: Updates Jackson dependency to 2.9.7.
* http://issues.couchbase.com/browse/JCBC-1251[JCBC-1251]: Allows to select "DISTINCT RAW" in N1ql dsl.

=== Fixed Issues

* http://issues.couchbase.com/browse/JVMCBC-579[JVMCBC-579]: Fixes the Response Time Observability threshold logging to use descending order instead of ascending as mandated in the sdk-rfc.
* http://issues.couchbase.com/browse/JCBC-1255[JCBC-1255]: Allows crypto transcoder to also transcode docs with no encryption requirements.

== Version 2.7.0 (2 October 2018)

Version 2.7.0 is the first release of the 2.7 series, bringing new features, enhancements, and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.7.0/Couchbase-Java-Client-2.7.0.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.7.0/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.7.0/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.7.0**
* com.couchbase.client:**core-io:1.7.0**
* io.reactivex:**rxjava:1.3.8**
* io.opentracing:**opentracing-api:0.31.0**

=== Enhancements & New Features

The major enhancements are:

* Committed Analytics query interface using official endpoint for querying and direct endpoint for keep alives rather than the proxying, which is more performant.
* Additional configuration capabilties in Bucket Settings builder with better defaults. 

* http://issues.couchbase.com/browse/JVMCBC-571[JVMCBC-571]: 
Switched to the official endpoint for querying Analytics service (from /query/service to /analytics/service).
* http://issues.couchbase.com/browse/JVMCBC-575[JVMCBC-575]: 
Expose HTTP Status code as part of Search response for java-client to act on it.
* http://issues.couchbase.com/browse/JVMCBC-576[JVMCBC-576]: 
Allow to override the TLS protocol version used, for example TLS 1.2 must be forced in Java 7.
* http://issues.couchbase.com/browse/JVMCBC-569[JVMCBC-569]: 
Switched to the new performant endpoint for Analytics service keep alive requests (from /analytics/version to /admin/ping).
* http://issues.couchbase.com/browse/JVMCBC-572[JVMCBC-572]: 
Add the document key to the span as tag if log redaction is not enabled.
* http://issues.couchbase.com/browse/JCBC-1244[JCBC-1244]: 
Expose the count of processed objects returned in the Analytics query metrics.
* http://issues.couchbase.com/browse/JCBC-916[JCBC-916]: 
Allow to configure ejection/eviction policy on bucket settings.
* http://issues.couchbase.com/browse/JCBC-1245[JCBC-1245]: 
Add better defaults in BucketSettings for RAM Quota and not requiring bucket password (for use with RBAC).
* http://issues.couchbase.com/browse/JCBC-1195[JCBC-1195]: 
Allow to configure different compression modes (off/active/passive) on bucket settings.
* http://issues.couchbase.com/browse/JCBC-1232[JCBC-1232]: 
FTS now honors the memory quota specified and responds with status code 429 if the quota is full. Add exponential backoff and retry the query in such a failure.
* http://issues.couchbase.com/browse/JCBC-1248[JCBC-1248]: 
Transparently retry certain retryable error codes as identified by sdk-rfc for Analytics queries.

=== Fixed Issues

* http://issues.couchbase.com/browse/JVMCBC-566[JVMCBC-566]: 
Signals on refresh intervals would be sent to both carrier and http refresher, which is a Noop in http refresher. Limit the refresh signals only to the carrier refresher.
* http://issues.couchbase.com/browse/JVMCBC-567[JVMCBC-567]: 
OnDemand service connections can still be in connected state when the service is removed. Fix the disconnect logic to be similar to pooled service.
* http://issues.couchbase.com/browse/JVMCBC-565[JVMCBC-565]: 
Half open http config stream can go undetected. 
Update to proactively fetching config from http configuration provider similar to carrier refresher on refresh signals. 
This handles the half open connection state in a less penalizing way than recreating a connection on idle timeout.

== Version 2.6.2 (4 September 2018)

Version 2.6.2 is the third release of the 2.6 series, bringing new features, enhancements and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.6.2/Couchbase-Java-Client-2.6.2.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.6.2/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.6.2/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.6.2**
* com.couchbase.client:**core-io:1.6.2**
* io.reactivex:**rxjava:1.3.7**
* io.opentracing:**opentracing-api:0.31.0**

=== Enhancements & New Features

* http://issues.couchbase.com/browse/JCBC-1227[JCBC-1227]: 
The _pretty_ option is now configurable for analytics queries.
* http://issues.couchbase.com/browse/JCBC-1229[JCBC-1229]: 
Support for parameterized queries has been added for analytics.
* http://issues.couchbase.com/browse/JCBC-1246[JCBC-1246]: 
Support for the analytics _priority_ param has been added.
* http://issues.couchbase.com/browse/JCBC-1233[JCBC-1233],
http://issues.couchbase.com/browse/JCBC-1234[JCBC-1234],
http://issues.couchbase.com/browse/JCBC-1235[JCBC-1235]: 
various smaller enhancements overall to improve the analytics experience. 

=== Fixed Issues

* http://issues.couchbase.com/browse/JCBC-1226[JCBC-1226]: 
Fixes a _NullPointerException_ if AnalyticsParams is not properly initialized.
* http://issues.couchbase.com/browse/JVMCBC-564[JVMCBC-564]: 
During rebalance, an issue has been fixed where the SDK would connect to a KV service earlier than it should, leading to errors and failed operations during rebalance. 
With this fix applied, especially when performing rebalance-in scenarios on memcached buckets, this problem will go away. 
Note that couchbase buckets are not as affected since the gradual vbucket (partition) movement prohibits sending operations to non-ready nodes.

 

== Version 2.6.1 (23 July 2018)

Version 2.6.1 is the second release of the 2.6 series, bringing new
features, enhancements and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.6.1/Couchbase-Java-Client-2.6.1.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.6.1/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.6.1/[Core
API
Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.6.1**
* com.couchbase.client:**core-io:1.6.1**
* io.reactivex:**rxjava:1.3.7**
* io.opentracing:**opentracing-api:0.31.0**

=== Enhancements & New Features

* http://issues.couchbase.com/browse/JVMCBC-552[JVMCBC-552]:  Improve ring buffer diagnostics. The diagnostic information about the\
requests contained in the ring buffer will be useful for debugging and adjusting
configuration on backpressure exception.

=== Fixed Issues

* http://issues.couchbase.com/browse/JVMCBC-556[JVMCBC-556]: Allow to distinguish between nodes on the same physical host with
different ports
* http://issues.couchbase.com/browse/JCBC-1223[JCBC-1223]: 2.6.0 release introduced a bug on the async persistence API where a timeout
of O will be applied if there was no timeout specified and this would cause timer
to fire quickly leading to timeout exception. Fixed the behavior to be similar
to previous releases.
* http://issues.couchbase.com/browse/JVMCBC-560[JVMCBC-560]: Nodes can temporarily go to service degraded state while increasing
the connection pool. If the node exclusively provides query/analytics service,
there might be an incorrect node disconnected event on the event bus. Fixed by
not marking node as disconnected if service is degraded.

=== Known Issues

* http://issues.couchbase.com/browse/JCBC-1226[JCBC-1226]: A
regression has been found in 2.6.0 which will be addressed in 2.6.2:
When using the analytics API without explicit params, a
NullPointerException is raised (i.e.
_bucket.query(AnalyticsQuery.simple("myquery"));_). As a workaround,
please specify empty params
explicitly: _bucket.query(AnalyticsQuery.simple("myquery",
AnalyticsParams.build()));_

== Version 2.6.0 (5 July 2018)

Version 2.6.0 is the first release of the 2.6 series, bringing new
features, enhancements and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.6.0/Couchbase-Java-Client-2.6.0.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.6.0/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.6.0/[Core
API
Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.6.0**
* com.couchbase.client:**core-io:1.6.0**
* io.reactivex:**rxjava:1.3.7**
* io.opentracing:**opentracing-api:0.31.0**

=== Enhancements & New Features

* http://issues.couchbase.com/browse/JCBC-1159[JCBC-1159],
http://issues.couchbase.com/browse/JCBC-1160[JCBC-1160]: A new
feature called "per operation tracing" has been introduced in
pre-releases and is now a stable and supported feature. Please see
the corresponding documentation and blog posts for more information
and usage. To provide a flexible and extensible implementation we are now also
depending on the opentracing-api dependency for this. This allows
you to plug in your own tracer (like jaegertracing or commerical
products) as well.
* http://issues.couchbase.com/browse/JCBC-1169[JCBC-1169],
http://issues.couchbase.com/browse/JCBC-1170[JCBC-1170]: Support
for Field-Level Encryption has been added to the SDK. This only
works in combination with a separate library which can be found on
maven central as well but can only be used with a Couchbase EE
subscription. Please see the corresponding documentation and blog
posts for more information and usage.
* http://issues.couchbase.com/browse/JVMCBC-490[JVMCBC-490]: Support
for transparent client side compression has been added to the SDK.
The Environment provides certain tunables to customize the default
settings (compressionMinSize and compressionMinRatio). If the server
also supports this feature (5.5 and newer), the SDK will
automatically negotiate and use it. Please see the corresponding
documentation and blog posts for more information and usage.
* http://issues.couchbase.com/browse/JCBC-1203[JCBC-1203],
http://issues.couchbase.com/browse/JVMCBC-537[JVMCBC-537]:
Support for client certificate authentication has been expanded from
pure KV only to all supported services. A new "CertAuthenticator"
has been introduced and it needs to be explicitly enabled on the
Environment via the "certAuthEnabled" configuration option. Please
see the corresponding documentation and blog posts for more
information and usage.
* http://issues.couchbase.com/browse/JVMCBC-542[JVMCBC-542]: Initial
support for multi network configurations has been added. This allows
the SDK to work in environments like Kubernetes and similar where
internal addresses might be exposed via a different hostname or port
combination. Note that there is a known issue outlined below with
the current implementation which prevents you from exposing many
nodes via the same hostname.
* http://issues.couchbase.com/browse/JVMCBC-500[JVMCBC-500]:
Internal and external dependencies have been bumped to their newest
versions.
* http://issues.couchbase.com/browse/JVMCBC-555[JVMCBC-555]:  The
analytics service can now also customize its IO pool if needed like
the other services do.
* http://issues.couchbase.com/browse/JVMCBC-554[JVMCBC-554]: The
analytics service can now also be customized through the
AnalyticsServiceConfig on the environment.
* http://issues.couchbase.com/browse/JVMCBC-528[JVMCBC-528]: More
information during the SASL auth steps is now provided to aid
debugging.
* http://issues.couchbase.com/browse/JVMCBC-529[JVMCBC-529]: When
using PersistTo/ReplicateTo overloads, the original CAS used in the
mutation is now returned with the exception.
* http://issues.couchbase.com/browse/JVMCBC-552[JVMCBC-552]:
Internal RingBuffer diagnostics have been improved so now more
information during the BackpressureException is provided to figure
out what has filled up the buffer in the first place to aid
debugging.
* http://issues.couchbase.com/browse/JVMCBC-530[JVMCBC-530]: Java 9
support has been added by providing Automatic-Module-Name
information to core-io and java-client.
* http://issues.couchbase.com/browse/JVMCBC-531[JVMCBC-531]: Read
bytes are discarded early in the N1QL streaming parser, leading to
less memory consumption on large responses.
* http://issues.couchbase.com/browse/JCBC-1158[JCBC-1158]: The
repository abstraction now allows annotations in parent classes.
* http://issues.couchbase.com/browse/JCBC-1179[JCBC-1179]: A new
"profile" option has been added to N1qlParams.

=== Fixed Issues

* http://issues.couchbase.com/browse/JVMCBC-510[JVMCBC-510]: Unknown
bucket capabilities returned from the server config are now ignored,
providing better forwards compatibility with newer server versions.
* http://issues.couchbase.com/browse/JVMCBC-523[JVMCBC-523]: When
the SDK bootstraps against "good" and "bad" nodes, the bad ones are
now properly cleaned up as soon as a good config can be found. This
reduces noise in the logs.
* http://issues.couchbase.com/browse/JVMCBC-548[JVMCBC-548]: The
original seed node list to bootstrap is now properly shuffled which
allows for better distribution during bootstrap and less contention
on specific nodes when many app servers are bootstrapped at the same
time.
* http://issues.couchbase.com/browse/JVMCBC-535[JVMCBC-535]: The SDK
now properly validates the last step in the SASL bootstrap sequence.
* http://issues.couchbase.com/browse/JVMCBC-513[JVMCBC-513]: A
NullPointerException on a bad host in the connection string during
bootstrap is now fixed.
* http://issues.couchbase.com/browse/JVMCBC-551[JVMCBC-551]: When
loading a terse bucket config via HTTP (as a fallback from the KV
approach) a bug has been fixed that confuses the bucket name with
the username and as a result can't properly load a config.
* http://issues.couchbase.com/browse/JCBC-1209[JCBC-1209]: A handful
codepaths have been audited to make sure subscribers are properly
registered so timed out operations are cleaned up as early as
possible once they are unsubscribed.
* http://issues.couchbase.com/browse/JCBC-1213[JCBC-1213]: In a
Search query the descending order now properly uses the "desc" token
on the wire (instead of previously "descending" which the search
engine did not understand and ignored).
* http://issues.couchbase.com/browse/JCBC-1184[JCBC-1184]: The
JavaDoc of the BucketManager#getDesignDocument method has been
clarified that an exception is raised if the document is not found
and not null returned for the blocking call (or an empty Observable
in the async case).
* http://issues.couchbase.com/browse/JCBC-1175[JCBC-1175]: An
incorrect response mapping of the queue remove (via subdoc remove)
has been fixed.
* http://issues.couchbase.com/browse/JCBC-1194[JCBC-1194]: When
using the ClusterManager without opening a bucket, the code now
properly round-robins through the bootstrap list so if one of the
nodes is down there is a chance that the operation can succeed.
* http://issues.couchbase.com/browse/JCBC-1207[JCBC-1207]: A bug has
been fixed where the SDK performed reverse DNS lookups during DNS
SRV bootstrapping which should not happen.

=== Known Issues

* http://issues.couchbase.com/browse/JVMCBC-556[JVMCBC-556]: A new
feature known as "multi network configuration" has been added, but
for now only nodes with individual hostnames are supported. Support
for nodes that all listen on the same physical hostname but on
different ports will be added in a future release.
* http://issues.couchbase.com/browse/JCBC-1223[JCBC-1223]: A
regression has been found in 2.6.0 which will be addressed in 2.6.1:
When API from the AsyncBucket is used that also uses durability
requirements but not an explicit timeout, the operation will always
time out immediately without a chance to complete. So affected is
for example the following call: _bucket.async().upsert(doc,
PersistTo.MASTER);_ a proper workaround for now is including an
explict timeout like so: _bucket.async.upsert(doc, PersistTo.MASTER,
2, TimeUnit.SECONDS);_
* http://issues.couchbase.com/browse/JCBC-1226[JCBC-1226]: A
regression has been found in 2.6.0 which will be addressed in 2.6.2:
When using the analytics API without explicit params, a
NullPointerException is raised (i.e.
_bucket.query(AnalyticsQuery.simple("myquery"));_). As a workaround,
please specify empty params
explicitly: _bucket.query(AnalyticsQuery.simple("myquery",
AnalyticsParams.build()));_

=== Changes

* http://issues.couchbase.com/browse/JVMCBC-482[JVMCBC-482]: Force
IPv4 property to false by default. This can be reversed with the
same system property as before, but is now forced to false since
Couchbase Server supports IPv6 and only comes into play anyways if
the JVM is forced to IPv6 but the server does not support it. If you
have relied on this behavior before and cannot upgrade the server,
please modify the system property "com.couchbase.forceIPv4" to
"true".

== Version 2.5.9 (7 June 2018)

Version 2.5.9 is the tenth release of the 2.5 series, bringing
enhancements and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.5.9/Couchbase-Java-Client-2.5.9.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.5.9/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.5.9/[Core
API
Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.5.9**
* com.couchbase.client:**core-io:1.5.9**
* io.reactivex:**rxjava:1.3.4**

=== Fixed Issues

* http://issues.couchbase.com/browse/JVMCBC-534[JVMCBC-534]: Fix
pooledService creating excessive endpoints on sending to downed node
* http://issues.couchbase.com/browse/JVMCBC-543[JVMCBC-543]: Clean
up stale connections when query node goes offline, otherwise the
connections may stick around until OS TCP timeout
* http://issues.couchbase.com/browse/JCBC-1207[JCBC-1207]: Dont do
reverse lookup on DNS SRV bootstrap

=== Enhancements & New Features

* http://issues.couchbase.com/browse/JCBC-1158[JCBC-1158]: Add
support for annotations in parent classes
* http://issues.couchbase.com/browse/JVMCBC-545[JVMCBC-545]: Improve
debug logging on Endpoint
* http://issues.couchbase.com/browse/JCBC-1209[JCBC-1209]: Audit and
add explicit subscribers to non-kv requests to check for timeouts

== Version 2.5.8 (1 May 2018)

Version 2.5.8 is the ninth release of the 2.5 series, bringing
enhancements and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.5.8/Couchbase-Java-Client-2.5.8.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.5.8/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.5.8/[Core
API
Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.5.8**
* com.couchbase.client:**core-io:1.5.8**
* io.reactivex:**rxjava:1.3.4**

=== Fixed Issues

* http://issues.couchbase.com/browse/JCBC-1194[JCBC-1194]: Enable
service on nodes in the bootstrap list in round robin for cluster
manager use without opening bucket.
* http://issues.couchbase.com/browse/JVMCBC-523[JVMCBC-523]:
Properly clean up services on failed connect
* http://issues.couchbase.com/browse/JVMCBC-531[JVMCBC-531]: Discard
read bytes in the parser on chunked response to reduce high memory
consumption

=== Enhancements & New Features

* http://issues.couchbase.com/browse/JVMCBC-529[JVMCBC-529]: Expose
original mutation cas on observe exceptions.

== Version 2.6.0-beta (13 April 2018)

Version 2.6.0 is the beta release of the 2.6 series, bringing new
features, enhancements and bugfixes over the last stable release.

*Note that this is a beta release for upcoming functionality and should
not be used in a production deployment.*

http://packages.couchbase.com/clients/java/2.6.0-beta/Couchbase-Java-Client-2.6.0-beta.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.6.0-beta/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.6.0-beta/[Core
API
Reference] 

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.6.0-beta**
* com.couchbase.client:**core-io:1.6.0-beta**
* io.reactivex:**rxjava:1.3.5**

It can be loaded from our prerelease maven repository:

[source,xml]
....
<dependencies>
    <dependency>
        <groupId>com.couchbase.client</groupId>
        <artifactId>java-client</artifactId>
        <version>2.6.0-beta</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>cb-pre</id>
        <name>Couchbase Prerelease Repo</name>
        <url>http://files.couchbase.com/maven2</url>
    </repository>
</repositories>
....

=== Enhancements & New Features

* Support for end-to-end traceability has been added, which includes
out of the box support for threshold-based trace information of
requests and their timings as well as experimental support for
OpenTracing compatible tracers.
* Support for field-level-encryption which allows cross-SDK encrypting
and decrypting of fields in JSON document bodies. The encryption
extension is maintained on a separate
https://github.com/couchbase/couchbase-java-client-crypto-extension[repository].
* Support for transparent end-to-end compression through snappy if the
server supports it.

Please see blog posts and additional documentation / announcements
around those features.

== Version 2.5.7 (4 April 2018)

Version 2.5.7 is the eighth release of the 2.5 series, bringing
enhancements and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.5.7/Couchbase-Java-Client-2.5.7.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.5.7/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.5.7/[Core
API
Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.5.7**
* com.couchbase.client:**core-io:1.5.7**
* io.reactivex:**rxjava:1.3.4**

=== Fixed Issues

* http://issues.couchbase.com/browse/JVMCBC-513[JVMCBC-513]: A
NullPointerException has been fixed on a bad host string as part of
the connection string.
* http://issues.couchbase.com/browse/JCBC-1175[JCBC-1175]: A bug in
the subdocument queuePop API has been fixed which doesn't "swallow"
concurrent access but rather returns a CAS mismatch as intended.

=== Enhancements & New Features

* http://issues.couchbase.com/browse/JCBC-1179[JCBC-1179]: Volatile
support for N1QL profile query param has been added which allows to
get more profiling information at query time. The API is intended to
be marked as comitted in the coming minor release cycle.

== Version 2.5.6 (6 March 2018)

Version 2.5.6 is the seventh release of the 2.5 series, bringing
enhancements and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.5.6/Couchbase-Java-Client-2.5.6.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.5.6/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.5.6/[Core
API
Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.5.6**
* com.couchbase.client:**core-io:1.5.6**
* io.reactivex:**rxjava:1.3.4**

=== Fixed Issues

* http://issues.couchbase.com/browse/JVMCBC-510[JVMCBC-510]: Unknown
bucket capabilities coming from a server config are now handled more
gracefully, making sure unknown capabilites do not break the client
parsing the server sent bucket config.

=== Enhancements & New Features

* http://issues.couchbase.com/browse/JVMCBC-492[JVMCBC-492],
http://issues.couchbase.com/browse/JVMCBC-493[JVMCBC-493]: When
the SDK connects to the server (Key/Value) it now negotiates its
identification string via JSON, providing better capabilities to
associate interactions with the server logs (if the server supports
it, it can now parse and uniquely identify a client instance and us
it in its logging).
* http://issues.couchbase.com/browse/JVMCBC-504[JVMCBC-504]: Snappy
compression is available (if the server supports it), but disabled
by default. This is mainly available for internal testing, if you
want to use it in production please move to the 2.6.x branch or
later which extended its internal support (Couchbase Server 5.5 and
later).
* http://issues.couchbase.com/browse/JVMCBC-480[JVMCBC-480]:
Infrastructure for redacted logging has been added, but only "user"
information will be wrapped in redaction tags. Please consult the
server documentation for additional tools which will then perform
the actual redaction for both client and server data (Couchbase
Server 5.5 and later).
* http://issues.couchbase.com/browse/JVMCBC-512[JVMCBC-512]: It is
now possible to configure the number of allowed
CouchbaseEnvironments based on a static config setting. Note that
this should only be tuned under very specific settings and is
considered advanced API.

== Version 2.6.0-dp1 (27 February 2018)

Version 2.6.0 is the first developer preview release of the 2.6 series,
bringing new features, enhancements and bugfixes over the last stable
release.

*Note that this is a developer preview for upcoming functionality and
should not be used in a production deployment.*

http://packages.couchbase.com/clients/java/2.6.0-dp1/Couchbase-Java-Client-2.6.0-dp1.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.6.0-dp1/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.6.0-dp1/[Core
API
Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.6.0-dp1**
* com.couchbase.client:**core-io:1.6.0-dp1**
* io.reactivex:**rxjava:1.3.5**

It can be loaded from our prerelease maven repository:

....
<dependencies>
    <dependency>
        <groupId>com.couchbase.client</groupId>
        <artifactId>java-client</artifactId>
        <version>2.6.0-dp1</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>cb-pre</id>
        <name>Couchbase Prerelease Repo</name>
        <url>http://files.couchbase.com/maven2</url>
    </repository>
</repositories>
....

=== Enhancements & New Features

* Support for end-to-end traceability has been added, which includes
out of the box support for threshold-based trace information of
requests and their timings as well as experimental support for
OpenTracing compatible tracers.
* Support for field-level-encryption which allows cross-SDK encrypting
and decrypting of fields in JSON document bodies.
* Support for transparent end-to-end compression through snappy if the
server supports it.

Please see blog posts and additional documentation / announcements
around those features.

== Version 2.5.5 (6 February 2018)

Version 2.5.5 is the sixth release of the 2.5 series, bringing
enhancements and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.5.5/Couchbase-Java-Client-2.5.5.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.5.5/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.5.5/[Core
API
Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.5.5**
* com.couchbase.client:**core-io:1.5.5**
* io.reactivex:**rxjava:1.3.4**

=== Fixed Issues

* http://issues.couchbase.com/browse/JVMCBC-487[JVMCBC-487]: A
regression was fixed which prevent the netty epoll native transport
from being properly repackaged. It is now possible to use the native
transport optionally again.

=== Enhancements & New Features

* http://issues.couchbase.com/browse/JCBC-1147[JCBC-1147]: Added
support for the Health Check "ping" command at the bucket level.
This command allows to proactively send requests to all enabled
services and get insight into their current status.
* http://issues.couchbase.com/browse/JVMCBC-490[JVMCBC-490]: Added
uncomitted support for "end-to-end" compression based on snappy.
Note that this preliminary support is meant for early adopters and
might change in future releases.
* http://issues.couchbase.com/browse/JVMCBC-480[JVMCBC-480]: Added
infrastructure and uncomitted support for log redaction. Note that
this preliminary support is meant for early adopters and might
change in future releases.
* http://issues.couchbase.com/browse/JCBC-1163[JCBC-1163]: A small
enhancement was added which logs the raw value if a N1QL response
row couldn't be decoded. This allows for easier troubleshooting.
* http://issues.couchbase.com/browse/JVMCBC-486[JVMCBC-486]: During
reconnect attempts, not every stack trace is logged anymore which
makes the logs less noisy and easier to parse.
* http://issues.couchbase.com/browse/JVMCBC-489[JVMCBC-489]:
Http-based service pools now start their queries at random offsets,
meaning that different nodes are getting hit on the first request,
allowing for a more even query distribution especially with long
running queries i.e. N1QL or analytics.

== Version 2.5.4 (9 January 2018)

Version 2.5.4 is the fifth release of the 2.5 series, bringing
enhancements and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.5.4/Couchbase-Java-Client-2.5.4.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.5.4/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.5.4/[Core
API
Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.5.4**
* com.couchbase.client:**core-io:1.5.4**
* io.reactivex:**rxjava:1.3.3**

=== Fixed Issues

* http://issues.couchbase.com/browse/JVMCBC-485[JVMCBC-485]: A minor
issue has been fixed which did allow to go the service pool size
below the configured minimum when cleaning up idle services. This
has no impact on the workload but shows misleading node disconnect
logs, so the logic has been changed to prevent that.

=== Enhancements & New Features

* http://issues.couchbase.com/browse/JVMCBC-475[JVMCBC-475],
http://issues.couchbase.com/browse/JVMCBC-476[JVMCBC-476]: Support
for IPv6 has been added throughout the stack, but it still disabled
by default to minimize the risk of being backwards incompatible. It
will be enabled with 2.6.0 by default. If you want to enable it
right now, set the "com.couchbase.forceIPv4" system property to
"false".
* http://issues.couchbase.com/browse/JCBC-1147[JCBC-1147]: The
HealthCheck API has been brought up to speed with the current
SDK-RFC. As a result, the API has been renamed to "diagnostics" on
the cluster level. Note that this API has been and still is
experimental, so there might be more (smalller) changes coming
before its finally stabilized. 

== Version 2.5.3 (5 December 2017)

Version 2.5.3 is the fourth release of the 2.5 series, bringing
enhancements and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.5.3/Couchbase-Java-Client-2.5.3.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.5.3/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.5.3/[Core
API
Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.5.3**
* com.couchbase.client:**core-io:1.5.3**
* io.reactivex:**rxjava:1.3.3**

=== Fixed Issues

* http://issues.couchbase.com/browse/JVMCBC-474[JVMCBC-474]: The
internal and repackaged netty dependency has been bumped to
4.0.53.Final which contains fixes around Java 6 & 7 compatibility.
* http://issues.couchbase.com/browse/JCBC-1152[JCBC-1152]: When the
server returns the LOCKED error code via key/value, it is now
properly translated on getAndLock into a
TemporaryLockFailureException in addition to TMPFAIL. This is
important on servers > 5.0.

=== Enhancements & New Features

* http://issues.couchbase.com/browse/JVMCBC-477[JVMCBC-477]: A new
libcouchbase & .NET compatible memcached bucket (ketama) hashing
strategy has been added, called StandardMemcachedHashingStrategy. It
will become the default in the next major SDK version.
* http://issues.couchbase.com/browse/JVMCBC-473[JVMCBC-473]: A new
configuration option "forceSaslPlain" has been added which falls
back to PLAIN key/value authentication. This is needed if a user
should be used for authentication which is to be authenticated
through LDAP. If secrecy is needed, we recommend using our TLS
 encrypted connection feature on top.
* http://issues.couchbase.com/browse/JVMCBC-481[JVMCBC-481]: When a
new config arrives, it is now quickly checked if the internal
revision number is greater and only then a full blown internal
config is created. While not user visible, it can help reduce the
possibility of unncessary repeated hostname lookups, which in
combination with slow or unreliable DNS setups can block computation
threads and lead to occasional timeouts.

== Version 2.5.2 (8 November 2017)

Version 2.5.2 is the third release of the 2.5 series, bringing
enhancements and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.5.2/Couchbase-Java-Client-2.5.2.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.5.2/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.5.2/[Core
API
Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.5.2**
* com.couchbase.client:**core-io:1.5.2**
* io.reactivex:**rxjava:1.3.3**

=== Fixed Issues

* http://issues.couchbase.com/browse/JVMCBC-471[JVMCBC-471]: A bug
in the "healthcheck" API has been fixed which when called in the
middle of nodes connecting the underlying channel would be null
leading to NullPointerExceptions. This is now handled more
gracefully.
* http://issues.couchbase.com/browse/JCBC-1144[JCBC-1144]: The
RetryBuilder had a bug which would not emit the underlying exception
into the downstream Observable if it got emitted in the exactly last
retry iteration. This has been fixed.

=== Enhancements & New Features

* http://issues.couchbase.com/browse/JVMCBC-470[JVMCBC-470]: It is
now possible to configure the lower bound of the config poll
interval via the configPollFloorInterval Environment property.
* http://issues.couchbase.com/browse/JVMCBC-468[JVMCBC-468]: The
TrustStore for SSL can now be configured separately from the
KeyStore, which gives you better control if both are maintained in
separate files.
* http://issues.couchbase.com/browse/JCBC-1140[JCBC-1140]: Thanks to
a community contribution the allocation overhead for JsonDocument
content (JsonObject, JsonArray) is reduced by roughly 10% but your
mileage may vary depending on the size of the content.
* http://issues.couchbase.com/browse/JCBC-1141[JCBC-1141]: A new
document type: ByteArrayDocument has been introduced (but not as a
committed API yet) which gives you the same benefits of a
BinaryDocument, but comes without the burden of manual ByteBuffer
management and reference counting.
* http://issues.couchbase.com/browse/JCBC-1142[JCBC-1142]: in an
effort to make the APIs between SDKs consistent, the subdocument
method "createParents" has been renamed to "createPath", but in a
backwards compatible way with deprecated methods. Please migrate to
the new API since it will be deleted in the next major release.

== Version 2.5.1 (3 October 2017)

Version 2.5.1 is the second release of the 2.5 series, bringing
enhancements and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.5.1/Couchbase-Java-Client-2.5.1.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.5.1/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.5.1/[Core
API
Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.5.1**
* com.couchbase.client:**core-io:1.5.1**
* io.reactivex:**rxjava:1.3.0**

=== Fixed Issues

* https://issues.couchbase.com/browse/JCBC-1129[JCBC-1129]: The
Subdocument API has been modified slightly so that it correctly
aligns with the SDK-RFC for this feature. No methods have been
removed, but the `createDocument` builder API is now
`upsertDocument` and the old one has been deprecated.
* https://issues.couchbase.com/browse/JCBC-1137[JCBC-1137]: Previous
releases added CouchbaseMock as a dependency, but it should actually
just be a test dependency.
* https://issues.couchbase.com/browse/JCBC-1131[JCBC-1131]: One
openBucket overload didn't actually respect the custom transcoders
passed in. This is now fixed and all bucket open methods properly
respect custom transcoders.
* https://issues.couchbase.com/browse/JVMCBC-466[JVMCBC-466]: When
continuousKeepAlive is enabled, closed sockets would still try to
run the keepalive, which could lead to reconnect attempts of nodes
that are not needed anymore and "runaway" sockets.
* https://issues.couchbase.com/browse/JVMCBC-465[JVMCBC-465],
https://issues.couchbase.com/browse/JVMCBC-467[JVMCBC-467]: Some
changes have been made to the reconnection logic so there are no
concurrent reconnect attempts. This fixes a problem where upgrading
from < 5.0 Server releases to > 5.0 Server releases wasn't
possible without restarting the application server.

== Version 2.5.0 (6 September 2017)

Version 2.5.0 is the first release of the 2.5 series, bringing
enhancements and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.5.0/Couchbase-Java-Client-2.5.0.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.5.0/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.5.0/[Core
API
Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.5.0**
* com.couchbase.client:**core-io:1.5.0**
* io.reactivex:**rxjava:1.3.0**

=== Enhancements & New Features

* https://issues.couchbase.com/browse/JCBC-1071[JCBC-1071]: Add
basic KV error map testing with mock
* https://issues.couchbase.com/browse/JCBC-1082[JCBC-1082]:
Implement subdoc GET_COUNT
* https://issues.couchbase.com/browse/JCBC-1100[JCBC-1100]: Counter
API doc should inform that expiry is only honoured on creation
* https://issues.couchbase.com/browse/JCBC-1106[JCBC-1106]: Expose
more N1QL Query Options
* https://issues.couchbase.com/browse/JCBC-1110[JCBC-1110]: Add
ReplicaGet Helper Class
* https://issues.couchbase.com/browse/JCBC-1115[JCBC-1115]: Enfore
Xattr ordering on builder
* https://issues.couchbase.com/browse/JCBC-1117[JCBC-1117]: Document
example of using CoreSendHook for logging request/response/timeout
and hostname
* https://issues.couchbase.com/browse/JCBC-1125[JCBC-1125]: Add
basic support for healthCheck API
* https://issues.couchbase.com/browse/JCBC-1126[JCBC-1126]: Promote
experimental APIs where appropriate
* https://issues.couchbase.com/browse/JCBC-1069[JCBC-1069]: Adding
union, intersect & except to DSL
* https://issues.couchbase.com/browse/JCBC-1070[JCBC-1070]: Getter
for object attributes added to DSL
* https://issues.couchbase.com/browse/JVMCBC-438[JVMCBC-438]: Set
config poll interval to 2.5s by default
* https://issues.couchbase.com/browse/JVMCBC-431[JVMCBC-431]: Add
support for InsertDoc and AccessDeleted in subdoc document flags
* https://issues.couchbase.com/browse/JVMCBC-460[JVMCBC-460]
:Discover FTS SSL through config
* https://issues.couchbase.com/browse/JVMCBC-441[JVMCBC-441]: Allow
to hook in before the RingBuffer
* https://issues.couchbase.com/browse/JVMCBC-442[JVMCBC-442]: Store
dispatched hostname in CouchbaseRequest
* https://issues.couchbase.com/browse/JVMCBC-443[JVMCBC-443]: Remove
Deprecated DCP from Core-IO
* https://issues.couchbase.com/browse/JVMCBC-444[JVMCBC-444]:
Enforce config poll floor at 50ms
* https://issues.couchbase.com/browse/JVMCBC-451[JVMCBC-451]:
Implement subdoc GET_COUNT
* https://issues.couchbase.com/browse/JVMCBC-456[JVMCBC-456]: Harden
and Optimize YASJL Parser
* https://issues.couchbase.com/browse/JVMCBC-457[JVMCBC-457]: Make
the new parser default for query parsing
* https://issues.couchbase.com/browse/JVMCBC-458[JVMCBC-458]:
Discover and bootstrap analytics service from cluster config
* https://issues.couchbase.com/browse/JVMCBC-461[JVMCBC-461]: Add
basic support for healthCheck API
* https://issues.couchbase.com/browse/JVMCBC-462[JVMCBC-462]:
Promote experimental APIs where appropriate
* https://issues.couchbase.com/browse/JVMCBC-449[JVMCBC-449]:
Exponential Retry Delay, please check arguments

=== Fixed Issues

* https://issues.couchbase.com/browse/JCBC-1111[JCBC-1111]: Handle
LOCKED in the conversions
* https://issues.couchbase.com/browse/JVMCBC-445[JVMCBC-445]:
ArrayOutOfBoundException in PooledService#sendFlush (concurrent
access on list)
* https://issues.couchbase.com/browse/JVMCBC-448[JVMCBC-448]:
Sporadic Unhandled Select Bucket status 1
* https://issues.couchbase.com/browse/JVMCBC-435[JVMCBC-435]: Issue
with number of java client connections increasing rapidly after fail
over on single node in cluster
* https://issues.couchbase.com/browse/JCBC-1086[JCBC-1086]:
Explicitly handle auth error for observe with xerror

=== Known Issues

* https://issues.couchbase.com/browse/JCBC-1129[JCBC-1129]:
Subdocument document options has createDocument flag for creating
documents if the document does not exist. This flag naming does not
conform to the specifications where it is named as upsertDocument.
This will be fixed in upcoming release 2.5.1.

== Version 2.4.8 (18 October 2017)

Version 2.4.8 is the ninth release of the 2.4 series, bringing important
bugfixes over the last stable release, especially when used with
Couchbase Server 5.0 and later.

http://packages.couchbase.com/clients/java/2.4.8/Couchbase-Java-Client-2.4.8.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.4.8/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.4.8/[Core
API
Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.4.8**
* com.couchbase.client:**core-io:1.4.8**
* io.reactivex:**rxjava:1.2.7**

=== Fixed Issues

* https://issues.couchbase.com/browse/JVMCBC-466[JVMCBC-466]: When
continuousKeepAlive is enabled, closed sockets would still try to
run the keepalive, which could lead to reconnect attempts of nodes
that are not needed anymore and "runaway" sockets.
* https://issues.couchbase.com/browse/JVMCBC-465[JVMCBC-465],
https://issues.couchbase.com/browse/JVMCBC-467[JVMCBC-467]: Some
changes have been made to the reconnection logic so there are no
concurrent reconnect attempts. This fixes a problem where upgrading
from < 5.0 Server releases to > 5.0 Server releases wasn't
possible without restarting the application server.
* https://issues.couchbase.com/browse/JVMCBC-460[JVMCBC-460]:
Discover FTS SSL through config
* https://issues.couchbase.com/browse/JVMCBC-445[JVMCBC-445]:
ArrayOutOfBoundException in PooledService#sendFlush (concurrent
access on list)
* https://issues.couchbase.com/browse/JVMCBC-448[JVMCBC-448]:
Sporadic Unhandled Select Bucket status 1
* https://issues.couchbase.com/browse/JVMCBC-435[JVMCBC-435]: Issue
with number of java client connections increasing rapidly after fail
over on single node in cluster

== Version 2.4.7 (12 July 2017)

Version 2.4.7 is the eighth release of the 2.4 series, bringing
enhancements and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.4.7/Couchbase-Java-Client-2.4.7.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.4.7/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.4.7/[Core
API
Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.4.7**
* com.couchbase.client:**core-io:1.4.7**
* io.reactivex:**rxjava:1.2.7**

=== Enhancements & New Features

* https://issues.couchbase.com/browse/JVMCBC-433[JVMCBC-433]: X.509
client side certificate support has been added.
* https://issues.couchbase.com/browse/JVMCBC-436[JVMCBC-436]:
KeepAlives are now able to detect and recycle dead tcp
connections/channels.
* https://issues.couchbase.com/browse/JVMCBC-434[JVMCBC-434]:
Support for "Enhanced Error Messages" has been added for Couchbase
Server 5.0
* https://issues.couchbase.com/browse/JVMCBC-430[JVMCBC-430]:
Support for createDocument flag in subdoc single path mutations for
Couchbase Server 5.0

=== Fixed Issues

* https://issues.couchbase.com/browse/JVMCBC-423[JVMCBC-423]: Timed
out (unsubscribed) operations are discarded and not sent over the
network anymore, leading to less overload of the whole core system
in failure situations
* https://issues.couchbase.com/browse/JVMCBC-439[JVMCBC-439]:
Fixed prepared statement dispatching with node hostname
* https://issues.couchbase.com/browse/JCBC-1090[JCBC-1090]:
Fixed DNS SRV Regression caused by JCBC-1079

== Version 2.4.6 (6 June 2017)

Version 2.4.6 is the seventh release of the 2.4 series, bringing
enhancements and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.4.6/Couchbase-Java-Client-2.4.6.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.4.6/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.4.6/[Core
API
Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.4.6**
* com.couchbase.client:**core-io:1.4.6**
* io.reactivex:**rxjava:1.2.7**

=== Enhancements & New Features

* https://issues.couchbase.com/browse/JVMCBC-427[JVMCBC-427]: The
SDK forces to use IPv4 addresses, even if the JVM is configured to
force IPv6 lookups (since the server only supports v4 right now).
* http://issues.couchbase.com/browse/JCBC-1080[JCBC-1080]: It is now
possible to read and write full documents through the
Subdocument-API when "xattr" is enabled.
* http://issues.couchbase.com/browse/JCBC-1078[JCBC-1078]: The
experimental API for extended attributes on the Subdocument-API has
been renamed to "xattr" for consistency reasons.
* http://issues.couchbase.com/browse/JCBC-1079[JCBC-1079]: When the
"com.couchbase.allowReverseDns" System property is set to false, the
SDK will avoid all reverse DNS lookups, making it possible to run
under constrained network setups. The downside of course is that
pretty hostnames can't be used in logging and IPs must be showed all
the time.

=== Fixed Issues

* https://issues.couchbase.com/browse/JVMCBC-428[JVMCBC-428]: The
HTTP Status code 401 is now correctly mapped internally to an
Authentication Error (instead of a generic failure). This should not
change anything on the user-facing API. 

=== Known Issues

* https://issues.couchbase.com/browse/JCBC-1090[JCBC-1090]: A known
regression over 2.4.5 which prevents DNS SRV bootstrap from working
correctly. This will be fixed in 2.4.7, if you are using DNS SRV
bootstrap please use 2.4.5 for now and upgrade once 2.4.7 has been
released.

== Version 2.4.5 (2 May 2017)

Version 2.4.5 is the sixth release of the 2.4 series, bringing
enhancements and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.4.5/Couchbase-Java-Client-2.4.5.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.4.5/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.4.5/[Core
API
Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.4.5**
* com.couchbase.client:**core-io:1.4.5**
* io.reactivex:**rxjava:1.2.7**

=== Enhancements & New Features

* https://issues.couchbase.com/browse/JCBC-1066[JCBC-1066]: Add
support for FTS Geo & TermRange Queries & Advanced Sort for
Couchbase Server 5.0
* https://issues.couchbase.com/browse/JCBC-1055[JCBC-1055]: Add
support for ephemeral bucket management for Couchbase Server 5.0
* https://issues.couchbase.com/browse/JCBC-1072[JCBC-1072]: Add
covenient authenticate overload for Couchbase Server 5.0
* http://issues.couchbase.com/browse/JCBC-1068[JCBC-1068]: Add dsl
support to ANY AND EVERY expression
* https://issues.couchbase.com/browse/JCBC-1074[JCBC-1074]:  Support
GetUsers change in returning domain instead of type for Couchbase
Server 5.0
* https://issues.couchbase.com/browse/JVMCBC-415[JVMCBC-415]:
Enforce CarrierRefresher poll floor for Couchbase Server 5.0 fast
failover support
* https://issues.couchbase.com/browse/JVMCBC-417[JVMCBC-417]: Shift
the carrier node refresh list on each attempt
* https://issues.couchbase.com/browse/JVMCBC-418[JVMCBC-418]: Add
mock support for kv error map integration test
* https://issues.couchbase.com/browse/JVMCBC-419[JVMCBC-419]:
 Support changes in user management rest endpoints due to rename of
builtin to local for Couchbase Server 5.0

=== Fixed Issues

* https://issues.couchbase.com/browse/JCBC-1015[JCBC-1067]: Expose
configPollInterval configurable from CouchbaseEnvironment builder.
* https://issues.couchbase.com/browse/JVMCBC-421[JVMCBC-413]:  Allow
to run HELLO after auth for optional backward compatibility support
for older Couchbase Server versions(less than 3.0).
* https://issues.couchbase.com/browse/JVMCBC-421[JVMCBC-421]: Close
LatencyStats on removal to avoid GC doing additional work by
explicitly cleaning up weak references. 

== Version 2.4.4 (4 April 2017)

Version 2.4.4 is the fifth release of the 2.4 series, bringing
enhancements and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.4.4/Couchbase-Java-Client-2.4.4.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.4.4/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.4.4/[Core
API
Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.4.4**
* com.couchbase.client:**core-io:1.4.4**
* io.reactivex:**rxjava:1.2.7**

=== Enhancements & New Features

* http://issues.couchbase.com/browse/JVMCBC-394[JVMCBC-394], http://issues.couchbase.com/browse/JCBC-1060[JCBC-1060]: 
Add username/password auth for support of RBACs in Couchbase Server
5.0.
* http://issues.couchbase.com/browse/JVMCBC-405[JVMCBC-405], http://issues.couchbase.com/browse/JCBC-1058[JCBC-1058]: 
Add support for user management in Couchbase Server 5.0.
* http://issues.couchbase.com/browse/JVMCBC-393[JVMCBC-393]:  Add
support for the extended KV error map in Couchbase Server 5.0.
* http://issues.couchbase.com/browse/JVMCBC-399[JVMCBC-399]: 
Perform HELLO before AUTH
* http://issues.couchbase.com/browse/JVMCBC-404[JVMCBC-404]:  Bump
Dependencies
* http://issues.couchbase.com/browse/JVMCBC-401[JVMCBC-401]: 
propagate error on endpoint encode
* http://issues.couchbase.com/browse/JVMCBC-408[JVMCBC-408]: 
Deprecate DCP
* http://issues.couchbase.com/browse/JVMCBC-410[JVMCBC-410]:  Allow
to configure the config polling interval
* http://issues.couchbase.com/browse/JVMCBC-409[JVMCBC-409]: 
Resolve addresses when parsing ConnectionString
* http://issues.couchbase.com/browse/JVMCBC-411[JVMCBC-411]:  Use
ports when building partitioned nodes list
* http://issues.couchbase.com/browse/JVMCBC-396[JVMCBC-396], http://issues.couchbase.com/browse/JCBC-1061[JCBC-1061]: 
Support to parse profiling info from N1QL query response
* http://issues.couchbase.com/browse/JCBC-1062[JCBC-1062]:  Optimize
LegacyTranscoder encoding for strings

=== Fixed Issues

* http://issues.couchbase.com/browse/JVMCBC-407[JVMCBC-407]:  Clean
up stateful resources on ConfigurationProvider termination
* http://issues.couchbase.com/browse/JVMCBC-403[JVMCBC-403]:  Fix
incorrect escape processing in streaming parser
* http://issues.couchbase.com/browse/JVMCBC-402[JVMCBC-402]:  Fix
ignored callbacksOnIoPool in N1ql and Analytics query row callbacks
* http://issues.couchbase.com/browse/JVMCBC-412[JVMCBC-412]:  Fix
extras leak on IllegalReferenceCountException
* http://issues.couchbase.com/browse/JCBC-1065[JCBC-1065]:  Fix api
doc to correctly mention about DesignDocumentDoesNotExistException
* http://issues.couchbase.com/browse/JCBC-1063[JCBC-1063]:  Never
compress JSON in LegacyDocument.

== Version 2.4.3 (7 March 2017)

Version 2.4.3 is the fourth release of the 2.4 series, bringing
enhancements and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.4.3/Couchbase-Java-Client-2.4.3.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.4.3/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.4.3/[Core
API
Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.4.3**
* com.couchbase.client:**core-io:1.4.3**
* io.reactivex:**rxjava:1.2.3**

=== Enhancements & New Features

This release fixes the following issues:

* http://issues.couchbase.com/browse/JVMCBC-391[JVMCBC-391]:  Fixes
a bug where empty documents can be written to server on NMV
rescheduling, if SSL is used
* http://issues.couchbase.com/browse/JCBC-1030[JCBC-1030], http://issues.couchbase.com/browse/JVMCBC-390[JVMCBC-390]: 
Add experimental support for Couchbase Analytics.
* http://issues.couchbase.com/browse/JVMCBC-395[JVMCBC-395]:  Add
support for detecting Ephemeral buckets using bucket capabilities in
configuration and short circuit persistTo calls
* http://issues.couchbase.com/browse/JVMCBC-392[JVMCBC-392]: 
Integrate an optional generic json parser yasjl for parsing N1QL
query responses
* http://issues.couchbase.com/browse/JVMCBC-397[JVMCBC-397]:  Avoid
concurrent modification/reading of bucketConfigs map
* http://issues.couchbase.com/browse/JCBC-1043[JCBC-1043]:  Add
toString for N1QL Rows and Sync Result
* http://issues.couchbase.com/browse/JCBC-1045[JCBC-1045]: 
Pre-check connection string to avoid IOOB exception

== Version 2.4.2 (9 February 2017)

Version 2.4.2 is the third release of the 2.4 series, bringing
enhancements and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.4.2/Couchbase-Java-Client-2.4.2.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.4.2/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.4.2/index.html[Core
API
Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.4.2**
* com.couchbase.client:**core-io:1.4.2**
* io.reactivex:**rxjava:1.2.3**

=== Enhancements & New Features

This release fixes the following issues:

* http://issues.couchbase.com/browse/JVMCBC-380[JVMCBC-380]
https://issues.couchbase.com/browse/JVMCBC-385[JVMCBC-385]: To
address a potential performance regression introduced in 2.4.1 with
N1QL (due to disabling the pipelining for ensuring correctness) the
Service pooling has been overhauled completely, leading to better
out of the box performance and more flexibility.
* http://issues.couchbase.com/browse/JVMCBC-341[JVMCBC-341]: The FTS
service endpoint has been equipped with application-level keepalive
(similar to the other services), bringing it in line functionality
wise with its counterparts. It uses the internal _/admin/ping_ HTTP
endpoint.
* http://issues.couchbase.com/browse/JCBC-1028[JCBC-1028],
http://issues.couchbase.com/browse/JVMCBC-384[JVMCBC-384]:
Experimental support for "Extended Attributes" (XATTR) has been
added to the API in preparation for Couchbase Server 5.0.

== Version 2.4.1 (19 January 2017)

Version 2.4.1 is the second release of the 2.4 series, bringing small
enhancements and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.4.1/Couchbase-Java-Client-2.4.1.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.4.1/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.4.1/index.html[Core
API
Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.4.1**
* com.couchbase.client:**core-io:1.4.1**
* io.reactivex:**rxjava:1.2.3**

=== Fixed Issues

This release fixes the following issues:

* http://issues.couchbase.com/browse/JVMCBC-380[JVMCBC-380], http://issues.couchbase.com/browse/JVMCBC-381[JVMCBC-381]:
Pipelining for all HTTP-based services has been disabled (N1QL, FTS,
Views) because it is not properly supported on the server side and
can lead to inconsistent responses that are hard to identify and
track down. Everyone who has had problems with N1QL queries
returning successfully, but only partial results are recommended to
upgrade.
 *If you are experiencing slowdown of your queries, you need to
increase the number of queryEndpoints to a higher setting in order
to allow for concurrent requests. In the future we are planning on a
more flexible pool implementation, but setting the queryEndpoints to
a fixed higher value (i.e. the number of application threads
concurrently querying) will help as well.*
* http://issues.couchbase.com/browse/JCBC-999[JCBC-999], http://issues.couchbase.com/browse/JVMCBC-383[JVMCBC-383]:
The BucketManager#info() method and equivalents are now properly
redistributing the underlying request to other servers if the first
one tried is not available. This increases the reliability of info
calls significantly.
* http://issues.couchbase.com/browse/JCBC-1037[JCBC-1037]: If a FTS
query is issued against a nonexistent index, it now properly errors
with a IndexDoesNotExistException, bringing it on-par with other
APIs in similar situations.

== Version 2.3.7 (19 January 2017)

Version 2.3.7 is the eigth release of the 2.3 series, bringing small
enhancements and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.3.7/Couchbase-Java-Client-2.3.7.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.3.7/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.3.7/index.html[Core
API
Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.3.7**
* com.couchbase.client:**core-io:1.3.7**
* io.reactivex:**rxjava:1.1.8**

=== Fixed Issues

This release fixes the following issues:

* http://issues.couchbase.com/browse/JVMCBC-380[JVMCBC-380], http://issues.couchbase.com/browse/JVMCBC-381[JVMCBC-381]:
Pipelining for all HTTP-based services has been disabled (N1QL, FTS,
Views) because it is not properly supported on the server side and
can lead to inconsistent responses that are hard to identify and
track down. Everyone who has had problems with N1QL queries
returning successfully, but only partial results are recommended to
upgrade.
 *If you are experiencing slowdown of your queries, you need to
increase the number of queryEndpoints to a higher setting in order
to allow for concurrent requests. In the future we are planning on a
more flexible pool implementation, but setting the queryEndpoints to
a fixed higher value (i.e. the number of application threads
concurrently querying) will help as well.*
* http://issues.couchbase.com/browse/JCBC-999[JCBC-999],
http://issues.couchbase.com/browse/JVMCBC-383[JVMCBC-383]: The
BucketManager#info() method and equivalents are now properly
redistributing the underlying request to other servers if the first
one tried is not available. This increases the reliability of info
calls significantly.
* Thanks to a community contribution, CouchbaseException subclasses
without a message are now properly propagating stack traces.

== Version 2.4.0 (5 January 2017)

Version 2.4.0 is the first release of the 2.4 series, bringing small
enhancements and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.4.0/Couchbase-Java-Client-2.4.0.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.4.0/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.4.0/index.html[Core
API
Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:2.4.0**
* com.couchbase.client:**core-io:1.4.0**
* io.reactivex:**rxjava:1.2.3**

=== New Features and Behavioral Changes

This release contains the following enhancements:

* RxJava has been updated to 1.2.3, which is backwards compatible to
1.1. which was used in the java-client 2.3.6.
* https://issues.couchbase.com/browse/JCBC-1021[JCBC-1021]: Support
for BigDecimal and BigInteger has been added to JsonObject and
JsonArray, making it easier to work with those types naturally.
* http://issues.couchbase.com/browse/JCBC-974[JCBC-974]: For
consistency reasons, the BucketManager now throws
DesignDocumentDoesNotExist in such cases instead of returning
different errors. It is now in-line with similar methods, providing
a more coherent API experience.
* http://issues.couchbase.com/browse/JCBC-1022[JCBC-1022],
http://issues.couchbase.com/browse/JCBC-1032[JCBC-1032]: Both the
bucket-level collections API, as well as the Authenticator APIs have
been marked as stable and can thus be considered supported API.
* http://issues.couchbase.com/browse/JVMCBC-378[JVMCBC-378]:
Optional support for custom IO pools per service has been added. By
default still one IO pool will be used, but it is possible to
override this now on a per-service basis. This has the nice effect
of being able to use different IO event loops for different
workloads (high throughput KV vs long running N1QL queries for
example).
* http://issues.couchbase.com/browse/JVMCBC-373[JVMCBC-373]: onError
calls are now also moved (by default) onto the computation
scheduler, similar to onNext calls.

=== Fixed Issues

This release fixes the following issues:

* https://issues.couchbase.com/browse/JCBC-1029[JCBC-1029:] A bug
with Long-running prepared N1QL query observables which may be
released too early and thus cannot be subscribed to has been fixed. 

== Version 2.3.6 (6 December 2016)

Version 2.3.6 is the seventh release of the 2.3 series, bringing small
enhancements and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.3.6/Couchbase-Java-Client-2.3.6.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.3.6/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.3.6/index.html[Core
API
Reference]

=== New Features and Behavioral Changes

This release contains the following enhancements:

* https://issues.couchbase.com/browse/JCBC-1024[JCBC-1024]: Add
"sort" option to FTS query.  Allows custom sort order for search
queries.
* https://issues.couchbase.com/browse/JCBC-1020[JCBC-1020]:
Collections interface for data structures
* https://issues.couchbase.com/browse/JCBC-981[JCBC-981]: Add
toString() on N1qlQuery
* https://issues.couchbase.com/browse/JCBC-1023[JCBC-1023]: Ignore
FTS integration tests if search service not found
* https://issues.couchbase.com/browse/JVMCBC-376[JVMCBC-376]: Add
support for legacy memcached node hashing as it is different in 2.x
series compared to 1.x. Legacy hashing can be turned on by
using LegacyMemcachedHashingStrategy in the environment builder. 
*Important:* _If you need interoperability between Java and other
SDKs when writing and/or reading to memcached buckets, you must pick
the LegacyMemcachedHashingStrategy since the Default one is not
compatible across languages  (and between Java 1.x and 2.x)_
* https://issues.couchbase.com/browse/JVMCBC-375[JVMCBC-375]:
Extract SSL related settings into SecureEnvironment.

=== Fixed Issues

This release fixes the following issues:

* https://issues.couchbase.com/browse/JCBC-1026[JCBC-1026:] Early
unsubscription can trigger buffer leaks.  If early unsubscribes on
the KV API are performed (that is, the async API is used and an
operator like timeout() fires before the data could be decoded and
the underlying buffers freed) the buffers from the decoding
operation are not freed and leak.
* https://issues.couchbase.com/browse/JCBC-1016[JCBC-1016]: Throw
PathNotFound instead of SUBDOC_PATH_NOT_FOUND on index not found
in List and key not found in Map
* https://issues.couchbase.com/browse/JCBC-1017[JCBC-1017], https://issues.couchbase.com/browse/JCBC-1018[JCBC-1018]:
Fix inconsistencies with the data structures RFC

== Version 2.3.5 (3 November 2016)

Version 2.3.5 is the sixth release of the 2.3 series, bringing small
enhancements and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.3.5/Couchbase-Java-Client-2.3.5.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.3.5/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.3.5/index.html[Core
API
Reference]

=== New Features and Behavioral Changes

This release contains the following enhancements:

* https://issues.couchbase.com/browse/JCBC-900[JCBC-900]:
Experimental support for Bucket-Level Datastructures has been added,
which advance the concept of subdocument APIs to actual programmable
datastructures like sets and maps in a cross-SDK fashion.
* https://issues.couchbase.com/browse/JCBC-1015[JCBC-1015]: When
performing a N1QL Query against Couchbase Server 4.5.1 or later you
can now specify the "pretty" param on the N1QL query params to
optimize network bandwith.

 

=== Fixed Issues

This release fixes the following issues:

* https://issues.couchbase.com/browse/JVMCBC-371[JVMCBC-371]: A
safeguard has been put into place that if the underlying network
"connect" call never returns for some reason it is now cut short
after a given delay and declared faulty to give the built-in retry
mechanisms a chance to run. By default this time is defined as 2
seconds over the "socket connect timeout" and can be customized
through the "com.couchbase.connectCallbackGracePeriod" system
property.
* https://issues.couchbase.com/browse/JVMCBC-372[JVMCBC-372]: The
internal sentRequestQueue for each socket has been subject to an
edge case where when the socket accepts requests but never returns
results (acting like a "black hole" and not closing the socket
either) the internal queue which matches the responses to the
requests can grow unbounded. This is now fixed and set to a size of
5120 outstanding requests per socket, customizable through the
"com.couchbase.sentRequestQueueLimit" system property. If the queue
grows too large the overflowing requests get put into the regular
retry cycle giving them a chance to complete eventually.
* https://issues.couchbase.com/browse/JVMCBC-370[JVMCBC-370]: The
internal DCP implementation has had a couple bugfixes around MDS
deployments.

 

== Version 2.3.4 (5 October 2016)

Version 2.3.4 is the fifth release of the 2.3 series, bringing small
enhancements and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.3.4/Couchbase-Java-Client-2.3.4.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.3.4/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.3.4/index.html[Core
API
Reference]

=== New Features and Behavioral Changes

This release contains the following enhancements:

* https://issues.couchbase.com/browse/JCBC-851[JCBC-851]:
Experimental support for cluster-level N1QL queries has been added
to the Cluster interface. Note that at least one bucket needs to be
open and the credentials need to be set properly using the
authenticate method in order to use this feature.
* https://issues.couchbase.com/browse/JVMCBC-365[JVMCBC-365]: When
using SCRAM SASL authentication mechanisms during bootstrap and an
error happens, the resulting error message now more clearly
indicates what is going on. Most likely the JVM does not support
empty keys for passwords, so either the JVM needs to be upgraded to
a newer version or a bucket password should be set (which we
recommend to do so anyways).

 

=== Fixed Issues

This release fixes the following issues:

* https://issues.couchbase.com/browse/JCBC-1007[JCBC-1007]: N1QL,
FTS and View queries are now properly evenly distributed in
MDS-scenarios.
* https://issues.couchbase.com/browse/JVMCBC-368[JVMCBC-368]: A
classloader leak on redeploy has been discovered and fixed in the
PauseDetector part of the metrics collection.

 

== Version 2.3.3 (6 September 2016)

Version 2.3.3 is the fourth release of the 2.3 series, bringing small
enhancements and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.3.3/Couchbase-Java-Client-2.3.3.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.3.3/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.3.3/index.html[Core API Reference]

=== New Features and Behavioral Changes

This release contains the following enhancements:

* https://issues.couchbase.com/browse/JCBC-995[JCBC-995]: Improved
custom transcoding for subdocument: optionalrawContent getter
on SubdocOperationResult, includeRaw option in the LookupInBuilders
(putting a copy of the raw JSON bytes into the result for GETs), new
abstract FragmentTranscoder that deals with byte arrays..
* https://issues.couchbase.com/browse/JCBC-901[JCBC-901]: The
experimental Authenticator interface has been introduced to store
implicit credentials for protected operations. Such operations for
now include opening a Bucket and getting aClusterManager instance.
* https://issues.couchbase.com/browse/JCBC-998[JCBC-998], https://issues.couchbase.com/browse/JVMCBC-357[JVMCBC-357]:
Added an experimental RawQueryExecutorwhich allows to execute N1QL
queries and get the raw JSON response from the server.
* https://issues.couchbase.com/browse/JVMCBC-361[JVMCBC-361]: When
a Node is DEGRADED, at least part of its Services are CONNECTED. As
such, a message can now be dispatched to a Node when it is either in
CONNECTED or DEGRADED state. The relevant Service will still have to
be CONNECTED for the message to go through, otherwise it will go
into the retry loop.
* https://issues.couchbase.com/browse/JVMCBC-358[JVMCBC-358]:
There's a new Endpoint selection strategy
(RoundRobinSelectionStrategy), which is used by theQueryEndpoint.
When several QueryEndpoints are configured, they will now properly
be used in a round-robin fashion.

=== Fixed Issues

This release fixes the following issues:

* https://issues.couchbase.com/browse/JVMCBC-364[JVMCBC-364]: The
query parser can fail when N1QL results are empty (no rows), in a
specific HTTP chunk configuration (where there is a split at the
"status" entry that follows the rows in the response).
* https://issues.couchbase.com/browse/JVMCBC-360[JVMCBC-360]: When
querying a view in reduce mode, the returnedinfo() section is empty
but the parser can leak a small amount of bytes. This has now been
fixed.

== Version 2.3.2 (10 August 2016)

Version 2.3.2 is the third release of the 2.3 series, bringing small
enhancements and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.3.2/Couchbase-Java-Client-2.3.2.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.3.2/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.3.2/[Core
API
Reference]

=== New Features and Behavioral Changes

This release contains the following enhancements:

* https://issues.couchbase.com/browse/JCBC-987[JCBC-987]: Support
for durability constraints (PersistTo and ReplicateTo) has been
added to subdocument's MutateInBuilder.
* https://issues.couchbase.com/browse/JCBC-982[JCBC-982]:
BucketSettings now exposes the raw bucket configuration when reading
from the server, and allows to provide parameters not covered by the
API when creating/updating buckets.
* https://issues.couchbase.com/browse/JCBC-983[JCBC-983],
https://issues.couchbase.com/browse/JVMCBC-350[JVMCBC-350]: Added
a simple client for cluster REST API to ClusterManager as a
ClusterApiClient. This is to easily send requests to nodes where the
REST API is exposed (usually on port 8091).
* https://issues.couchbase.com/browse/JVMCBC-342[JVMCBC-342]: When a
CouchbaseEnvironment is shutdown(), the internal counter used to
issue warnings in case of multiple environments is decreased.
Additionally an event is triggered on the EventBus.
* https://issues.couchbase.com/browse/JVMCBC-351[JVMCBC-351]: Don't
limit SSL to SunX509 algorithm but instead use the platform's
default. This default can always be changed at runtime via the
"ssl.KeyManagerFactory.algorithm" security property (set in the Java
security properties file or by calling Security.setProperty(...)).
Thanks to contributor @arana3!
* https://issues.couchbase.com/browse/JCBC-985[JCBC-985],
https://issues.couchbase.com/browse/JCBC-976[JCBC-976]:
Experimental FTS API enhancements: Fix fts errors handling/parsing,
StringQuery becomes QueryStringQuery, fix highlight style being
optional, renamed ScanConsistency to SearchConsistency.
* https://issues.couchbase.com/browse/JVMCBC-344[JVMCBC-344],
https://issues.couchbase.com/browse/JVMCBC-349[JVMCBC-349]:
RxJava, Disruptor and Netty internal dependencies have been updated
to their latest bugfix releases. Subsequently, usage of deprecated
Disruptor APIs have been refactored out.
* https://issues.couchbase.com/browse/JVMCBC-355[JVMCBC-355]:
Improves diagnosability of errors related to
UnicastAutoReleaseSubject by adding an identifier to these subjects.

=== Fixed Issues

This release fixes the following issues:

* https://issues.couchbase.com/browse/JCBC-984[JCBC-984]: Don't
broadcast query plan to non-query nodes when using prepared
statements.
* https://issues.couchbase.com/browse/JCBC-992[JCBC-992]: DNS SRV
workaround when default nameserver is IPv6: Bootstrap now allows to
provide an explicit value for java.naming.provider.url.
* https://issues.couchbase.com/browse/JVMCBC-345[JVMCBC-345],
https://issues.couchbase.com/browse/JVMCBC-346[JVMCBC-346],
https://issues.couchbase.com/browse/JVMCBC-347[JVMCBC-347]:
Various fixes linked to SDK bootstrap: Don't silently ignore
ConnectException, avoid subscribe() without error handler in
configuration/bootstrap Observables, maintain internal bootstrap
state in config provider. Fixed an issue where a node seen as down
during bootstrap would never be reconnected to later on, even when
it would come back online.
* https://issues.couchbase.com/browse/JVMCBC-348[JVMCBC-348]: Catch
exceptions that event bus consumers may trigger.
* https://issues.couchbase.com/browse/JVMCBC-352[JVMCBC-352]: Fixed
an issue with the N1QL streaming parser where some packet splitting
layouts would confuse the parser into interpreting results as RAW.
This would usually translate into either JSON parse errors (rows
emitted would be malformed JSON) or an IllegalStateException with
the "...in TRANSITION..." message.
* https://issues.couchbase.com/browse/JVMCBC-354[JVMCBC-354]: The
BucketManager#getDesignDocuments and associated
GetDesignDocumentsRequest hit an API that is only working on data
nodes (unlike the rest of 8091 APIs). Fixed an issue when, in a MDS
configuration, such request would incorrectly be sent to non-data
nodes.

== Version 2.3.1 (22 June 2016)

This release is the second release of the 2.3 series, bringing small
enhancements\
and bugfixes over the last stable release.

http://packages.couchbase.com/clients/java/2.3.1/Couchbase-Java-Client-2.3.1.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.3.1/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.3.1/[Core
API
Reference]

=== Fixed Issues

This release fixes the following issues:

* https://issues.couchbase.com/browse/JCBC-975[JCBC-975]: Replace
occurrences of StringBuffer with StringBuilder
* https://issues.couchbase.com/browse/JCBC-978[JCBC-978]: Fix Index
DSL "WITH nodes" option
* https://issues.couchbase.com/browse/JCBC-978[JVMCBC-343]:
WaitStrategy needs to be created for every CouchbaseCore

== Version 2.3.0 (10 June 2016)

Version 2.3.0 is the first general availability release of the 2.3
series. It adds new features for N1QL query, performance enhancements
and supports the developer preview full text search available in
Couchbase Server 4.5.

http://packages.couchbase.com/clients/java/2.3.0/Couchbase-Java-Client-2.3.0.zip[Download] | http://docs.couchbase.com/sdk-api/couchbase-java-client-2.3.0/[API
Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-1.3.0/[Core
API
Reference]

=== New features and behavioral changes

This release contains the following enhancements:

* https://issues.couchbase.com/browse/JVMCBC-271[JVMCBC-271]: The
long deprecated queryEnabled and queryPort environment params have
been removed since they are useless as of now.
* https://issues.couchbase.com/browse/JCBC-958[JCBC-958],
https://issues.couchbase.com/browse/JCBC-959[JCBC-959],
https://issues.couchbase.com/browse/JCBC-957[JCBC-957]: The
Fulltext-Search API has been heavily reworked and streamlined.
* https://issues.couchbase.com/browse/JCBC-954[JCBC-954],
https://issues.couchbase.com/browse/JCBC-971[JCBC-971]: The
subdocument APIs have been marked as stable and slightly polished.
* https://issues.couchbase.com/browse/JCBC-955[JCBC-955]: The N1QL
Index Management API has been marked as stable.
* https://issues.couchbase.com/browse/JVMCBC-333[JVMCBC-333]: A
custom KeyStore can now be passed in during CouchbaseEnvironment
setup (in addition to passing the keystore filepath).
* https://issues.couchbase.com/browse/JCBC-964[JCBC-964],
https://issues.couchbase.com/browse/JVMCBC-338[JVMCBC-338]:
Support for disabling metrics when performing a N1QL query to save
on the response size.
* https://issues.couchbase.com/browse/JVMCBC-334[JVMCBC-334]:
Support for N1QL SELECT RAW has been added.
* https://issues.couchbase.com/browse/JCBC-965[JCBC-965]: A generic
param option has been added to the N1qlParams class.
* RxJava has been updated to 1.1.5
* Retry logic during rebalance ("Not My VBucket") has been aligned
with the SDK
https://github.com/couchbaselabs/sdk-rfcs/issues/10[RFC].
* https://issues.couchbase.com/browse/JVMCBC-335[JVMCBC-335]: For
advanced use cases, the RingBuffer waiting strategy for the request
buffer can now be tuned. Use with care!

=== Fixed Issues

This release fixes the following issues:

* https://issues.couchbase.com/browse/JCBC-968[JCBC-968],
https://issues.couchbase.com/browse/JVMCBC-337[JVMCBC-337]: The
DocumentFragment does not carry the CAS on multi lookup, this issue
has been fixed.
* https://issues.couchbase.com/browse/JCBC-973[JCBC-973]: A
regression has been fixed where disabled flush on the bucket was not
surfaced as an exception inside the SDK when BucketManager#flush()
is called.
// end::latest[]

