= Install and Start Using the Java SDK with Couchbase Server
:navtitle: Start Using the SDK

[abstract]
The Couchbase Java SDK allows Java applications to access a Couchbase cluster.
It offers traditional synchronous APIs as well as scalable asynchronous APIs to maximize performance.

include::6.0@sdk:shared:partial$install-couchbase.adoc[tag=section_gb4_psc_kv]

[#java-installing-sdk]
== Installing the SDK

IMPORTANT: At least Java 6 is required, all newer Java versions are supported (and encouraged).
Especially Java 8 is recommended since it brings performance enhancements and lambda expressions which are very convenient when used in an asynchronous context.

All stable releases of the Java SDK are primarily distributed through Maven.
As a result the dependency can be included easily using your favorite package manager.
For Maven itself, it typically looks like this:

[source,xml]
----
<dependencies>
  <dependency>
    <groupId>com.couchbase.client</groupId>
    <artifactId>java-client</artifactId>
    <version>2.7.3</version>
  </dependency>
</dependencies>
----

The `java-client` dependency will pull in two more transitive dependencies.
One is called `com.couchbase.client.core-io` and is a internal dependency which performs all the underlying tasks like IO and cluster management.
The other dependency is `RxJava` which is both used internally and exposed as a first-class API to the user in order to perform scalable and performant asynchronous, reactive operations.

Information on new features, fixes, known issues as well as information on how to install older release versions is xref:sdk-release-notes.adoc[in the release notes].
You will also find other install options there, including a zip file which includes all transitive dependencies and Javadocs.

[#java-using-sdk]
== Using the SDK

The code snippet below shows how the Java SDK may be used for some common operations:

[source,java]
----
import com.couchbase.client.java.*;
import com.couchbase.client.java.document.*;
import com.couchbase.client.java.document.json.*;
import com.couchbase.client.java.query.*;

public class Example {

    public static void main(String... args) throws Exception {

        // Initialize the Connection
        Cluster cluster = CouchbaseCluster.create("localhost");
        cluster.authenticate("username", "password");
        Bucket bucket = cluster.openBucket("bucketname");

        // Create a JSON Document
        JsonObject arthur = JsonObject.create()
            .put("name", "Arthur")
            .put("email", "kingarthur@couchbase.com")
            .put("interests", JsonArray.from("Holy Grail", "African Swallows"));

        // Store the Document
        bucket.upsert(JsonDocument.create("u:king_arthur", arthur));

        // Load the Document and print it
        // Prints Content and Metadata of the stored Document
        System.out.println(bucket.get("u:king_arthur"));

        // Create a N1QL Primary Index (but ignore if it exists)
        bucket.bucketManager().createN1qlPrimaryIndex(true, false);

        // Perform a N1QL Query
        N1qlQueryResult result = bucket.query(
            N1qlQuery.parameterized("SELECT name FROM `bucketname` WHERE $1 IN interests",
            JsonArray.from("African Swallows"))
        );

        // Print each found Row
        for (N1qlQueryRow row : result) {
            // Prints {"name":"Arthur"}
            System.out.println(row);
        }
    }
}
----

[#java-connect-disconnect]
== Connecting & Disconnecting

Most of the operations performed against Couchbase are done against a [.api]`Bucket` instance.
A [.api]`Bucket` reference can be obtained through a [.api]`Cluster` reference which allows you to manage more buckets at the same time and reuse the underlying IO and computation resources efficiently.

To obtain a [.api]`Cluster` the [.api]`CouchbaseCluster#create` method needs to be called.
If no arguments are provided it will connect to a cluster listening on `localhost`.
Note that not all nodes of the cluster need to be passed it, just a few to allow it to bootstrap itself are enough.
We recommend more than one though since if one of the nodes happens to be not available during application startup it still has a chance to try another one and bootstrap properly.

To connect to a Couchbase bucket, you must use Couchbase _Role-Based Access Control_ (RBAC).
This is fully described in the section xref:6.0@server:learn:security/authorization-overview.adoc[Authorization].
A username and password for the current user must be specified.
Following successful authentication, the bucket can be opened.

Once the SDK has successfully reached one node it will throw your bootstrap list away and replace it with a complete up-to-date list of nodes in the cluster.

Here is how you can create a [.api]`Cluster` reference in a few different ways:

[source,java]
----
// Connects to localhost
Cluster cluster = CouchbaseCluster.create();

// Connects to a cluster on 10.0.0.1 and tries 10.0.0.2
// if the other one does not respond during bootstrap.
Cluster cluster = CouchbaseCluster.create("10.0.0.1", "10.0.0.2");
----

If you have an environment with port mapping, such as Couchbase Server and the SDK in separate containers under Kubernetes, see the multi-network configuration _note_ under xref:managing-connections.adoc#connecting-to-a-bucket[Managing Connections]

Once a [.api]`Cluster` reference is available, you can open [.api]`Bucket` instances and then perform operations on them:

[source,java]
----
// Connects to localhost
Cluster cluster = CouchbaseCluster.create();

// Authenticates
cluster.authenticate("username", "password");

// Opens the "myTestBucket" bucket
Bucket myTestBucket = cluster.openBucket("myTestBucket");
----

IMPORTANT: It is very important that cluster and bucket instances are created during startup and are then reused until the application shuts down.
Connection setup is expensive and the SDK is designed to be thread safe and can be efficiently used across all your application threads.

Finally you need to close the buckets and/or disconnect from the [.api]`Cluster`.
If a cluster disconnect is issued, all buckets will be automatically closed.

[source,java]
----
// Just close a single bucket
bucket.close();

// Disconnect and close all buckets
cluster.disconnect();
----

More information on managing connections including error handling can be found xref:managing-connections.adoc[here].

[#java-api-reference]
== API Reference

Each stable Java SDK version has the Javadocs API reference published.
The reference for the latest version can be found http://docs.couchbase.com/sdk-api/couchbase-java-client-2.7.4/[here^].

[#java-contributing]
== Contributing

Couchbase welcomes community contributions to the Java SDK.
The https://github.com/couchbase/couchbase-java-client[Java SDK source code^] is available on GitHub.
Please see the https://github.com/couchbase/couchbase-java-client/blob/master/CONTRIBUTING.md[CONTRIBUTING^] file for further information.
