= Distributed Transactions from the Java SDK
:description: A practical guide to using Couchbase’s distributed ACID transactions, via the Java API.
:navtitle: ACID Transactions
:page-partial:
:page-topic-type: howto
:page-aliases: acid-transactions


[abstract]
{description}

include::7.0@sdk:shared:partial$acid-transactions.adoc[tag=intro]

You may also want to start with our https://github.com/couchbaselabs/couchbase-transactions-java-examples[transactions examples repository],
which features useful downloadable examples of using Distributed Transactions.

Javadocs are available https://docs.couchbase.com/sdk-api/couchbase-transactions-java/index.html?overview-summary.html[online].


== Requirements

* Couchbase Server 6.6.1 or above.
* Couchbase Java client 3.1.5 or above.
It is recommended to follow the transitive dependency for the transactions library from Maven.
include::7.0@sdk:shared:partial$acid-transactions.adoc[tag=requirements]


== Getting Started

Couchbase transactions require no additional components or services to be configured. 
Simply add the transactions library into your project.
The latest version, as of July 2021, is 1.2.1.

With Gradle this can be accomplished by modifying these sections of your build.gradle file like so:

[source,gradle]
----
dependencies {
    compile group: 'com.couchbase.client', name: 'couchbase-transactions', version: '1.2.1'
}
----

Or with Maven:

[source,maven]
----
<dependency>
    <groupId>com.couchbase.client</groupId>
    <artifactId>couchbase-transactions</artifactId>
    <version>1.2.1</version>
</dependency>
----

This will automatically pull in any transitive dependencies of this library, including a compatible version of the Couchbase Java SDK.

A complete simple gradle project is available on our https://github.com/couchbaselabs/couchbase-transactions-java-examples[transactions examples repository].


== Initializing Transactions

To make it easy to use any of the following examples, here are all the imports used by them:

[source,java]
----
include::example$TransactionsExample.java[tag=imports,indent=0]
----

The starting point is the `Transactions` object.  
It is very important that the application ensures that only one of these is created, as it performs automated background processes that should not be duplicated.

[source,java]
----
include::example$TransactionsExample.java[tag=init,indent=0]
----


== Configuration

Transactions can optionally be globally configured at the point of creating the `Transactions` object:

[source,java]
----
include::example$TransactionsExample.java[tag=config,indent=0]
----

include::7.0@sdk:shared:partial$acid-transactions.adoc[tag=config]


include::7.0@sdk:shared:partial$acid-transactions.adoc[tag=creating]

As with the Couchbase Java Client, you can use the library in either synchronous mode:

[source,java]
----
include::example$TransactionsExample.java[tag=create,indent=0]
----

or asynchronous modes, using the Project Reactor reactive library:

[source,java]
----
include::example$TransactionsExample.java[tag=createReactive,indent=0]
----

The synchronous mode is the easiest to write and understand.
The asynchronous API allows you to build your application in a reactive style, which can help you scale with excellent efficiency.
Those new to reactive programming may want to check out https://projectreactor.io/[the Project Reactor site] for more details on this powerful paradigm.

include::7.0@sdk:shared:partial$acid-transactions.adoc[tag=lambda-ctx]

== Examples
A code example is worth a thousand words, so here is a quick summary of the main transaction operations.
They are described in more detail below. 

.With the synchronous API
[source,java]
----
include::example$TransactionsExample.java[tag=examples,indent=0]
----


.With the asynchronous API
[source,java]
----
include::example$TransactionsExample.java[tag=examplesReactive,indent=0]
----


include::7.0@sdk:shared:partial$acid-transactions.adoc[tag=mechanics]


== Key-Value Mutations

=== Replacing

Replacing a document requires a `ctx.get()` call first.
This is necessary so that the transactions library can check that the document is not involved in another transaction.
If it is, then the transactions library will handle this at the `ctx.replace()` point.  
Generally, this involves rolling back what has been done so far, and retrying the lambda.

.With the synchronous API:
[source,java]
----
include::example$TransactionsExample.java[tag=replace,indent=0]
----

.Asynchronous API:
[source,java]
----
include::example$TransactionsExample.java[tag=replaceReactive,indent=0]
----

=== Removing

As with replaces, removing a document requires a `ctx.get()` call first.

.Synchronous API:
[source,java]
----
include::example$TransactionsExample.java[tag=remove,indent=0]
----

.With the asynchronous API:
[source,java]
----
include::example$TransactionsExample.java[tag=removeReactive,indent=0]
----

NOTE: For those using the asynchronous API - some `ctx` methods, notably `ctx.remove()`, return `Mono<Void>`.
There is a common 'gotcha' with `Mono<Void>` in that it does not trigger a 'next' reactive event - only a 'completion' event.
This means that some reactive operators chained afterwards - including the common `flatMap` - will not trigger.
Generally, you will to do `ctx.remove(...).then(...)` rather than `ctx.remove(...).flatMap(...)`.

=== Inserting

.With the asynchronous API:
[source,java]
----
include::example$TransactionsExample.java[tag=insert,indent=0]
----

.With the synchronous API:
----
include::example$TransactionsExample.java[tag=insertReactive,indent=0]
----

== Key-Value Reads

There are two ways to get a document with Key-Value, `get` and `getOptional`:

[source,java]
----
include::example$TransactionsExample.java[tag=get,indent=0]
----

`get` will cause the transaction to fail with `TransactionFailed` (after rolling back any changes, of course).
It is provided as a convenience method so the developer does not have to check the `Optional` if the document must exist for the transaction to succeed.

Gets will 'read your own writes', e.g. this will succeed:

[source,java]
----
include::example$TransactionsExample.java[tag=getReadOwnWrites,indent=0]
----

include::7.0@sdk:shared:partial$acid-transactions.adoc[tag=query-intro]

=== Using N1QL
If you already use N1QL from the Java SDK, then its use in transactions is very similar.
it returns the same `QueryResult` you are used to, and takes most of the same options.

You must take create to write `ctx.query()` inside the lambda however, rather than `cluster.query()` or `scope.query()`.

An example of SELECTing some rows from the `travel-sample` bucket:

[source,java]
----
include::example$TransactionsExample.java[tag=queryExamplesSelect,indent=0]
----

Rather than specifying the full "`travel-sample`.inventory.hotel" name each time, it is easier to pass a reference to the inventory `Scope`:

[source,java]
----
include::example$TransactionsExample.java[tag=queryExamplesSelectScope,indent=0]
----

An example using a `Scope` for an UPDATE:

[source,java]
----
include::example$TransactionsExample.java[tag=queryExamplesUpdate,indent=0]
----

=== Read Your Own Writes
As with Key-Value operations, N1QL queries support Read Your Own Writes.

This example shows INSERTing a document and then SELECTing it again.

[source,java]
----
include::example$TransactionsExample.java[tag=queryInsert,indent=0]
----
<1> The inserted document is only staged at this point. as the transaction has not yet committed.
Other transactions, and other non-transactional actors, will not be able to see this staged insert yet.
<2> But the SELECT can, as we are reading a mutation staged inside the same transaction.

=== Mixing Key-Value and N1QL
Key-Value operations and queries can be freely intermixed, and will interact with each other as you would expect.

In this example we insert a document with Key-Value, and read it with a SELECT.
<1> As with the 'Read Your Own Writes' example, here the insert is only staged, and so it is not visible to other transactions or non-transactional actors.
<2> But the SELECT can view it, as the insert was in the same transaction.

[source,java]
----
include::example$TransactionsExample.java[tag=queryRyow,indent=0]
----


=== Query Options
Query options can be provided via `TransactionsQueryOptions`, which provides a subset of the options in the Java SDK's `QueryOptions`.

[source,java]
----
include::example$TransactionsExample.java[tag=queryOptions,indent=0]
----

include::7.0@sdk:shared:partial$acid-transactions.adoc[tag=query-options]

See the xref:howtos:n1ql-queries-with-sdk.adoc#query-options[QueryOptions documentation] for details on these.

include::7.0@sdk:shared:partial$acid-transactions.adoc[tag=query-perf]

include::7.0@sdk:shared:partial$acid-transactions.adoc[tag=query-single]

[source,java]
----
include::example$TransactionsExample.java[tag=querySingle,indent=0]
----

You can also run a single query transaction against a particular `Scope` (these examples will exclude the full error handling for brevity):

[source,java]
----
include::example$TransactionsExample.java[tag=querySingleScoped,indent=0]
----

and configure it:

[source,java]
----
include::example$TransactionsExample.java[tag=querySingleConfigured,indent=0]
----

== Committing

Committing is automatic: if there is no explicit call to `ctx.commit()` at the end of the transaction logic callback, and no exception is thrown, it will be committed.

With the asynchronous API, if you leave off the explicit call to `commit` then you may need to call `.then()` on the result of the chain to convert it to the required `Mono<Void>` return type:

[source,java]
----
include::example$TransactionsExample.java[tag=commit,indent=0]
----

As soon as the transaction is committed, all its changes will be atomically visible to reads from other transactions.
The changes will also be committed (or "unstaged") so they are visible to non-transactional actors, in an eventually consistent fashion.

Commit is final: after the transaction is committed, it cannot be rolled back, and no further operations are allowed on it.

An asynchronous cleanup process ensures that once the transaction reaches the commit point, it will be fully committed - even if the application crashes.


// == A Full Transaction Example
include::7.0@sdk:shared:partial$acid-transactions.adoc[tag=example]

A complete version of this example is available on our https://github.com/couchbaselabs/couchbase-transactions-java-examples[GitHub transactions examples page].

[source,java]
----
include::example$TransactionsExample.java[tag=full,indent=0]
----


// concurrency
include::7.0@sdk:shared:partial$acid-transactions.adoc[tag=concurrency]

[source,java]
----
include::example$TransactionsExample.java[tag=concurrency,indent=0]
----

These events will be raised in the event of a non-transactional write being detected and overridden.
The event contains the key of the document involved, to aid the application with debugging.


== Rollback

If an exception is thrown, either by the application from the lambda, or by the transactions library, then that attempt is rolled back.
The transaction logic may or may not be retried, depending on the exception.
//- see link:#error-handling[Error handling and logging].

If the transaction is not retried then it will throw a `TransactionFailed` exception, and its `getCause` method can be used for more details on the failure.

The application can use this to signal why it triggered a rollback, as so:

[source,java]
----
include::example$TransactionsExample.java[tag=rollback-cause,indent=0]
----

The transaction can also be explicitly rolled back:

[source,java]
----
include::example$TransactionsExample.java[tag=rollback,indent=0]
----

In this case, if `ctx.rollback()` is reached, then the transaction will be regarded as successfully rolled back and no TransactionFailed will be thrown.

After a transaction is rolled back, it cannot be committed, no further operations are allowed on it, and the library will not try to automatically commit it at the end of the code block.


//  Error Handling
include::7.0@sdk:shared:partial$acid-transactions.adoc[tag=error]



//  txnfailed
include::7.0@sdk:shared:partial$acid-transactions.adoc[tag=txnfailed]

[source,java]
----
include::example$TransactionsExample.java[tag=config-expiration,indent=0]
----

include::7.0@sdk:shared:partial$acid-transactions.adoc[tag=txnfailed1]

Similar to `TransactionResult`, `SingleQueryTransactionResult` also has an `unstagingComplete()` method.

=== Full Error Handling Example

Pulling all of the above together, this is the suggested best practice for error handling:

[source,java]
----
include::example$TransactionsExample.java[tag=full-error-handling,indent=0]
----


include::7.0@sdk:shared:partial$acid-transactions.adoc[tag=cleanup]

=== Monitoring Cleanup

If the application wishes to monitor cleanup it may subscribe to these events:

[source,java]
----
include::example$TransactionsExample.java[tag=cleanup-events,indent=0]
----

`TransactionCleanupEndRunEvent` is raised whenever a current 'run' is finished, and contains statistics from the run.
(A run is typically around every 60 seconds, with default configuration.)

A `TransactionCleanupAttempt` event is raised when an expired transaction was found by this process, and a cleanup attempt was made.
It contains whether that attempt was successful, along with any logs relevant to the attempt.

In addition, if cleanup fails to cleanup a transaction that is more than two hours past expiry, it will raise the `TransactionCleanupAttempt` event at WARN level (rather than the default DEBUG).
With most default configurations of the event-bus (see <<Logging>> below), this will cause that event to be logged somewhere visible to the application.
If there is not a good reason for the cleanup to be failed (such as a downed node that has not yet been failed-over), then the user is encouraged to report the issue.

== Logging

To aid troubleshooting, each transaction maintains a list of log entries, which can be logged on failure like this:

[source,java]
----
include::example$TransactionsExample.java[tag=logging,indent=0]
----

or for the asynchronous API:

[source,java]
----
include::example$TransactionsExample.java[tag=async_logging,indent=0]
----

A failed transaction can involve dozens, even hundreds, of lines of logging, so the application may prefer to write failed transactions into a separate file.

For convenience there is also a config option that will automatically write this programmatic log to the standard Couchbase Java logging configuration inherited from the SDK if a transaction fails.
This will log all lines of any failed transactions, to `WARN` level:
[source,java]
----
include::example$TransactionsExample.java[tag=config_warn,indent=0]
----


By default the Couchbase Java logging event-bus is setup to look for and use SLF4J/logback, log4j1, and log4j2 on the classpath, and to fallback to java.util.Logging.  

Please see the xref:howtos:collecting-information-and-logging.adoc[Java SDK logging documentation] for details.

Most applications will have their own preferred Java logging solution in-place already.
For those starting from scratch here is a complete example using the basic `java.util.Logging`:

[source,java]
----
include::example$TransactionsExample.java[tag=full-logging,indent=0]
----


== Tracing
[.status]#Developer Preview#

The 1.1.6 release introduces support, at a Developer Preview level, for detailed tracing.
This telemetry is particularly useful for monitoring performance.

Note: Developer Preview here means the feature works and is safe to use, but the naming of spans and attributes, and which spans are created, may change before this feature is generally available.

If the underlying Couchbase Java SDK is configured for tracing, then no further work is required: transaction spans will be output automatically.
See the xref:howtos:observability-tracing.adoc[Couchbase Java SDK Request Tracing documentation] for how to configure this.

=== Parent Spans

While the above is sufficient to use and output transaction spans, the application may wish to indicate that the transaction is part of a larger span -- for instance, a user request.
It can do this by passing that as a parent span.

If you have an existing OpenTelemetry span you can easily convert it to a Couchbase `RequestSpan` and pass it to the transactions library:

[source,java]
----
include::example$TransactionsExample.java[tag=tracing-wrapped,indent=0]
----

== Concurrent Operations with the Async API

The async API allows operations to be performed concurrently inside a transaction, which can assist performance.
There are two rules the application needs to follow:

* The first mutation must be performed alone, in serial.
This is because the first mutation also triggers the creation of metadata for the transaction.
* All concurrent operations must be allowed to complete fully, so the transaction library can track which operations need to be rolled back in the event of failure.
This means the application must 'swallow' the error, but record that an error occurred, and then at the end of the concurrent operations, if an error occurred, throw an error to cause the transaction to retry.

These rules are demonstrated here:

[source,java]
----
include::example$TransactionsExample.java[tag=concurrentOps,indent=0]
----


include::7.0@sdk:shared:partial$acid-transactions.adoc[tag=custom-metadata-1]

[source,java]
----
include::example$TransactionsExample.java[tag=custom-metadata,indent=0]
----

include::7.0@sdk:shared:partial$acid-transactions.adoc[tag=custom-metadata-2]


== Deferred Commits

NOTE: The deferred commit feature is currently in alpha, and the API may change.

Deferred commits allow a transaction to be paused just before the commit point.
Optionally, everything required to finish the transaction can then be bundled up into a context that may be serialized into a String or byte array, and deserialized elsewhere (for example, in another process).
The transaction can then be committed, or rolled back.

The intention behind this feature is to allow multiple transactions, potentially spanning multiple databases, to be brought to just before the commit point, and then all committed together.

Here's an example of deferring the initial commit and serializing the transaction:

[source,java]
----
include::example$TransactionsExample.java[tag=defer1,indent=0]
----

And then committing the transaction later:

[source,java]
----
include::example$TransactionsExample.java[tag=defer2,indent=0]
----

Alternatively the transaction can be rolled back:

[source,java]
----
include::example$TransactionsExample.java[tag=defer3,indent=0]
----

The transaction expiry timer (which is configurable) will begin ticking once the transaction starts, and is not paused while the transaction is in a deferred state.



include::7.0@sdk:shared:partial$acid-transactions.adoc[tag=further]
