= Diagnosing and preventing Network Problems with Health Check
:navtitle: Health Check
:page-topic-type: howto

[abstract]
In today's distributed and virtual environments, users will often not have full administrative control over their whole network. 
Health Check introduces _Ping_ to check nodes are still healthy, and to force idle connections to be kept alive in environments with eager shutdowns of unused resources.
_Diagnostics_ requests a report from a node, giving instant health check information.





== Ping

At its simplest, `ping` provides information about the current state of the connections in the Couchbase Cluster, by actively polling:

// 2.7 SDK
[source,java]
----
void printDiagnostics(Bucket bucket) {
    bucket.ping();
    DiagnosticsReport report = cluster.diagnostics();
    System.out.println(report.exportToJson(true));
}
----

Which, for a single-node test cluster, will return a payload similar to this:
// TODO -- multiple nodes

// 2.x SDK
----
{
  "services" : {
    "view" : [ {
      "last_activity_us" : 2863,
      "state" : "connected",
      "id" : "0x46ee8659",
      "remote" : "localhost:8092",
      "local" : "localhost:53309"
    } ],
    "fts" : [ {
      "last_activity_us" : 2625,
      "state" : "connected",
      "id" : "0x1c5de614",
      "remote" : "localhost:8094",
      "local" : "localhost:53308"
    } ],
    "kv" : [ {
      "last_activity_us" : 19243,
      "state" : "connected",
      "id" : "0x7d942ebb",
      "remote" : "localhost:11210",
      "local" : "localhost:53307"
    } ],
    "n1ql" : [ {
      "last_activity_us" : 1963,
      "state" : "connected",
      "id" : "0x8de927d",
      "remote" : "localhost:8093",
      "local" : "localhost:53310"
    } ]
  },
  "sdk" : "couchbase-java-client/2.5.8 (git: 2.5.8, core: 1.5.8) (Mac OS X/10.13.4 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_171-b11)",
  "id" : "9c7e2ac7-9a41-4e67-8cdf-bf16abaa35a4",
  "version" : 1
}
----

If you only wish to know if there's a connection that's up, filter out the rest of the information:

// 2.x example
[source,java]
----
boolean allEndpointsConnected(DiagnosticsReport report) {
    for (EndpointHealth endpoint : report.endpoints()) {
        if (endpoint.state() != LifecycleState.CONNECTED) {
            return false;
        }
    }
    return true;
}
----




== Diagnostics


`Diagnostics` returns a list of the nodes that the SDK currently has (or had) a connection to, and the current status of the connection.
However this call _does not_ actively poll the nodes, reporting instead the state the last time it tried to access each node.
If you want the _current_ status, then use xref:#ping[Ping].

[source,javascript]
----
bucket.diagnostics((err, res) => {
    console.log(res)
})
/*
{
    "id":"0x10290d100","kv":[
        {
            "id":"0000000072b21d66",
            "last_activity_us":2363294,
            "local":"10.112.195.1:51473",
            "remote":"10.112.195.101:11210",
            "status":"connected"
        },
        {
            "id":"000000000ba84e5e",
            "last_activity_us":7369021,
            "local":"10.112.195.1:51486",
            "remote":"10.112.195.102:11210",
            "status":"connected"
        },
        {
            "id":"0000000077689398",
            "last_activity_us":4855640,
            "local":"10.112.195.1:51409",
            "remote":"10.112.195.103:11210",
            "status":"connected"
        }
    ],
    "sdk":"libcouchbase/2.9.5-njs couchnode/2.6.9 (node/10.16.0; v8/6.8.275.32-node.52; ssl/1.1.1b)",
    "version":1
}
*/
----

////

== Results Fields

// This section to move to Concept Doc:
// (after MD --> asciidoc translation)

The following sections describe the individual fields which are part of the JSON
payload as well as the `DiagnosticsResult` part of the actual API. Later
sections introduce both the raw JSON as well as the API.

## Version
- Mandatory, Integer

The report layout version. Currently it must always be `1`.

## ID
- Mandatory, String

The report must have `"id"` property, which might be configurable by SDK users,
and automatically generated otherwise (It should be at least unique in scope of
the application, but UUID is also fit). This field is able to be specified by
the user in the function call.

## Configuration revision
- Mandatory for `ping()`, Not used for `diagnostics()`, Integer

The `ping()` report should contain Reportrevision of the configuration that the
SDK is actively using when the report is generated. It also helps to determine
the full list of nodes.

## SDK identifier
- Mandatory, String

The same as identifier seen in HELO command and User-Agent in HTTP requests.

## Services
- Mandatory, Array

On the top level we have `"services"` key, which contains map of service keys, to
arrays of the endpoints.

| Service Key | Description                                                                                                                              |
|-------------|------------------------------------------------------------------------------------------------------------------------------------------|
| `"kv"`      | Memcached binary protocol sockets                                                                                                        |
| `"config"`  | If configuration colling mechanism uses dedicated sockets, they should use separate key (even though they technically `"kv"` or `"http"` |
| `"mgmt"`    | Sockets for management requests (administering the cluster or bucket properties                                                          |
| `"view"`    | Couchbase View queries                                                                                                                   |
| `"n1ql"`    | N1QL queries                                                                                                                             |
| `"fts"`     | Full text search (CBFT) queries                                                                                                          |
| `"cbas"`    | Analytics queries                                                                                                                        |

### Sevice Id
- Mandatory, String

The service object must have some string identifier (`"id"`), which is unique in
scope of resource container (the entity which generates report). For example, it
could be a socket descriptor, or corresponding in-memory address of wrapping
structure.

The Service id is a logical identifier for the same "socket structure", and
should stay the same across reconnect attempts for example (even if the
`"local"` field would change on a reconnect attempt).

When SDK does not control the socket directly, but still willing to expose
connection metrics, it could use the connection hashcode or object id here, so
that the user will be able to track connection throughout the several consequent
reports (in scope of report ID).

### Service state
- Mandatory, String

The list of service states provided here defines an exhaustive list, and it is
expected that not all SDKs are able to show all of these states, BUT they should
not define new states that are not part of this list. If additional information
is required, it can be placed in the "details" field.

The `"state"` field describes the current connection conditions. Here are all the
possible fields for the Diagnostics API:

* `"new"`: the connection is initialized but it has never been connected (or
  trying to) yet
* `"connecting"`: identifies the connection in the initial connect attempt
* `"authenticating"`: state during connecting or reconnecting where the client
  is actively performing the authentication (i.e. SASL).
* `"connected"`, normal case, everything operating
* `"disconnected"`, always indicated unexpectedly
* `"reconnecting"`: trying to reconnect after a first initial connect attempt
* `"disconnecting"`, planned, if say the map changed or the cluster requested a
  graceful connection shut down; some requests may still be in flight.

In case of PING API, the states defined as following:

* `"timeout"`: the server wasn't able to reply to ping request in time. The time
  should be the same as for corresponding service request.
* `"ok"`: the service responded with successful code, see `"latency_us"` for
  latency
* `"error"`: some error happened (more information might be supplied in
  `"details"`)

### Scope
- Mandatory for scoped services, String

On services which are scoped to a bucket, then the `"scope"` field needs to
reflect the bucket name. On services where there is no bucket scoping, the field
can be omitted (in practice, right now the scope field is needed for kv services
where the value is the bucket name).

### Service Latency
- Mandatory for `ping()` report, Integer

This field must specify latency time in microseconds. It has to be specified
when active keep-alive used (`ping()` API). Ignored for `diagnostics()` API.

### Service Last Activity
- Mandatory for `diagnostics()` report, Integer

The field must specify the time in microseconds since relative last activity of
the service (not absolute as in epoch). This field is mandatory, if activity
happened yet and can be omitted if none has happened yet (since 0 would be
ambiguous as there might have been traffic at the time of the health
check). Optional for ping report.

### Service Local Address
- Optional, String

This field must contain endpoint local address in `"host:port"` form. This field
is optional as not all HTTP libraries expose socket API.

### Service Remote Address
- Mandatory, String

This field must contain remote address that matches what was supplied in the
configuration from the cluster and not be modified in the SDK (like resolve it),
which `$HOST` substitution if necessary. This field is mandatory.

### Service Details
- Optional, String

The endpoint entry of the JSON might contain optional field `"details"` with the
string, describing current state of the endpoint. It might be a humanized
description of the current state (status code for example, next time to
reconnect etc.). Those details can also contain SDK specific information and are
not standardized as part of this RFC.



////



