= Diagnosing and preventing Network Problems with Health Check
:navtitle: Health Check
:page-topic-type: howto

[abstract]
In today's distributed and virtual environments, users will often not have full administrative control over their whole network. 
Health Check introduces _Ping_ to check nodes are still healthy, and to force idle connections to be kept alive in environments with eager shutdowns of unused resources.
_Diagnostics_ requests a report from a node, giving instant health check information.


Diagnosing problems in distributed environments is far from easy, so Couchbase provides a _Health Check API_ with `Ping()` for active monitoring. ans `Diagnostics()` for a look at what the client believes is the current state of the cluster. 
More extensive discussion of the uses of Health Check can be found in the xref:concept-docs:health-check.adoc[Health Check Concept Guide].


== Ping

At its simplest, `ping` provides information about the current state of the connections in the Couchbase Cluster, by actively polling:

[source,java]
----
include::devguide:example$java/src/main/java/com/couchbase/devguide/HealthCheck.java[tag=ping]
----


== Diagnostics


`Diagnostics` returns a list of the nodes that the SDK currently has (or had) a connection to, and the current status of the connection.
However this call _does not_ actively poll the nodes, reporting instead the state the last time it tried to access each node.
If you want the _current_ status, then use xref:#ping[Ping].

[source,java]
----
include::devguide:example$java/src/main/java/com/couchbase/devguide/HealthCheck.java[tag=diagnostics]
----
