= Health Check
:description: pass:q[Health Check provides `ping()` and `diagnostics()` tests for the health of the network and the cluster.]
:page-aliases: concept-docs:health-check.adoc
// :page-aliases: ROOT:health-check.adoc
:page-toclevels: 2



[abstract]
{description}



In today's distributed and virtual environments, users will often not have full administrative control over their whole network.
Working in distributed environments is hard. Latencies come and go, so do connections in their entirety.
Is it a network glitch, or is the remote cluster down?
Sometimes just knowing the likely cause is enough to get a good start on a workaround, or at least avoid hours wasted on an inappropriate solution.

Health Check features _Ping_ to check nodes are still healthy, and to force idle connections to be kept alive in environments with eager shutdowns of unused resources.
_Diagnostics_ requests a report from a node, giving instant health check information.



// Uses
include::{version-common}@sdk:pages:partial$health-check.adoc[tag="uses"]



== Ping


`Ping` _actively_ queries the status of the specified services, giving status and latency information for every node reachable.
In addition to its use as a monitoring tool, a regular `Ping` can be used in an environment which does not respect keep alive values for a connection.

At its simplest, `ping` provides information about the current state of the connections in the Couchbase Cluster, by actively polling:

[source,java]
----
include::devguide:example$java/HealthCheck.java[tag=ping-basic]
----

This will print the latency for each socket (endpoint) connected per service. More information is available on the classes. 
Usually though, you want to regularly perform the ping and then print the results into the log. 
This is made easy by the `exportToJson` method:

[source,java]
----
include::devguide:example$java/HealthCheck.java[tag=ping-json-export]
----

By default the SDK will ping all services available on the target cluster. 
You can customize the type of services to ping through the `PingOptions`:

[source,java]
----
include::devguide:example$java/HealthCheck.java[tag=ping-options]
----

In this example, only the Query service is included in the ping report.

Note that `ping` is available both at the `Cluster` and the `Bucket` level. 
The difference is that at the cluster level, the key-value (Data) service might not be
included based on the Couchbase Server version in use. 
If you want to make sure the key-value service is included, perform it at the bucket level.


== Diagnostics

Diagnostics works in a similar fashion to `ping` in the sense that it returns a report of how all the sockets/endpoints are doing, but the main difference is that it is passive. 
While a ping proactively sends an operation across the network, a diagnostics report just returns whatever current state the client is in. 
This makes it much cheaper to call on a regular basis, but does not provide any live insight into network slowness, etc.

[source,java]
----
include::devguide:example$java/HealthCheck.java[tag=diagnostics-basic]
----

Because it is passive, diagnostics are only available at the `Cluster` level and cover everything in the current SDK state. Also, because it is not doing any I/O you cannot proactively filter the list of services that are returned, all you need to do is look only at the ones that are interesting to you.

A `DiagnosticsResult` has one interesting property over a ping result -- it provides a cumulative `ClusterState` through the `state()` method. 
The state can be `ONLINE`, `DEGRADED` or `OFFLINE`.
This allows to give a single, although simplistic, view on how your cluster is doing from a client point of view. 
The state is determined as follows:

 * If at least one socket is open and all of them are connected, it is `ONLINE`
 * If at least one is connected but not all are, it is `DEGRADED`
 * If none are connected, it is `OFFLINE`

You can iterate over the individual states and apply a different algorithm if needed.
