= JSON Modelling
:description: The Java SDK supports multiple options for working with JSON.
:navtitle: JSON Modelling
:page-topic-type: howto
:lang: Java
:page-toclevels: 2

include::project-docs:partial$attributes.adoc[]


== Philosophy

The Couchbase Server is a key-value store that's agnostic to what's stored, but it's very common to store JSON.

The Java SDK has these main objectives for JSON:

* Be usable 'out-of-the-box'.  A simple JSON library is included, so you can get started right away.  Bonus: it's simple to use and very fast!

* Be agnostic.  Your application may already be using its own JSON representation, and it shouldn't be forced to use the built-in JSON library.
We use https://github.com/FasterXML/jackson[Jackson] internally, so if you're already using that popular ecosystem's annotations you're set to go. But you're never locked into it, and you can use other libraries like https://github.com/google/gson/[Gson] easily.

== Getting Started

The examples below assume you're familiar with connecting to a Couchbase cluster using the Java SDK, and opening resources.  Please check out xref:hello-world:start-using-sdk[the Getting Started guide] for help with this.

=== Inserting a simple object

Let's assume we have a very simple JSON structure we want to insert:

[source,json]
----
include::example$Json.java[tag=arthur,indent=0]
----

Once we've connected to a Couchbase server and the bucket, scope, and collection that we want to write to, we know that inserting is as simple as:

[source,java]
----
include::example$Json.java[tag=upsert,indent=0]
----

But how do we model that JSON object?

We mentioned the simple JSON library that we ship with the SDK, and let's look at this first:

[source,java]
----
include::example$Json.java[tags=jsonobject-imports,indent=0]
----

[source,java]
----
include::example$Json.java[tags=jsonobject,indent=0]
----

=== Retrieving

Couchbase's `Collection.get()` method returns a `GetResult` object, which can then be converted back into a `JsonObject`.
In this example, we print the JSON back, and access one of the fields:

[source,java]
----
include::example$Json.java[tags=retrieve-json,indent=0]
----

=== Using Java's `Map` data structure

The `JsonObject` is modelled on the classic Java `Map` data structure, and in fact is backed by one.
So we can easily create an object from an existing Map:

[source,java]
----
include::example$Json.java[tags=map,indent=0]
----

The resulting `JsonObject` can be inserted as normal.
But most JSON serializers can handle simple objects like a Map already, and ours (backed by Jackson) is no different. So you can simply:

[source,java]
----
include::example$Json.java[tags=map-insert,indent=0]
----

Once the data is in Couchbase, it is stored in exactly the same way, that is to say, as the JSON representation we started this example with!

So whether we inserted a Map or a JsonObject, we could retrieve it as a JsonObject... or indeed a Map:

[source,java]
----
include::example$Json.java[tags=retrieve-map,indent=0]
----

While you are free to use Map, this is capable of storing any valid Java value, including ones that can't be represented as JSON. JsonObject offers validation to make sure that only the relevant xref:#datatypes[datatypes] are stored, which will give you greater diagnostics and robustness.

=== Inserting a JSON string or `.json` file

If we read the contents of a file to get a JSON string, we can also inflate a JsonObject from that string:

[source,java]
----
include::example$Json.java[tags=file-imports,indent=0]
----

[source,java]
----
include::example$Json.java[tags=file,indent=0]
----

This might seem a little clumsy though:
We're reading a string, inflating it into a JsonObject, passing it to a serializer which will... turn it back into a string again to send over the network to the Couchbase server!

We could instead simply pass it through with the Raw JSON Transcoder:

[source,java]
----
include::example$Json.java[tags=file-raw-imports,indent=0]
----

[source,java]
----
include::example$Json.java[tags=file-raw,indent=0]
----

This approach could also be used to handle JSON created by other libraries such as Gson.
See the xref:transcoders-nonjson.adoc#rawjsontranscoder[Transcoder documentation] for more details.

=== Serializing objects

It's common to want to serialize your own objects, rather than creating Json programmatically or textually. 
Luckily our built-in JSON serializer makes light work of this task.
Using this simple class:

[source,java]
----
include::example$Json.java[tags=person-class,indent=0]
----

We could insert the exact same JSON as before with:

[source,java]
----
include::example$Json.java[tags=insert-person,indent=0]
----

It's now trivial to return the data either as a JsonObject, exactly as we've done before, or indeed as a Person object:

[source,java]
----
include::example$Json.java[tags=get-person,indent=0]
----

[#ObjectMapper]
=== More complex Object to JSON mapping

Because the SDK's serializer is backed by an industry standard library (Jackson), it is easy to model all kinds of Object to JSON mappings.
Though the SDK automatically uses your version of Jackson when it finds the library on the CLASSPATH, you may wish to be explicit, or use an already configured ObjectMapper, as in this example:

[source,java]
----
include::example$Json.java[tags=object-mapper-imports,indent=0]
----

[source,java]
----
include::example$Json.java[tags=object-mapper;!object-mapper-dates,indent=0]
----

With this setup, we can then configure our classes as we wish.
Here, we've just renamed the Java class and its fields in Spanish.
But the generated JSON will have the same fields as before, for easy interoperability:

[source,java]
----
include::example$Json.java[tags=persona-class;!exclude,indent=0]
----

[#datatypes]
== Modelling JSON datatypes in Java

We've only looked at a few datatypes so far, JSON objects `{}`, strings, and integers. But the full range of JSON types can be expressed, with the obvious mappings to Java.

* string `"hello"`
* integer `123`
* float `123.456`
* boolean: `true`, `false`
* object: `JavaObject`, `Map`
* array: `JavaArray`, `List`
* null

In general, these values can be inserted as top-level values, or nested within an object or array. Let's look at a few examples:

=== Nested object

This example shows a variety of data types, including a nested array ("possessions") and object ("address"):

[source,java]
----
include::example$Json.java[tags=nested,indent=0]
----

=== Top level values other than JsonObject

Although it's common to use a JsonObject, or a JsonArray as the inserted value to couchbase, other values are supported.

For example, to insert a string value, we could simply:

[source,java]
----
include::example$Json.java[tags=string,indent=0]
----

We can retrieve this value as usual, with the appropriate `.contentAs()`:

[source,java]
----
include::example$Json.java[tags=string-get,indent=0]
----

=== Dates

JSON has no built-in representation of dates, so commonly they are represented as one of:

* a string-formatted https://www.w3.org/TR/NOTE-datetime[ISO-8601^] date 
* an offset in seconds or milliseconds from the Unix epoch 1 January 1970 UTC

While it doesn't matter which you choose (as long as you serialize and deserialize your Date object consistently!) it may make sense to store the dates in Couchbase in a format that can be easily manipulated using the xref:7.0@server:n1ql:n1ql-language-reference/datefun.adoc[date functions in N1QL].

Handily, as we can see on the same page, the
xref:7.0@server:n1ql:n1ql-language-reference$datefun.adoc#date-formats[supported date formats] are the usual convention in JSON.

Let's look at a brief example of how we might implement this, to serialize a new Event class:

[source,java]
----
include::example$Json.java[tags=event-class;!exclude,indent=0]
----

We'll need a few extra imports:

[source,java]
----
include::example$Json.java[tags=time-imports,indent=0]
----

As we are controlling the serialization carefully, we'll also want to register our own <<ObjectMapper,ObjectMapper>> as above, and additionally configure some of the date handling properties:

[source,java]
----
include::example$Json.java[tags=object-mapper-dates,indent=0]
----

Now all this is set up we can simply serialize and deserialize our Event objects exactly as we've done before:

[source,java]
----
include::example$Json.java[tags=event,indent=0]
----


== Subdocuments

The JsonObjects work equally well with the xref:subdocument-operations.adoc[Sub-Document] API.
So taking our original "Arthur" object above, we can insert a simple value:

[source,java]
----
include::example$Json.java[tags=subdoc-simple,indent=0]
----

[source,json]
----
include::example$Json.java[tags=subdoc-simple-json,indent=0]
----

Or we could insert another nested object:

[source,java]
----
include::example$Json.java[tags=subdoc-object,indent=0]
----

[source,json]
----
include::example$Json.java[tags=subdoc-object-json,indent=0]
----

NOTE: Currently, paths cannot exceed 1024 characters, and cannot be more than 32 levels deep.
DJSON documents with more than 32 nested layers cannot be parsed, atttempting to do so will result in a `DocumentTooDeepException` exception.


== Identifying the type of arbitrary JSON

Though you will often be mapping objects to JSON according to a defined schema, sometimes you may wish to handle values with unknown types.

As we want to interrogate a specific Java object with well-defined semantics, we again want to specify the <<ObjectMapper,ObjectMapper>> used.

We can now convert the result to Jackson's `JsonNode`, and use its rich set of methods to identify and handle arbitrary values:

[source,java]
----
include::example$Json.java[tags=identify-imports,indent=0]
----

[source,java]
----
include::example$Json.java[tags=identify,indent=0]
----


== Additional Resources

* Read more about the xref:7.0@server:learn:data/data.adoc[Couchbase Data Model].
