= Key Value Operations
:navtitle: KV Operations
:page-topic-type: howto
:page-aliases: document-operations.adoc

WARNING: These pages cover the first _Developer Preview_ of the Couchbase .NET SDK 3.0 (DP1).
As such they are likely to change without notice.
The DP1 code _should not_ be used in production.


The complete code sample used on this page can be downloaded from
///  xref::example$document.cs[here]
- from which you can see in context how to authenticate and connect to a Couchbase Cluster, then perform these Bucket operations.


== Documents

A _document_ refers to an entry in the database (other databases may refer to the same concept as a _row_).
A document has an ID (_primary key_ in other databases), which is unique to the document and by which it can be located.
The document also has a value which contains the actual application data.
See xref::concept-docs:documents.adoc[the concept guide to _Documents_] for a deeper dive into documents in the Couchbase Data Platform.
Or read on, for a hands-on introduction to working with documents from the .NET SDK.

== CRUD Operations

The core interface to Couchbase Server is simple KV operations on full documents.
Make sure you're familiar with the basics of authorization and connecting to a Cluster from the xref::hello-world:start-using-sdk.adoc[Start Using the SDK section].
We're going to expand on the short _Upsert_ example we used there, adding options as we move through the various CRUD operations.
Here is the _Insert_ operation at its simplest:

[source,csharp]
----
Insert
var document = new {foo = "bar", bar = "foo"};
var result = await collection.Insert("document-key", document);
----

Options may be added to operations:

[source,csharp]
----
Insert (with options)
var document = new {foo = "bar", bar = "foo"};
var result = await collection.Insert("document-key", document,
    new InsertOptions
    {
        Cas = 12345,
        Timeout = TimeSpan.FromSeconds(5)
    }
);
----

Setting a Compare and Swap (CAS) value is a form of optimistic locking - dealt with in depth in the xref:concurrent-document-mutations.adoc[CAS page].
Here we just note that the CAS is a value representing the current state of an item; each time the item is modified, its CAS changes.
The CAS value is returned as part of a document’s metadata whenever a document is accessed.
Without explicitly setting it, a newly-created document would have a CAS value of _0_.

_Timeout_ is an optional parameter which in the .NET SDK has a type value of `TimeSpan`.
Timeout sets the timeout value for the underlying network connection.
We will add to these options for the _Replace_ example:

[source,csharp]
----
var document = new {foo = "bar", bar = "foo"};
var result = await collection.Replace("document-key", document,
    new ReplaceOptions
    {
        Cas = 12345,
        Expiration = TimeSpan.FromMinutes(1),
        Timeout = TimeSpan.FromSeconds(5)
    }
);
----

Expiration sets an explicit time to live (TTL) for a document, for which you can also xref:sdk-xattr-example.adoc[see a more detailed example of TTL discovery] later in the docs.
We'll discuss modifying `Expiration` in more details xref:#net-modifying-expiration[below].
For a discussion of item (Document) _vs_ Bucket expiration, see the 
xref:6.5@server:learn:buckets-memory-and-storage/expiration.adoc#expiration-bucket-versus-item[Expiration Overview page].

[source,csharp]
----
var document = new {foo = "bar", bar = "foo"};
var result = await collection.Upsert("document-key", document,
    new UpsertOptions
    {
        Cas = 12345,
        Expiration = TimeSpan.FromMinutes(1),
        PersistTo = PersistTo.One,
        ReplicateTo = ReplicateTo.One,
        Timeout = TimeSpan.FromSeconds(5)
    }
);
----

Here, we have add _Durability_ options, namely `PersistTo` and `ReplicateTo`.
In Couchbase Server releases before 6.5, Durability was set with these two options -- see the xref:https://docs.couchbase.com/dotnet-sdk/2.7/durability.html[6.0 Durability documentation] -- covering  how many replicas the operation must be propagated to and how many persisted copies of the modified record must exist. 
Couchbase Data Platform 6.5 refines these two options, with xref:synchronous-replication.adoc[Synchronous Replication] -- although they remain essentially the same in use -- as well as adding the option of xref:transactions.adoc[atomic document transactions].


[TIP]
.Sub-Document Operations
====
All of these operations involve fetching the complete document from the Cluster.
Where the number of operations or other circumstances make bandwidth a significant issue, the SDK can work on just a specific _path_ of the document with xref:subdocument-operations.adoc[Sub-Docunent Operations].
====

== Retrieving full documents

Using the `Get()` method with the document key can be done in a similar fashion to the other operations:

[source,csharp]
----
var result = await collection.Get(“document-key”);
var content = result.ContentAs<string>();
----

Timeout can also be set - as in the earlier `Insert` example:

[source,csharp]
----
Get (with options)
var result = await collection.Get(“document-key”,
    new GetOptions
    {
        Timeout = TimeSpan.FromSeconds(5)
    }
);
var content = result.ContentAs<string>();
----


== Removing

When removing a document, you will have the same concern for durability as with any additive modification to the Bucket:

Remove (with options)
[source,csharp]
----
var result = await collection.Remove("document-key",
    new RemoveOptions
    {
        Cas = 12345,
        PersistTo = PersistTo.One,
        ReplicateTo = ReplicateTo.One,
        Timeout = TimeSpan.FromSeconds(5)
    }
);
----

== Expiration / TTL

By default, Couchbase documents do not expire, but transient or temporary data may be needed for user sessions, caches, or other temporary documents. 
Using `Touch()`, you can set expiration values on documents to handle transient data:

[source,csharp]
----
var result = await collection.Touch("document-key", TimeSpan.FromSeconds(10));
----

A network timeout can be set with the optional `TouchOptions()`, in the same fashion as earlier examples on this page:

[source,csharp]
----
var result = await collection.Touch("document-key", TimeSpan.FromSeconds(30),
    new TouchOptions
    {
        Timeout = TimeSpan.FromSeconds(5)
    }
);
----

== Atomic document modifications

The value of a document can be increased or decreased atomically using `Binary.Increment()` and `.Binary.Decrement()`.

.Increment
[source,csharp]
----
// increment binary value by 1, if document doesn’t exist, seed it at 1000
await collection.Binary.Increment("document-key", 1, 1000);
----

[source,csharp]
----
.Increment (with options)
// increment binary value by 1, if document doesn’t exist, seed it at 1000
// optional arguments:
// - Timeout (TimeSpan)
// - Expiration (TimeSpan)
// - CAS (ulong)

await collection.Binary.Increment("document-key", 1, 1000, TimeSpan.FromSeconds(5), TimeSpan.FromDays(1), cas);
----

.Decrement
[source,csharp]
----
// decrement binary value by 1, if document doesn’t exist, seed it at 1000
await collection.Binary.Decrement("document-key", 1, 1000);
----

.Increment (with options)
[source,csharp]
----
// decrement binary value by 1, if document doesn’t exist, seed it at 1000
// optional arguments:
// - Timeout (TimeSpan)
// - Expiration (TimeSpan)
// - CAS (ulong)
await collection.Binary.Decrement("document-key", 1, 1000, TimeSpan.FromSeconds(5), TimeSpan.FromDays(1), cas);
----

NOTE: Increment & Decrement are considered part of the ‘binary’ API and as such may still be subject to change

== Additional Resources

Working on just a specific path within a JSON document will reduce network bandwidth requirements - see the xref:subdocument-operations.adoc[Sub-Document] pages.
For working with metadata on a document, reference our xref:sdk-xattr-example.adoc[Extended Attributes] pages.

Another way of increasing network performance is to _pipeline_ operations with xref:batching-operations.adoc[Batching Operations].

As well as various xref:concept-docs:data-model.adoc[Formats] of JSON, Couchbase can work directly with xref:non-json.adoc[arbitary bytes, or binary format].

Our xref:n1ql-queries-with-sdk.adoc[Query Engine] enables retrieval of information using the SQL-like syntax of N1QL.

