= N1QL Queries from the SDK
:navtitle: N1QL from the SDK
:page-topic-type: howto
:page-aliases: n1ql-query
:lang: Java
:version: 3.0.0
:example-source: 3.0@java-sdk:howtos:example$Queries.java
:example-source-lang: java

You can query for documents in Couchbase using the N1QL query language, a language based on SQL, but designed for structured and flexible JSON documents.

Our query service uses N1QL, which will be fairly familiar to anyone who's used any dialect of SQL.
<<Additional Resources>> for learning about N1QL are listed at the bottom of the page.
Before you get started you may wish to checkout the xref:6.0@server:n1ql:n1ql-language-reference/index.adoc[N1QL intro page].

[TIP]
.N1QL Compared to Key-Value
====
N1QL is excellent for performing queries against multiple documents, but if you only need to access or mutate a single document and you know its unique ID, it will be
much more efficient to use the Key-Value API.  We strongly recommend using both APIs to create a flexible, performant application.
====

include::1.0@scala-sdk:howtos:partial$n1ql-getting-started.adoc[]

== A Simple Query
Here's the basics of how to run a simple query to fetch 10 random rows from travel-sample and print the results:

[source,java]
----
include::example$Queries.java[tag=simple]
----

(Note that we won't be covering the N1QL language itself in any detail here, but if you're familiar with SQL you'll see it's very similar.)

The Java SDK will throw an exception derived from `CouchbaseException` if there are any errors.

include::1.0@scala-sdk:howtos:partial$n1ql-placeholders.adoc[]
include::1.0@scala-sdk:howtos:partial$n1ql-scan-consistency.adoc[]

== Streaming Large Result Sets
The Java API provides three distinct APIs for all services:

* The blocking API you've seen so far, that returns a `QueryResult` containing all rows.

* An async API that returns a `CompletableFuture<QueryResult>`.  This in turn contains a `List<JsonObject> rowsAs(T)`.  It can be accessed like this:

[source,java]
----
include::example$Queries.java[tag=async]
----

* A reactive API, that can be used to stream rows.

The former two APIs buffer all rows in-memory until they can be returned to you.  With smaller queries this is likely to be fine, but for large data sets this could lead to Java `OutOfMemoryError` exceptions.

The recommended solution is to use the reactive API.  Reactive programming is a sophisticated paradigm that is rapidly gaining popularity for its ability to handle, amongst other things, streaming large amounts of data over fallible networks, while allowing error handling and backpressure.

The Java SDK exposes primitives from the https://projectreactor.io/[Project Reactor] library, most notably `Mono` and `Flux`.  We strongly recommend https://projectreactor.io/learn[learning] a little of this library first, and the following examples will assume basic familiarity with Reactor.

Here's how to perform a query and stream the results using the reactive API:

[source,java]
----
include::example$Queries.java[tag=reactive]
----

include::1.0@scala-sdk:howtos:partial$n1ql-additional-resources.adoc[]

