= Provisioning Cluster Resources
:description: Provisioning cluster resources is managed at the collection or bucket level, depending upon the service affected.
:navtitle: Provisioning Cluster Resources
:page-aliases: ROOT:managing-clusters.adoc
:page-toclevels: 2

// API refs
:bucket-api-reference: pass:q[BucketManager -- https://docs.couchbase.com/sdk-api/couchbase-java-client/com/couchbase/client/java/Cluster.html#buckets()[`Cluster.buckets()`]]
:user-api-reference: pass:q[UserManager -- https://docs.couchbase.com/sdk-api/couchbase-java-client/com/couchbase/client/java/Cluster.html#users()[`Cluster.users()`]]
:query-api-reference: pass:q[QueryIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-java-client/com/couchbase/client/java/Cluster.html#queryIndexes()[`Cluster.queryIndexes()`]]
:analytics-api-reference: pass:q[AnalyticsIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-java-client/com/couchbase/client/java/Cluster.html#analyticsIndexes()[`Cluster.analyticsIndexes()`]]
:search-api-reference: pass:q[SearchIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-java-client/com/couchbase/client/java/Cluster.html#searchIndexes()[`Cluster.searchIndexes()`]]
:collection-api-reference: pass:q[CollectionManager -- https://docs.couchbase.com/sdk-api/couchbase-java-client/com/couchbase/client/java/Bucket.html#collections()[`Bucket.collections()`]]
:view-api-reference: pass:q[ ViewIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-java-client/com/couchbase/client/java/Bucket.html#viewIndexes()[`Bucket.viewIndexes()`]]

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}
Common use cases are outlined here, less common use cases are covered in the https://pkg.go.dev/github.com/couchbase/gocb/v2?tab=doc[API docs].

include::{version-server}@sdk:shared:partial$flush-info-pars.adoc[tag=management-intro]

The Java SDK also comes with some convenience functionality for common Couchbase management requests.

Management operations in the SDK may be performed through several interfaces depending on the object:

* {bucket-api-reference}
* {user-api-reference}
* {query-api-reference} 
* {analytics-api-reference}
* {search-api-reference}
* {collection-api-reference}
* {view-api-reference}

NOTE: When using a Couchbase version earlier than 6.5, you must create a valid Bucket connection using `Cluster.bucket(name)` before you can use cluster level managers.


== Creating and Removing Buckets

The `BucketManager` interface may be used to create and delete buckets from the Couchbase cluster.
It is instantiated through the `Cluster.buckets()` method.

[source,java]
----
include::example$ProvisioningResourcesBuckets.java[tag=creatingbucketmgr,indent=0]
----

The `BucketSettings` object is used for creating or updating buckets, and for exposing information about existing buckets.

include::{version-server}@sdk:shared:partial$flush-info-pars.adoc[tag=update-bucket-warning]

Here is the list of parameters available:

|====
| Name | Description | Can be updated
| `name string` | The name of the bucket, required for creation. | false
| `flushEnabled boolean` | Enables flushing to be performed on this bucket (see the <<java-flushing>> section below). | true
| `replicaIndexes boolean` | Whether or not to replicate indexes. | false
| `ramQuotaMB uint64` | How much memory should each node use for the bucket, required for creation. | true
| `numReplicas` int | The number of replicas to use for the bucket. | true
| `bucketType BucketType` | The type of the bucket, required for creation. | false
| `evictionPolicy EvictionPolicyType` | The type of the eviction to use for the bucket, defaults to `VALUE_ONLY`. | true (note: changing will cause the bucket to restart causing temporary inaccessibility)
| `maxExpiry time.Duration` | The default maximum time-to-live to apply to documents in the bucket. (note: This option is only available for Couchbase and Ephemeral buckets in Couchbase Enterprise Edition.) | true
| `compressionMode CompressionMode` | The compression mode to apply to documents in the bucket. (note: This option is only available for Couchbase and Ephemeral buckets in Couchbase Enterprise Edition.) | true
| `conflictResolutionType ConflictResolutionType` | The conflict resolution type to apply to conflicts on the bucket, defaults to `SEQUENCE_NUMBER` | false
|====

The following example creates a "hello" bucket:

[source,java]
----
include::example$ProvisioningResourcesBuckets.java[tag=createBucket,indent=0]
----

We can now get this bucket and update it to enable Flush:

[source,java]
----
include::example$ProvisioningResourcesBuckets.java[tag=updateBucket,indent=0]
----

Once you no longer need to use the bucket, you can remove it:

[source,java]
----
include::example$ProvisioningResourcesBuckets.java[tag=removeBucket,indent=0]
----

[#java-flushing]
== Flushing Buckets

include::{version-server}@sdk:shared:partial$flush-info-pars.adoc[tag=flush-intro]

You can flush a bucket in the SDK by using the `flushBucket` method:

[source,java]
----
include::example$ProvisioningResourcesBuckets.java[tag=flushBucket,indent=0]
----

The `Flush` operation may fail if the bucket does not have flush enabled, in that case it will return a `BucketNotFlushableException`.

== Collection Management

The CollectionManager interface may be used to create and delete scopes and collections from the Couchbase cluster.
It is instantiated through the `Bucket.collections()` method.
Refer to the https://docs.couchbase.com/sdk-api/couchbase-java-client/com/couchbase/client/java/manager/collection/CollectionManager.html[`CollectionManager` API documentation] --
and to its https://docs.couchbase.com/sdk-api/couchbase-java-client/com/couchbase/client/java/manager/collection/AsyncCollectionManager.html[Async counterpart] --
for further details.

[source,java]
----
include::example$CollectionManagerExample.java[tag=create-collection-manager,indent=0]
----

You can create a scope:

[source,java]
----
include::example$CollectionManagerExample.java[tag=create-scope,indent=0]
----

You can then create a collection within that scope:

[source,java]
----
include::example$CollectionManagerExample.java[tag=create-collection,indent=0]
----

Finally, you can drop unneeded collections and scopes:

[source,java]
----
include::example$CollectionManagerExample.java[tag=drop-collection,indent=0]

include::example$CollectionManagerExample.java[tag=drop-scope,indent=0]

----

Note that the most minimal permissions to create and drop a Scope or Collections is
xref:server:learn:security/roles.adoc#manage-scopes[Manage Scopes]
along with
xref:server:learn:security/roles.adoc#data-reader[Data Reader]

You can create users with the appropriate RBAC programmatically:

[source,java]
----
include::example$CollectionManagerExample.java[tag=scopeAdmin, indent=0]

----

== Index Management

include::{version-server}@sdk:shared:partial$flush-info-pars.adoc[tag=index-management-intro]

=== QueryIndexManager

The `QueryIndexManager` interface contains the means for managing indexes used for queries.
It can be instantiated through the `Cluster.queryIndexes()` method.

include::{version-server}@sdk:shared:partial$flush-info-pars.adoc[tag=query-index-manager-intro]

The example below shows how to create a simple primary index, restricted to a named scope and collection, by calling the `createPrimaryIndex()` method.
Note that you cannot provide a named scope or collection separately, both must be set for the `QueryIndexManager` to create an index on the relevant keyspace path. 

.Creating a primary index

[source,java]
----
include::example$QueryIndexManagerExample.java[tag=primary,indent=0]
----

When a primary index name is not specified, the SDK will create the index as `#primary` by default.
However, if you wish to provide a custom name, you can simply set an `indexName` property in the `CreatePrimaryQueryIndexOptions` object.

You may have noticed that the example also sets the `ignoreIfExists` boolean flag. 
When set to `true`, this optional argument ensures that an exception is not thrown if an index under the same name already exists.

Creating a _secondary_ index follows a similar approach, with some minor differences:

.Creating a secondary index

[source,java]
----
include::example$QueryIndexManagerExample.java[tag=secondary,indent=0]
----

The `createIndex()` method requires an index name to be provided, along with the fields to create the index on.
Like the _primary_ index, you can restrict a _secondary_ index to a named scope and collection by passing some options.

Indexes can easily take a long time to build if they contain a lot of documents.
In these situations, it is more ideal to build indexes in the background.
To achieve this we can use the `deferred` boolean option, and set it to `true`.

.Deferring index creation

[source,java]
----
include::example$QueryIndexManagerExample.java[tag=defer-indexes,indent=0]
----

To delete a query index you can use the `dropIndex()` or `dropPrimaryIndex()` methods. 
Which one you use depends on the type of query index you wish to drop from the database.

.Deleting an index

[source,java]
----
include::example$QueryIndexManagerExample.java[tag=drop-primary-or-secondary-index,indent=0]
----

// * Search - note & link to FTS page & API?

== View Management

include::{version-server}@sdk:shared:partial$flush-info-pars.adoc[tag=view-management]

In the SDK, design documents are represented by the `DesignDocument` and `View` objects.
All operations on design documents are performed on the `ViewIndexManager` instance:

////
[source,java,indent=0]
----
include::devguide:example$go/provisioning-resources-views.go[tag=viewmgr]
----

The following example upserts a design document with two views:

[source,java,indent=0]
----
include::devguide:example$go/provisioning-resources-views.go[tag=createView]
----

include::7.0@sdk:shared:partial$flush-info-pars.adoc[tag=one-view-update-warning]

Note the use of `DesignDocumentNamespaceDevelopment`, the other option is `DesignDocumentNamespaceProduction`.
This parameter specifies whether the design document should be created as development, or as production -- with the former running over only a small fraction of the documents.

Now that we've created a design document we can fetch it:

[source,java,indent=0]
----
include::devguide:example$go/provisioning-resources-views.go[tag=getView]
----

We've created the design document using `DesignDocumentNamespaceDevelopment` and now want to push it to production, we can do this with:

[source,java,indent=0]
----
include::devguide:example$go/provisioning-resources-views.go[tag=publishView]
----

To remove this design document:

[source,java,indent=0]
----
include::devguide:example$go/provisioning-resources-views.go[tag=removeView]
----
////
