= Authenticating against Couchbase Server
:description: As well as Role-Based Access Control (RBAC), Couchbase offers connection with Certificate Authentication, and works transparently with LDAP.
:page-topic-type: howto
:page-edition: Enterprise Edition
:page-aliases: ROOT:sdk-authentication-overview

[abstract]
{description}


Our xref:hello-world:start-using-sdk.adoc[Getting Started] guide covered the basics for authorizing against a Couchbase cluster, but you may need to use alternative authentication methods such as Certification.


== RBAC

Our xref:hello-world:start-using-sdk.adoc[Getting Started] guide introduced basic authentication against a Couchbase cluster:

[source,java]
----
include::example$Auth.java[tag=rbac-simple,indent=0]
----

If you need to provide custom options, the same credentials can be supplied to the `ClusterOptions`:

[source,java]
----
include::example$Auth.java[tag=rbac-clusteroptions,indent=0]
----

Note that this is actually just a convenience overload for the `PasswordAuthenticator`, which can also be used directly to supply more advanced options.

[source,java]
----
include::example$Auth.java[tag=rbac-pwd,indent=0]
----

In this example, the `PLAIN` authentication mechanism is enabled as well, which is needed if LDAP is enabled on the server side and no TLS encrypted connection is used.

include::7.1@sdk:shared:partial$auth-overview.adoc[tag=rbac]

include::7.1@sdk:shared:partial$auth-overview.adoc[tag=cert-auth]


== Authenticating the Java Client by Certificate

For sample procedures whereby certificates can be generated and deployed, see xref:7.1@server:manage:manage-security/manage-certificates.adoc[Manage Certificates].
The rest of this document assumes that the processes there, or something similar, have been followed.
That is, a cluster certificate has been created and installed on the server, a client certificate has been created, and it is stored in a JVM keystore along with the cluster's certificate.

[source,java]
----
include::example$Auth.java[tag=certauth,indent=0]
----

In addition to providing the initialized `KeyStore` directly, the `CertificateAuthenticator` can also be initialized from a key store path, a key directly or a `KeyManagerFactory` for maximum flexibility. Please see the API documentation for the `CertificateAuthenticator` for more details.

include::7.1@sdk:shared:partial$auth-overview.adoc[tag=ldap]

[source,java]
----
include::example$Auth.java[tag=rbac-pwd,indent=0]
----

Note that `.onlyEnablePlainSaslMechanism()` requires SDK 3.0.9 or newer.
