= Authentication
:description: As well as Role-Based Access Control (RBAC), Couchbase offers connection with Certificate Authentication, and works transparently with LDAP.
:page-topic-type: howto
:page-edition: Enterprise Edition
:page-aliases: ROOT:sdk-authentication-overview

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}


Our xref:hello-world:start-using-sdk.adoc[Getting Started] guide covered the basics for authorizing against a Couchbase cluster, but you may need to use alternative authentication methods such as Certification.


== RBAC

Our xref:hello-world:start-using-sdk.adoc[Getting Started] guide introduced basic authentication against a Couchbase cluster:

[source,java]
----
include::example$Auth.java[tag=rbac-simple,indent=0]
----

If you need to provide custom options, the same credentials can be supplied to the `ClusterOptions`:

[source,java]
----
include::example$Auth.java[tag=rbac-clusteroptions,indent=0]
----

Note that this is actually just a convenience overload for the `PasswordAuthenticator`, which can also be used directly to supply more advanced options.

[source,java]
----
include::example$Auth.java[tag=rbac-pwd,indent=0]
----

In this example, the `PLAIN` authentication mechanism is enabled as well, which is needed if LDAP is enabled on the server side and no TLS encrypted connection is used.

include::{version-common}@sdk:shared:partial$auth-overview.adoc[tag=rbac]

include::{version-common}@sdk:shared:partial$auth-overview.adoc[tag=cert-auth]


== Authenticating the Java Client by Certificate

To learn how to generate and deploy certificates, see xref:7.1@server:manage:manage-security/manage-certificates.adoc[Manage Certificates].
The rest of this section assumes you followed those processes, or did something similar.

For the following example, you will need a client certificate and the associated private key.
These must be stored together in the same Java KeyStore file or pkcs12 bundle.

If your cluster's root certificate does not come from a well-known Certificate Authority (CA), you must tell the client to trust the cluster's root certificate.
This example assumes the cluster's root certificate is available in a file called `ca-cert.pem`.

TIP: To trust multiple root certificates, put them all in the same `ca-certs.pem` file.

[source,java]
----
include::example$Auth.java[tag=certauth,indent=0]
----

`CertificateAuthenticator` has several static factory methods.
If you prefer not to load your own `KeyStore` object, you can create a `CertificateAuthenticator` from a `Path` to a key store file, or from an in-memory certificate & key.
For maximum flexibility, you can even provide your own `KeyManagerFactory`.
Please see the https://docs.couchbase.com/sdk-api/couchbase-core-io/com/couchbase/client/core/env/CertificateAuthenticator.html[API documentation] for the `CertificateAuthenticator` for more details.

include::{version-common}@sdk:shared:partial$auth-overview.adoc[tag=ldap]

[source,java]
----
include::example$Auth.java[tag=rbac-pwd,indent=0]
----

Note that `.onlyEnablePlainSaslMechanism()` requires SDK 3.0.9 or newer.
