= Integrations & Ecosystem
:navtitle: Integrations
:page-topic-type: project-doc
:page-aliases: 

[abstract]

The Couchbase Java SDK is often used with unofficial and third party tools and applications to integrate into broader language and platform ecosystems, and across data lakes in heterogeneous environments.


include::6.5@sdk:shared:partial$integrations.adoc[tag=intro]


include::6.5@sdk:shared:partial$integrations.adoc[tag=official]

The Couchbase Java SDK is a first class citizen in the https://spring.io/projects/spring-data-couchbase[Spring Data] world, and there are many examples of using the SDK with https://blog.couchbase.com/couchbase-spring-boot-spring-data/[Spring Boot] and Spring Data (and Spring Data JPA).

Couchbase also supports integrating with xref:24@spark-connector:java-api.adoc[Spark].


include::6.5@sdk:shared:partial$integrations.adoc[tag=important]

Many dataflow tools integrate with Couchbase, including https://github.com/apache/nifi/tree/main/nifi-nar-bundles/nifi-couchbase-bundle[Apache NiFi], 
https://wildfly-extras.github.io/wildfly-camel/#_camel_couchbase[Apache Camel],
and https://github.com/couchbaselabs/flink-connector-couchbase[Apache Flink].
Why not make development easier, and use https://blog.couchbase.com/create-a-zeppelin-interpreter-for-couchbase/[Apache Zeppelin]?


include::6.5@sdk:shared:partial$integrations.adoc[tag=other]

https://github.com/differentway/couchmove [Couchmove] is an open-source Java migration tool for Couchbase, inspired by Flyway.
It can help you "track, manage and apply changes, in your Couchbase buckets."
The philosophy of the project claims to "strongly favors simplicity and convention over configuration".

In CouchMove you write your migrations in N1QL, while in https://github.com/couchbaselabs/CouchVersion[CouchVersion] you can write them using the Java SDK, which essentially allow you to create more complex migrations.
CouchVersion provides a new approach for adding changes (change sets) based on Java classes and methods with appropriate annotations.
