= Vector Search
:page-toclevels: 2
:description: Vector Search from the SDK, to enable AI integration, semantic search, and the RAG framework.


// Note to editors
// 
// This page pulls in content from -sdk-common-
// and code samples from -example-dir-
// 
// It can be seen built at wwww.


[abstract]
{description}




////
* Couchbase Server 7.6 introduces Vector Search to enable AI integration, semantic search, and the RAG framework.
A developer-friendly vector indexing engine exposes a vector database and search functionality.
With Couchbase Vector Search, you can enable fast and highly accurate semantic search, ground LLM responses in relevant data to reduce hallucinations, and enhance or enable use cases like personalized searches in e-commerce and media & entertainment, product recommendations, fraud detection, and reverse image search.
You can also enable full access to an AI ecosystem with a Langchain integration, the most popular open-source framework for LLM-driven applications.
+
A Vector Search database includes:
+
** Standard Couchbase vertical/horizontal scaling
** Indexing capable of efficient Insert/Update/Removal of Items (or documents)
** Storage of raw Embedding Vectors in the Data Service in the documents themselves
** Querying Vector Indexes (REST and UI via a JSON object/fragment, Couchbase SDKs, and {sqlpp})
** {sqlpp}/N1QL integration
** Third-party framework integration: Langchain (later Llamaindex + others)
** Full support for Replicas Partitions and file-based Rebalance
////



////
Vector queries with GSI are fast and scale up, but sometimes you may wish to use Vector with the Search Service instead.

Hybrid searches can combine Vector, geo-spatial search, range search, and traditional fuzzy text search for apps that...........
////


This is currently implemented using xref:full-text-searching-with-sdk.adoc[Search Indexes], and can even be combined with traditional full text search queries.
Vector embeddings can be an array of floats or a xref:server:vector-search:run-vector-search-ui.adoc#base64[base64 encoded string].


== Prerequisites

Couchbase Server 7.6.0
(7.6.2 for base64-encoded vectors) -- or recent Capella instance.

== Examples

=== Single vector query

In this first example we are performing a single vector query:

[source,java]
----
include::devguide:example$java/Search.java[tag=vector1,indent=0]
----

Let's break this down.
We create a `SearchRequest`, which can contain a traditional FTS query `SearchQuery` and/or the new `VectorSearch`.
Here we are just using the latter.

The `VectorSearch` allows us to perform one or more `VectorQuery` s.

The `VectorQuery` itself takes the name of the document field that contains embedded vectors ("vector_field" here), plus actual vector query in the form of a `float[]`.

(Note that Couchbase itself is not involved in generating the vectors, and these will come from an external source such as an embeddings API.)

Finally we execute the `SearchRequest` against the FTS index "travel-sample-index", which has previously been setup to vector index the "vector_field" field.

This happens to be a scoped index so we are using `scope.search()`.
If it was a global index we would use `cluster.search()` instead - see <<Scoped vs Global Indexes>>.

It returns the same `SearchResult` detailed earlier.

=== Multiple vector queries
You can run multiple vector queries together:

[source,java]
----
include::devguide:example$java/Search.java[tag=vector3,indent=0]
----

How the results are combined (ANDed or ORed) can be controlled with `vectorSearchOptions().vectorQueryCombination()`.

=== Combining FTS and vector queries

You can combine a traditional FTS query with vector queries:

[source,java]
----
include::devguide:example$java/Search.java[tag=vector2,indent=0]
----

How the results are combined (ANDed or ORed) can be controlled with `vectorSearchOptions().vectorQueryCombination()`.



////
=== FTS queries
And note that traditional FTS queries, without vector search, are also supported with the new `cluster.search()` / `scope.search()` APIs:
[source,java]
----
include::devguide:example$java/Search.java[tag=vector4,indent=0]
----

////





// integrations??





== Further Reading

* xref:server:vector-search:vector-search.adoc[Vector Search for AI Apps docs (self-managed Couchbase Server)]
* xref:cloud::vector-search:vector-search.adoc[Vector Search for AI Apps docs (Capella DBaaS)]
* Vector Search in the https://docs.couchbase.com/sdk-api/couchbase-scala-client/com/couchbase/client/scala/search/vector/index.html[Scala API reference].

// https://developer.couchbase.com/tutorial-python-langchain-pdf-chat
