= Pre-release Archive Release Notes
:navtitle: α & β Release Notes
:page-topic-type: project-doc
:page-aliases: 3.0αλφα-sdk-release-notes

[abstract] Release notes for the 3.0 Alpha & Beta Releases

In the run-up to the SDK 3.0 API releases, several αλφα and βετα releases were made.
Their release notes are maintained here for archive purposes.
The 3.0 series release notes proper can be found xref:sdk-release-notes.adoc[here], along with install instructions for all supported platforms.
Please note that none of the pre-releases listed below are supported; all _supported_ (GA) releases can be found xref:sdk-release-notes.adoc[here].

WARNING: These are the pre-release α & β Release Notes maintained purely for archive and information purposes.
These releases are unsupported.
Supported (GA) releases can be found xref:sdk-release-notes.adoc[on the general 3.0 Release Notes page].


== Version 3.0.0-beta.2 (22 November 2019)

This is the second beta release of the third generation Java SDK.
While it is not yet suitable to be used in production, the surface area of the API is largely complete and not expected to change dramatically.

http://packages.couchbase.com/clients/java/3.0.0-beta.2/Couchbase-Java-Client-3.0.0-beta.2.zip[Download] |
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.0-beta.2/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.0-beta.2/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.0-beta.2**
* com.couchbase.client:**core-io:2.0.0-beta.2**
* io.projectreactor:**reactor-core:3.3.0.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.2**

=== Enhancements

* http://issues.couchbase.com/browse/JCBC-1467[JCBC-1467]:
The Search API has been completely refactored and aligned with the SDK-RFC.
* http://issues.couchbase.com/browse/JCBC-1504[JCBC-1504]:
Cluster connect now defers all I/O errors into the operation.
* http://issues.couchbase.com/browse/JCBC-1510[JCBC-1510]:
Bucket open now defers all I/O errors into the operation.
* http://issues.couchbase.com/browse/JVMCBC-637[JVMCBC-637]:
Support for tracing has been added.
* http://issues.couchbase.com/browse/JVMCBC-760[JVMCBC-760]:
Security can be configured from the connection string.
* http://issues.couchbase.com/browse/JVMCBC-761[JVMCBC-761]:
TCP Keepalive support has been added.
* http://issues.couchbase.com/browse/JVMCBC-769[JVMCBC-769]:
Exists uses GetMeta underneath instead of "observe".
* http://issues.couchbase.com/browse/JCBC-1502[JCBC-1502]:
If the user adds jackson as a dependency, a new JsonSerializer is automatically used.
* http://issues.couchbase.com/browse/JCBC-1503[JCBC-1503]:
Support added for deserializing JSON into parameterized types through TypeRef.
* http://issues.couchbase.com/browse/JCBC-1487[JCBC-1487]:
Jackson afterburner module is enabled by default.

=== Bug Fixes

* http://issues.couchbase.com/browse/JVMCBC-764[JVMCBC-764]:
TLS connections were not working, this is now fixed.
* http://issues.couchbase.com/browse/JVMCBC-755[JVMCBC-755]:
Revert KV opaque back to global instead of per socket.
* http://issues.couchbase.com/browse/JCBC-1360[JCBC-1360]:
Should not allow user to set timeout value greater than the KV supported value.
* http://issues.couchbase.com/browse/JCBC-1492[JCBC-1492]:
Subdoc now transparently reorders operations so XATTR calls are handled properly.
* http://issues.couchbase.com/browse/JCBC-1477[JCBC-1477]:
A bug with view query timeouts have been fixed.

=== API Changes

* http://issues.couchbase.com/browse/JCBC-1498[JCBC-1498]:
Error handling (exceptions) have been heavily reworked and aligned, so please expect exceptions to be renamed and different ones to be thrown.
* http://issues.couchbase.com/browse/JCBC-1496[JCBC-1496]:
On subdocument mutations, arrayAppend and similar take a List of values.
* http://issues.couchbase.com/browse/JVMCBC-772[JVMCBC-772]:
The Authenticator now holds the SASL mechanism instead the IoConfig.
* http://issues.couchbase.com/browse/JVMCBC-771[JVMCBC-771]:
RequestTimeoutException has been renamed to TimeoutException.
* http://issues.couchbase.com/browse/JVMCBC-765[JVMCBC-765]:
The CertificateAuthenticator now holds the client certificates instead of the SecurityConfig.
* http://issues.couchbase.com/browse/JCBC-1497[JCBC-1497]:
All deprecated APIs are removed.
* http://issues.couchbase.com/browse/JCBC-1512[JCBC-1512]:
ExpandMacro is gone, there are now sentinel values that are passed in.

== Version 3.0.0-beta.1 (30 September 2019)

This is the first beta release of the third generation Java SDK.
While it is not yet suitable to be used in production, the surface area of the API is largely complete and not expected to change dramatically.

http://packages.couchbase.com/clients/java/3.0.0-beta.1/Couchbase-Java-Client-3.0.0-beta.1.zip[Download] |
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.0-beta.1/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.0-beta.1/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.0-beta.1**
* com.couchbase.client:**core-io:2.0.0-beta.1**
* io.projectreactor:**reactor-core:3.2.10.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.2**

=== Enhancements

* http://issues.couchbase.com/browse/JCBC-1358[JCBC-1358]:
Add retry and error handling for prepared statements / query
* http://issues.couchbase.com/browse/JCBC-1397[JCBC-1397]:
Add support for query index manager
* http://issues.couchbase.com/browse/JCBC-1399[JCBC-1399]:
Add diagnostics functionality
* http://issues.couchbase.com/browse/JCBC-1401[JCBC-1401]:
Add ping functionality
* http://issues.couchbase.com/browse/JCBC-1402[JCBC-1402]:
Add getAllReplicas
* http://issues.couchbase.com/browse/JCBC-1403[JCBC-1403]:
Add getAnyReplica
* http://issues.couchbase.com/browse/JCBC-1415[JCBC-1415]:
Add ReactiveBucketManager
* http://issues.couchbase.com/browse/JCBC-1417[JCBC-1417]:
Add ReactiveCollectionManager
* http://issues.couchbase.com/browse/JCBC-1422[JCBC-1422]:
Add BucketManager timeout option
* http://issues.couchbase.com/browse/JCBC-1423[JCBC-1423]:
Add options blocks to UserManager functions
* http://issues.couchbase.com/browse/JCBC-1439[JCBC-1439]:
Add support for readonly on analytics queries
* http://issues.couchbase.com/browse/JCBC-1441[JCBC-1441],
http://issues.couchbase.com/browse/JCBC-1454[JCBC-1454]:
Add support for DataStructures
Add passthrough serializer to access raw json values
* http://issues.couchbase.com/browse/JCBC-1452[JCBC-1452]:
Expose ClusterOptions on connect
* http://issues.couchbase.com/browse/JCBC-1374[JCBC-1374]:
Add reactive versions of User/GroupManager

=== Bug Fixes

* http://issues.couchbase.com/browse/JCBC-1431[JCBC-1431]:
Handle memcached being restarted during cluster connection
* http://issues.couchbase.com/browse/JCBC-1432[JCBC-1432]:
Fix theorectical overflow error comparing system times in LazyCircuitBreaker
* http://issues.couchbase.com/browse/JCBC-1433[JCBC-1433]:
Setting certain N1QL query options causes the request to fail
* http://issues.couchbase.com/browse/JCBC-1440[JCBC-1440]:
`exists` no longer throws if the document does not exist
* http://issues.couchbase.com/browse/JVMCBC-749[JVMCBC-749]:
NonChunked handler needs to reset currentRequest

=== API Changes
This release, transitioning as it does from alpha to beta, involved a focused effort to make sure all the SDK implementations align.
The breaking API changes below were unavoidable, but we expect now to make few further changes going forwards in beta.

* http://issues.couchbase.com/browse/JCBC-1282[JCBC-1282]:
Error handling updated has been updated for consistency
* http://issues.couchbase.com/browse/JCBC-1405[JCBC-1405]:
Fix getAndLock signature
* http://issues.couchbase.com/browse/JCBC-1409[JCBC-1409]:
FullDocument MutateInSpec is deprecated, pending removal pre-GA.  Use `upsert("", ...)` instead.
* http://issues.couchbase.com/browse/JCBC-1410[JCBC-1410]:
getAnyReplica and getAllReplicas return new GetReplicaResult type
* http://issues.couchbase.com/browse/JCBC-1413[JCBC-1413]:
Update search metadata
* http://issues.couchbase.com/browse/JCBC-1438[JCBC-1438],
http://issues.couchbase.com/browse/JCBC-1442[JCBC-1442],
http://issues.couchbase.com/browse/JCBC-1448[JCBC-1448],
http://issues.couchbase.com/browse/JCBC-1463[JCBC-1463],
http://issues.couchbase.com/browse/JCBC-1466[JCBC-1466],
Encoding and decoding has been altered substantially, transitioning to a simpler model based around `Transcoders`
* http://issues.couchbase.com/browse/JCBC-1455[JCBC-1455]:
Rename expiration to expiry
* http://issues.couchbase.com/browse/JCBC-1459[JCBC-1459]:
LookupInSpec.getFullDocument is deprecated, pending removal pre-GA.  Use `get("")` instead.
* http://issues.couchbase.com/browse/JCBC-1465[JCBC-1465]:
Rename shutdown to disconnect on *Cluster
* http://issues.couchbase.com/browse/JCBC-1469[JCBC-1469]:
Rename isMaster to isReplica in GetReplicaResult
* http://issues.couchbase.com/browse/JCBC-1470[JCBC-1470]:
Add StoreSemantics to subdoc LookupIn
* http://issues.couchbase.com/browse/JCBC-1471[JCBC-1471]:
Remove withExpiry from lookupIn
* http://issues.couchbase.com/browse/JCBC-1472[JCBC-1472]:
Remove durability from touch


== Version 3.0.0-alpha.7 (2 September 2019)

This is the seventh pre-release of the third generation Java SDK.

http://packages.couchbase.com/clients/java/3.0.0-alpha.7/Couchbase-Java-Client-3.0.0-alpha.7.zip[Download] | 
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.0-alpha.7/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.0-alpha.7/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.0-alpha.7**
* com.couchbase.client:**core-io:2.0.0-alpha.7**
* io.projectreactor:**reactor-core:3.2.12.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.2**

Note that since this release depends on core-io, it also includes transitive fixes and enhancements that may not all be reflected in the following list.

=== Enhancements

* http://issues.couchbase.com/browse/JCBC-1388[JCBC-1388]:
Support for managing View Indexes has been added.
* http://issues.couchbase.com/browse/JCBC-1424[JCBC-1424]:
Support for managing Analytics Indexes has been added.
* http://issues.couchbase.com/browse/JCBC-1421[JCBC-1421]:
Support for managing buckets has been added.
* http://issues.couchbase.com/browse/JCBC-1420[JCBC-1420]:
The Search Index management API has been greatly expanded and modified.
* http://issues.couchbase.com/browse/JCBC-1375[JCBC-1375]:
User and Group management APIs have been added.
* http://issues.couchbase.com/browse/JVMCBC-615[JVMCBC-615]:
Support for alternate addresses has been brought back to SDK 3 (including kubernetes support)
* http://issues.couchbase.com/browse/JVMCBC-723[JVMCBC-723]:
It is now possible to disable DNS SRV bootstrapping if needed.
* http://issues.couchbase.com/browse/JVMCBC-722[JVMCBC-722]:
X509 certificates can now be loaded from Strings directly as additional convenience overloads.
* http://issues.couchbase.com/browse/JCBC-1391[JCBC-1391]:
The error handling and retry story has been greatly improved throughout the full SDK.
* http://issues.couchbase.com/browse/JCBC-1411[JCBC-1411]:
In HTTP-based services the `meta` has been renamed to `metaData`.
* http://issues.couchbase.com/browse/JCBC-1390[JCBC-1390]:
The `durabilityLevel` has been removed in favor of another `durability` overload.
* http://issues.couchbase.com/browse/JCBC-1396[JCBC-1396]:
Timeout names and default values in the configuration has been aligned with other SDKs.
* http://issues.couchbase.com/browse/JVMCBC-729[JVMCBC-729]:
A new query prepare mechanism is support when a cluster version 6.5 and later is used.
* http://issues.couchbase.com/browse/JVMCBC-600[JVMCBC-600]:
Support for Mapped Diagnostic Context in Logging has been introduced (and `clientContext` from java options).
* http://issues.couchbase.com/browse/JVMCBC-731[JVMCBC-731]:
Mutation tokens are enabled by default and the CAS-based observe has been removed.

=== Bug Fixes

* http://issues.couchbase.com/browse/JCBC-1414[JCBC-1414]:
`geometry` has been removed from the `ViewRow` since spatial queries have also been removed earlier.
* http://issues.couchbase.com/browse/JCBC-1428[JCBC-1428]:
NonChunkedHttpMessageHandler fails the second time it is enabled.
* http://issues.couchbase.com/browse/JCBC-1406[JCBC-1406]:
The `expiration` option has been added to LookupIn.
* http://issues.couchbase.com/browse/JCBC-1407[JCBC-1407]:
LookupIn GetFull shouldn't expose xattr option.
* http://issues.couchbase.com/browse/JVMCBC-725[JVMCBC-725]:
Chunked handler should not close channel when being removed.
* http://issues.couchbase.com/browse/JVMCBC-724[JVMCBC-724]:
Non-Chunked HTTP Hander must report when request complete.
* http://issues.couchbase.com/browse/JVMCBC-727[JVMCBC-727]:
Fail cluster-level queries quickly if not serviceable.
* http://issues.couchbase.com/browse/JVMCBC-733[JVMCBC-733]:
Only dispatch view requests to nodes with primary partitions.
* http://issues.couchbase.com/browse/JVMCBC-734[JVMCBC-734]:
Close channel on unknown KV opaque.
* http://issues.couchbase.com/browse/JVMCBC-735[JVMCBC-735]:
Close KV connection on certain response status codes.
* http://issues.couchbase.com/browse/JVMCBC-737[JVMCBC-737]:
Harden HTTP handlers for write race conditions.
* http://issues.couchbase.com/browse/JVMCBC-728[JVMCBC-728]:
Subdoc MutateInOptions with CAS value provided is not cosidered during mutation.


== Version 3.0.0-alpha.6 (2 August 2019)

This is the sixth pre-release of the third generation Java SDK.

http://packages.couchbase.com/clients/java/3.0.0-alpha.6/Couchbase-Java-Client-3.0.0-alpha.6.zip[Download] | 
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.0-alpha.6/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.0-alpha.6/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.0-alpha.6**
* com.couchbase.client:**core-io:2.0.0-alpha.6**
* io.projectreactor:**reactor-core:3.2.10.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.2**

Note that since this release depends on core-io, it also includes transitive fixes and enhancements that may not all be reflected in the following list.

=== Enhancements

* http://issues.couchbase.com/browse/JCBC-1386[JCBC-1386]:
AsyncCluster and ReadtiveCluster create methods have been made asynchronous.
* http://issues.couchbase.com/browse/JCBC-1386[JCBC-1386]:
Group and user management API has been added.
* http://issues.couchbase.com/browse/JCBC-1386[JCBC-1386]:
A major rework of the get-based API has removed the Optional return type for consistency reasons.
* http://issues.couchbase.com/browse/JCBC-1386[JCBC-1386]:
Support for collection management has been added.
* http://issues.couchbase.com/browse/JCBC-1385[JCBC-1385]:
The default scope is now exposed on the bucket API directly.
* http://issues.couchbase.com/browse/JCBC-1377[JCBC-1377]:
Support for bucket management has been added. 
* http://issues.couchbase.com/browse/JCBC-1376[JCBC-1376]:
OpenTracing has been removed from the API for now until the implementation has been reworked.
* http://issues.couchbase.com/browse/JVMCBC-667[JVMCBC-667]:
Added support for DNS SRV bootstrapping.
* http://issues.couchbase.com/browse/JVMCBC-694[JVMCBC-694]:
When using Couchbase Server 6.5 and later, cluster-level queries can now be performed without opening a bucket.
* http://issues.couchbase.com/browse/JVMCBC-706[JVMCBC-706]:
The IO handlers now consolidate internal flush syscalls to reduce them as much as possible, leading to measurable performance improvements in highly concurrent workloads.
* http://issues.couchbase.com/browse/JVMCBC-711[JVMCBC-711]:
Unknown/Unsupported KeyValue error status codes are now logged so they can be better debugged.
* http://issues.couchbase.com/browse/JVMCBC-717[JVMCBC-717]:
Explicit support for the new KeyValue status DurableWriteReCommitInProgress has been added and mapped to an exception.
* http://issues.couchbase.com/browse/JVMCBC-673[JVMCBC-673]:
KeyValue error map response codes are now handled like in core-io 1.x (aside from transparent retry logic).
* http://issues.couchbase.com/browse/JVMCBC-703[JVMCBC-703]:
Durable writes are now short circuited early on when they are not available on the server side.

=== Bug Fixes

* http://issues.couchbase.com/browse/JVMCBC-704[JVMCBC-704]:
The initial seed nodes are now kept fresh which each subsequent config update.
* http://issues.couchbase.com/browse/JVMCBC-705[JVMCBC-705]:
If the underlying socket is closed upon an endpoint (channel), the endpoint now triggers a proactive reconnect.
* http://issues.couchbase.com/browse/JVMCBC-707[JVMCBC-707]: 
Shutting down the core (and the core environment) is properly synchronized with its internal state, preventing early shutdown reports while the inner shutdown is still happening.
* http://issues.couchbase.com/browse/JVMCBC-710[JVMCBC-710]: 
A race condition has been fixed which made concurrent requests possible against non-pipelined HTTP sockets which lead to queries not being executed properly.

== Version 3.0.0-alpha.5 (4 July 2019)

This is the fifth pre-release of the third generation Java SDK.

http://packages.couchbase.com/clients/java/3.0.0-alpha.5/Couchbase-Java-Client-3.0.0-alpha.5.zip[Download] | 
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.0-alpha.5/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.0-alpha.5/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.0-alpha.5**
* com.couchbase.client:**core-io:2.0.0-alpha.5**
* io.projectreactor:**reactor-core:3.2.10.RELEASE**
* io.opentracing:**opentracing-api:0.31.0**
* org.reactivestreams:**reactive-streams:1.0.2**

Note that since this release depends on core-io, it also includes transitive fixes and enhancements that may not all be reflected in the following list.

=== Enhancements

* http://issues.couchbase.com/browse/JCBC-1363[JCBC-1363], http://issues.couchbase.com/browse/JCBC-1282[JCBC-1282]: 
The exception hierarchy has been modified to align more closely with the other SDKs.
* http://issues.couchbase.com/browse/JVMCBC-700[JVMCBC-700]: 
On client initialization, diagnostics information with versions and config settings is printed at INFO level.

=== Bug Fixes

* http://issues.couchbase.com/browse/JVMCBC-686[JVMCBC-686]: 
Fixed default collection support when collections enabled.
* http://issues.couchbase.com/browse/JVMCBC-689[JVMCBC-689]: 
Now no longer get `DecodingFailedException` while performing sub_doc operations.
* http://issues.couchbase.com/browse/JVMCBC-1234[JVMCBC-1234]: 
Double check event loop before connecting.
* http://issues.couchbase.com/browse/JVMCBC-688[JVMCBC-688]: 
Always fetch cas-based observe fails for concurrent modifications.

== Version 3.0.0-alpha.4 (12 June 2019)

This is the fourth pre-release of the third generation Java SDK.

http://packages.couchbase.com/clients/java/3.0.0-alpha.4/Couchbase-Java-Client-3.0.0-alpha.4.zip[Download] | 
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.0-alpha.4/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.0-alpha.4/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.0-alpha.4**
* com.couchbase.client:**core-io:2.0.0-alpha.4**
* io.projectreactor:**reactor-core:3.2.10.RELEASE**
* io.opentracing:**opentracing-api:0.31.0**
* org.reactivestreams:**reactive-streams:1.0.2**

Note that since this release depends on core-io, it also includes transitive fixes and enhancements that may not all be reflected in the following list.

=== New Features

* http://issues.couchbase.com/browse/JCBC-1345[JCBC-1345]: 
Prepared statement support is now available again for N1Ql queries.
* http://issues.couchbase.com/browse/JVMCBC-626[JVMCBC-626]: 
The connection string can now be used to load properties and seed nodes with custom ports.
* http://issues.couchbase.com/browse/JVMCBC-676[JVMCBC-676]: 
Multiple sockets/endpoints for the KV service has been brought back (from 2.x functionality).

=== Enhancements

* http://issues.couchbase.com/browse/JCBC-1347[JCBC-1347]: 
The `pretty` N1Ql query option has been removed since it is not needed.
* http://issues.couchbase.com/browse/JCBC-1355[JCBC-1355]: 
Spatial view API support has been removed since it is deprecated on the server.
* http://issues.couchbase.com/browse/JCBC-1282[JCBC-1282]: 
The exception hierachy for error handling has been overhauled.
* http://issues.couchbase.com/browse/JVMCBC-684[JVMCBC-684]: 
Event bus event categories are now extendable by other components.
* http://issues.couchbase.com/browse/JVMCBC-668[JVMCBC-668]: 
Collection IDs are now refreshed automatically if they change.

=== Bug Fixes

* http://issues.couchbase.com/browse/JVMCBC-671[JVMCBC-671]: 
Accidential pipelining for streaming results (which led to timed out requests) has been fixed.
* http://issues.couchbase.com/browse/JVMCBC-681[JVMCBC-681]: 
The SDK now avoids resolving network addresses early, laying the groundwork for Kubernetes support.

== Version 3.0.0-alpha.3 (13 May 2019)

This is the third pre-release of the third generation Java SDK.

http://packages.couchbase.com/clients/java/3.0.0-alpha.3/Couchbase-Java-Client-3.0.0-alpha.3.zip[Download] | 
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.0-alpha.3/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.0-alpha.3/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.0-alpha.3**
* com.couchbase.client:**core-io:2.0.0-alpha.3**
* io.projectreactor:**reactor-core:3.2.8.RELEASE**
* io.opentracing:**opentracing-api:0.31.0**
* org.reactivestreams:**reactive-streams:1.0.2**

Note that since this release depends on core-io, it also includes transitive fixes and enhancements that may not all be reflected in the following list.

=== New Features

* http://issues.couchbase.com/browse/JCBC-1319[JCBC-1319]: 
Initial support for search index management capabilities.
* http://issues.couchbase.com/browse/JVMCBC-651[JVMCBC-651]: 
JSON query streaming parsers reworked completely on top of Jackson so they are more efficient, faster, and produce less garbage.
* http://issues.couchbase.com/browse/JVMCBC-617[JVMCBC-617]: 
It is now possible to populate the environment from system properties.

=== Enhancements

* http://issues.couchbase.com/browse/JCBC-1322[JCBC-1322]: 
Add `consistentWith` to `QueryOptions`.
* http://issues.couchbase.com/browse/JVMCBC-650[JVMCBC-650]: 
Traffic capturing can now be enabled on the environment.
* http://issues.couchbase.com/browse/JVMCBC-659[JVMCBC-659]: 
Native transports can be disabled with a switch on the environment.
* http://issues.couchbase.com/browse/JVMCBC-664[JVMCBC-664]: 
The SDK now passes the timeout down to the sync durability KV infrastructure.

=== Bug Fixes

* http://issues.couchbase.com/browse/JVMCBC-658[JVMCBC-658]: 
Improved config fetching and support for clusters deployed with `cluster_run`.
* http://issues.couchbase.com/browse/JVMCBC-669[JVMCBC-669]: 
Fixed a bug which prevent a node removal being picked up during rebalance out.
* http://issues.couchbase.com/browse/JVMCBC-655[JVMCBC-655]: 
Collection ID improvements (UnsignedLEB128 outputs bytes in reversed order).

== Version 3.0.0-alpha.2 (04 April 2019)

This is the second pre-release of the third generation Java SDK.

http://packages.couchbase.com/clients/java/3.0.0-alpha.2/Couchbase-Java-Client-3.0.0-alpha.2.zip[Download] | 
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.0-alpha.2/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.0-alpha.2/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.0-alpha.2**
* com.couchbase.client:**core-io:2.0.0-alpha.2**
* io.projectreactor:**reactor-core:3.2.8.RELEASE**
* io.opentracing:**opentracing-api:0.31.0**
* org.reactivestreams:**reactive-streams:1.0.2**

Note that since this release depends on core-io, it also includes transitive fixes and enhancements that may not all be reflected in the following list.

=== New Features

* http://issues.couchbase.com/browse/JCBC-1313[JCBC-1313]: 
Initial query support for the Analytics service.
* http://issues.couchbase.com/browse/JCBC-1314[JCBC-1314]: 
Initial query support for the View service.
* http://issues.couchbase.com/browse/JCBC-1315[JCBC-1315]: 
Initial query support for the Search service.

=== Enhancements

* http://issues.couchbase.com/browse/JCBC-1310[JCBC-1310]: 
Get signatures change to include explicit Optionals on Monos which make it easier to handle non-existing documents.
* http://issues.couchbase.com/browse/JCBC-1316[JCBC-1316]: 
Reworked the API for N1QL queries.

=== Bug Fixes

* http://issues.couchbase.com/browse/JCBC-1311[JCBC-1311]: 
Shutdown is now correctly propagated into core-io.
* http://issues.couchbase.com/browse/JCBC-1305[JCBC-1305]: 
Removes unused expiry from RemoveOptions
* http://issues.couchbase.com/browse/JVMCBC-639[JVMCBC-639]: 
IO threads are now daemon threads to not prevent the JVM from shutting down even when the SDK was not properly shutdown in the first place.


== Version 3.0.0-alpha.1 (12 March 2019)

This is the first pre-release of the third generation Java SDK and a complete rewrite over the 2.x series. As such, there are no release notes for this release present.

