// placeholder to archive the 3.0αλφα sdk release notes.

= Couchbase Java SDK Release Notes and Archives
:navtitle: Release Notes
:page-topic-type: project-doc

These pages cover the 3.0 alpha versions of the Couchbase Java SDK, the archive is maintained purely to preserve this snapshot of SDK development.

For release notes, download links, and installation methods for the latest 3.n SDK releases, see xref:sdk-release-notes.adoc[the current Release Notes page].
For release notes, download links, and installation methods for 2.7 and earlier releases of the Couchbase Java Client (which will not work with Distributed Transactions), please see the xref:2.7@java-sdk::sdk-release-notes[2.x Java Release Notes & Download Archive].

Note, Distributed ACID Transactions is available as a separate library for the 3.0 Java SDK.
Please see the xref:distributed-transactions-java-release-notes.adoc[Transaction Release Notes page].


== Installation

At least Java 8 is required for current releases; all newer, vendor supported Java versions are supported (and encouraged), up to and including Java 11. 
See the xref:compatibility-versions-features.adoc[Compatibility] section for details.
Java 11 is recommended, which has various enhancements like lambda local variable type inference, profiling tools, and updated security features.

== Version 3.0.0-alpha.7 (2 September 2019)

This is the seventh pre-release of the third generation Java SDK.

http://packages.couchbase.com/clients/java/3.0.0-alpha.7/Couchbase-Java-Client-3.0.0-alpha.7.zip[Download] | 
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.0-alpha.7/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.0-alpha.7/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.0-alpha.7**
* com.couchbase.client:**core-io:2.0.0-alpha.7**
* io.projectreactor:**reactor-core:3.2.10.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.2**

Note that since this release depends on core-io, it also includes transitive fixes and enhancements that may not all be reflected in the following list.

=== Enhancements

* http://issues.couchbase.com/browse/JCBC-1388[JCBC-1388]:
Support for managing View Indexes has been added.
* http://issues.couchbase.com/browse/JCBC-1424[JCBC-1424]:
Support for managing Analytics Indexes has been added.
* http://issues.couchbase.com/browse/JCBC-1421[JCBC-1421]:
Support for managing buckets has been added.
* http://issues.couchbase.com/browse/JCBC-1420[JCBC-1420]:
The Search Index management API has been greatly expanded and modified.
* http://issues.couchbase.com/browse/JCBC-1375[JCBC-1375]:
User and Group management APIs have been added.
* http://issues.couchbase.com/browse/JVMCBC-615[JVMCBC-615]:
Support for alternate addresses has been brought back to SDK 3 (including kubernetes support)
* http://issues.couchbase.com/browse/JVMCBC-723[JVMCBC-723]:
It is now possible to disable DNS SRV bootstrapping if needed.
* http://issues.couchbase.com/browse/JVMCBC-722[JVMCBC-722]:
X509 certificates can now be loaded from Strings directly as additional convenience overloads.
* http://issues.couchbase.com/browse/JCBC-1391[JCBC-1391]:
The error handling and retry story has been greatly improved throughout the full SDK.
* http://issues.couchbase.com/browse/JCBC-1411[JCBC-1411]:
In HTTP-based services the `meta` has been renamed to `metaData`.
* http://issues.couchbase.com/browse/JCBC-1390[JCBC-1390]:
The `durabilityLevel` has been removed in favor of another `durability` overload.
* http://issues.couchbase.com/browse/JCBC-1396[JCBC-1396]:
Timeout names and default values in the configuration has been aligned with other SDKs.
* http://issues.couchbase.com/browse/JVMCBC-729[JVMCBC-729]:
A new query prepare mechanism is support when a cluster version 6.5 and later is used.
* http://issues.couchbase.com/browse/JVMCBC-600[JVMCBC-600]:
Support for Mapped Diagnostic Context in Logging has been introduced (and `clientContext` from java options).
* http://issues.couchbase.com/browse/JVMCBC-731[JVMCBC-731]:
Mutation tokens are enabled by default and the CAS-based observe has been removed.

=== Bug Fixes

* http://issues.couchbase.com/browse/JCBC-1414[JCBC-1414]:
`geometry` has been removed from the `ViewRow` since spatial queries have also been removed earlier.
* http://issues.couchbase.com/browse/JCBC-1428[JCBC-1428]:
NonChunkedHttpMessageHandler fails the second time it is enabled.
* http://issues.couchbase.com/browse/JCBC-1406[JCBC-1406]:
The `expiration` option has been added to LookupIn.
* http://issues.couchbase.com/browse/JCBC-1407[JCBC-1407]:
LookupIn GetFull shouldn't expose xattr option.
* http://issues.couchbase.com/browse/JVMCBC-725[JVMCBC-725]:
Chunked handler should not close channel when being removed.
* http://issues.couchbase.com/browse/JVMCBC-724[JVMCBC-724]:
Non-Chunked HTTP Hander must report when request complete.
* http://issues.couchbase.com/browse/JVMCBC-727[JVMCBC-727]:
Fail cluster-level queries quickly if not serviceable.
* http://issues.couchbase.com/browse/JVMCBC-733[JVMCBC-733]:
Only dispatch view requests to nodes with primary partitions.
* http://issues.couchbase.com/browse/JVMCBC-734[JVMCBC-734]:
Close channel on unknown KV opaque.
* http://issues.couchbase.com/browse/JVMCBC-735[JVMCBC-735]:
Close KV connection on certain response status codes.
* http://issues.couchbase.com/browse/JVMCBC-737[JVMCBC-737]:
Harden HTTP handlers for write race conditions.
* http://issues.couchbase.com/browse/JVMCBC-728[JVMCBC-728]:
Subdoc MutateInOptions with CAS value provided is not cosidered during mutation.

== Version 3.0.0-alpha.6 (2 August 2019)

This is the sixth pre-release of the third generation Java SDK.

http://packages.couchbase.com/clients/java/3.0.0-alpha.6/Couchbase-Java-Client-3.0.0-alpha.6.zip[Download] | 
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.0-alpha.6/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.0-alpha.6/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.0-alpha.6**
* com.couchbase.client:**core-io:2.0.0-alpha.6**
* io.projectreactor:**reactor-core:3.2.10.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.2**

Note that since this release depends on core-io, it also includes transitive fixes and enhancements that may not all be reflected in the following list.

=== Enhancements

* http://issues.couchbase.com/browse/JCBC-1386[JCBC-1386]:
AsyncCluster and ReadtiveCluster create methods have been made asynchronous.
* http://issues.couchbase.com/browse/JCBC-1386[JCBC-1386]:
Group and user management API has been added.
* http://issues.couchbase.com/browse/JCBC-1386[JCBC-1386]:
A major rework of the get-based API has removed the Optional return type for consistency reasons.
* http://issues.couchbase.com/browse/JCBC-1386[JCBC-1386]:
Support for collection management has been added.
* http://issues.couchbase.com/browse/JCBC-1385[JCBC-1385]:
The default scope is now exposed on the bucket API directly.
* http://issues.couchbase.com/browse/JCBC-1377[JCBC-1377]:
Support for bucket management has been added. 
* http://issues.couchbase.com/browse/JCBC-1376[JCBC-1376]:
OpenTracing has been removed from the API for now until the implementation has been reworked.
* http://issues.couchbase.com/browse/JVMCBC-667[JVMCBC-667]:
Added support for DNS SRV bootstrapping.
* http://issues.couchbase.com/browse/JVMCBC-694[JVMCBC-694]:
When using Couchbase Server 6.5 and later, cluster-level queries can now be performed without opening a bucket.
* http://issues.couchbase.com/browse/JVMCBC-706[JVMCBC-706]:
The IO handlers now consolidate internal flush syscalls to reduce them as much as possible, leading to measurable performance improvements in highly concurrent workloads.
* http://issues.couchbase.com/browse/JVMCBC-711[JVMCBC-711]:
Unknown/Unsupported KeyValue error status codes are now logged so they can be better debugged.
* http://issues.couchbase.com/browse/JVMCBC-717[JVMCBC-717]:
Explicit support for the new KeyValue status DurableWriteReCommitInProgress has been added and mapped to an exception.
* http://issues.couchbase.com/browse/JVMCBC-673[JVMCBC-673]:
KeyValue error map response codes are now handled like in core-io 1.x (aside from transparent retry logic).
* http://issues.couchbase.com/browse/JVMCBC-703[JVMCBC-703]:
Durable writes are now short circuited early on when they are not available on the server side.

=== Bug Fixes

* http://issues.couchbase.com/browse/JVMCBC-704[JVMCBC-704]:
The initial seed nodes are now kept fresh which each subsequent config update.
* http://issues.couchbase.com/browse/JVMCBC-705[JVMCBC-705]:
If the underlying socket is closed upon an endpoint (channel), the endpoint now triggers a proactive reconnect.
* http://issues.couchbase.com/browse/JVMCBC-707[JVMCBC-707]: 
Shutting down the core (and the core environment) is properly synchronized with its internal state, preventing early shutdown reports while the inner shutdown is still happening.
* http://issues.couchbase.com/browse/JVMCBC-710[JVMCBC-710]: 
A race condition has been fixed which made concurrent requests possible against non-pipelined HTTP sockets which lead to queries not being executed properly.

== Version 3.0.0-alpha.5 (4 July 2019)

This is the fifth pre-release of the third generation Java SDK.

http://packages.couchbase.com/clients/java/3.0.0-alpha.5/Couchbase-Java-Client-3.0.0-alpha.5.zip[Download] | 
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.0-alpha.5/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.0-alpha.5/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.0-alpha.5**
* com.couchbase.client:**core-io:2.0.0-alpha.5**
* io.projectreactor:**reactor-core:3.2.10.RELEASE**
* io.opentracing:**opentracing-api:0.31.0**
* org.reactivestreams:**reactive-streams:1.0.2**

Note that since this release depends on core-io, it also includes transitive fixes and enhancements that may not all be reflected in the following list.

=== Enhancements

* http://issues.couchbase.com/browse/JCBC-1363[JCBC-1363], http://issues.couchbase.com/browse/JCBC-1282[JCBC-1282]: 
The exception hierarchy has been modified to align more closely with the other SDKs.
* http://issues.couchbase.com/browse/JVMCBC-700[JVMCBC-700]: 
On client initialization, diagnostics information with versions and config settings is printed at INFO level.

=== Bug Fixes

* http://issues.couchbase.com/browse/JVMCBC-686[JVMCBC-686]: 
Fixed default collection support when collections enabled.
* http://issues.couchbase.com/browse/JVMCBC-689[JVMCBC-689]: 
Now no longer get `DecodingFailedException` while performing sub_doc operations.
* http://issues.couchbase.com/browse/JVMCBC-1234[JVMCBC-1234]: 
Double check event loop before connecting.
* http://issues.couchbase.com/browse/JVMCBC-688[JVMCBC-688]: 
Always fetch cas-based observe fails for concurrent modifications.

== Version 3.0.0-alpha.4 (12 June 2019)

This is the fourth pre-release of the third generation Java SDK.

http://packages.couchbase.com/clients/java/3.0.0-alpha.4/Couchbase-Java-Client-3.0.0-alpha.4.zip[Download] | 
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.0-alpha.4/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.0-alpha.4/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.0-alpha.4**
* com.couchbase.client:**core-io:2.0.0-alpha.4**
* io.projectreactor:**reactor-core:3.2.10.RELEASE**
* io.opentracing:**opentracing-api:0.31.0**
* org.reactivestreams:**reactive-streams:1.0.2**

Note that since this release depends on core-io, it also includes transitive fixes and enhancements that may not all be reflected in the following list.

=== New Features

* http://issues.couchbase.com/browse/JCBC-1345[JCBC-1345]: 
Prepared statement support is now available again for N1Ql queries.
* http://issues.couchbase.com/browse/JVMCBC-626[JVMCBC-626]: 
The connection string can now be used to load properties and seed nodes with custom ports.
* http://issues.couchbase.com/browse/JVMCBC-676[JVMCBC-676]: 
Multiple sockets/endpoints for the KV service has been brought back (from 2.x functionality).

=== Enhancements

* http://issues.couchbase.com/browse/JCBC-1347[JCBC-1347]: 
The `pretty` N1Ql query option has been removed since it is not needed.
* http://issues.couchbase.com/browse/JCBC-1355[JCBC-1355]: 
Spatial view API support has been removed since it is deprecated on the server.
* http://issues.couchbase.com/browse/JCBC-1282[JCBC-1282]: 
The exception hierachy for error handling has been overhauled.
* http://issues.couchbase.com/browse/JVMCBC-684[JVMCBC-684]: 
Event bus event categories are now extendable by other components.
* http://issues.couchbase.com/browse/JVMCBC-668[JVMCBC-668]: 
Collection IDs are now refreshed automatically if they change.

=== Bug Fixes

* http://issues.couchbase.com/browse/JVMCBC-671[JVMCBC-671]: 
Accidential pipelining for streaming results (which led to timed out requests) has been fixed.
* http://issues.couchbase.com/browse/JVMCBC-681[JVMCBC-681]: 
The SDK now avoids resolving network addresses early, laying the groundwork for Kubernetes support.

== Version 3.0.0-alpha.3 (13 May 2019)

This is the third pre-release of the third generation Java SDK.

http://packages.couchbase.com/clients/java/3.0.0-alpha.3/Couchbase-Java-Client-3.0.0-alpha.3.zip[Download] | 
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.0-alpha.3/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.0-alpha.3/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.0-alpha.3**
* com.couchbase.client:**core-io:2.0.0-alpha.3**
* io.projectreactor:**reactor-core:3.2.8.RELEASE**
* io.opentracing:**opentracing-api:0.31.0**
* org.reactivestreams:**reactive-streams:1.0.2**

Note that since this release depends on core-io, it also includes transitive fixes and enhancements that may not all be reflected in the following list.

=== New Features

* http://issues.couchbase.com/browse/JCBC-1319[JCBC-1319]: 
Initial support for search index management capabilities.
* http://issues.couchbase.com/browse/JVMCBC-651[JVMCBC-651]: 
JSON query streaming parsers reworked completely on top of Jackson so they are more efficient, faster, and produce less garbage.
* http://issues.couchbase.com/browse/JVMCBC-617[JVMCBC-617]: 
It is now possible to populate the environment from system properties.

=== Enhancements

* http://issues.couchbase.com/browse/JCBC-1322[JCBC-1322]: 
Add `consistentWith` to `QueryOptions`.
* http://issues.couchbase.com/browse/JVMCBC-650[JVMCBC-650]: 
Traffic capturing can now be enabled on the environment.
* http://issues.couchbase.com/browse/JVMCBC-659[JVMCBC-659]: 
Native transports can be disabled with a switch on the environment.
* http://issues.couchbase.com/browse/JVMCBC-664[JVMCBC-664]: 
The SDK now passes the timeout down to the sync durability KV infrastructure.

=== Bug Fixes

* http://issues.couchbase.com/browse/JVMCBC-658[JVMCBC-658]: 
Improved config fetching and support for clusters deployed with `cluster_run`.
* http://issues.couchbase.com/browse/JVMCBC-669[JVMCBC-669]: 
Fixed a bug which prevent a node removal being picked up during rebalance out.
* http://issues.couchbase.com/browse/JVMCBC-655[JVMCBC-655]: 
Collection ID improvements (UnsignedLEB128 outputs bytes in reversed order).

== Version 3.0.0-alpha.2 (04 April 2019)

This is the second pre-release of the third generation Java SDK.

http://packages.couchbase.com/clients/java/3.0.0-alpha.2/Couchbase-Java-Client-3.0.0-alpha.2.zip[Download] | 
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.0-alpha.2/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.0-alpha.2/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.0-alpha.2**
* com.couchbase.client:**core-io:2.0.0-alpha.2**
* io.projectreactor:**reactor-core:3.2.8.RELEASE**
* io.opentracing:**opentracing-api:0.31.0**
* org.reactivestreams:**reactive-streams:1.0.2**

Note that since this release depends on core-io, it also includes transitive fixes and enhancements that may not all be reflected in the following list.

=== New Features

* http://issues.couchbase.com/browse/JCBC-1313[JCBC-1313]: 
Initial query support for the Analytics service.
* http://issues.couchbase.com/browse/JCBC-1314[JCBC-1314]: 
Initial query support for the View service.
* http://issues.couchbase.com/browse/JCBC-1315[JCBC-1315]: 
Initial query support for the Search service.

=== Enhancements

* http://issues.couchbase.com/browse/JCBC-1310[JCBC-1310]: 
Get signatures change to include explicit Optionals on Monos which make it easier to handle non-existing documents.
* http://issues.couchbase.com/browse/JCBC-1316[JCBC-1316]: 
Reworked the API for N1QL queries.

=== Bug Fixes

* http://issues.couchbase.com/browse/JCBC-1311[JCBC-1311]: 
Shutdown is now correctly propagated into core-io.
* http://issues.couchbase.com/browse/JCBC-1305[JCBC-1305]: 
Removes unused expiry from RemoveOptions
* http://issues.couchbase.com/browse/JVMCBC-639[JVMCBC-639]: 
IO threads are now daemon threads to not prevent the JVM from shutting down even when the SDK was not properly shutdown in the first place.


== Version 3.0.0-alpha.1 (12 March 2019)

This is the first pre-release of the third generation Java SDK and a complete rewrite over the 2.x series. As such, there are no release notes for this release present.

