= Compatibility of Couchbase Features, Couchbase Server Versions, and the Couchbase Java SDK
:navtitle: Compatibility
:page-aliases: ROOT:overview,ROOT:compatibility-versions-features,compatibility-versions-features

[abstract]
Features available in different SDK versions, and compatibility between Server and SDK.

The 3.0 SDK requires Java 8 or later to be installed, earlier versions will not work. 
_Java 11 is recommended_, which has various enhancements like lambda local variable type inference, profiling tools, and updated security features. 
Most of the flavors available will do, although we may only provide support for OpenJDK and Oracle JDK going forward. 
The Java SDK _has not been tested (and is not supported on) Java 12 or later_.


== Couchbase Version/SDK Version Matrix

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.
The matrix below denotes the version of Couchbase Server, the version of the Java SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*:This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
[cols="40,25,20,20,25"]
|===
| | SDK 2.4, 2.5 | SDK 2.6 | SDK 2.7  | SDK 3.0 

| *Server 5.0-5.5*
| *✔*
| *✔*
| *✔*
| *◎*

| *Server 6.0*
| ◎
| *✔*
| *✔*
| *✔*


| *Server 6.5*
| *✖*
| ◎
| *✔*
| *✔*
|===

Note the https://www.couchbase.com/support-policy[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.


[#jdk-compat]
== JDK Version Compatibility

The Java SDK is tested with Oracle JDK and OpenJDK.
Other JDK implementations might work but are not tested and are unsupported.
We recommend running the latest LTS version (i.e. at the time of writing JDK 11) with the highest patch version available.

The following JDK releases are supported:

* OpenJDK 11 with HotSpot JVM (recommended)
* Oracle JDK 11 (recommended)
* OpenJDK 1.8 with HotSpot JVM
* Oracle JDK 1.8

Please make sure you run on one of the latest patch releases, since they provide stability improvements and security fixes in general.


== Couchbase Feature Availability Matrix

.Couchbase Server and SDK Supported Version Matrix
|===
| | Server 5.0, 5.1, & 5.5 | Server 6.0 | Server 6.5

| Enhanced Durability
3+| All SDK versions

| Durable Writes 
2+| Not Supported
| Since 3.0

| Analytics
| DP in 5.5 with 2.6
2+| Since 2.7

| Distributed ACID Transactions
2+| Not Supported
| Since 3.0

| Collections
2+| Not Supported
| Developer Preview in 6.5, SDK 3.0

|===

include::6.5@sdk:shared:partial$network-requirements.adoc


include::6.5@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]
