= Compatibility
:description: Platform compatibility, and features available in different SDK versions, and compatibility between Server and SDK. \
Plus notes on Cloud, networks, and AWS Lambda.
:page-aliases: ROOT:overview.adoc,ROOT:compatibility-versions-features.adoc,compatibility-versions-features.adoc
:page-toclevels: 3
:table-caption!:


[abstract]
{description}


The {sdk_dot_minor} SDK requires Java 8 or later
_Java {java_latest_lts_version} is recommended_.



== Platform Compatibility


=== JDK Version Compatibility

include::{version-common}@sdk:shared:partial$compat.adoc[tag=jdk-compat]


=== OS Compatibility

In general, the JVM eliminates concerns about underlying OS compatibility, 
and Couchbase JVM SDKs can be expected to run on all of the Operating Systems supported by xref:{version-server}@server:install:install-platforms.adoc[Couchbase Server].


include::{version-common}@sdk:shared:partial$compat.adoc[tag=os-compat]


The JVM SDKs should also be expected to run on other commonly-available GNU/Linux distributions which support an appropriate JDK, but not all combinations can be tested -- notable exceptions are listed below.

==== Alpine Linux Compatibility

The https://netty.io[Netty] I/O library used by our JVM SDKs supports native optimizations to achieve higher throughput and lower latency 
-- which the SDK enables by default. 
Those modules are compiled against `glibc` and Alpine Linux uses `musl` instead --
so the {name-sdk} is unable to complete bootstrapping on this platform.

Because Alpine Linux does not have the `glibc` support needed,
we highly recommend that you seek an alternative distribution where possible. 
If that is not a option, then a possible workaround that can be applied is as follows:

* Disable native IO and native TLS by setting both the `ioEnvironment.enableNativeIo` and `security.enableNativeTls` client settings to false, as in this example:
+
[source,java]
----
Cluster cluster = Cluster.connect(
  connectionString,
  ClusterOptions.clusterOptions(username, password)
    .environment(env -> env
      .ioEnvironment(it -> it.enableNativeIo(false))
      .securityConfig(it -> it.enableNativeTls(false))
    )
);
----

* Alternatively, disable it in Netty itself via the following system properties:
+
[source,shell]
----
-Dcom.couchbase.client.core.deps.io.netty.transport.noNative=true
-Dcom.couchbase.client.core.deps.io.netty.handler.ssl.noOpenSsl=true
----

The downside of these workarounds is potentially reduced performance, which can be determined through benchmarking and profiling.




// Platforms, Chipsets, and Virtual Environments.
include::{version-common}@sdk:shared:partial$compat.adoc[tag=virtual]





// Network Requirements
include::{version-common}@sdk:shared:partial$compat.adoc[tag=network-requirements]



// Serverless Environments
include::{version-common}@sdk:shared:partial$compat.adoc[tag=serverless]






== Couchbase Server Compatibility


Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.

=== Couchbase Version/SDK Version Matrix


include::{version-common}@sdk:shared:partial$compat.adoc[tag=matrix-notes1]



.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
|===
| | 3.4, 3.5 | 3.6, 3.7 | 3.8 | 3.9-3.13

| *Server 8.0* ①
| *✔*
| *✔*
| *✔*
| *✔*

| *Server 7.6* ①
| *✔*
| *✔*
| *✔*
| *✔*

| *Server 7.2*
| *◎*
| *◎*
| *✔*
| *✔*
|===



include::{version-common}@sdk:shared:partial$compat.adoc[tag=matrix-notes2]




=== Capella Compatibility


include::{version-common}@sdk:shared:partial$compat.adoc[tag=cloud]


=== Couchbase New Feature Availability Matrix

.Couchbase Server and SDK Supported Version Matrix
[.table-merge-cells]
[cols="7,6,6,6"]
|===
| | Server 7.2 | Server 7.6  | Server 8.0

| KV Range Scan
| N/A
2+| All supported SDK versions

| Vector Search
| N/A
2+| From SDK 3.6.0 (base64 encoded vectors from 3.7.0)

| Preferred Server Group Replica Reads
| N/A
2+| From SDK 3.7.4 (with Server 7.6.2 onwards)

| Vector Query using GSI
2+| N/A
| From SDK 3.9.0 ①
|===


include::{version-common}@sdk:shared:partial$compat.adoc[tag=feature-notes]



=== Spring Data Couchbase Compatibility

https://projects.spring.io/spring-data-couchbase/[Spring Data Couchbase^] uses the Java SDK underneath and as a result is also provides different compatibilities with Couchbase Server.
The following table provides an overview at the time of Java SDK {sdk_dot_minor}'s release:

.Recommended Spring Data Couchbase per Server Version Matrix
[#table_spring_versions]
|===
|  | SDC 5.4 - 5.5 | SDC 6.0 - 6.1

| _Status ->_
| _Maintenance Support_
| _New Features, Active Development_

| *Server 7.2 - 8.0*
| *Compatible*
| *Recommended*
|===

NOTE: Check the Spring Data Couchbase's compile dependencies -- older versions may link an out-of-date version of the SDK in their dependencies list, although a supported version should be in the `updates`.
Please make sure that you are using a supported version of the Couchbase Java SDK, prefereably the latest version, which will contain any available bug fixes.
Using the latest Spring Data Couchbase should ensure that this is so.


=== Quarkus Java Compatibility

include::1.4@quarkus-extension::compatibility.adoc[tag=compat-table]

See the xref:quarkus-extension:ROOT:overview.adoc[Couchbase Quarkus Java Extension docs] for details of using Quarkus, and the compatibility with Quarkus, GraalVM, and the Couchbase Java SDK.


=== API Version

include::{version-common}@sdk:shared:partial$compat.adoc[tag=api-version]




== SDK API Stability


=== Interface Stability

include::{version-common}@sdk:shared:partial$compat.adoc[tag=interface-stability-section]


=== Older SDK Versions


include::{version-common}@sdk:shared:partial$compat.adoc[tag=archive-link]

