= Compatibility of Couchbase Features, Couchbase Server Versions, and the Couchbase Java SDK
:navtitle: Compatibility
:page-aliases: ROOT:overview,ROOT:compatibility-versions-features,compatibility-versions-features

[abstract]
Features available in different SDK versions, and compatibility between Server and SDK.

The 3.0 SDK requires Java 8 or later to be installed, earlier versions will not work. 
_Java 11 is recommended_, which has various enhancements like lambda local variable type inference, profiling tools, and updated security features. 
Most of the flavors available will do, although we may only provide support for OpenJDK and Oracle JDK going forward. 
The Java SDK _has not been tested (and is not supported on) Java 12 or later_.

== Couchbase Version/SDK Version Matrix

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.
The matrix below denotes the version of Couchbase Server, the version of the .NET SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*:This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
[cols="40,25,20,20,25"]
|===
| | SDK 2.4, 2.5 | SDK 2.6 | SDK 2.7  | SDK 3.0 

| *Server 5.0-5.5*
| *✔*
| *✔*
| *✔*
| *✔*

| *Server 6.0*
| ◎
| *✔*
| *✔*
| *✔*


| *Server 6.5*
| *✖*
| ◎
| *✔*
| *✔*
|===

Note the https://www.couchbase.com/support-policy[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.

== Couchbase Feature Availability Matrix

TBI


include::6.5@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]
