= Compatibility of Couchbase Features, Couchbase Server Versions, and the Couchbase Java SDK
:description: Features available in different SDK versions, and compatibility between Server and SDK. \
Plus notes on Cloud, networks, and AWS Lambda.
:navtitle: Compatibility
:page-aliases: ROOT:overview,ROOT:compatibility-versions-features,compatibility-versions-features
:page-toclevels: 2

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}

The 3.3 SDK requires Java 8 or later to be installed, earlier versions will not work.
_Java 17 is recommended_, which has various enhancements like sealed classes, pattern matching for switch expressions (in preview), and further updates and improvements on core libraries.
Most of the flavors available will do, although we may only provide support for OpenJDK and Oracle JDK going forward. 

== Couchbase Version/SDK Version Matrix

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.
The matrix below denotes the version of Couchbase Server, the version of the Java SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*: This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
[cols="40,20,25"]
|===
| | SDK 3.0, 3.1 | SDK 3.2, 3.3

| *Server 5.5*
| *✔*
| *✔*

| *Server 6.0*
| *✔*
| *✔*

| *Server 6.5-6.6*
| *✔*
| *✔*

| *Server 7.0-7.1*
| *◎*
| *✔*
|===

Note the https://www.couchbase.com/support-policy[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.

=== Capella Compatibility

At time of release, the Couchbase 3.3 Java SDK is fully compatible with Couchbase Capella, our fully-hosted database-as-a-service.
To make development easier, the 3.3 SDK includes the Capella client certificate ready installed.


[#jdk-compat]
== JDK Version Compatibility

The Java SDK is tested with Oracle JDK and OpenJDK.
Other JDK implementations might work but are not tested and are unsupported.
We recommend running the latest LTS version (i.e. at the time of writing JDK 17) with the highest patch version available.

We only support LTS versions of Oracle JDK and OpenJDK.
Other versions may work -- _but they are not tested and they are not supported_.

The following JDK releases are supported at time of 3.3 SDK release (April 2022):

* https://adoptium.net/[OpenJDK 11] (Hotspot recommended) or https://www.oracle.com/java/technologies/downloads/#jdk11[Oracle JDK 11]
* https://adoptium.net/[OpenJDK 17 with HotSpot JVM] (recommended)
* https://www.oracle.com/java/technologies/downloads/#jdk17[Oracle JDK 17 (recommended)]
* https://adoptium.net/[OpenJDK 1.8 with HotSpot JVM]
* https://www.oracle.com/java/technologies/downloads/#java8[Oracle JDK 1.8]

Please make sure you run on one of the latest patch releases, since they provide stability improvements and security fixes in general.


== OS Compatibility

In general, the JVM eliminates concerns about underlying OS compatibility, 
and Couchbase JVM SDKs can be expected to run on all of the Operating Systems supported by xref:7.1@server:install:install-platforms.adoc[Couchbase Server].

Specifically, the 3.3 SDK is tested with the following OSs and platforms:


****
[discrete]
=== GNU/Linux

* Amazon Linux 2.
* Red Hat Enterprise Linux 7 & 8;
* CentOS 7 & 8.
* Ubuntu (LTS) 16.04 (_Xenial_), 18.04 (_Bionic_), & 20.04 (_Focal_).
* Debian 9 (_Stretch_) & 10 (_Buster_).
* Alpine Linux (_Oracle JDK only_) -- but see <<alpine-linux-compatibility, workaround note below>>.

[discrete]
=== Microsoft Windows

Microsoft Windows 10 / All LTS releases from Windows Server 2016.

[discrete]
=== Mac OS X

The current and previous two releases of OS X.
At time of writing (April 2022): 10.15 (_Catalina_), 11 (_Big Sur_), and 12 (_Monterey_).
M1 ARM  architecture is fully supported in the 3.3 Java SDK.

[discrete]
=== ARM Processor Support

Java 3.3 SDK supports AWS Amazon Graviton2 and Apple M1 ARM processors.
****

The JVM SDKs should also be expected to run on other commonly-available GNU/Linux distributions which support an appropriate JDK, but not all combinations can be tested -- notable exceptions are listed below.

=== Alpine Linux Compatibility

The https://netty.io[Netty] I/O library used by our JVM SDKs supports native optimizations to achieve higher throughput and lower latency 
-- which the SDK enables by default. 
Those modules are compiled against `glibc` and Alpine Linux uses `musl` instead --
so the Java SDK is unable to complete bootstrapping on this platform.

Because Alpine Linux does not have the `glibc` support needed,
we highly recommend that you seek an alternative distribution where possible. 
If that is not a option, then a possible workaround that can be applied is as follows:

* Disable the native IO:
+
[source,toml]
====
ClusterEnvironment env = ClusterEnvironment.builder().ioEnvironment(IoEnvironment.enableNativeIo(false)).build();
====

* Disable it in Netty itself via the following system property:
`-Dcom.couchbase.client.core.deps.io.netty.transport.noNative=true`

The downside of these workarounds is potentially reduced performance, which can be determined through benchmarking and profiling.


== Couchbase Feature Availability Matrix

.Couchbase Server and SDK Supported Version Matrix
[.table-merge-cells] 
[cols="7,5,5,5,7"]
|===
| | Server 5.5 | Server 6.0 | Server 6.5 & 6.6 | Server 7.0 & 7.1

| Enhanced Durability
4+| All SDK versions

| Durable Writes 
2+| Not Supported
2+| Since SDK 3.0

| Analytics
| DP in 5.5 with SDK 2.6
3+| Since SDK 2.7

| Distributed ACID Transactions
2+| Not Supported
2+| Since SDK 3.3 included in SDK.
Since SDK 3.0 with With Java Transactions Libraryfootnote:[3.0.7 or more recent recommended; preferably, follow the transitive dependency for the transactions library in Maven.]

| N1QL Queries inside the Transaction Lambda
3+| Not Supported
| Since SDK 3.1, or since 3.0.7 with Java Transactions Libraryfootnote:[1.2.1 or newer recommended.]

| Default Collections
2+| Not Supported
| Developer Preview in 6.5-6.6, SDK 3.0
| Since SDK 3.0.6

| Scope-Level N1QL Queries & all Collections features
3+| Not Supported
2+| Since SDK 3.2.0

| Field Level Encryption v2
2+| Not Supported
3+| Since SDK 3.0.5footnote:[Field Level Encryption distributed as separate library.]

| Request Tracing
2+| Not Supported
3+| Since SDK 3.1.0
|===

include::7.1@sdk:shared:partial$network-requirements.adoc[]


[#spring-compat]
== Spring Data Couchbase Compatibility

https://projects.spring.io/spring-data-couchbase/[Spring Data Couchbase^] uses the Java SDK underneath and as a result is also provides different compatibilities with Couchbase Server.
The following table provides an overview.

.Recommended Spring Data Couchbase per Server Version Matrix
[#table_spring_versions]
|===
|  | SDC 4.0 - 4.2

| _Status ->_
| _New Features, Active Development_

| *Server 6.0*
| *Recommended*

| *Server 6.5 & 6.6*
| *Recommended*

| *Server 7.0 & 7.1*
| *Recommended*
|===

NOTE: Check the Spring Data Couchbase's compile dependencies -- older versions may link an out-of-date version of the Java SDK in their dependencies list, although a supported version should be in the `updates`.
Please make sure that you are using a supported version of the Couchbase Java SDK, prefereably the latest version, which will contain any available bug fixes.
Using the latest Spring Data Couchbase should ensure that this is so.

[CAUTION]
.Reactor Core Version
====
SpringBoot may set the io.projectreactor version at an earlier version than the one needed by the current version of https://search.maven.org/artifact/com.couchbase.client/core-io/2.2.0/jar[Couchbase JVM Core IO]. 
In case of errors, override with Core IO's preferred version, e.g.:

----
<dependency>
    <groupId>io.projectreactor</groupId>
    <artifactId>reactor-core</artifactId>
    <version>3.4.6.RELEASE</version>
</dependency>
----
====

include::7.1@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]

include::7.1@sdk:shared:partial$api-version.adoc[tag=api-version]

include::7.1@sdk:pages:partial$archive.adoc[tag=link]
