= Couchbase Distributed ACID Transactions for Java SDK Release Notes
:navtitle: Transactions Release Notes
:page-topic-type: project-doc
:page-aliases: transactions-release-notes

Couchbase Distributed ACID Transactions is distributed as a separate library for the Java SDK.
This page features the release notes for that library -- for release notes, download links, and installation methods for the latest 3.x Java SDK releases, see xref:sdk-release-notes.adoc[the current Release Notes page].

== Using Distributed Transactions

See the xref:6.5@server:learn:data/distributed-acid-transactions.adoc[Distributed ACID Transactions concept doc] in the server documentation for details of how Couchbase implements transactions.
The xref:howtos:distributed-acid-transactions-from-the-sdk.adoc[Distributed Transactions HOWTO doc] walks you through all aspects of working with Distributed Transactions.



== Distributed Transactions Java 1.0.0-beta.2

This is the second _Beta_ release of Distributed ACID Transactions 1.0.0 for Couchbase Server 6.5 and the Java 3.0.0 client.

Built on Couchbase java-client version 3.0.0-alpha.7.
Requires Couchbase Server 6.5 beta or above.

== Breaking changes
As a rule, we do not make breaking API changes after GA release, and only consider them rarely during the beta period.
This particular change aligns the transaction and Java libraries much better, makes for a more natural and usable API, and requires little porting work.

* https://issues.couchbase.com/browse/TXNJ-121[TXNJ-121]: Align with the Couchbase Java client,
by renaming the `get` method to `getOptional`, `getOrError` to `get`, and `TransactionJsonDocument` to `TransactionGetResult`.

=== Performance

* https://issues.couchbase.com/browse/TXNJ-40[TXNJ-40]:
Retry operations on many transient errors, rather than retrying the full transaction.

=== New features

* https://issues.couchbase.com/browse/TXNJ-85[TXNJ-85]:
Supported deferred commit for transactions.  Please see the documentation for details.
* https://issues.couchbase.com/browse/TXNJ-112[TXNJ-112]:
(Experimental) Allow the number of ATRs to be configured.
This can potentially be used to improve transactions throughput, but is currently experimental and should be used only with Couchbase's guidance.

== Distributed Transactions Java 1.0.0-beta.1

This is the first _Beta_ release of Distributed ACID Transactions 1.0.0 for Couchbase Server 6.5 and the Java 3.0.0 client.

Built on Couchbase java-client version 3.0.0-alpha.6.
Requires Couchbase Server 6.5 beta or above.

=== New features

* https://issues.couchbase.com/browse/TXNJ-41[TXNJ-41]:
Add fields required for backup
* https://issues.couchbase.com/browse/TXNJ-52[TXNJ-52],
https://issues.couchbase.com/browse/TXNJ-53[TXNJ-53],
https://issues.couchbase.com/browse/TXNJ-56[TXNJ-56],
https://issues.couchbase.com/browse/TXNJ-71[TXNJ-71],
https://issues.couchbase.com/browse/TXNJ-72[TXNJ-72],
https://issues.couchbase.com/browse/TXNJ-75[TXNJ-75],
https://issues.couchbase.com/browse/TXNJ-76[TXNJ-76],
https://issues.couchbase.com/browse/TXNJ-83[TXNJ-83]:
More readable and useful logging

=== Bug-fixes and stability

* https://issues.couchbase.com/browse/TXNJ-47[TXNJ-47]:
Improved handling for expiry -- the transaction will now try to enter Aborted state
* https://issues.couchbase.com/browse/TXNJ-50[TXNJ-50]:
Intermittent reactive asserts about blocking on a thread from the "parallel" scheduler
* https://issues.couchbase.com/browse/TXNJ-55[TXNJ-55]:
Retry transient errors while rolling back ATR entry, rather than retrying transaction
* https://issues.couchbase.com/browse/TXNJ-57[TXNJ-57]:
Add log redaction for document keys
* https://issues.couchbase.com/browse/TXNJ-59[TXNJ-59]:
Fix an issue with the lost cleanup thread aborting early
* https://issues.couchbase.com/browse/TXNJ-64[TXNJ-64]:
Commit documents in the order they were staged
* https://issues.couchbase.com/browse/TXNJ-79[TXNJ-79], https://issues.couchbase.com/browse/TXNJ-81[TXNJ-81]:
Improved handling of transient server errors while trying to create ATR entries
* https://issues.couchbase.com/browse/TXNJ-90[TXNJ-90]:
Improved handling of conflicts when multiple applications start at once and try to create the client record
* https://issues.couchbase.com/browse/TXNJ-96[TXNJ-96]:
Improved handling of transient errors removing entries from the client record

=== Deprecations and removals

* https://issues.couchbase.com/browse/TXNJ-92[TXNJ-92]:
OpenTracing removed from API -- will be re-added when _OpenTelemetry_ is ready
