= Couchbase Java SDK Release Notes and Archives
:navtitle: Release Notes
:page-topic-type: project-doc
:page-aliases: relnotes-java-sdk

== Installation

At least Java 8 is required for current releases; all newer, vendor supported Java versions are supported (and encouraged). 
See the xref:2.7@java-sdk::compatibility-versions-features.adoc[Compatibility] section for details.
Java 11 is recommended which has various enhancements like lambda local variable type inference, profiling tools and updated security features.

== Version 3.0.0-alpha.5 (4 July 2019)

This is the fifth pre-release of the third generation Java SDK.

http://packages.couchbase.com/clients/java/3.0.0-alpha.5/Couchbase-Java-Client-3.0.0-alpha.5.zip[Download] | 
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.0-alpha.5/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.0-alpha.5/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.0-alpha.5**
* com.couchbase.client:**core-io:2.0.0-alpha.5**
* io.projectreactor:**reactor-core:3.2.10.RELEASE**
* io.opentracing:**opentracing-api:0.31.0**
* org.reactivestreams:**reactive-streams:1.0.2**

Note that since this release depends on core-io, it also includes transitive fixes and enhancements that may not all be reflected in the following list.

=== Enhancements

* http://issues.couchbase.com/browse/JCBC-1363[JCBC-1363], http://issues.couchbase.com/browse/JCBC-1282[JCBC-1282]: 
The exception hierarchy has been modified to align more closely with the other SDKs.
* http://issues.couchbase.com/browse/JVMCBC-700[JVMCBC-700]: 
On client initialization, diagnostics information with versions and config settings is printed at INFO level.

=== Bug Fixes

* http://issues.couchbase.com/browse/JVMCBC-686[JVMCBC-686]: 
Fixed default collection support when collections enabled.
* http://issues.couchbase.com/browse/JVMCBC-689[JVMCBC-689]: 
Now no longer get `DecodingFailedException` while performing sub_doc operations.
* http://issues.couchbase.com/browse/JVMCBC-1234[JVMCBC-1234]: 
Double check event loop before connecting.
* http://issues.couchbase.com/browse/JVMCBC-688[JVMCBC-688]: 
Always fetch cas-based observe fails for concurrent modifications.

== Version 3.0.0-alpha.4 (12 June 2019)

This is the fourth pre-release of the third generation Java SDK.

http://packages.couchbase.com/clients/java/3.0.0-alpha.4/Couchbase-Java-Client-3.0.0-alpha.4.zip[Download] | 
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.0-alpha.4/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.0-alpha.4/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.0-alpha.4**
* com.couchbase.client:**core-io:2.0.0-alpha.4**
* io.projectreactor:**reactor-core:3.2.10.RELEASE**
* io.opentracing:**opentracing-api:0.31.0**
* org.reactivestreams:**reactive-streams:1.0.2**

Note that since this release depends on core-io, it also includes transitive fixes and enhancements that may not all be reflected in the following list.

=== New Features

* http://issues.couchbase.com/browse/JCBC-1345[JCBC-1345]: 
Prepared statement support is now available again for N1Ql queries.
* http://issues.couchbase.com/browse/JVMCBC-626[JVMCBC-626]: 
The connection string can now be used to load properties and seed nodes with custom ports.
* http://issues.couchbase.com/browse/JVMCBC-676[JVMCBC-676]: 
Multiple sockets/endpoints for the KV service has been brought back (from 2.x functionality).

=== Enhancements

* http://issues.couchbase.com/browse/JCBC-1347[JCBC-1347]: 
The `pretty` N1Ql query option has been removed since it is not needed.
* http://issues.couchbase.com/browse/JCBC-1355[JCBC-1355]: 
Spatial view API support has been removed since it is deprecated on the server.
* http://issues.couchbase.com/browse/JCBC-1282[JCBC-1282]: 
The exception hierachy for error handling has been overhauled.
* http://issues.couchbase.com/browse/JVMCBC-684[JVMCBC-684]: 
Event bus event categories are now extendable by other components.
* http://issues.couchbase.com/browse/JVMCBC-668[JVMCBC-668]: 
Collection IDs are now refreshed automatically if they change.

=== Bug Fixes

* http://issues.couchbase.com/browse/JVMCBC-671[JVMCBC-671]: 
Accidential pipelining for streaming results (which led to timed out requests) has been fixed.
* http://issues.couchbase.com/browse/JVMCBC-681[JVMCBC-681]: 
The SDK now avoids resolving network addresses early, laying the groundwork for Kubernetes support.

== Version 3.0.0-alpha.3 (13 May 2019)

This is the third pre-release of the third generation Java SDK.

http://packages.couchbase.com/clients/java/3.0.0-alpha.3/Couchbase-Java-Client-3.0.0-alpha.3.zip[Download] | 
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.0-alpha.3/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.0-alpha.3/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.0-alpha.3**
* com.couchbase.client:**core-io:2.0.0-alpha.3**
* io.projectreactor:**reactor-core:3.2.8.RELEASE**
* io.opentracing:**opentracing-api:0.31.0**
* org.reactivestreams:**reactive-streams:1.0.2**

Note that since this release depends on core-io, it also includes transitive fixes and enhancements that may not all be reflected in the following list.

=== New Features

* http://issues.couchbase.com/browse/JCBC-1319[JCBC-1319]: 
Initial support for search index management capabilities.
* http://issues.couchbase.com/browse/JVMCBC-651[JVMCBC-651]: 
JSON query streaming parsers reworked completely on top of Jackson so they are more efficient, faster, and produce less garbage.
* http://issues.couchbase.com/browse/JVMCBC-617[JVMCBC-617]: 
It is now possible to populate the environment from system properties.

=== Enhancements

* http://issues.couchbase.com/browse/JCBC-1322[JCBC-1322]: 
Add `consistentWith` to `QueryOptions`.
* http://issues.couchbase.com/browse/JVMCBC-650[JVMCBC-650]: 
Traffic capturing can now be enabled on the environment.
* http://issues.couchbase.com/browse/JVMCBC-659[JVMCBC-659]: 
Native transports can be disabled with a switch on the environment.
* http://issues.couchbase.com/browse/JVMCBC-664[JVMCBC-664]: 
The SDK now passes the timeout down to the sync durability KV infrastructure.

=== Bug Fixes

* http://issues.couchbase.com/browse/JVMCBC-658[JVMCBC-658]: 
Improved config fetching and support for clusters deployed with `cluster_run`.
* http://issues.couchbase.com/browse/JVMCBC-669[JVMCBC-669]: 
Fixed a bug which prevent a node removal being picked up during rebalance out.
* http://issues.couchbase.com/browse/JVMCBC-655[JVMCBC-655]: 
Collection ID improvements (UnsignedLEB128 outputs bytes in reversed order).

== Version 3.0.0-alpha.2 (04 April 2019)

This is the second pre-release of the third generation Java SDK.

http://packages.couchbase.com/clients/java/3.0.0-alpha.2/Couchbase-Java-Client-3.0.0-alpha.2.zip[Download] | 
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.0-alpha.2/[API Reference] | http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.0-alpha.2/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.0-alpha.2**
* com.couchbase.client:**core-io:2.0.0-alpha.2**
* io.projectreactor:**reactor-core:3.2.8.RELEASE**
* io.opentracing:**opentracing-api:0.31.0**
* org.reactivestreams:**reactive-streams:1.0.2**

Note that since this release depends on core-io, it also includes transitive fixes and enhancements that may not all be reflected in the following list.

=== New Features

* http://issues.couchbase.com/browse/JCBC-1313[JCBC-1313]: 
Initial query support for the Analytics service.
* http://issues.couchbase.com/browse/JCBC-1314[JCBC-1314]: 
Initial query support for the View service.
* http://issues.couchbase.com/browse/JCBC-1315[JCBC-1315]: 
Initial query support for the Search service.

=== Enhancements

* http://issues.couchbase.com/browse/JCBC-1310[JCBC-1310]: 
Get signatures change to include explicit Optionals on Monos which make it easier to handle non-existing documents.
* http://issues.couchbase.com/browse/JCBC-1316[JCBC-1316]: 
Reworked the API for N1QL queries.

=== Bug Fixes

* http://issues.couchbase.com/browse/JCBC-1311[JCBC-1311]: 
Shutdown is now correctly propagated into core-io.
* http://issues.couchbase.com/browse/JCBC-1305[JCBC-1305]: 
Removes unused expiry from RemoveOptions
* http://issues.couchbase.com/browse/JVMCBC-639[JVMCBC-639]: 
IO threads are now daemon threads to not prevent the JVM from shutting down even when the SDK was not properly shutdown in the first place.


== Version 3.0.0-alpha.1 (12 March 2019)

This is the first pre-release of the third generation Java SDK and a complete rewrite over the 2.x series. As such, there are no release notes for this release present.
