= SDK Release Notes
:description: Release notes, installation instructions, and download archive for the Couchbase Java Client.
:navtitle: Release Notes
:page-topic-type: project-doc
:page-toclevels: 2
:page-partial:
:page-aliases: relnotes-java-sdk,ROOT:sdk-release-notes,ROOT:relnotes-java-sdk,ROOT:release-notes,ROOT:download-links,server:sdks:java-2.2/download-links

[abstract]
{description}

These pages cover the 3._x_ versions of the Couchbase Java SDK. 
For release notes, download links, and installation methods for 2.7 and earlier releases of the Couchbase Java Client, please see the https://docs-archive.couchbase.com/java-sdk/2.7/sdk-release-notes.html[2.x Java Release Notes & Download Archive].

=== Installation

See the xref:project-docs:sdk-full-installation.adoc[Full Installation] guide for details.


// tag::all[]


[#latest-release]
== Java SDK 3.7 Releases

We always recommend using the latest version of the SDK -- it contains all of the latest security patches and support for new and upcoming features.
All patch releases for each dot minor release should be API compatible, and safe to upgrade;
any changes to expected behavior are noted in the release notes that follow.

////
# get version numbers like this
src=../couchbase-jvm-clients
grep '<reactor.version>' $src/pom.xml
grep ' <reactive-streams.version>' $src/pom.xml
echo tracing-opentelemetry ; grep '<version>' $src/tracing-opentelemetry/pom.xml | head -2 | tail -1 ; grep '<opentelemetry.version>' $src/pom.xml 
echo tracing-opentracing ; grep '<version>' $src/tracing-opentracing/pom.xml | head -2 | tail -1 ; grep '<opentracing.version>' $src/tracing-opentracing/pom.xml
echo metrics-opentelemetry ; grep '<version>' $src/metrics-opentelemetry/pom.xml | head -2 | tail -1 ; grep '<opentelemetry.version>' $src/pom.xml 
echo metrics-micrometer ; grep '<version>' $src/metrics-micrometer/pom.xml | head -2 | tail -1 ; grep '<micrometer.version>' $src/metrics-micrometer/pom.xml 
////



=== Version 3.7.0 (15 June 2024)

This is the first release of 3.7 series.

https://packages.couchbase.com/clients/java/3.7.0/Couchbase-Java-Client-3.7.0.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.7.0/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.7.0/[Core API Reference]

The supported and tested dependencies for this release are:

* io.projectreactor:**reactor-core:3.6.3**
* org.reactivestreams:**reactive-streams:1.0.4**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Couchbase Version | Built Against              | API Stability
| `tracing-opentelemetry`   | 1.5.0             | OpenTelemetry 1.31.0       | Committed
| `tracing-opentracing`     | 1.5.0             | OpenTracing 0.33.0         | Committed
| `metrics-opentelemetry`   | 0.7.0             | OpenTelemetry 1.31.0       | Volatile
| `metrics-micrometer`      | 0.7.0             | Micrometer 1.10.9          | Volatile
|=======================

==== Improvements
* https://issues.couchbase.com/browse/JCBC-2149[JCBC-2149]:
Adds support for base64-encoded vectors in `VectorQuery`.



== Java SDK 3.6 Releases

=== Version 3.6.2 (29 April 2024)

This is a regular maintenance release.

https://packages.couchbase.com/clients/java/3.6.2/Couchbase-Java-Client-3.6.2.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.6.2/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.6.2/[Core API Reference]

The supported and tested dependencies for this release are:

* io.projectreactor:**reactor-core:3.6.3**
* org.reactivestreams:**reactive-streams:1.0.4**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Couchbase Version | Built Against              | API Stability
| `tracing-opentelemetry`   | 1.4.2             | OpenTelemetry 1.31.0       | Committed
| `tracing-opentracing`     | 1.4.2             | OpenTracing 0.33.0         | Committed
| `metrics-opentelemetry`   | 0.6.2             | OpenTelemetry 1.31.0       | Volatile
| `metrics-micrometer`      | 0.6.2             | Micrometer 1.10.9          | Volatile
|=======================

==== Improvements

* https://issues.couchbase.com/browse/JVMCBC-1508[JVMCBC-1508]:
Upgraded Netty dependency.
* https://issues.couchbase.com/browse/JVMCBC-1509[JVMCBC-1509]:
Upgraded Jackson dependency.
* https://issues.couchbase.com/browse/JCBC-2135[JCBC-2135]:
Added binary support for transactions.

==== Bugfixes

* https://issues.couchbase.com/browse/JVMCBC-1506[JVMCBC-1506]:
Reduced the rate at which messages appear in the server's `http_access.log` when a user provides valid credentials but does not have permission to access the bucket.
* https://issues.couchbase.com/browse/JVMCBC-1512[JVMCBC-1512]:
Updated Service in Cluster Configuration if only the port is changed.


=== Version 3.6.1 (5 April 2024)

This is a regular maintenance release.

https://packages.couchbase.com/clients/java/3.6.1/Couchbase-Java-Client-3.6.1.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.6.1/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.6.1/[Core API Reference]

The supported and tested dependencies for this release are:

* io.projectreactor:**reactor-core:3.6.3**
* org.reactivestreams:**reactive-streams:1.0.4**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Couchbase Version | Built Against              | API Stability
| `tracing-opentelemetry`   | 1.4.1             | OpenTelemetry 1.31.0       | Committed
| `tracing-opentracing`     | 1.4.1             | OpenTracing 0.33.0         | Committed
| `metrics-opentelemetry`   | 0.6.1             | OpenTelemetry 1.31.0       | Volatile
| `metrics-micrometer`      | 0.6.1             | Micrometer 1.10.9          | Volatile
|=======================

==== Improvements

* https://issues.couchbase.com/browse/JVMCBC-1477[JVMCBC-1477]:
Reduced the rate at which messages appear in the server’s `http_access.log` when invalid credentials are provided resulting in 401 errors.  
Issues resulting in 403 errors will be handled in a future release.
* https://issues.couchbase.com/browse/JVMCBC-1498[JVMCBC-1498]:
The fields of a `SearchRow` from a Full-Text Search result are now included in the output of `SearchRow.toString()`.
* https://issues.couchbase.com/browse/JVMCBC-1499[JVMCBC-1499]:
Disabled DNS SRV caching. The SDK now responds quicker to DNS changes in dynamic environments like Kubernetes.
* https://issues.couchbase.com/browse/JVMCBC-1500[JVMCBC-1500]:
Added `EventingFunctionLanguageCompatibility.VERSION_7_2_0`.
* https://issues.couchbase.com/browse/JVMCBC-1504[JVMCBC-1504]:
Deprecated static methods that return new config builders, like `TimeoutConfig.builder()` and `TimeoutConfig.kvTimeout(Duration)`.
See the following example for the recommended way to configure client settings:
+
[source,java]
----
Cluster cluster = Cluster.connect(
  connectionString,
  ClusterOptions.clusterOptions(username, password)
    .environment(env -> env
      .timeoutConfig(timeout -> timeout
        .kvTimeout(Duration.ofSeconds(3))
      )
    )
);
----

=== Version 3.6.0 (11 March 2024)

Version 3.6.0 is the first release of the 3.6 series.

https://packages.couchbase.com/clients/java/3.6.0/Couchbase-Java-Client-3.6.0.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.6.0/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.6.0/[Core API Reference]

The supported and tested dependencies for this release are:
* io.projectreactor:**reactor-core:3.6.3**
* org.reactivestreams:**reactive-streams:1.0.4**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Couchbase Version | Built Against              | API Stability
| `tracing-opentelemetry`   | 1.4.0             | OpenTelemetry 1.31.0       | Committed
| `tracing-opentracing`     | 1.4.0             | OpenTracing 0.33.0         | Committed
| `metrics-opentelemetry`   | 0.6.1             | OpenTelemetry 1.31.0       | Volatile
| `metrics-micrometer`      | 0.6.1             | Micrometer 1.10.9          | Volatile
|=======================

==== Improvements

* https://issues.couchbase.com/browse/JCBC-2116[JCBC-2116]:
Added support for vector search, a new feature in Couchbase Server 7.6.
This API is currently at `@Stability.Uncommitted` level.
* https://issues.couchbase.com/browse/JCBC-2131[JCBC-2131]:
`Scope.searchIndexes()` is now part of the committed public API.
* https://issues.couchbase.com/browse/JVMCBC-1487[JVMCBC-1487]:
Upgraded reactor-core from 3.5.8 to 3.6.3.
* https://issues.couchbase.com/browse/JVMCBC-1488[JVMCBC-1488]:
Upgraded Jackson from 2.16.0 to 2.16.1.
* https://issues.couchbase.com/browse/JVMCBC-1489[JVMCBC-1489]:
Upgraded Netty from 4.1.101 to 4.1.107.
* https://issues.couchbase.com/browse/JVMCBC-1491[JVMCBC-1491]:
`Collection.scan()` methods are now part of the SDK's committed public API.
These methods do range-scans of documentIds.
This feature requires Couchbase Server 7.6 or later.
* https://issues.couchbase.com/browse/JVMCBC-1493[JVMCBC-1493]:
`Collection.lookupInAnyReplica()` and `Collection.lookupInAllReplicas()` are now part of the SDK’s committed public API.
These methods do sub-document lookups against replicas.
This feature requires Couchbase Server 7.6 or later.

==== Bugfixes

* https://issues.couchbase.com/browse/JCBC-2125[JCBC-2125]:
Fixed an issue with `ScopeSearchIndexManager`, `disallowQuerying`, and `freezePlan` methods, which were not waiting for the server result before returning in the blocking API.
* https://issues.couchbase.com/browse/JVMCBC-1480[JVMCBC-1480]:
`couchbase2:` should use exponential backoff when bypassing `BestEffortRetryStrategy`.
* https://issues.couchbase.com/browse/JVMCBC-1494[JVMCBC-1494]:
If you specify `min=1` for a Full-Text Search disjunction query, the SDK now always sends the value to the server.
Previously, the SDK assumed `1` was the default value, and omitted the parameter in that case.


== Java SDK 3.5 Releases

=== Version 3.5.3 (6 February 2024)

This is a regular maintenance release.

https://packages.couchbase.com/clients/java/3.5.3/Couchbase-Java-Client-3.5.3.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.5.3/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.5.3/[Core API Reference]

The supported and tested dependencies for this release are:

* io.projectreactor:**reactor-core:3.5.8**
* org.reactivestreams:**reactive-streams:1.0.4**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Couchbase Version | Built Against              | API Stability
| `tracing-opentelemetry`   | 1.3.3             | OpenTelemetry 1.31.0       | Committed
| `tracing-opentracing`     | 1.3.3             | OpenTracing 0.33.0         | Committed
| `metrics-opentelemetry`   | 0.5.3             | OpenTelemetry 1.31.0       | Volatile
| `metrics-micrometer`      | 0.5.3             | Micrometer 1.10.9          | Volatile
|=======================


==== Improvements

* https://issues.couchbase.com/browse/JVMCBC-1460[JVMCBC-1460]:
`couchbase2` now supports compressing data between the SDK and the server.
* https://issues.couchbase.com/browse/JVMCBC-1464[JVMCBC-1464]:
The `metrics-opentelemetry` package is now aligned with the same `OpenTelemetry` version as `tracing-opentelemetry`.
* https://issues.couchbase.com/browse/JVMCBC-1468[JVMCBC-1468]:
`Cluster.connect` now validates that connection strings using the `couchbase2` scheme have exactly one host.
(Previously, hosts after the first were silently ignored.).
* https://issues.couchbase.com/browse/JVMCBC-1470[JVMCBC-1470]:
Improved support for Full Text Search in `couchbase2` mode.
* https://issues.couchbase.com/browse/JVMCBC-1472[JVMCBC-1472]:
`couchbase2` errors will now include diagnostic information when CNG is running with the `--debug` flag.
* https://issues.couchbase.com/browse/JCBC-2117[JCBC-2117]:
Support added for `maxTTL` value of -1 for collection "no expiry".

==== Bugfixes

* https://issues.couchbase.com/browse/JVMCBC-1475[JVMCBC-1475:
Accessing the terms of a `TermFacet` result no longer throws `NullPointerException` if the target field is absent from all documents.


=== Version 3.5.2 (5 January 2024)

This is a regular maintenance release.

https://packages.couchbase.com/clients/java/3.5.2/Couchbase-Java-Client-3.5.2.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.5.2/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.5.2/[Core API Reference]

The supported and tested dependencies for this release are:

* io.projectreactor:**reactor-core:3.5.8**
* org.reactivestreams:**reactive-streams:1.0.4**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Couchbase Version | Built Against              | API Stability
| `tracing-opentelemetry`   | 1.3.2             | OpenTelemetry 1.31.0       | Committed
| `tracing-opentracing`     | 1.3.2             | OpenTracing 0.33.0         | Committed
| `metrics-opentelemetry`   | 0.5.2             | OpenTelemetry 1.31.0       | Volatile
| `metrics-micrometer`      | 0.5.2             | Micrometer 1.10.9          | Volatile
|=======================


==== Improvements

* https://issues.couchbase.com/browse/JCBC-2113[JCBC-2113]:
Added a `QueryMetadata.signatureBytes()` method for accessing query signatures that are not JSON Objects.

==== Bugfixes

* https://issues.couchbase.com/browse/JVMCBC-1455[JVMCBC-1455]:
Fixed compatibility with `couchbase2://` endpoints by upgrading internal GRPC dependency. 
All `couchbase2://` users should upgrade to this release.
* https://issues.couchbase.com/browse/JVMCBC-1463[JVMCBC-1463]:
Fixed compatibility between `couchbase2://` endpoints and the `tracing-opentelemetry` module.


=== Version 3.5.1 (8 December 2023)

This is a regular maintenance release.

https://packages.couchbase.com/clients/java/3.5.1/Couchbase-Java-Client-3.5.1.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.5.1/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.5.1/[Core API Reference]

The supported and tested dependencies for this release are:

* io.projectreactor:**reactor-core:3.5.8**
* org.reactivestreams:**reactive-streams:1.0.4**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Couchbase Version | Built Against              | API Stability
| `tracing-opentelemetry`   | 1.3.1             | OpenTelemetry 1.31.0       | Committed
| `tracing-opentracing`     | 1.3.1             | OpenTracing 0.33.0         | Committed
| `metrics-opentelemetry`   | 0.5.1             | OpenTelemetry 1.31.0       | Volatile
| `metrics-micrometer`      | 0.5.1             | Micrometer 1.10.9          | Volatile
|=======================

==== Improvements

* https://issues.couchbase.com/browse/JVMCBC-1435[JVMCBC-1435],
https://issues.couchbase.com/browse/JVMCBC-1436[JVMCBC-1436]:
Upgraded Netty and Jackson dependencies.
* https://issues.couchbase.com/browse/JVMCBC-1440[JVMCBC-1440]:
Adding `DocumentNotLockedException` supporting future Couchbase Server versions that will return an error code when unlocking a document that is not locked.

==== Bugfixes

* https://issues.couchbase.com/browse/JVMCBC-1433[JVMCBC-1433]:
The SDK can now connect to Memcached buckets whose names contain the percent (`%`) character.
(We'd like to take this opportunity to remind everyone that Memcached buckets are deprecated in favor of Ephemeral buckets.)
* https://issues.couchbase.com/browse/JVMCBC-1437[JVMCBC-1437]:
With Couchbase Server versions that support updating a collection's max expiry, it's now possible to clear the expiry by passing `Duration.ZERO` for the new value.
* https://issues.couchbase.com/browse/JVMCBC-1441[JVMCBC-1441]:
The SDK now handles an additional error case for `IndexNotFoundException`.
* https://issues.couchbase.com/browse/JVMCBC-1442[JVMCBC-1442]:
Fixed a dependency issue with `tracing-opentelemetry` module.


=== Version 3.5.0 (21 November 2023)

Version 3.5.0 is the first release of the 3.5 series.

The SDK now supports the new couchbase2 protocol, which is upcoming in future Couchbase Server versions.
It can be enabled through using a connection string starting with `couchbase2://`.
Please see xref:howtos:managing-connections.adoc#cloud-native-gateway[Cloud Native Gateway] for more information.

The SDK now directly depends on SLF4J, which may impact some users -- see below for details.

https://packages.couchbase.com/clients/java/3.5.0/Couchbase-Java-Client-3.5.0.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.5.0/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.5.0/[Core API Reference]

The supported and tested dependencies for this release are:

* io.projectreactor:**reactor-core:3.5.8**
* org.reactivestreams:**reactive-streams:1.0.4**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Couchbase Version | Built Against              | API Stability
| `tracing-opentelemetry`   | 1.3.0             | OpenTelemetry 1.31.0       | Committed
| `tracing-opentracing`     | 1.3.0             | OpenTracing 0.33.0         | Committed
| `metrics-opentelemetry`   | 0.5.0             | OpenTelemetry 1.31.0       | Volatile
| `metrics-micrometer`      | 0.5.0             | Micrometer 1.10.9          | Volatile
|=======================

==== API Impacting

* https://issues.couchbase.com/browse/JVMCBC-1319[JVMCBC-1319]:
BEHAVIORAL CHANGE
+
As https://www.couchbase.com/forums/t/embracing-slf4j-in-couchbase-java-sdk-3-5/36474[previously announced], the SLF4J API is now a required dependency, and the SDK does all logging through SLF4J. The following client settings for customizing logging behavior are deprecated, and no longer have any effect:

** `logger.disableSlf4J`
** `logger.fallbackToConsole`
** `logger.consoleLoggerFormatter`
+
If your project does not already use SLF4J, please follow the announcement link for details and a mini-migration guide.

==== Improvements

* https://issues.couchbase.com/browse/JVMCBC-1402[JVMCBC-1402],
https://issues.couchbase.com/browse/JVMCBC-1410[JVMCBC-1410]:
Upgraded Netty from 4.1.96 to 4.1.100, and upgraded `OpenTelemetry` dependency.
* https://issues.couchbase.com/browse/JVMCBC-1430[JVMCBC-1430]:
Optimization: removed creation of unnecessary metrics labels when default `LoggingMeter` is used.
* https://issues.couchbase.com/browse/JVMCBC-1391[JVMCBC-1391]:
The Bucket Manager API is now forward-compatible with future versions of Couchbase Server that might support storage engine types other than "magma" and "couchstore".
* https://issues.couchbase.com/browse/JVMCBC-1327[JVMCBC-1327]:
Improved support for failover handling in future server versions.

==== Bugfixes

* https://issues.couchbase.com/browse/JVMCBC-1264[JVMCBC-1264]:
DNS SRV lookups now honor the DNS search path.
This enables DNS SRV resolution in Kubernetes environments where the `*-srv` hostname advertised by the Couchbase Operator is a partial name that must be resolved using a suffix from the DNS search path.
* https://issues.couchbase.com/browse/JVMCBC-1426[JVMCBC-1426]:
When Couchbase Server is too busy to start a new KV range scan, the SDK now retries instead of throwing a `CouchbaseException`.



== Java SDK 3.4 Releases

=== Version 3.4.11 (4 October 2023)

With thanks to our community for the contribution, support for Micrometer Observation has been added via the new `tracing-micrometer-observation` module.

https://packages.couchbase.com/clients/java/3.4.11/Couchbase-Java-Client-3.4.11.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.4.11/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.4.11/[Core API Reference]

The supported and tested dependencies for this release are:

* io.projectreactor:**reactor-core:3.5.8**
* org.reactivestreams:**reactive-streams:1.0.4**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Couchbase Version | Built Against              | API Stability
| `tracing-opentelemetry`   | 1.2.11             | OpenTelemetry 1.19.0       | Committed
| `tracing-opentracing`     | 1.2.11             | OpenTracing 0.33.0         | Committed
| `metrics-opentelemetry`   | 0.4.11             | OpenTelemetry 1.19.0       | Volatile
| `metrics-micrometer`      | 0.4.11             | Micrometer 1.10.9          | Volatile
|=======================

==== Improvements
* https://issues.couchbase.com/browse/JCBC-2046[JCBC-2046]:
With thanks to our community for the contribution, support for Micrometer Observation has been added via the new `tracing-micrometer-observation` module.
* https://issues.couchbase.com/browse/JVMCBC-1327[JVMCBC-1327]:
Internal improvements to support upcoming faster failover and config push features.

==== Bugfixes
* https://issues.couchbase.com/browse/JVMCBC-1364[JVMCBC-1364]:
Fixed decoding of certain niche sub-document errors, so they no longer raise a `DecodingFailureException`.


=== Version 3.4.10 (6 September 2023)

This is a standard maintenance release.

https://packages.couchbase.com/clients/java/3.4.10/Couchbase-Java-Client-3.4.10.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.4.10/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.4.10/[Core API Reference]

The supported and tested dependencies for this release are:

* io.projectreactor:**reactor-core:3.5.8**
* org.reactivestreams:**reactive-streams:1.0.4**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Couchbase Version | Built Against              | API Stability
| `tracing-opentelemetry`   | 1.2.10             | OpenTelemetry 1.19.0       | Committed
| `tracing-opentracing`     | 1.2.10             | OpenTracing 0.33.0         | Committed
| `metrics-opentelemetry`   | 0.4.10             | OpenTelemetry 1.19.0       | Volatile
| `metrics-micrometer`      | 0.4.10             | Micrometer 1.10.9          | Volatile
|=======================

==== Improvements
* https://issues.couchbase.com/browse/JVMCBC-1367[JVMCBC-1367]:
The `db.couchbase.operations` metric now has `db.name` (bucket), `db.couchbase.scope`, `db.couchbase.collection` and `outcome` labels (tags).
This new feature is at Stability.Volatile, and may change before it is promoted to Stability.Committed in a future release.
* https://issues.couchbase.com/browse/JVMCBC-1311[JVMCBC-1311],
https://issues.couchbase.com/browse/JVMCBC-1352[JVMCBC-1352]:
Upgraded dependencies.

==== Bugfixes
* https://issues.couchbase.com/browse/JVMCBC-1350[JVMCBC-1350]:
`lookupInAnyReplica` now throws `FeatureNotAvailableException` if the server does not support the feature.
* https://issues.couchbase.com/browse/JVMCBC-1351[JVMCBC-1351]:
`lookupInAnyReplica` no longer hangs when too many operations are specified.
* https://issues.couchbase.com/browse/JVMCBC-1353[JVMCBC-1353]:
Removed the unrelocated `io.opentracing` classes that accidentally slipped into version 2.4.9 of the Couchbase `core-io` library.
* https://issues.couchbase.com/browse/JVMCBC-1361[JVMCBC-1361]:
When the SDK receives multiple cluster map versions at the same time, it is now more careful about applying only the most recent version.
Before this change, there was a brief window where the SDK could apply an obsolete cluster map.
If this happened, the SDK would temporarily dispatch requests to incorrect or non-existent nodes.
This condition was typically short-lived, and healed the next time the SDK polled for an updated cluster map, or dispatched a KV request to the wrong node.
* https://issues.couchbase.com/browse/JVMCBC-1368[JVMCBC-1368]:
Fixed a rare `java.lang.ArithmeticException: / by zero` exception in `RoundRobinSelectionStrategy.select` that could occur during rebalance.


=== Version 3.4.9 (2 August 2023)

This release adds support for Sub-Document reads from replicas at @Stability.Volatile level: see `collection.lookupInAnyReplica()` and `collection.lookupInAllReplicas()`.

https://packages.couchbase.com/clients/java/3.4.9/Couchbase-Java-Client-3.4.9.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.4.9/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.4.9/[Core API Reference]

The supported and tested dependencies for this release are:

* io.projectreactor:**reactor-core:3.5.0**
* org.reactivestreams:**reactive-streams:1.0.4**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Couchbase Version | Built Against              | API Stability
| `tracing-opentelemetry`   | 1.2.9             | OpenTelemetry 1.19.0       | Committed
| `tracing-opentracing`     | 1.2.9             | OpenTracing 0.33.0         | Committed
| `metrics-opentelemetry`   | 0.4.9             | OpenTelemetry 1.19.0       | Volatile
| `metrics-micrometer`      | 0.4.9             | Micrometer 1.10.0          | Volatile
|=======================

==== Improvements
* https://issues.couchbase.com/browse/JVMCBC-1339[JVMCBC-1339]:
When KV traffic capture is enabled, each `ReadTrafficCapturedEvent` now contains a single protocol frame, and the human-readable frame description is more accurate.
* https://issues.couchbase.com/browse/JVMCBC-1320[JVMCBC-1320]:
The `waitUntilReady` method is now more aggressive about retrying failed pings.
Also, waiting for a desired state of `DEGRADED` no longer fails when the client is fully connected to the cluster.
* https://issues.couchbase.com/browse/JVMCBC-1343[JVMCBC-1343]:
Reduced the default value for the `io.idleHttpConnectionTimeout` client setting to 1 second.
The previous default (4.5 seconds) was too close to the 5-second server-side timeout, and could lead to spurious request failures.
* https://issues.couchbase.com/browse/JCBC-2078[JCBC-2078]:
Support for Sub-Document read from replica.


=== Version 3.4.8 (19 July 2023)
This is a regular maintenance release.

https://packages.couchbase.com/clients/java/3.4.8/Couchbase-Java-Client-3.4.8.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.4.8/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.4.8/[Core API Reference]

The supported and tested dependencies for this release are:

* io.projectreactor:**reactor-core:3.5.0**
* org.reactivestreams:**reactive-streams:1.0.4**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Couchbase Version | Built Against              | API Stability
| `tracing-opentelemetry`   | 1.2.8             | OpenTelemetry 1.19.0       | Committed
| `tracing-opentracing`     | 1.2.8             | OpenTracing 0.33.0         | Committed
| `metrics-opentelemetry`   | 0.4.8             | OpenTelemetry 1.19.0       | Volatile
| `metrics-micrometer`      | 0.4.8             | Micrometer 1.10.0          | Volatile
|=======================

==== Improvements
* https://issues.couchbase.com/browse/JCBC-2077[JCBC-2077]:
Upcoming Couchbase server release 7.6 will support having SQL++ queries read from replicas, in scenarios where the active is unavailable (such as failover).
This improves availability, though users should be aware that they may be reading stale data.
The option is activated with `scope.query("...", queryOptions().useReplica(true))`, and is disabled by default.
It will only work against 7.6 and above: against older server versions, it will raise a `FeatureNotAvailableException`.
* https://issues.couchbase.com/browse/JVMCBC-1322[JVMCBC-1322]:
The `waitUntilReady()` method now logs additional diagnostic information to the `com.couchbase.core.WaitUntilReady` logging category at `DEBUG` level.
* https://issues.couchbase.com/browse/JCBC-2059[JCBC-2059]:
If a `Cluster` becomes eligible for garbage collection, and you haven't called `cluster.disconnect()` yet, the SDK now logs a warning and disconnects the cluster for you. 
This prevent the abandoned cluster's network connections from living forever. Please do not rely on this "auto-disconnect" feature. 
It's always better to call `cluster.disconnect()` as soon as you're done talking to the cluster, so the network connections and other resources get released right away.
* https://issues.couchbase.com/browse/JCBC-2076[JCBC-2076]:
`Collection.touch` now has an additional overload that allows specifying the expiry as an `Instant` instead of a `Duration`.

=== Version 3.4.7 (12 June 2023)
This is a regular maintenance release.

https://packages.couchbase.com/clients/java/3.4.7/Couchbase-Java-Client-3.4.7.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.4.7/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.4.7/[Core API Reference]

The supported and tested dependencies for this release are:

* io.projectreactor:**reactor-core:3.5.0**
* org.reactivestreams:**reactive-streams:1.0.4**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Couchbase Version | Built Against              | API Stability
| `tracing-opentelemetry`   | 1.2.7             | OpenTelemetry 1.19.0       | Committed
| `tracing-opentracing`     | 1.2.7             | OpenTracing 0.33.0         | Committed
| `metrics-opentelemetry`   | 0.4.7             | OpenTelemetry 1.19.0       | Volatile
| `metrics-micrometer`      | 0.4.7             | Micrometer 1.10.0          | Volatile
|=======================

==== API Impacting
* https://issues.couchbase.com/browse/JCBC-2075[JCBC-2075]:
Deprecated `ArrayInsert.createPath()`. Calling this method always causes `mutateIn` to throw an exception, because the "array insert" sub-document command does not support creating missing parent objects. If you want to create missing parent objects, please use `MutateInSpec.arrayAppend()` or `arrayPrepend()` instead of `arrayInsert()`.

==== Improvements
* https://issues.couchbase.com/browse/JCBC-2069[JCBC-2069]:
`Collection.getAndTouch` now has an additional overload that allows specifying the expiry as an `Instant` instead of a `Duration`.
* https://issues.couchbase.com/browse/JVMCBC-1290[JVMCBC-1290]:
Added a new environment config property, `SecurityConfig.enableCertificateVerification(boolean)`, which defaults to true. The purpose of this property is to allow disabling TLS certificate verification in development environments where configuring the CA certificate to trust is not practical. Setting this to false is equivalent to configuring the environment to use `InsecureTrustManager.INSTANCE`.
For compatibility with other modern Couchbase SDKs, certificate verification can now be disabled using the connection string parameter: `tls_verify=none`.
This config property is introduced at stability level `Volatile`, meaning it may change in a patch release without notice.
* https://issues.couchbase.com/browse/JVMCBC-1278[JVMCBC-1278],
https://issues.couchbase.com/browse/JVMCBC-1310[JVMCBC-1310],
https://issues.couchbase.com/browse/JVMCBC-1313[JVMCBC-1313]:
Dependencies updated.

==== Bugs
* https://issues.couchbase.com/browse/JVMCBC-1283[JVMCBC-1283]:
A faceted Full-Text Search result's `SearchNumericRange.min()` and `max()` methods now correctly return null instead of zero when the respective range endpoint is unbounded.
* https://issues.couchbase.com/browse/JVMCBC-1288[JVMCBC-1288]:
Fixed a regression in Couchbase Java SDK 3.4.5 and Scala SDK 1.4.5 that prevented Full-Text Search result rows from including an explanation when requested.
* https://issues.couchbase.com/browse/JVMCBC-1292[JVMCBC-1292]:
Removed `META-INF/versions/9/module-info.class` from the `core-io` jar. This file was associated with an improperly repackaged dependency, and never should have been there.

=== Version 3.4.6 (4 May 2023)
This is a regular maintenance release.

https://packages.couchbase.com/clients/java/3.4.6/Couchbase-Java-Client-3.4.6.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.4.6/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.4.6/[Core API Reference]

The supported and tested dependencies for this release are:

* io.projectreactor:**reactor-core:3.5.0**
* org.reactivestreams:**reactive-streams:1.0.4**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Couchbase Version | Built Against              | API Stability
| `tracing-opentelemetry`   | 1.2.6             | OpenTelemetry 1.19.0       | Committed
| `tracing-opentracing`     | 1.2.6             | OpenTracing 0.33.0         | Committed
| `metrics-opentelemetry`   | 0.4.6             | OpenTelemetry 1.19.0       | Volatile
| `metrics-micrometer`      | 0.4.6             | Micrometer 1.10.0          | Volatile
|=======================

==== Improvements
* https://issues.couchbase.com/browse/JCBC-1570[JCBC-1570],
https://issues.couchbase.com/browse/JCBC-2058[JCBC-2058]:
The `osgi-feature` artifact now uses Log4j 2 instead of Log4j 1.

==== Bugs
* https://issues.couchbase.com/browse/JCBC-2062[JCBC-2062]:
Fixed a regression in 3.4.5 that caused `ReactiveCollection.lookupIn` to always throw `StackOverflowException`.
* https://issues.couchbase.com/browse/JVMCBC-1275[JVMCBC-1275]:
Fixed a regression in Couchbase Java SDK 3.4.5 and Scala SDK 1.4.5 that caused Full Text Search `term` queries to throw `NullPointerException` unless `prefixLength` and `fuzziness` were specified.
* https://issues.couchbase.com/browse/JVMCBC-1281[JVMCBC-1281]:
Fixed a regression in Java SDK 3.4.5 that could cause Full-Text Search results to be sorted in the wrong order if the sort option was specified using a mix of strings and `SearchSort` objects.
* https://issues.couchbase.com/browse/JVMCBC-1285[JVMCBC-1285]:
Fixed a regression in Couchbase Java SDK 3.4.5 and Scala SDK 1.4.5 that caused Full-Text Search queries to fail to report the locations of some terms. Specifically, any location that did not have `arrayPositions` was omitted from the results.

=== Version 3.4.5 (13 April 2023)
This is a regular maintenance release.

https://packages.couchbase.com/clients/java/3.4.5/Couchbase-Java-Client-3.4.5.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.4.5/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.4.5/[Core API Reference]

The supported and tested dependencies for this release are:

* io.projectreactor:**reactor-core:3.5.0**
* org.reactivestreams:**reactive-streams:1.0.4**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Couchbase Version | Built Against              | API Stability
| `tracing-opentelemetry`   | 1.2.5             | OpenTelemetry 1.19.0       | Committed
| `tracing-opentracing`     | 1.2.5             | OpenTracing 0.33.0         | Committed
| `metrics-opentelemetry`   | 0.4.5             | OpenTelemetry 1.19.0       | Volatile
| `metrics-micrometer`      | 0.4.5             | Micrometer 1.10.0          | Volatile
|=======================

==== Improvements
* https://issues.couchbase.com/browse/JVMCBC-1223[JVMCBC-1223]:
Adds a `RetryReason.AUTHENTICATION_ERROR` at `Uncommitted` API stability level.
A custom `RetryStrategy` can use this new, more granular information to distinguish if a connection problem is down to an authentication issue.

==== Bugs
* https://issues.couchbase.com/browse/JCBC-2032[JCBC-2032]:
The JSON returned by `SearchQuery.export()` no longer contains extra fields unrelated to the query.
* https://issues.couchbase.com/browse/JVMCBC-1252[JVMCBC-1252]:
Orphaned "observe" operations will no longer occasionally contain a `total_duration_us` field equal to 0.
* https://issues.couchbase.com/browse/JVMCBC-1255[JVMCBC-1255]:
If you were subscribing to the event bus and printing all the events, you may have noticed `Event.toString()` throwing a `NullPointerException` if the event context is null.
`Event.toString()` now handles null contexts more gracefully, and no longer throws this exception.

=== Version 3.4.4 (8 March 2023)
This is a regular maintenance release.

https://packages.couchbase.com/clients/java/3.4.4/Couchbase-Java-Client-3.4.4.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.4.4/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.4.4/[Core API Reference]

The supported and tested dependencies for this release are:

* io.projectreactor:**reactor-core:3.5.0**
* org.reactivestreams:**reactive-streams:1.0.4**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Couchbase Version | Built Against              | API Stability
| `tracing-opentelemetry`   | 1.2.4             | OpenTelemetry 1.19.0       | Committed
| `tracing-opentracing`     | 1.2.4             | OpenTracing 0.33.0         | Committed
| `metrics-opentelemetry`   | 0.4.4             | OpenTelemetry 1.19.0       | Volatile
| `metrics-micrometer`      | 0.4.4             | Micrometer 1.10.0          | Volatile
|=======================


==== Improvements
* https://issues.couchbase.com/browse/JCBC-2050[JCBC-2050]:
Coordinates in Full-Text Search geographic queries can now be specified using a staged builder, so it's harder to accidentally swap the latitude and longitude components. Example usage:
```
Coordinate eiffelTower = Coordinate.lat(48.858093).lon(2.294694);
```
Or, if you prefer to specify longitude first:
```
Coordinate eiffelTower = Coordinate.lon(2.294694).lat(48.858093);
```
* https://issues.couchbase.com/browse/JVMCBC-1237[JVMCBC-1237]:
Added "network" as an alias for the "io.networkResolution" connection string parameter.
For example, the connection string "couchbase://example.com?network=external" is now equivalent to "couchbase://example.com?io.networkResolution=external".
This was done for compatibility with other Couchbase SDKs that use "network" as the name of this parameter.

==== Bugs
* https://issues.couchbase.com/browse/JVMCBC-1232[JVMCBC-1232]:
`Cluster.connect()` now rejects connection strings that have no addresses (like "couchbase://").
Before this change, it would accept the invalid connection string, and subsequent operations would fail with a misleading error message: "The cluster does not support cluster-level queries".
* https://issues.couchbase.com/browse/JVMCBC-1234[JVMCBC-1234]:
Fixed a regression in Java SDK 3.4.3 and Scala SDK 1.4.3 that caused SQL++ query result metadata to always include metrics, regardless of the "metrics" query option.

=== Version 3.4.3 (9 February 2023)
This is a regular maintenance release.

https://packages.couchbase.com/clients/java/3.4.3/Couchbase-Java-Client-3.4.3.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.4.3/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.4.3/[Core API Reference]

The supported and tested dependencies for this release are:

* io.projectreactor:**reactor-core:3.5.0**
* org.reactivestreams:**reactive-streams:1.0.4**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Couchbase Version | Built Against              | API Stability
| `tracing-opentelemetry`   | 1.2.3             | OpenTelemetry 1.19.0       | Committed
| `tracing-opentracing`     | 1.2.3             | OpenTracing 0.33.0         | Committed
| `metrics-opentelemetry`   | 0.4.3             | OpenTelemetry 1.19.0       | Volatile
| `metrics-micrometer`      | 0.4.3             | Micrometer 1.10.0          | Volatile
|=======================


==== Improvements

* https://issues.couchbase.com/browse/JCBC-2034[JCBC-2034]:
`CollectionQueryIndexManager` has been added at a `@Stability.Volatile` level, to better allow management of query indexes at the Collection level.
Documentation and an upgrade to a higher stability level will follow in the next minor SDK bump.
Until then, users are encourage to try out the new functionality and provide feedback -- but should expect the possibility of API changes.
* https://issues.couchbase.com/browse/JVMCBC-1181[JVMCBC-1181]:
It is now possible to authenticate over secure connections even if the JVM does not support the SASL PLAIN authentication mechanisms.
* https://issues.couchbase.com/browse/JVMCBC-1184[JVMCBC-1184]:
Updated dependencies.
* https://issues.couchbase.com/browse/JVMCBC-1213[JVMCBC-1213]:
If too many operations are specified in a single sub-document lookup, the exception message now indicates why the operation failed.

==== Bug Fixes

* https://issues.couchbase.com/browse/JVMCBC-1160[JVMCBC-1160]:
When a sub-document path has a syntax error or is inappropriate for an operation, the SDK now throws `PathInvalidException`.
Prior to this change, it would throw a generic `CouchbaseException` with the message "Unexpected SubDocument response code".
* https://issues.couchbase.com/browse/JCBC-2045[JCBC-2045]:
`WatchQueryIndexOptions` now extends `CommonOptions`, allowing standard options such as timeout to be specified.


=== Version 3.4.2 (16 January 2023)

This is a regular maintenance release.

https://packages.couchbase.com/clients/java/3.4.2/Couchbase-Java-Client-3.4.2.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.4.2/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.4.2/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.4.2**
* com.couchbase.client:**core-io:2.4.2**
* io.projectreactor:**reactor-core:3.5.0**
* org.reactivestreams:**reactive-streams:1.0.4**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Couchbase Version | Built Against              | API Stability
| `tracing-opentelemetry`   | 1.2.2             | OpenTelemetry 1.19.0       | Committed
| `tracing-opentracing`     | 1.2.2             | OpenTracing 0.33.0         | Committed
| `metrics-opentelemetry`   | 0.4.2             | OpenTelemetry 1.19.0       | Volatile
| `metrics-micrometer`      | 0.4.2             | Micrometer 1.10.0          | Volatile
|=======================


==== Improvements
* https://issues.couchbase.com/browse/JVMCBC-1175[JVMCBC-1175]:
The SDK now includes native libraries for IO and TLS that can enhance performance on `aarch_64` architectures like Graviton and Apple Silicon. Previously, native libraries were included only for `x86_64` architectures.
Native libraries for IO and TLS are enabled by default. If you need to disable native IO, set the `ioEnvironment.enableNativeIo` client setting to false. To disable native TLS, set the `security.enableNativeTls` client setting to false.

==== Bugs
* https://issues.couchbase.com/browse/JVMCBC-1161[JVMCBC-1161]:
Fixed a minor issue where `cluster.disconnect()` could occasionally timeout due to a race condition.
* https://issues.couchbase.com/browse/JVMCBC-1176[JVMCBC-1176]:
Setting `security.enableNativeTls` to false now prevents the SDK from even attempting to load the native TLS library. (Prior to this change, the SDK would load the library and just not use it.) In addition to saving a bit of memory, this prevents the JVM from segfaulting on Alpine Linux where glibc is not available.
* https://issues.couchbase.com/browse/JVMCBC-1180[JVMCBC-1180]:
Supporting in transactions a future version of Couchbase Server that requires query_context be sent in all queries.
* https://issues.couchbase.com/browse/JVMCBC-1174[JVMCBC-1174]:
Fixed a regression that prevented native TLS from being used regardless of whether the `security.enableNativeTls` client setting was set to true.


=== Version 3.4.1 (7 December 2022)

Version 3.4.1 is the second release of the 3.4 series.
The headline change is support for the KV range scan feature (`collection.scan()`), added at @Stability.Volatile level.
This feature will be available in a future version of Couchbase Server.

https://packages.couchbase.com/clients/java/3.4.1/Couchbase-Java-Client-3.4.1.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.4.1/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.4.1/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.4.1**
* com.couchbase.client:**core-io:2.4.1**
* io.projectreactor:**reactor-core:3.5.0**
* org.reactivestreams:**reactive-streams:1.0.4**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Couchbase Version | Built Against              | API Stability
| `tracing-opentelemetry`   | 1.2.1             | OpenTelemetry 1.19.0       | Committed
| `tracing-opentracing`     | 1.2.1             | OpenTracing 0.33.0         | Committed
| `metrics-opentelemetry`   | 0.4.1             | OpenTelemetry 1.19.0       | Volatile
| `metrics-micrometer`      | 0.4.1             | Micrometer 1.10.0          | Volatile
|=======================


==== Improvements
* https://issues.couchbase.com/browse/JVMCBC-1163[JVMCBC-1163]:
Dependencies have been updated.
* https://issues.couchbase.com/browse/JVMCBC-1156[JVMCBC-1156]:
The traffic tracing functionality has been enchanced to perform Wireshark-style dissection of portions of the KV protocol.
* https://issues.couchbase.com/browse/JCBC-1984[JCBC-1984]:
KV range scan functionality (`collection.scan()`) added at @Stability.Volatile level.
Users are encouraged to experiment with the feature and provide feedback ahead of its formal release in 3.5.0.
* https://issues.couchbase.com/browse/JCBC-2018[JCBC-2018]:
Make Core and CoreEnvironment Autocloseable.
* https://issues.couchbase.com/browse/JCBC-2009[JCBC-2009]:
Fixed an issue where ArraySetOptions was extending CommonDatastructureOptions incorrectly.
* https://issues.couchbase.com/browse/JCBC-2021[JCBC-2021]:
Diagnostics for an endpoint now include the state of the endpoint's circuit breaker.
* https://issues.couchbase.com/browse/JCBC-2027[JCBC-2027]:
The `ClusterEnvironment.Builder` methods that take a `Builder` are deprecated in favor of the overloads that take a `Consumer<Builder>`.
For example, `ioConfig(IoConfig.Builder)` is deprecated in favor of `ioConfig(Consumer<IoConfig.Builder>)`.
The methods that take a `Consumer<Builder>` are preferable because they allow customizing the config without clobbering the previous values.
* https://issues.couchbase.com/browse/JCBC-2028[JCBC-2028]:
`Cluster.connect` now throws an `IllegalArgumentException` if you pass a pre-built `ClusterEnvironment` and a connection string incompatible with the environment.
Before this change, an incompatibility was logged as a warning, and the connection string scheme and parameters were ignored.
`ConnectionStringIgnoredEvent` is now deprecated, since the SDK never publishes it anymore.
** A pre-built environment without TLS enabled is incompatible with a connection string that specifies the secure `couchases` scheme.
** A pre-built environment is incompatible with a connection string that has parameters.
* https://issues.couchbase.com/browse/JVMCBC-1159[JVMCBC-1159]:
Transactions now support upcoming server query_context changes.

==== Bugs
* https://issues.couchbase.com/browse/JVMCBC-1157[JVMCBC-1157]:
The SDK no longer rejects a `PersistTo` requirement in a bucket using the Magma storage engine. Before this change, the SDK would refuse the request because it misidentified Magma buckets as ephemeral (unable to persist documents).
* https://issues.couchbase.com/browse/JVMCBC-1167[JVMCBC-1167]:
If you call `CancellationErrorContext.getWaitUntilReadyContext()` on an error context that didn't come from a "wait until ready" request, the method is now guaranteed to return null instead of sometimes throwing a `ClassCastException`.
* https://issues.couchbase.com/browse/JCBC-2024[JCBC-2024]:
Fixed a memory leak in ManagerMessageHandler.
* https://issues.couchbase.com/browse/JVMCBC-1247[JVMCBC-1247]:
The SDK now throws `InvalidArgumentException: Failed to parse connection string` if the connection string has a syntax error.
For example, the following connection string is malformed, because the `couchbase://` part is repeated:
`couchbase://foo.example.com,couchbase://bar.example.com`.
The correct way to include multiple addresses in a connection string is to specify the scheme only once, and to join addresses with commas, like:
`couchbase://foo.example.com,bar.example.com`

=== Version 3.4.0 (24 October 2022)

Version 3.4.0 is the first release of the 3.4 series.

https://packages.couchbase.com/clients/java/3.4.0/Couchbase-Java-Client-3.4.0.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.4.0/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.4.0/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.4.0**
* com.couchbase.client:**core-io:2.4.0**
* io.projectreactor:**reactor-core:3.4.24**
* org.reactivestreams:**reactive-streams:1.0.4**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Couchbase Version | Built Against              | API Stability
| `tracing-opentelemetry`   | 1.2.0             | OpenTelemetry 1.16.0       | Committed
| `tracing-opentracing`     | 1.2.0             | OpenTracing 0.33.0         | Committed
| `metrics-opentelemetry`   | 0.4.0             | OpenTelemetry 1.16.0       | Volatile
| `metrics-micrometer`      | 0.4.0             | Micrometer 1.9.2           | Volatile
|=======================


==== Improvements
* https://issues.couchbase.com/browse/JVMCBC-1102[JVMCBC-1102]:
Added support for serverless execution environments including AWS Lambda.
* https://issues.couchbase.com/browse/JCBC-2004[JCBC-2004]:
Changed `AuthenticationFailureException` error message to indicate that bucket hibernation is now a potential cause.
Bucket hibernation is a feature coming in a future Couchbase release.
* https://issues.couchbase.com/browse/JCBC-1979[JCBC-1979]:
A transactional `ctx.insert()` now consistently raises a `DocumentAlreadyExistsException` if the document already exists.
If this is caught, the transaction is now allowed to continue.
* https://issues.couchbase.com/browse/JVMCBC-1144[JVMCBC-1144]:
If your Couchbase Server cluster's root certificate is signed by a well-known certificate authority whose certificate is included in the JVM's trust store, it's no longer necessary to configure the certificate in the securityConfig settings.
* https://issues.couchbase.com/browse/JVMCBC-1154[JVMCBC-1154]:
Maintenance dependency bump.

==== Bugs
* https://issues.couchbase.com/browse/JCBC-2002[JCBC-2002]:
`expiryTime` will now return an empty optional if no expiry set.
* https://issues.couchbase.com/browse/JCBC-1987[JCBC-1987]:
Fixed a problem where `QueryIndexManager.buildDeferredIndexes` would throw `InternalServerFailureException` when building indexes on the default collection if there were also deferred indexes in a different collection.
* https://issues.couchbase.com/browse/JVMCBC-1141[JVMCBC-1141]:
Provide required OpenTelemetry span attributes.
* https://issues.couchbase.com/browse/JVMCBC-1155[JVMCBC-1155]:
Make sure targeted round robin request keeps retrying if no config is available.


== Java SDK 3.3 Releases


=== Version 3.3.4 (9 September 2022)

Version 3.3.4 is the fifth release of the 3.3 series, and is a maintenance release.

https://packages.couchbase.com/clients/java/3.3.4/Couchbase-Java-Client-3.3.4.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.3.4/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.3.4/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.3.4**
* com.couchbase.client:**core-io:2.3.4**
* io.projectreactor:**reactor-core:3.4.22**
* org.reactivestreams:**reactive-streams:1.0.4**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Version | Built Against              | API Stability
| `tracing-opentelemetry`   | 1.1.4   | OpenTelemetry 1.16.0       | Committed
| `tracing-opentracing`     | 1.1.4   | OpenTracing 0.33.0         | Committed
| `metrics-opentelemetry`   | 0.3.4   | OpenTelemetry 1.16.0       | Volatile
| `metrics-micrometer`      | 0.3.4   | Micrometer 1.9.2           | Volatile
|=======================


==== Improvements
* https://issues.couchbase.com/browse/JVMCBC-1131[JVMCBC-1131]:
Added ability to track the number of created instances.
Users can now set to hard-fail if too many instances are created.
* https://issues.couchbase.com/browse/JVMCBC-1134[JVMCBC-1134]:
Updated `MemcachedProtocol::decodeStatus` to be inlineable.
* https://issues.couchbase.com/browse/JVMCBC-1135[JVMCBC-1135]:
Moved `Core#reconfiguration` off IO threads.
* https://issues.couchbase.com/browse/JVMCBC-1143[JVMCBC-1143]:
Failed telemetry spans will now record their exception and error status.
* https://issues.couchbase.com/browse/JVMCBC-1145[JVMCBC-1145]:
Updated maintenance dependencies.
* https://issues.couchbase.com/browse/JCBC-1985[JCBC-1985]:
Added optional `Cluster` instance limit.
* https://issues.couchbase.com/browse/JCBC-1975[JCBC-1975]:
Added support for a Couchbase Server 7.1 performance optimisation for transactions that reduces memory requirements in clients.
* https://issues.couchbase.com/browse/JCBC-1989[JCBC-1989]:
Added `Closeable` capability to the `Cluster` class, which enables usage of the `try-with-resources` pattern.
* https://issues.couchbase.com/browse/JVMCBC-1139[JVMCBC-1139]:
Added support for Configuration Profiles.
Note that this API is currently marked as `@Stability.Volatile` and could be subject to change.
* https://issues.couchbase.com/browse/JVMCBC-1126[JVMCBC-1126]:
Updated metrics and tracing dependencies.

==== Bug Fixes
* https://issues.couchbase.com/browse/JVMCBC-1125[JVMCBC-1125]:
Fixed a rare `CompletionException` seen from transactions when a very aggressive cleanup window is configured.
* https://issues.couchbase.com/browse/JVMCBC-1136[JVMCBC-1136]:
Removed verbose transactions cleanup debug "stop on" logging that was being logged at INFO level.
* https://issues.couchbase.com/browse/JCBC-1993[JCBC-1993]:
Fixed issue where a `NullPointerException` was thrown for a non-existent FTS index.
* https://issues.couchbase.com/browse/JCBC-1955[JCBC-1955]:
Fixed a bug where concurrent transactions could hang due to scheduler starvation.


=== Version 3.3.3 (2 August 2022)

Version 3.3.3 is the fourth release of the 3.3 series, and is a maintenance release.

https://packages.couchbase.com/clients/java/3.3.3/Couchbase-Java-Client-3.3.3.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.3.3/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.3.3/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.3.3**
* com.couchbase.client:**core-io:2.3.3**
* io.projectreactor:**reactor-core:3.4.21**
* org.reactivestreams:**reactive-streams:1.0.4**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Version | Built Against              | API Stability
| `tracing-opentelemetry`   | 1.1.2   | OpenTelemetry 1.13.0       | Committed
| `tracing-opentracing`     | 1.1.2   | OpenTracing 0.33.0         | Committed
| `metrics-opentelemetry`   | 0.3.2   | OpenTelemetry 1.13.0-alpha | Volatile
| `metrics-micrometer`      | 0.3.2   | Micrometer 1.8.4           | Volatile
|=======================

==== Improvements
* https://issues.couchbase.com/browse/JVMCBC-1116[JVMCBC-1116]:
Dependency versions have been increased.
* https://issues.couchbase.com/browse/JVMCBC-1121[JVMCBC-1121]:
In some rare cases -- such as an application crash -- a transaction is left for the async cleanup algorithm to finish; 
by default it will find this within one minute.
In cases where this does not happen, this will trigger a warning after two hours -- not the two days that was previously the case.

==== Bug Fixes
* https://issues.couchbase.com/browse/JVMCBC-1110[JVMCBC-1110]:
Transaction clients now reliably remove themselves from client records on shutdown.
* https://issues.couchbase.com/browse/JVMCBC-1119[JVMCBC-1119]:
The num (kv) nodesExt to equal number of nodes check can lead to otherwise healthy clusters being flagged as not ready.
The check has been removed, and now the ` Bucket `waitUntilReady` will not timeout on these edge cases.
* https://issues.couchbase.com/browse/JVMCBC-1120[JVMCBC-1120]:
`ClusterConfig#allNodeAddresses` now takes global config into account -- avoiding the triggering of some unnecessary reconfigurations.
* https://issues.couchbase.com/browse/JVMCBC-1112[JVMCBC-1112]:
Deprecated Reactor Processors have been replaced.
* https://issues.couchbase.com/browse/JVMCBC-1115[JVMCBC-1115]:
The SDK now allows for configurations with _only_ TLS ports.


=== Version 3.3.2 (6 July 2022)

Version 3.3.2 is the third release of the 3.3 series, and is a maintenance release.

https://packages.couchbase.com/clients/java/3.3.2/Couchbase-Java-Client-3.3.2.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.3.2/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.3.2/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.3.2**
* com.couchbase.client:**core-io:2.3.2**
* io.projectreactor:**reactor-core:3.4.17**
* org.reactivestreams:**reactive-streams:1.0.3**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Version | Built Against              | API Stability
| `tracing-opentelemetry`   | 1.1.2   | OpenTelemetry 1.13.0       | Committed
| `tracing-opentracing`     | 1.1.2   | OpenTracing 0.33.0         | Committed
| `metrics-opentelemetry`   | 0.3.2   | OpenTelemetry 1.13.0-alpha | Volatile
| `metrics-micrometer`      | 0.3.2   | Micrometer 1.8.4           | Volatile
|=======================

==== Bug Fixes

* https://issues.couchbase.com/browse/JVMCBC-1103[JVMCBC-1103]:
To reduce overhead, the `MAX_PARALLEL_FETCH` value in `KeyValueBucketRefresher` has been updated to only fetch one config per poll interval.

* https://issues.couchbase.com/browse/JVMCBC-1104[JVMCBC-1104]:
Fixed issue where the global refresher did not honor the config poll interval.


=== Version 3.3.1 (8 June 2022)

Version 3.3.1 is the second release of the 3.3 series, and is a maintenance release.

https://packages.couchbase.com/clients/java/3.3.1/Couchbase-Java-Client-3.3.1.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.3.1/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.3.1/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.3.1**
* com.couchbase.client:**core-io:2.3.1**
* io.projectreactor:**reactor-core:3.4.17**
* org.reactivestreams:**reactive-streams:1.0.3**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Version | Built Against              | API Stability
| `tracing-opentelemetry`   | 1.1.1   | OpenTelemetry 1.13.0       | Committed
| `tracing-opentracing`     | 1.1.1   | OpenTracing 0.33.0         | Committed
| `metrics-opentelemetry`   | 0.3.1   | OpenTelemetry 1.13.0-alpha | Volatile
| `metrics-micrometer`      | 0.3.1   | Micrometer 1.8.4           | Volatile
|=======================

==== Improvements

* https://issues.couchbase.com/browse/JVMCBC-1089[JVMCBC-1089]:
SDK users can now customize the `ConsoleLogger` format.
* https://issues.couchbase.com/browse/JVMCBC-1093[JVMCBC-1093]:
Previously, when a DNS SRV lookup failure occured, the SDK logged this as a `WARNING` along with a stack trace.
The lookup failure is typically harmless, so the log message has now been downgraded to `INFO` level, without a stack trace.
* https://issues.couchbase.com/browse/JVMCBC-1088[JVMCBC-1088]:
Updated Netty to version `4.1.77.Final`.


=== Version 3.3.0 (26 April 2022)

Version 3.3.0 is the first release of the 3.3 series.

The three headline changes in this release:

* Supports the new functionality of Couchbase Server 7.1.
* Directly integrates transactions into the SDK rather than requiring a separate library.  Existing users of the transactions library can refer to the xref:project-docs:distributed-acid-transactions-migration-guide.adoc[Distributed Transactions Migration Guide] to see the simple steps needed to migrate, which we recommend.
* Bundles the public server security certificates for Couchbase Capella, to make it easier for users to get started with Capella.

https://packages.couchbase.com/clients/java/3.3.0/Couchbase-Java-Client-3.3.0.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.3.0/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.3.0/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.3.0**
* com.couchbase.client:**core-io:2.3.0**
* io.projectreactor:**reactor-core:3.4.17**
* org.reactivestreams:**reactive-streams:1.0.3**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Version | Built Against              | API Stability
| `tracing-opentelemetry`   | 1.1.0   | OpenTelemetry 1.13.0       | Committed
| `tracing-opentracing`     | 1.1.0   | OpenTracing 0.33.0         | Committed
| `metrics-opentelemetry`   | 0.3.0   | OpenTelemetry 1.13.0-alpha | Volatile
| `metrics-micrometer`      | 0.3.0   | Micrometer 1.8.4           | Volatile
|=======================

==== Improvements
* https://issues.couchbase.com/browse/JCBC-1929[JCBC-1929]:
Integrated transactions library into SDK.
* https://issues.couchbase.com/browse/JVMCBC-1070[JVMCBC-1070]:
Bundled public Capella CA certificate.
* https://issues.couchbase.com/browse/JVMCBC-1074[JVMCBC-1074]:
If you try to connect to Capella without enabling TLS, now you'll get an exception that says TLS is required (instead of an `UnknownHostException`).
* https://issues.couchbase.com/browse/JVMCBC-1076[JVMCBC-1076]:
Deprecated `Event.createdAt()` in favor of a version that returns an `Instant`.
* https://issues.couchbase.com/browse/JVMCBC-1078[JVMCBC-1078]:
Made `schedulerThreadCount` customizable.
* https://issues.couchbase.com/browse/JVMCBC-1079[JVMCBC-1079]:
Added ConnectionString SDK 3 compatibility attributes.
* https://issues.couchbase.com/browse/JVMCBC-1082[JVMCBC-1082]:
Updated maintenance dependencies.
* https://issues.couchbase.com/browse/JVMCBC-1085[JVMCBC-1085]:
Exposed last connect attempt failure through `Diagnostics`.
* https://issues.couchbase.com/browse/JCBC-1886[JCBC-1886]:
Allow to list the number of currently available replicas for a document ID.
* https://issues.couchbase.com/browse/JCBC-1923[JCBC-1923]:
Added warning when ignoring connection string parameters or scheme.

==== Bugs
* https://issues.couchbase.com/browse/JCBC-1922[JCBC-1922]:
`NOT_STORED` when inserting a document will now correctly raise a `DocumentAlreadyExistsException` (rather than a `DocumentNotFoundException` as before).
* https://issues.couchbase.com/browse/JVMCBC-1077[JVMCBC-1077]:
Shutting down a ClusterEnvironment now correctly stops a `Meter` owned by the cluster. This plugs a resource leak where `LoggingMeter` worker threads would never be stopped.


== Java SDK 3.2 Releases

=== Version 3.2.7 (25 April 2022)

Version 3.2.7 is the eighth release of the 3.2 series.

https://packages.couchbase.com/clients/java/3.2.7/Couchbase-Java-Client-3.2.7.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.2.7/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.2.7/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.2.7**
* com.couchbase.client:**core-io:2.2.7**
* io.projectreactor:**reactor-core:3.4.17**
* org.reactivestreams:**reactive-streams:1.0.3**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Version | Built Against             | API Stability
| `tracing-opentelemetry`   | 1.0.7   | OpenTelemetry 1.9.1       | Committed
| `tracing-opentracing`     | 1.0.7   | OpenTracing 0.33.0        | Committed
| `metrics-opentelemetry`   | 0.2.7   | OpenTelemetry 1.7.1-alpha | Volatile
| `metrics-micrometer`      | 0.2.7   | Micrometer 1.7.5          | Volatile
|=======================

==== Bugs
* https://issues.couchbase.com/browse/JCBC-1922[JCBC-1922]:
The KeyValue error code `NOT_STORED` is now properly mapped to `DocumentExistsException` on `insert` and `mutateIn`.
* https://issues.couchbase.com/browse/JVMCBC-1077[JVMCBC-1077]:
The environment now properly shuts down the `Meter` if it is owned and not passed in externally.

==== Improvements
* https://issues.couchbase.com/browse/JVMCBC-1082[JVMCBC-1082]:
Updated internal and external dependencies.
 * Netty from 4.1.73 to 4.1.76
 * Jackson from 2.13.1 to 2.13.2 (and 2.13.2.2)
 * Reactor from 3.4.14 to 3.4.17 

=== Version 3.2.6 (2 March 2022)

Version 3.2.6 is the seventh release of the 3.2 series.

https://packages.couchbase.com/clients/java/3.2.6/Couchbase-Java-Client-3.2.6.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.2.6/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.2.6/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.2.6**
* com.couchbase.client:**core-io:2.2.6**
* io.projectreactor:**reactor-core:3.4.14**
* org.reactivestreams:**reactive-streams:1.0.3**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Version | Built Against             | API Stability
| `tracing-opentelemetry`   | 1.0.6   | OpenTelemetry 1.9.1       | Committed
| `tracing-opentracing`     | 1.0.6   | OpenTracing 0.33.0        | Committed
| `metrics-opentelemetry`   | 0.2.6   | OpenTelemetry 1.7.1-alpha | Volatile
| `metrics-micrometer`      | 0.2.6   | Micrometer 1.7.5          | Volatile
|=======================

==== Bugs
* https://issues.couchbase.com/browse/JVMCBC-1060[JVMCBC-1060]:
Fixed an issue where rate limited exceptions were not thrown for `SearchIndexManager` errors.
* https://issues.couchbase.com/browse/JVMCBC-1071[JVMCBC-1071]:
The SDK now ensures that negative values are not sent to the `ValueRecorder`.
* https://issues.couchbase.com/browse/JCBC-1918[JCBC-1918]:
Executing a Full-Text Search query with an open-ended date range facet no longer results in a `NullPointerException`.
* https://issues.couchbase.com/browse/JCBC-1919[JCBC-1919]:
Index fields are now quoted in the analytics index manager.
* https://issues.couchbase.com/browse/JCBC-1921[JCBC-1921]:
QueryIndexManager `buildDeferredIndexes` no longer throws a `ParsingFailureException` against Couchbase Server 6.0.

==== New Features
* https://issues.couchbase.com/browse/JVMCBC-1057[JVMCBC-1057]:
Added core infrastructure for the Backup service. 
Users can now make custom HTTP requests to the Backup service.
* https://issues.couchbase.com/browse/JVMCBC-1064[JVMCBC-1064]:
When implementing a custom `RetryStrategy`, a new overload of `RetryAction.noRetry` lets you specify an exception translator for converting the default request cancellation exception into your preferred exception class.

==== Improvements
* https://issues.couchbase.com/browse/JVMCBC-1065[JVMCBC-1065]:
`RetryReason.allowsNonIdempotentRetry()` is now public, so you can call it from a custom `RetryStrategy`.
* https://issues.couchbase.com/browse/JVMCBC-1066[JVMCBC-1066]:
When `SecurityConfig.Builder.trustCertificate(Path)` is given a file containing more than one certificate, it now trusts all the certificates instead of just the first one.
Likewise, the result of `SecurityConfig.decodeCertificates(List<String>)` now includes all certificates in each string, not just the first certificate in each string.
* https://issues.couchbase.com/browse/JVMCBC-1068[JVMCBC-1068]:
Added explicit handling of `FeatureNotAvailable` for Magma on CE.
* https://issues.couchbase.com/browse/JVMCBC-1069[JVMCBC-1069]:
Added explicit handling of `FeatureNotAvailable` for Query CE.
* https://issues.couchbase.com/browse/JCBC-1916[JCBC-1916]:
Updated the Analytics Management API Javadocs.
* https://issues.couchbase.com/browse/JCBC-1917[JCBC-1917]:
You can now configure properties of the `ClusterEnvironment` without having to build and shut down the environment.
The new `ClusterOptions.environment(Consumer<ClusterEnvironment.Builder>)` method lets you configure properties of a `ClusterEnvironment` owned by the Cluster, so you don't need to manage the environment yourself.
Example usage:
[source,java]
----
Cluster cluster = Cluster.connect("localhost", clusterOptions(username, password)
    .environment(env -> env.ioConfig().captureTraffic(ServiceType.MANAGER)));
----

=== Version 3.2.5 (2 February 2022)

Version 3.2.5 is the sixth release of the 3.2 series.

https://packages.couchbase.com/clients/java/3.2.5/Couchbase-Java-Client-3.2.5.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.2.5/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.2.5/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.2.5**
* com.couchbase.client:**core-io:2.2.5**
* io.projectreactor:**reactor-core:3.4.14**
* org.reactivestreams:**reactive-streams:1.0.3**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Version | Built Against             | API Stability
| `tracing-opentelemetry`   | 1.0.5   | OpenTelemetry 1.9.1       | Committed
| `tracing-opentracing`     | 1.0.5   | OpenTracing 0.33.0        | Committed
| `metrics-opentelemetry`   | 0.2.5   | OpenTelemetry 1.7.1-alpha | Volatile
| `metrics-micrometer`      | 0.2.5   | Micrometer 1.7.5          | Volatile
|=======================

==== API Impacting
* https://issues.couchbase.com/browse/JCBC-1901[JCBC-1901]:
Removed the Azure link type from the analytics management API, due to a change in the underlying server API.
(Note that this interface is marked @Stability.Volatile indicating that it can change.)

==== Bugs
* https://issues.couchbase.com/browse/JCBC-1895[JCBC-1895]:
Fixed an issue where `lookupInResult.contentAs(0, Boolean.class)` was throwing a `DecodingFailureException` on a Sub-Document exists operation.
* https://issues.couchbase.com/browse/JCBC-1896[JCBC-1896]:
Fixed an issue where `JsonValueSerializerWrapper` was unable to support decoding via TypeRef.
* https://issues.couchbase.com/browse/JCBC-1904[JCBC-1904]:
Fixed issues with constant and URL bindings and also introduced convenience methods to load a function from raw JSON.
* https://issues.couchbase.com/browse/JVMCBC-1046[JVMCBC-1046]:
Added fix to not load the global config if a node is not in the seed node list anymore.
* https://issues.couchbase.com/browse/JVMCBC-1058[JVMCBC-1058]:
The SDK now throws a more descriptive `FeatureNotAvailableException` for scopes and collections on memcached buckets.

==== Improvements
* https://issues.couchbase.com/browse/JCBC-1860[JCBC-1860]:
`ConflictResolutionType.CUSTOM` has now been added to the bucket management API.
* https://issues.couchbase.com/browse/JCBC-1864[JCBC-1864]:
FTS options now include `IncludeLocations` and `Operator`.
* https://issues.couchbase.com/browse/JCBC-1876[JCBC-1876]:
Query API now supports preserving TTL.
* https://issues.couchbase.com/browse/JCBC-1882[JCBC-1882]:
Index management API now supports managing indexes for a collection.
* https://issues.couchbase.com/browse/JCBC-1898[JCBC-1898]:
Added convenience method for getting raw bytes from `GetResult`.
* https://issues.couchbase.com/browse/JCBC-1902[JCBC-1902]:
The SDK now sends the configured user timeout to search.
* https://issues.couchbase.com/browse/JCBC-1905[JCBC-1905]:
Added convenience methods for loading eventing function JSON.
* https://issues.couchbase.com/browse/JCBC-1909[JCBC-1909]:
Added `scanWait` to `AnalyticsOptions`.
* https://issues.couchbase.com/browse/JCBC-1903[JCBC-1903]:
Added javadocs for bucket management API.
* https://issues.couchbase.com/browse/JCBC-1908[JCBC-1908]:
Added javadocs for query index management APIs.
* https://issues.couchbase.com/browse/JVMCBC-1055[JVMCBC-1055],
https://issues.couchbase.com/browse/JVMCBC-1047[JVMCBC-1047],
https://issues.couchbase.com/browse/JVMCBC-1051[JVMCBC-1051]:
Updated dependencies.
Netty goes from 4.1.72.Final to 4.1.73.Final.
Jackson from 2.13.0 to 2.13.1.
Reactor from 3.4.12 to 3.4.14.
log4j (an optional dependency) from 2.15.0 to 2.17.1.
* https://issues.couchbase.com/browse/JVMCBC-1037[JVMCBC-1037]:
Added a minor performance optimisation that avoids `whenComplete` closure for timeout cancellation.
* https://issues.couchbase.com/browse/JVMCBC-1045[JVMCBC-1045]:
Added an internal watchdog that updates the cluster configuration if the number of nodes changes.
* https://issues.couchbase.com/browse/JVMCBC-1048[JVMCBC-1048]:
Added change that ensures the SDK always sets `RequestContext` on `RequestSpan`.
* https://issues.couchbase.com/browse/JVMCBC-1056[JVMCBC-1056]:
Added more log information on unexpected endpoint disconnect.
* https://issues.couchbase.com/browse/JVMCBC-1059[JVMCBC-1059]:
The SDK now handles any `retry:true` field in a query error result by retrying it.


=== Version 3.2.4 (9 December 2021)

Version 3.2.4 is the fifth release of the 3.2 series.

https://packages.couchbase.com/clients/java/3.2.4/Couchbase-Java-Client-3.2.4.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.2.4/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.2.4/[Core API Reference]

NOTE: This release introduces support for JDK 17.

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.2.4**
* com.couchbase.client:**core-io:2.2.4**
* io.projectreactor:**reactor-core:3.4.12**
* org.reactivestreams:**reactive-streams:1.0.3**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Version | Built Against             | API Stability
| `tracing-opentelemetry`   | 1.0.4   | OpenTelemetry 1.7.1       | Committed
| `tracing-opentracing`     | 1.0.4   | OpenTracing 0.33.0        | Committed
| `metrics-opentelemetry`   | 0.2.4   | OpenTelemetry 1.7.1-alpha | Volatile
| `metrics-micrometer`      | 0.2.4   | Micrometer 1.7.5          | Volatile
|=======================

==== Bugs
* https://issues.couchbase.com/browse/JCBC-1892[JCBC-1892]:
`EventingFunctionSettings` can now be empty - this fixes an issue with loading eventing functions from the cluster.

==== Improvements
* https://issues.couchbase.com/browse/JVMCBC-1033[JVMCBC-1033], https://issues.couchbase.com/browse/JVMCBC-1034[JVMCBC-1034]:
Updated internal and external dependencies to their latest bugfix versions. 
This also updates OpenTelemetry to 1.7.x.
* https://issues.couchbase.com/browse/JCBC-1881[JCBC-1881]:
Added (volatile) support for the `magma` storage backend when creating a bucket through the bucket manager.
* https://issues.couchbase.com/browse/JVMCBC-1035[JVMCBC-1035]:
The (internal) `subDocumentField` is now serializable - this is needed for apache spark integration.
* https://issues.couchbase.com/browse/JVMCBC-1032[JVMCBC-1032]:
Added (volatile) support for Rate/Quota Limits. 
This is needed for Couchbase Capella.
* https://issues.couchbase.com/browse/JVMCBC-1039[JVMCBC-1039]:
Included `httpStatus` in Query and Analytics Error Context, as well as the `vbucket` in the KV error context. 
This helps with debugging.


=== Version 3.2.3 (2 November 2021)

Version 3.2.3 is the fourth release of the 3.2 series.

https://packages.couchbase.com/clients/java/3.2.3/Couchbase-Java-Client-3.2.3.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.2.3/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.2.3/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.2.3**
* com.couchbase.client:**core-io:2.2.3**
* io.projectreactor:**reactor-core:3.4.9**
* org.reactivestreams:**reactive-streams:1.0.3**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Version | Built Against             | API Stability
| `tracing-opentelemetry`   | 1.0.3   | OpenTelemetry 1.3.0       | Committed
| `tracing-opentracing`     | 1.0.3   | OpenTracing 0.33.0        | Committed
| `metrics-opentelemetry`   | 0.2.3   | OpenTelemetry 1.3.0-alpha | Volatile
| `metrics-micrometer`      | 0.2.3   | Micrometer 1.7.0          | Volatile
|=======================

==== Improvements
* https://issues.couchbase.com/browse/JVMCBC-1026[JVMCBC-1026]:
Support for error map v2 has been added to ensure the config can be parsed without failure.

=== Version 3.2.2 (6 October 2021)

Version 3.2.2 is the third release of the 3.2 series.

https://packages.couchbase.com/clients/java/3.2.2/Couchbase-Java-Client-3.2.2.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.2.2/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.2.2/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.2.2**
* com.couchbase.client:**core-io:2.2.2**
* io.projectreactor:**reactor-core:3.4.9**
* org.reactivestreams:**reactive-streams:1.0.3**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Version | Built Against             | API Stability
| `tracing-opentelemetry`   | 1.0.2   | OpenTelemetry 1.3.0       | Committed
| `tracing-opentracing`     | 1.0.2   | OpenTracing 0.33.0        | Committed
| `metrics-opentelemetry`   | 0.2.2   | OpenTelemetry 1.3.0-alpha | Volatile
| `metrics-micrometer`      | 0.2.2   | Micrometer 1.7.0          | Volatile
|=======================

==== Improvements
* https://issues.couchbase.com/browse/JCBC-1872[JCBC-1872]:
Bring `NodeLocatorHelper` to SDK 3 from 2.
* https://issues.couchbase.com/browse/JCBC-1875[JCBC-1875]:
Document and polish Eventing Management API.
* https://issues.couchbase.com/browse/JVMCBC-1015[JVMCBC-1015]:
Improve client side error message when TLS is enforced on the server side.
* https://issues.couchbase.com/browse/JVMCBC-1016[JVMCBC-1016]:
Gracefully handle more invalid connection string cases.
* https://issues.couchbase.com/browse/JVMCBC-1022[JVMCBC-1022]:
Batch-Log messages in DefaultEventBus. 
Now events which are overflowing are not directly logged to stderr but rather batched up and logged at interval.
Note that this implies some "loss of precision", as not all dropped events are logged - one event per type is preserved.

==== Bugs
* https://issues.couchbase.com/browse/JVMCBC-1017[JVMCBC-1017]:
Fixed issue with Threshold Logging Tracing not working due to `RequestContext` not being set.
* https://issues.couchbase.com/browse/JCBC-1873[JCBC-1873]:
Rename EventingFunction to `validate_ssl_certificates` to conform to spec.
* https://issues.couchbase.com/browse/JVMCBC-1020[JVMCBC-1020]:
Added `target` property to `QueryRequest` and ensured it is honored for prepare and execute, so they are both run on the same node. 
This fix removes need for `TargetedQueryRequest`.


=== Version 3.2.1 (1 September 2021)

Version 3.2.1 is the second release of the 3.2 series.

https://packages.couchbase.com/clients/java/3.2.1/Couchbase-Java-Client-3.2.1.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.2.1/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.2.1/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.2.1**
* com.couchbase.client:**core-io:2.2.1**
* io.projectreactor:**reactor-core:3.4.9**
* org.reactivestreams:**reactive-streams:1.0.3**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Version | Built Against             | API Stability
| `tracing-opentelemetry`   | 1.0.1   | OpenTelemetry 1.3.0       | Committed
| `tracing-opentracing`     | 1.0.1   | OpenTracing 0.33.0        | Committed
| `metrics-opentelemetry`   | 0.2.1   | OpenTelemetry 1.3.0-alpha | Volatile
| `metrics-micrometer`      | 0.2.1   | Micrometer 1.7.0          | Volatile
|=======================

==== Known Issues
* https://issues.couchbase.com/browse/JVMCBC-1017[JVMCBC-1017]:
The `ThresholdLoggingTracer` will not record any request and will not log them into the log file. 
If you rely on this functionality please use 3.1.7 as only 3.2.0 and 3.2.1 are affected. 
This issue will be addressed in 3.2.2.

==== Bug Fixes
* https://issues.couchbase.com/browse/JVMCBC-1002[JVMCBC-1002]:
Default log level reverted to INFO.
* https://issues.couchbase.com/browse/JVMCBC-1007[JVMCBC-1007]:
`LoggingMeter` was incorrectly marked as Volatile in SDK 3.2 -- now fixed.
* https://issues.couchbase.com/browse/JCBC-1850[JCBC-1850]:
Fixed `NullPointerException` with `OpenTracing`.

==== Improvements
* https://issues.couchbase.com/browse/JCBC-1732[JCBC-1732]:
Eventing Management API added.
* https://issues.couchbase.com/browse/JCBC-1852[JCBC-1852]:
FLE: Optionally read @Encrypted POJO properties from unencrypted JSON fields.
* https://issues.couchbase.com/browse/JCBC-1858[JCBC-1858]:
Added convenience method for getting raw JSON bytes from `LookupInResult`.
* https://issues.couchbase.com/browse/JCBC-1859[JCBC-1859]:
Allow to create `CollectionSpec` for default scope.
* https://issues.couchbase.com/browse/JCBC-1868[JCBC-1868]:
Make `JsonValueModule` compatible with Jackson < 2.8.
* https://issues.couchbase.com/browse/JVMCBC-1010[JVMCBC-1010]:
Maintenance dependency bump.
* https://issues.couchbase.com/browse/JVMCBC-990[JVMCBC-990]:
Fixed `WaitUntilReady` timing out with 6.0.x and unhealthy seed nodes.
* https://issues.couchbase.com/browse/JVMCBC-999[JVMCBC-999]:
Properly map server query timeout while streaming.
* https://issues.couchbase.com/browse/JVMCBC-1004[JVMCBC-1004]:
Configure and apply default log level for `ConsoleLogger`.
* https://issues.couchbase.com/browse/JVMCBC-1005[JVMCBC-1005]:
Allow to export Context as Map.
* https://issues.couchbase.com/browse/JVMCBC-1006[JVMCBC-1006]:
`ErrorContext` must be included in message.


=== Version 3.2.0 (20 July 2021)

Version 3.2.0 is the first release of the 3.2 series.
It promotes to GA support for the scopes and collections provided by Couchbase Server 7.0, and also OpenTelemetry.

https://packages.couchbase.com/clients/java/3.2.0/Couchbase-Java-Client-3.2.0.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.2.0/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.2.0/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.2.0**
* com.couchbase.client:**core-io:2.2.0**
* io.projectreactor:**reactor-core:3.4.6**
* org.reactivestreams:**reactive-streams:1.0.3**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Version | Built Against             | API Stability
| `tracing-opentelemetry`   | 1.0.0   | OpenTelemetry 1.3.0       | Committed
| `tracing-opentracing`     | 1.0.0   | OpenTracing 0.33.0        | Committed
| `metrics-opentelemetry`   | 0.2.0   | OpenTelemetry 1.3.0-alpha | Volatile
| `metrics-micrometer`      | 0.2.0   | Micrometer 1.7.0          | Volatile
|=======================

==== Known Issues
* https://issues.couchbase.com/browse/JVMCBC-1017[JVMCBC-1017]:
The `ThresholdLoggingTracer` will not record any request and will not log them into the log file. 
If you rely on this functionality please use 3.1.7 as only 3.2.0 and 3.2.1 are affected. 
This issue will be addressed in 3.2.2.

==== Bug Fixes
* https://issues.couchbase.com/browse/JVMCBC-949[JVMCBC-949]:
Opening a non-default collection on an memcached bucket now fails fast.
* https://issues.couchbase.com/browse/JVMCBC-983[JVMCBC-983]:
Ignore slow subscribers on certain Flux intervals.
* https://issues.couchbase.com/browse/JCBC-1822[JCBC-1822]:
`BatchHelper` now supports MDS deployments.

==== Interface Changes
All interface changes are to interfaces that are currently in beta and marked `@Stability.Volatile` or `@Stability.Uncommitted`.

* https://issues.couchbase.com/browse/JVMCBC-978[JVMCBC-978]:
Rename `AggregatingMeter` to `LoggingMeter`.
* https://issues.couchbase.com/browse/JVMCBC-934[JVMCBC-934]:
Threshold and Orphan output is now in new format.
* https://issues.couchbase.com/browse/JVMCBC-979[JVMCBC-979]:
Rename `ThresholdRequestTracer` to `ThresholdLoggingTracer`.
* https://issues.couchbase.com/browse/JCBC-1823[JCBC-1823]:
Promote collection APIs from Volatile to Committed.
* https://issues.couchbase.com/browse/JCBC-1844[JCBC-1844]:
Promote `BatchHelper` from Volatile to Uncommitted.

==== Improvement
* https://issues.couchbase.com/browse/JVMCBC-980[JVMCBC-980]:
Add exception wrappers to Tracers and Meters.
* https://issues.couchbase.com/browse/JVMCBC-987[JVMCBC-987]:
Allow supplying an SDK2-compatible memcached hashing strategy.
* https://issues.couchbase.com/browse/JVMCBC-988[JVMCBC-988]:
Map Query Error 13014 to `AuthenticationException`.
* https://issues.couchbase.com/browse/JVMCBC-989[JVMCBC-989]:
Add timeout_ms to threshold logging tracer output.
* https://issues.couchbase.com/browse/JVMCBC-991[JVMCBC-991]:
Optimize metric dispatching.
* https://issues.couchbase.com/browse/JVMCBC-992[JVMCBC-992]:
Cache NodeIdentifier in NodeInfo.
* https://issues.couchbase.com/browse/JVMCBC-993[JVMCBC-993]:
Optimize early discard of events which are not going to be logged.
* https://issues.couchbase.com/browse/JVMCBC-996[JVMCBC-996]:
Throw `FeatureNotAvailableException` if scope level queries are not available.
* https://issues.couchbase.com/browse/JVMCBC-997[JVMCBC-997]:
Duplicate attributes from dispatch_to_server to improve tracing.
* https://issues.couchbase.com/browse/JVMCBC-998[JVMCBC-998]:
Performance: Do not set tracing spans if not needed.
* https://issues.couchbase.com/browse/JVMCBC-981[JVMCBC-981]:
Support CoreHttpClient requests to manager service.
* https://issues.couchbase.com/browse/JVMCBC-984[JVMCBC-984]:
Dependency bump: Netty 4.1.63 to 4.1.65, micrometer 1.6.6 to 1.7.0.
* https://issues.couchbase.com/browse/JCBC-1242[JCBC-1242],
https://issues.couchbase.com/browse/JCBC-1837[JCBC-1837]:
Add OSGi bundle.
* https://issues.couchbase.com/browse/JCBC-1787[JCBC-1787]:
Validate expiry instants.
* https://issues.couchbase.com/browse/JCBC-1838[JCBC-1838]:
Add support for SDK2-compatible `LegacyTranscoder`.
* https://issues.couchbase.com/browse/JCBC-1841[JCBC-1841]:
Update OpenTelemetry to 1.3.0.


== Java SDK 3.1 Releases


=== Version 3.1.8 (1 March 2022)

Version 3.1.8 is the ninth release of the 3.1 series, bringing stabilizations over 3.1.7.

https://packages.couchbase.com/clients/java/3.1.8/Couchbase-Java-Client-3.1.8.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.1.8/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.1.8/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.1.8**
* com.couchbase.client:**core-io:2.1.8**
* io.projectreactor:**reactor-core:3.4.15**
* org.reactivestreams:**reactive-streams:1.0.3**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Version | Built Against             | API Stability
| `tracing-opentelemetry`   | 0.3.8   | OpenTelemetry 1.2.0       | Volatile
| `tracing-opentracing`     | 0.3.8   | OpenTracing 0.33.0        | Volatile
| `metrics-opentelemetry`   | 0.1.8   | OpenTelemetry 1.2.0-alpha | Volatile
| `metrics-micrometer`      | 0.1.8   | Micrometer 1.6.6          | Volatile
|=======================

==== Bug Fixes

* https://issues.couchbase.com/browse/JVMCBC-1067[JVMCBC-1067]:
Internal and external maintenance dependencies are updated to their latest available bugfix releases (including Netty to 4.1.74.Final).
* https://issues.couchbase.com/browse/JVMCBC-1046[JVMCBC-1046]:
Added fix to not load the global config if a node is not in the seed node list anymore.
* https://issues.couchbase.com/browse/JVMCBC-1006[JVMCBC-1006]:
`ErrorContext` is now included in the message of a `CouchbaseException`.
* https://issues.couchbase.com/browse/JVMCBC-1895[JCBC-1895]:
Fixed an issue where `lookupInResult.contentAs(0, Boolean.class)` was throwing a `DecodingFailureException` on a Sub-Document exists operation.
* https://issues.couchbase.com/browse/JVMCBC-1896[JCBC-1896]:
Fixed an issue where `JsonValueSerializerWrapper` was unable to support decoding via TypeRef.

=== Version 3.1.7 (11 August 2021)

Version 3.1.7 is the eigth release of the 3.1 series, bringing stabilizations and enhancements over 3.1.6.

https://packages.couchbase.com/clients/java/3.1.7/Couchbase-Java-Client-3.1.7.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.1.7/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.1.7/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.1.7**
* com.couchbase.client:**core-io:2.1.7**
* io.projectreactor:**reactor-core:3.4.6**
* org.reactivestreams:**reactive-streams:1.0.3**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Version | Built Against             | API Stability
| `tracing-opentelemetry`   | 0.3.7   | OpenTelemetry 1.2.0       | Volatile
| `tracing-opentracing`     | 0.3.7   | OpenTracing 0.33.0        | Volatile
| `metrics-opentelemetry`   | 0.1.7   | OpenTelemetry 1.2.0-alpha | Volatile
| `metrics-micrometer`      | 0.1.7   | Micrometer 1.6.6          | Volatile
|=======================

==== Bug Fixes

* https://issues.couchbase.com/browse/JVMCBC-949[JVMCBC-949]:
Opening a non-default collection on an memcached bucket now fails fast.
* https://issues.couchbase.com/browse/JVMCBC-983[JVMCBC-983]:
Ignore slow subscribers on certain Flux intervals.
* https://issues.couchbase.com/browse/JCBC-1822[JCBC-1822]:
`BatchHelper` now supports MDS deployments.
* https://issues.couchbase.com/browse/JCBC-1850[JCBC-1850]:
Ignore null values for attributed in OpenTelemetry and OpenTracing.
* https://issues.couchbase.com/browse/JVMCBC-990[JVMCBC-990]:
Gracefully handle cluster-level WaitUntilReady against clusters < 6.5.

==== Improvements

* https://issues.couchbase.com/browse/JVMCBC-996[JVMCBC-996]:
Throw `FeatureNotAvailableException` if scope level queries are not available.
* https://issues.couchbase.com/browse/JVMCBC-988[JVMCBC-988]:
Query error code 13014 is now mapped to `AuthenticationException`.
* https://issues.couchbase.com/browse/JCBC-1838[JCBC-1838]:
Add support for SDK2-compatible `LegacyTranscoder`.
* https://issues.couchbase.com/browse/JVMCBC-987[JVMCBC-987]:
Allow supplying an SDK2-compatible memcached hashing strategy.
* https://issues.couchbase.com/browse/JVMCBC-999[JVMCBC-999]:
Properly map server query timeout while streaming.

=== Version 3.1.6 (4 June 2021)

Version 3.1.6 is the seventh release of the 3.1 series, bringing stabilizations and enhancements over 3.1.5.

https://packages.couchbase.com/clients/java/3.1.6/Couchbase-Java-Client-3.1.6.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.1.6/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.1.6/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.1.6**
* com.couchbase.client:**core-io:2.1.6**
* io.projectreactor:**reactor-core:3.4.6**
* org.reactivestreams:**reactive-streams:1.0.3**

==== Bug Fixes
* https://issues.couchbase.com/browse/JCBC-1676[JCBC-1676]:
Bucket creation now succeeds against Community Edition 6.5 and above.
* https://issues.couchbase.com/browse/JVMCBC-972[JVMCBC-972]:
Only open one GCCCP connection per node.

==== Improvements
* https://issues.couchbase.com/browse/JCBC-1808[JCBC-1808]:
Updated tracing and metrics module dependencies.
* https://issues.couchbase.com/browse/JCBC-1649[JCBC-1649]:
Update analytics management API to support compound dataverse names.
* https://issues.couchbase.com/browse/JCBC-1815[JCBC-1815]:
Improve error context for BatchHelper.
* https://issues.couchbase.com/browse/JVMCBC-939[JVMCBC-939]:
Improve no collection access handling.
* https://issues.couchbase.com/browse/JVMCBC-974[JVMCBC-974]:
Restructure AggregatingMeter output format.
* https://issues.couchbase.com/browse/JVMCBC-975[JVMCBC-975]:
Further improve wait until ready diagnostics.
* https://issues.couchbase.com/browse/JVMCBC-977[JVMCBC-977]:
Improve bucket configuration handling (revEpoch).

=== Version 3.1.5 (6 May 2021)

Version 3.1.5 is the sixth release of the 3.1 series, bringing stabilizations and enhancements over 3.1.4.

https://packages.couchbase.com/clients/java/3.1.5/Couchbase-Java-Client-3.1.5.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.1.5/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.1.5/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.1.5**
* com.couchbase.client:**core-io:2.1.5**
* io.projectreactor:**reactor-core:3.4.5**
* org.reactivestreams:**reactive-streams:1.0.3**

==== Bug Fixes

* https://issues.couchbase.com/browse/JCBC-1804[JCBC-1804]:
Ensure `contentAsObject/Array()` works with a custom JsonSerializer.
* https://issues.couchbase.com/browse/JVMCBC-965[JVMCBC-965]:
Better error logging during bucket failures, which helps with troubleshooting.
* https://issues.couchbase.com/browse/JVMCBC-963[JVMCBC-963]:
Add better retry handling for local and global bucket config fetch failures, making it more resilient.
* https://issues.couchbase.com/browse/JVMCBC-967[JVMCBC-967]:
Work around and fix a `OverflowException` with `PersistTo`/`ReplicateTo`, caused by Reactor.

==== Improvements

* https://issues.couchbase.com/browse/JVMCBC-958[JVMCBC-958]:
Improve the performance of individual collection ID fetches, speeding up the time of bootstrap whan a lot of collections are opened.
* https://issues.couchbase.com/browse/JCBC-1756[JCBC-1756]:
Adds volatile support for preserving the expiry on certain mutation operations.
* https://issues.couchbase.com/browse/JVMCBC-959[JVMCBC-959]:
Allow `IoEnvironment` config to be overridden by system properties.
* https://issues.couchbase.com/browse/JCBC-1801[JCBC-1801]:
Allow to create a `SearchIndex` from a JSON definition.
* https://issues.couchbase.com/browse/JVMCBC-962[JVMCBC-962]:
Add (internal, volatile) request callback functionality.
* https://issues.couchbase.com/browse/JCBC-1733[JCBC-1733]:
Add support for collections to `SearchOptions`.

=== Version 3.1.4 (7 April 2021)

Version 3.1.4 is the fifth release of the 3.1 series, bringing stabilizations and enhancements over 3.1.3.

https://packages.couchbase.com/clients/java/3.1.4/Couchbase-Java-Client-3.1.4.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.1.4/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.1.4/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.1.4**
* com.couchbase.client:**core-io:2.1.4**
* io.projectreactor:**reactor-core:3.4.4**
* org.reactivestreams:**reactive-streams:1.0.3**

WARNING: Due to protocol level changes, Java SDK 3.1.4 and later are not compatible with _pre-release_ versions of Couchbase Server 7.0.

==== Bug Fixes

* https://issues.couchbase.com/browse/JCBC-1798[JCBC-1798]:
Fixes ViewResult.metaData() throwing Exception when debug=true.
* https://issues.couchbase.com/browse/JVMCBC-940[JVMCBC-940]:
Better error handling of collection ID fetch failures.
* https://issues.couchbase.com/browse/JVMCBC-948[JVMCBC-948]:
CAS is only usable with Sub-Document when using StoreSemantics.REPLACE.
This server-side restriction is now also checked client-side, and a `InvalidArgumentException` raised.
* https://issues.couchbase.com/browse/JVMCBC-950[JVMCBC-950]:
waitUntilReady is now more resilient to just-created buckets.
* https://issues.couchbase.com/browse/JVMCBC-954[JVMCBC-954]:
More resilient handling of rebalances.

==== Improvements

* https://issues.couchbase.com/browse/JCBC-1786[JCBC-1786]:
Transcoders now allow contentAs(Object.class).
Java Map and List collections are used to represent JSON objects and arrays.
* https://issues.couchbase.com/browse/JCBC-1795[JCBC-1795]:
Allow `MutateInSpec.remove("")`, which removes the entire document.
* https://issues.couchbase.com/browse/JVMCBC-936[JVMCBC-936]:
Allow customizing TLS cipher list.
* https://issues.couchbase.com/browse/JVMCBC-941[JVMCBC-941]:
Support modified protocol for collections in Couchbase Server 7.0 (in beta).
* https://issues.couchbase.com/browse/JVMCBC-943[JVMCBC-943]:
Apply OpenTelemetry best practices.
* https://issues.couchbase.com/browse/JVMCBC-944[JVMCBC-944]:
Add implementation version to OpenTelemetry APIs.
* https://issues.couchbase.com/browse/JVMCBC-947[JVMCBC-947]:
Remove request counter metric.
* https://issues.couchbase.com/browse/JVMCBC-951[JVMCBC-951]:
Move GetAny/AllReplicas into core.
* https://issues.couchbase.com/browse/JVMCBC-955[JVMCBC-955]:
Distinguish between CAS mismatch and DML failure on query error.


=== Version 3.1.3 (2 March 2021)

Version 3.1.3 is the fourth release of the 3.1 series, bringing stabilizations and enhancements over 3.1.2.

https://packages.couchbase.com/clients/java/3.1.3/Couchbase-Java-Client-3.1.3.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.1.3/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.1.3/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.1.3**
* com.couchbase.client:**core-io:2.1.3**
* io.projectreactor:**reactor-core:3.4.3**
* org.reactivestreams:**reactive-streams:1.0.3**

==== Improvements

* https://issues.couchbase.com/browse/JCBC-1776[JCBC-1776],
https://issues.couchbase.com/browse/JVMCBC-924[JVMCBC-924],
https://issues.couchbase.com/browse/JVMCBC-925[JVMCBC-925]:
Updated dependencies: OpenTelemetry to 1.0.0, Netty dependency to 4.1.59, netty-tcnative-boringssl-static to 2.0.36, Reactor to 2.4.3, Jackson to 2.12.1.
* https://issues.couchbase.com/browse/JCBC-1774[JCBC-1774]:
Added pre-flight sanity check before using a JacksonJsonSerializer found on the classpath.
* https://issues.couchbase.com/browse/JVMCBC-919[JVMCBC-919]:
Support for Project Reactor BlockHound integration.
* https://issues.couchbase.com/browse/JVMCBC-926[JVMCBC-926]:
Performance: Replace new byte[] full copies with ByteBufUtil.getBytes.
* https://issues.couchbase.com/browse/JVMCBC-927[JVMCBC-927]:
Performance: Improve performance of metrics hot code path.

==== Bugs

* https://issues.couchbase.com/browse/JVMCBC-930[JVMCBC-930]:
Threshold and Orphan Reporting now report the correct time units.
* https://issues.couchbase.com/browse/JVMCBC-932[JVMCBC-932]:
Fixed a memory leak when OrphanReporter is disabled.
* https://issues.couchbase.com/browse/JVMCBC-933[JVMCBC-933]:
ThresholdRequestTracer and OrphanReporter now use bounded queues.

==== Internal Improvements

* https://issues.couchbase.com/browse/JVMCBC-912[JVMCBC-912]:
Refactor property loading.
* https://issues.couchbase.com/browse/JVMCBC-918[JVMCBC-918]:
Move ProjectionsApplier into core.
* https://issues.couchbase.com/browse/JVMCBC-920[JVMCBC-920]:
Move MutationState logic to core.
* https://issues.couchbase.com/browse/JVMCBC-921[JVMCBC-921]:
Add OpenTelemetry attributes for spans.
* https://issues.couchbase.com/browse/JVMCBC-929[JVMCBC-929]:
Retain stability annotations at runtime.


=== Version 3.1.2 (2 February 2021)

Version 3.1.2 is the third release of the 3.1 series, bringing stabilizations and enhancements over 3.1.1.

https://packages.couchbase.com/clients/java/3.1.2/Couchbase-Java-Client-3.1.2.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.1.2/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.1.2/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.1.2**
* com.couchbase.client:**core-io:2.1.2**
* io.projectreactor:**reactor-core:3.4.1**
* org.reactivestreams:**reactive-streams:1.0.3**

==== API Affecting

* https://issues.couchbase.com/browse/JCBC-1763[JCBC-1763]:
CollectionManager::getScope is now deprecated, in favour of using getAllScopes.

==== Enhancements

* https://issues.couchbase.com/browse/JVMCBC-915[JVMCBC-915]:
As a performance optimization, loading a collection now only fetches the information required for that collection, rather than the full collection manifest.
* https://issues.couchbase.com/browse/JVMCBC-916[JVMCBC-916]:
Any send HTTP request will send a hostname if hostnames are used, rather than IP, leading to consistent hostname use across the system.


=== Version 3.1.1 (12 January 2021)

Version 3.1.1 is the second release of the 3.1 series, bringing stabilizations and enhancements over 3.1.0.

https://packages.couchbase.com/clients/java/3.1.1/Couchbase-Java-Client-3.1.1.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.1.1/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.1.1/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.1.1**
* com.couchbase.client:**core-io:2.1.1**
* io.projectreactor:**reactor-core:3.4.1**
* org.reactivestreams:**reactive-streams:1.0.3**

==== API Affecting

* https://issues.couchbase.com/browse/JVMCBC-906[JVMCBC-906]:
Removed Tracer as a _mandatory_ argument from `OpenTelemetrySpan`.
(The OpenTelemetry module is marked `@Stability.Volatile`, indicating that there may be API-breaking changes.
The volatility arises from the underlying `OpenTelemetry` library itself being at a beta/volatile level.)

==== Bugs

* https://issues.couchbase.com/browse/JVMCBC-909[JVMCBC-909]:
Retry opening the bucket until timeout when it is not found, to allow for it not yet being created.
* https://issues.couchbase.com/browse/JVMCBC-910[JVMCBC-910]:
WaitUntilReady will now wait if bucket not present yet, before it starts to time out.
* https://issues.couchbase.com/browse/JVMCBC-911[JVMCBC-911],
https://issues.couchbase.com/browse/JCBC-1728[JCBC-1728]:
Certain collection-related error codes have changed.
* https://issues.couchbase.com/browse/JCBC-1730[JCBC-1730]:
Support for collections added to `BatchHelper`.
* https://issues.couchbase.com/browse/JCBC-1747[JCBC-1747]:
Prepared non-adhoc queries on scopes were failing, as query_context was not being passed to the individual prepare and/or execute statements.
This has now been fixed, and scope-level queries are working as expected. 

==== Enhancements

* https://issues.couchbase.com/browse/JVMCBC-907[JVMCBC-907]:
The Orphan Reporter can now be disabled.
* https://issues.couchbase.com/browse/JVMCBC-908[JVMCBC-908]:
Updated OpenTelemetry to 0.13.
* https://issues.couchbase.com/browse/JCBC-1749[JCBC-1749]:
Escape the scope for scope-level queries now enabled, as a fix in the server means that this works.
* https://issues.couchbase.com/browse/JCBC-1746[JCBC-1746]:
Expose partition information from the query management API on `QueryIndex` class.


=== Version 3.1.0 (2 December 2020)

Version 3.1.0 is the first GA release of the 3.1 series, bringing stabilizations and enhancements over 3.0.10 and the 3.0 SDK, and adding features to support Couchbase Server 6.6 and 7.0β.

https://packages.couchbase.com/clients/java/3.1.0/Couchbase-Java-Client-3.1.0.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.1.0/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.1.0/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.1.0**
* com.couchbase.client:**core-io:2.1.0**
* io.projectreactor:**reactor-core:3.4.0**
* org.reactivestreams:**reactive-streams:1.0.3**

==== Enhancements

* https://issues.couchbase.com/browse/JCBC-1731[JCBC-1731]:
Experimental support for Metrics (`Meter`) and the internals have been reworked around the `RequestTracer`. The new metrics implementation is disabled by default but will be enabled in the future. We encourage you to try it out and provide feedback, please see the documentation section on tracing and metrics for further information.
* https://issues.couchbase.com/browse/JCBC-1646[JCBC-1646]:
The minimum durability level can now be configured on the `BucketManager`.
* https://issues.couchbase.com/browse/JVMCBC-904[JVMCBC-904]:
Internal and external dependencies have been updated, including project reactor to `3.4.0`.
* https://issues.couchbase.com/browse/JVMCBC-905[JVMCBC-905]:
It is now possible to disable TLS hostname verification as part of the `SecurityConfig`.
* https://issues.couchbase.com/browse/JVMCBC-901[JVMCBC-901]:
Support for transactions with {sqlpp_url}[{sqlpp} (formerly N1QL)] queries has been added to the core subsystem so that the upper transaction dependency can make use of it.

In addition to the tickets outlined below, different interfaces have been elevated from `Uncomitted` or `Volatile` to `Comitted`. These include:

* Expiry Key/Value read and write APIs that take an `Instant`.
* Geo-Polygon Search
* Search Flex-Index Option
* Search Disable-Scoring Option


== Java SDK 3.0 Releases


=== Version 3.0.10 (3 November 2020)

Version 3.0.10 is a maintenance release, bringing enhancements over the last stable release.

https://packages.couchbase.com/clients/java/3.0.10/Couchbase-Java-Client-3.0.10.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.10/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.11/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.10**
* com.couchbase.client:**core-io:2.0.11**
* io.projectreactor:**reactor-core:3.3.9.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.3**

==== Enhancements

* https://issues.couchbase.com/browse/JVMCBC-898[JVMCBC-898]:
Added fallback for lastDispatchedTo in context, to improve debuggability.
* https://issues.couchbase.com/browse/JVMCBC-899[JVMCBC-899]:
Updated OpenTelemetry to 0.9.1.


=== Version 3.0.9 (7 October 2020)

Version 3.0.9 is a bugfix release of the 3.0 series, bringing enhancements and bugfixes over the last stable release.

https://packages.couchbase.com/clients/java/3.0.9/Couchbase-Java-Client-3.0.9.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.9/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.10/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.9**
* com.couchbase.client:**core-io:2.0.10**
* io.projectreactor:**reactor-core:3.3.9.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.3**

==== API Affecting
* https://issues.couchbase.com/browse/JCBC-1716[JCBC-1716]: The Analytics getPendingMutations API had a return value (`Map<String, Long>`) that did not reflect what was returned from the server.
The return value has been changed to `Map<String, Map<String, Long>>` accordingly.
As the getPendingMutations method was previously uncallable due to the resulting deserialization failure, we believe this API change - though technically breaking - will not impact any users, and we have kept the API version at 3.x.

==== Bug Fixes
* https://issues.couchbase.com/browse/JCBC-1713[JCBC-1713]: 
Improve LDAP auth failure handling.
* https://issues.couchbase.com/browse/JCBC-1718[JCBC-1718]: 
`Expiry` fixed for `touch` and `getAndTouch` methods.
* https://issues.couchbase.com/browse/JVMCBC-885[JVMCBC-885]: 
Allow overriding of `BestEffortRetryStrategy`.
* https://issues.couchbase.com/browse/JVMCBC-889[JVMCBC-889]: 
Make sure WaitUntilReady always times out.
* https://issues.couchbase.com/browse/JVMCBC-890[JVMCBC-890]: 
Enforce only negotiate PLAIN when using TLS with PasswordAuthenticator.
* https://issues.couchbase.com/browse/JVMCBC-892[JVMCBC-892]: 
Service pool idle time check must happen more often.
* https://issues.couchbase.com/browse/JVMCBC-894[JVMCBC-894]: 
BatchHelper: handle success case with no body gracefully.
* https://issues.couchbase.com/browse/JVMCBC-872[JVMCBC-872]: 
Subdoc 'no access' error code is now reported correctly.
This helps users to identify and fix permissions errors for system XATTRs.

==== Enhancements
* https://issues.couchbase.com/browse/JCBC-1651[JCBC-1651]: 
Geopolygon search support.
* https://issues.couchbase.com/browse/JCBC-1652[JCBC-1652]: 
Added Options To Use FTS Hints (Flex Index).
* https://issues.couchbase.com/browse/JCBC-1695[JCBC-1695]: 
Added support to pass Score as FTS parameter.
* https://issues.couchbase.com/browse/JCBC-1707[JCBC-1707]: 
Retrofited Geo Search Queries to allow Coordinate Usage.
* https://issues.couchbase.com/browse/JCBC-1709[JCBC-1709]: 
Allow to access ReactiveScope from Scope.
* https://issues.couchbase.com/browse/JCBC-1712[JCBC-1712]: 
Clarified Javadoc lockTime on getAndLock.
* https://issues.couchbase.com/browse/JCBC-1715[JCBC-1715]: 
Allow to provide custom http headers for the `RawManager`.
* https://issues.couchbase.com/browse/JCBC-1717[JCBC-1717]: 
Support for targeting requests to a given node.
This allows to always send QueryRequests related to a given transaction to the same query node.
* https://issues.couchbase.com/browse/JVMCBC-888[JVMCBC-888], 
https://issues.couchbase.com/browse/JVMCBC-893[JVMCBC-893]: 
Dependency bumps: Netty to 4.1.52.Final, OpenTelemetry to 0.8.
* https://issues.couchbase.com/browse/JVMCBC-886[JVMCBC-886]: 
Improve LDAP auth failure handling.
* https://issues.couchbase.com/browse/JVMCBC-896[JVMCBC-896]: 
Fast dispatch pooled requests.


=== Version 3.0.8 (31 August 2020)

Version 3.0.8 is a bugfix release of the 3.0 series, bringing enhancements and bugfixes over the last stable release.

https://packages.couchbase.com/clients/java/3.0.8/Couchbase-Java-Client-3.0.8.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.8/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.9/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.8**
* com.couchbase.client:**core-io:2.0.9**
* io.projectreactor:**reactor-core:3.3.9.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.3**

==== Enhancements

* https://issues.couchbase.com/browse/JCBC-1705[JCBC-1705]:
A (uncomitted) API has been added which allows to very efficiently perform bulk fetch and bulk exists operations. See the `BatchHelper` class for more details.
* https://issues.couchbase.com/browse/JCBC-1684[JCBC-1684]:
The `PingOptions` services can now be configured through a vararg, making it easier to use.
* https://issues.couchbase.com/browse/JCBC-1691[JCBC-1691]:
A (uncomitted) API has been added which allows sending all kinds of requests to the cluster manager (called raw manager API).
* https://issues.couchbase.com/browse/JVMCBC-883[JVMCBC-883]:
The client is now a little less verbose when performing a DNS SRV request and the underlying JDK operation times out.
* https://issues.couchbase.com/browse/JVMCBC-879[JVMCBC-879]:
Updated internal and external dependencies to their latest maintenance releases.
* https://issues.couchbase.com/browse/JVMCBC-871[JVMCBC-871]:
On the `IoConfig` it is now possible to `captureTraffic()` with empty arguments, implying that all traffic will be captured.
* https://issues.couchbase.com/browse/JVMCBC-874[JVMCBC-874]:
When dealing with unknown collections, the SDK now returns a more user friendly retry reason when it can (outdated manifest vs. collection not found).
* https://issues.couchbase.com/browse/JVMCBC-875[JVMCBC-875]:
On the request timeout exception, the retry reasons are now accessible directly.
* https://issues.couchbase.com/browse/JCBC-1693[JCBC-1693]:
The `UserManager` API has been extended to support collections and scopes (needs at least Server 7.0 to be usable).
* https://issues.couchbase.com/browse/JCBC-1660[JCBC-1660]:
Support for scope-level {sqlpp} queries has been added (needs at least Server 7.0 to be usable).
* https://issues.couchbase.com/browse/JCBC-1658[JCBC-1658]:
Support for scope-level analytics queries has been added (needs at least Server 7.0 to be usable).

==== Bug Fixes
* https://issues.couchbase.com/browse/JCBC-1696[JCBC-1696]:
When adding the option `withExpiry(true)` to `GetOptions`, it is now possible to use a custom transcoder which is JSON compatible.
* https://issues.couchbase.com/browse/JVMCBC-805[JVMCBC-805]:
The client now handles bootstrapping against nodes much better which do not have the data service enabled (in an MDS setup).
* https://issues.couchbase.com/browse/JVMCBC-882[JVMCBC-882]:
A bug has been fixed where when bootstrapping against a node with no data service enabled, the endpoint would not be cleaned up and would keep trying to reconnect.
* https://issues.couchbase.com/browse/JVMCBC-872[JVMCBC-872]:
The client now more explicitly handles an error response code (`NO_ACCESS`) when a subdocument request is performed against a system xattr.
* https://issues.couchbase.com/browse/JVMCBC-873[JVMCBC-873]:
Durability information is now properly unwrapped from an optional when exported and dumped (for example as part of an exception).
* https://issues.couchbase.com/browse/JVMCBC-880[JVMCBC-880]:
The client now trackes multiple parallel bucket open attempts (against different buckets) in a better way, making sure that an internal state is only switched when all those bucket open attempts have completed (and not just the first one).
* https://issues.couchbase.com/browse/JVMCBC-878[JVMCBC-878]:
`EndpointDiagnostics` had the local and remote hostnames mixed up, they now show up in the correct order.

=== Version 3.0.7 (4 August 2020)

Version 3.0.7 is the eighth release of the 3.0 series, bringing enhancements and bugfixes over the last stable release.

https://packages.couchbase.com/clients/java/3.0.7/Couchbase-Java-Client-3.0.7.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.7/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.8/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.7**
* com.couchbase.client:**core-io:2.0.8**
* io.projectreactor:**reactor-core:3.3.8.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.3**

==== API Affecting
* https://issues.couchbase.com/browse/JCBC-1681[JCBC-1681]: 
Removed cas from `IncrementOptions` and `DecrementOptions`.  
CAS is not supported by the underlying protocol and should not have been exposed in these options.
* https://issues.couchbase.com/browse/JCBC-1625[JCBC-1625]: 
Deprecated `maxTTL` on BucketSettings in favor of `maxExpiry`.

==== Bug Fixes
* https://issues.couchbase.com/browse/JCBC-1647[JCBC-1647]: 
Deprecated `EjectionPolicy` in favor of `EvictionPolicyType`.
And added the "noEviction" and "nruEviction" policies used by ephemeral buckets.
This fixed a but where the BucketManager didn't recognize ephemeral bucket ejection values.
Users can now set a non-default ejection policy when creating an ephemeral bucket.
* https://issues.couchbase.com/browse/JCBC-1668[JCBC-1668]: 
Fixes an NPE when `toString` or `fieldsAs` is called when no fields are present in the result. 
In this case just null should now be returned, instead of a NPE deep down in the Jackson serializer stack.
* https://issues.couchbase.com/browse/JVMCBC-870[JVMCBC-870]: 
A bug in the chunk response parser prohibited responses meant that View reduce responses were never completed, and as a result timed out on the user side.
The completion of view results with reduce enabled has now been fixed.

==== Enhancements
* https://issues.couchbase.com/browse/JCBC-1661[JCBC-1661], https://issues.couchbase.com/browse/JCBC-1665[JCBC-1665]: 
Building on the expiry improvements in the previous release, this adds a new `expiryTime()` method that returns expiry as an `Instant`, which better expresses the concept than the `Duration` returned by `expiry()`.  
The latter will be deprecated in a future release.  
Similarly, everywhere a `Duration`-based expiry could be provided previously, an overload has been added to take an `Instant`-based expiry.
* https://issues.couchbase.com/browse/JCBC-1666[JCBC-1666]: 
Made `bucket.scope("_default").collection("_default")` behave just like `bucket.defaultCollection()`.
`AsyncScope.collection()` now no longer refreshes collection map for default collection.
* https://issues.couchbase.com/browse/JCBC-1670[JCBC-1670]: 
Added WaitUntilReadyOptions.serviceTypes() overload that accepts varargs.
* https://issues.couchbase.com/browse/JVMCBC-867[JVMCBC-867]: 
Performance improvement: do not grab ByteBuf slice when extracting server response time.
* https://issues.couchbase.com/browse/JVMCBC-869[JVMCBC-869]: 
Maintenance dependency bump: Netty -> 4.1.51, Jackson -> 2.11.1, Reactor -> 3.3.7, OpenTelemetry -> 0.6.0.

=== Version 3.0.6 (14 July 2020)

Version 3.0.6 is the seventh release of the 3.0 series, bringing enhancements and bugfixes over the last stable release.

https://packages.couchbase.com/clients/java/3.0.6/Couchbase-Java-Client-3.0.6.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.6/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.7/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.6**
* com.couchbase.client:**core-io:2.0.7**
* io.projectreactor:**reactor-core:3.3.5.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.3**

==== Enhancements
* https://issues.couchbase.com/browse/JCBC-1645[JCBC-1645]:
Specifying document expiries has been made significantly easier.
Expiries are supplied as a `Duration`.  
The new behaviour is that if that duration is less than 50 years, then it will be interpreted as being a relative timestamp from the current time.
E.g. `Duration.ofDays(35)` will expire in 35 days time.
(Previously, a `Duration` longer than 30 days would be interpreted as being an epoch time.
Unless this epoch time occurred in the future then it would expire immediately.
In order to preserve compatibility for users that worked around this behaviour, any `Duration` longer than 50 years will continue to be interpreted as an epoch time.)
* https://issues.couchbase.com/browse/JCBC-1632[JCBC-1632]:
Bootstrapping is now fully pipelined for performance, building on the improvements in the previous release.
* https://issues.couchbase.com/browse/JVMCBC-865[JVMCBC-865]:
Changed the default idle timeout to 4.5s for http connections, to support performance improvements in query service.

==== Bug Fixes
* https://issues.couchbase.com/browse/JCBC-1662[JCBC-1662]:
`MutateInMacro` for CRC32 is fixed.
* https://issues.couchbase.com/browse/JCBC-1664[JCBC-1664]:
`viewQuery` with `ViewOptions.viewOptions().keys(keys)` was returning a bad_request error.
This is now fixed.
* https://issues.couchbase.com/browse/JVMCBC-849[JVMCBC-849]:
Redundant global loading exceptions no longer propagated -- now logged at `debug` level.
* https://issues.couchbase.com/browse/JVMCBC-856[JVMCBC-856]:
A just-opened connection in pool no longer gets cleaned up prematurely .
* https://issues.couchbase.com/browse/JVMCBC-858[JVMCBC-858]:
Channel writeAndFlush failures are no longer ignored.
* https://issues.couchbase.com/browse/JVMCBC-862[JVMCBC-862]:
Race condition with node identifier change on bootstrap identified.
New logic and some changes to the config provider code ensures that retry and resubscribe picks up fresh seed nodes.
* https://issues.couchbase.com/browse/JVMCBC-863[JVMCBC-863]:
Bucket-Level ping report no longer includes other view and KV services buckets.
* https://issues.couchbase.com/browse/JVMCBC-866[JVMCBC-866]:
Trailing : no longer added to IPv6 addresses without [].
'invalid IPv6 address' warnings now no longer produced when trying to connect to a valid Ipv6 address thus specified.


=== Version 3.0.5 (2 June 2020)

Version 3.0.5 is the sixth release of the 3.0 series, bringing enhancements and bugfixes over the last stable release.

https://packages.couchbase.com/clients/java/3.0.5/Couchbase-Java-Client-3.0.5.zip[Download] |
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.5/[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.6/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.5**
* com.couchbase.client:**core-io:2.0.6**
* io.projectreactor:**reactor-core:3.3.5.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.3**

==== Enhancements

* http://issues.couchbase.com/browse/JVMCBC-852[JVMCBC-852]:
Bumped Reactor to 3.3.5, Netty to 4.1.50.Final, and Jackson to 2.11.0.
* https://issues.couchbase.com/browse/JVMCBC-693[JVMCBC-693]:
For performance, the KV bootstrap sequence is now partially pipelined.

In addition, there are internal revisions to support the forthcoming Field Level Encryption (FLE) support.
This will be available in a separate library for Enterprise Edition subscribers.

==== Bug Fixes

* http://issues.couchbase.com/browse/JVMCBC-851[JVMCBC-851]:
Reactive getAllReplicas methods will now honor a provided custom transcoder.
* http://issues.couchbase.com/browse/JVMCBC-849[JVMCBC-849]:
Duplicate global loading exceptions are now swallowed to remove redundant warnings from logging (this was a cosmetic-only issue).

=== Version 3.0.4 (7 May 2020)

Version 3.0.4 is the fifth release of the 3.0 series, bringing enhancements and bugfixes over the last stable release.

https://packages.couchbase.com/clients/java/3.0.4/Couchbase-Java-Client-3.0.4.zip[Download] |
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.4/[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.5/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.4**
* com.couchbase.client:**core-io:2.0.5**
* io.projectreactor:**reactor-core:3.3.4.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.3**

==== Enhancements

* http://issues.couchbase.com/browse/JVMCBC-841[JVMCBC-841]:
Bumped Netty dependency to 2.0.30, and reactor to 3.3.4

==== Bug Fixes

* http://issues.couchbase.com/browse/JVMCBC-845[JVMCBC-845]:
If a rebalance is stopped in the middle, an edge case occasionally causes KV ops to time out as the fast forward map is chosen over the retry.
The behavior has now been changed so that the client will try the old and new servers to make sure the operation eventually gets dispatched to the right node.
* http://issues.couchbase.com/browse/JCBC-1626[JCBC-1626]:
If bucket is not flushable, a `BucketNotFlushableException` is now raised.

=== Version 3.0.3 (7 April 2020)

Version 3.0.3 is the fourth release of the 3.0 series, bringing enhancements and bugfixes over the last stable release.

https://packages.couchbase.com/clients/java/3.0.3/Couchbase-Java-Client-3.0.3.zip[Download] |
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.3/[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.4/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.3**
* com.couchbase.client:**core-io:2.0.4**
* io.projectreactor:**reactor-core:3.3.3.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.2**

==== Enhancements

* http://issues.couchbase.com/browse/JCBC-1603[JCBC-1603], http://issues.couchbase.com/browse/JCBC-1606[JCBC-1606]:
Exposed API to set the CollectionsExample TTL.
CreateCollection CollectionSpec now includes `MaxTTL`.
* http://issues.couchbase.com/browse/JCBC-1617[JCBC-1617]:
Attempting to work with the collection manager on clusters where CollectionsExample are not available (or enabled as a DP) will now result in a `FeatureNotAvailable` failure.
* http://issues.couchbase.com/browse/JVMCBC-830[JVMCBC-830]:
Added more convenient overloads for SecurityConfig and CertAuth.
These overloads initialize both the SecurityConfig and the CertificateAuthenticator directly from a KeyStore or TrustStore.
* http://issues.couchbase.com/browse/JVMCBC-831[JVMCBC-831]:
Improves timeout for waitUntilReady -- the `waitUntilReady` helper should now throw a proper timeout exception.
* http://issues.couchbase.com/browse/JVMCBC-832[JVMCBC-832]:
Added support for multiple ports per hostname in the connection string -- without having to use the explicit SeedNode set overload.
* http://issues.couchbase.com/browse/JVMCBC-835[JVMCBC-835]:
Using "localhost:8091" as a connection string would set the kv bootstrap port to 8091, which is not desired behavior.
To prevent this from happening again, the code now checks for this condition, fails fast, and also provides guidance on what the connection string should look like instead.
* http://issues.couchbase.com/browse/JVMCBC-836[JVMCBC-836]:
Enabled Unordered Execution by Default.
* http://issues.couchbase.com/browse/JVMCBC-837[JVMCBC-837]:
Updates OpenTelemetry to 0.3 (beta).

==== Bug Fixes

* http://issues.couchbase.com/browse/JCBC-1618[JCBC-1618]:
Named fields in SearchRows results are now deserialized.
* http://issues.couchbase.com/browse/JVMCBC-834[JVMCBC-834]:
'CollectionNotFoundException' now triggers a retry, and if no collection refresh is currently in progress it will proactively trigger a new one.
Now Docs created under custom collection should no longer raise an exception when a collection has been created in the meantime, but the collection is not found as no refresh is in progress.
* http://issues.couchbase.com/browse/JVMCBC-826[JVMCBC-826]:
A NullPointerException was occuring when LDAP is enabled.
The code now explicitly fails the connection with a descriptive error message instructing the user what to do next (either use TLS which is preferred) or enable PLAIN on the password authenticator (insecure).
* http://issues.couchbase.com/browse/JVMCBC-827[JVMCBC-827]:
Search query results row_hit typo resulted in 0 being returned for total rows. 
This has now been fixed. 
* http://issues.couchbase.com/browse/JVMCBC-828[JVMCBC-828]:
Omit internal config request in orphan reporting.
* http://issues.couchbase.com/browse/JVMCBC-839[JVMCBC-839]:
Bootstrap will now correctly use the mapped port if alternate addr is present.


=== Version 3.0.2 (3 March 2020)

Version 3.0.2 is the third release of the 3.0 series, bringing  enhancements and bugfixes over the last stable release.

https://packages.couchbase.com/clients/java/3.0.2/Couchbase-Java-Client-3.0.2.zip[Download] |
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.2/[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.3/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.2**
* com.couchbase.client:**core-io:2.0.3**
* io.projectreactor:**reactor-core:3.3.1.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.2**

==== Enhancements

* http://issues.couchbase.com/browse/JCBC-1588[JCBC-1588]:
Give TypeRef overload of JsonSerializer a default "unsupported" impl, making it easier for applications to implement custom JsonSerializers.
* http://issues.couchbase.com/browse/JVMCBC-813[JVMCBC-813]:
Improved error message for bucket is missing.
* http://issues.couchbase.com/browse/JVMCBC-815[JVMCBC-815]:
Check if key exceeds size limits.
* http://issues.couchbase.com/browse/JVMCBC-818[JVMCBC-818]:
Trimmed netty stack in connect failures for more readable output.
* http://issues.couchbase.com/browse/JVMCBC-819[JVMCBC-819]:
Distinguished bucket not found in select bucket failures.
* http://issues.couchbase.com/browse/JVMCBC-823[JVMCBC-823]:
Added a global component to the core id.
* http://issues.couchbase.com/browse/JVMCBC-825[JVMCBC-825]:
Support added for new VATTR HELLO flag.

==== Bug Fixes

* http://issues.couchbase.com/browse/JCBC-1587[JCBC-1587]:
Exists no longer returns wrong value if executed right after remove.
* http://issues.couchbase.com/browse/JCBC-1600[JCBC-1600]:
Using expiry together with document flags on a Sub-Document `mutateIn` no longer causes an incorrect flags field to be sent.
* http://issues.couchbase.com/browse/JCBC-1604[JCBC-1604]:
Properly clear cache when repreparing/retrying query.
* http://issues.couchbase.com/browse/JVMCBC-824[JVMCBC-824]:
Native Netty transports not included, resulting in fallback to default implementation.  Only affected 2.0.2 core release.

=== Version 3.0.1 (5 February 2020)

Version 3.0.1 is the second release of the 3.0 series, bringing  enhancements and bugfixes over the last stable release.

https://packages.couchbase.com/clients/java/3.0.1/Couchbase-Java-Client-3.0.1.zip[Download] |
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.1/[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.2/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.1**
* com.couchbase.client:**core-io:2.0.2**
* io.projectreactor:**reactor-core:3.3.1.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.2**

==== Enhancements

* http://issues.couchbase.com/browse/JCBC-1578[JCBC-1578]:
Added support for Java Object Serialization as a custom `Transcoder`.
* http://issues.couchbase.com/browse/JVMCBC-808[JVMCBC-808]:
The internal packaged `netty` dependency has been reduced to the minimum amount of artifacts needed, trimming the resulting jar size a little.

==== Bug Fixes

* http://issues.couchbase.com/browse/JCBC-1574[JCBC-1574]:
`JsonObject/Array.put(String,Object)` now supports writing generic Maps and Lists.
* http://issues.couchbase.com/browse/JCBC-1580[JCBC-1580]:
The code for get projections had an import for unbundled jackson which prevented it from working in an environment where no unbundled jackson is on the classpath.
This no longer occurs.
* http://issues.couchbase.com/browse/JCBC-1582[JCBC-1582]:
The client context ID is now propagated into the `PREPARE` query if needed.
* http://issues.couchbase.com/browse/JVMCBC-806[JVMCBC-806]:
TLS: remote hostname and port are passed down to the SSL engine, making sure that hostname validation works as expected.
* http://issues.couchbase.com/browse/JCBC-1575[JCBC-1575]:
Bucket Management: BucketSettings load does now recognize numReplicas properly.

==== Known Issues

* http://issues.couchbase.com/browse/JVMCBC-805[JVMCBC-805]:
When bootstrapping against a non-KV node the KV socket is not cleaned up properly. 
As a workaround (and as we recommend in general), please only bootstrap against nodes which have the KV service enabled.
Or maintain a list of KV nodes in xref:howtos:managing-connections.adoc#using-dns-srv-records[DNS SRV].

=== Version 3.0.0 (10 January 2020)

This is the first GA release of the third generation Java SDK.

https://packages.couchbase.com/clients/java/3.0.0/Couchbase-Java-Client-3.0.0.zip[Download] |
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.0/[API Reference] | 
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.0/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.0**
* com.couchbase.client:**core-io:2.0.0**
* io.projectreactor:**reactor-core:3.3.1.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.2**

==== Enhancements

The following list describes the API changes between 3.0.0 beta.2 and 3.0.0 GA.

* http://issues.couchbase.com/browse/JCBC-1563[JCBC-1563]:
Added the reactive API to the view index manager.
* http://issues.couchbase.com/browse/JVMCBC-776[JVMCBC-776]:
Added support for server-side KV tracing statistics.
* http://issues.couchbase.com/browse/JCBC-1522[JCBC-1522]:
All data commands have been instrumented to be included in RTO (Response Time Observability).
* http://issues.couchbase.com/browse/JCBC-1566[JCBC-1566], http://issues.couchbase.com/browse/JCBC-1568[JCBC-1568]:
The Search API has been slightly improved to align with the SDK RFC.
* http://issues.couchbase.com/browse/JCBC-1599[JCBC-1599]:
Bucket, Scope and Collection instances are now cached so repeated open attempts produce less garbage and happen quicker.
* http://issues.couchbase.com/browse/JVMCBC-785[JVMCBC-785], http://issues.couchbase.com/browse/JVMCBC-786[JVMCBC-786], http://issues.couchbase.com/browse/JVMCBC-675[JVMCBC-675]:
View, Search, Analytics, and Query retryable error codes are now retried as part of the configured retry strategy.
* http://issues.couchbase.com/browse/JCBC-1561[JCBC-1561], http://issues.couchbase.com/browse/JCBC-1562[JCBC-1562]:
Added Option overloads to collection and search index managers.
* http://issues.couchbase.com/browse/JVMCBC-787[JVMCBC-787], http://issues.couchbase.com/browse/JVMCBC-788[JVMCBC-788]:
View requests and KV collection requests are now short-circuited against unsupported clusters.
* http://issues.couchbase.com/browse/JCBC-1552[JCBC-1552]:
Added support for Java 9 automatic module names.

* http://issues.couchbase.com/browse/JCBC-1554[JCBC-1554]:
`JsonArry` and `JsonObject` now support `toArray` in addition to `toString`.
* http://issues.couchbase.com/browse/JCBC-1545[JCBC-1545]:
The `ping` command has been reintroduced to the cluster and bucket level APIs.
* http://issues.couchbase.com/browse/JCBC-1518[JCBC-1518]:
An internal server error from the KV engine is now properly mapped to the exception equivalent.
* http://issues.couchbase.com/browse/JVMCBC-779[JVMCBC-779]:
It is now possible to customize the event loop thread count instead of having to provide a new event loop itself.
* http://issues.couchbase.com/browse/JVMCBC-767[JVMCBC-767]:
A new `ConfigIdleRedialTimeout` has been introduced which recycles idle HTTP streaming connections.
* http://issues.couchbase.com/browse/JVMCBC-782[JVMCBC-782]:
The orphan response reporter (as part of RTO) has been ported to SDK 3 from SDK 2 and is now enabled by default.
* http://issues.couchbase.com/browse/JVMCBC-784[JVMCBC-784]:
Idle HTTP connections are now closed after 30 seconds.
* http://issues.couchbase.com/browse/JVMCBC-773[JVMCBC-773]:
SASL PLAIN is now not negotiated by default on non-TLS connections to prevent downgrade attacks out of the box.
* http://issues.couchbase.com/browse/JVMCBC-795[JVMCBC-795]:
Requests are now failed fast if it can be determined that the service is not available on the cluster.
* http://issues.couchbase.com/browse/JVMCBC-790[JVMCBC-790]:
The concept of backpressure has been re-introduced but in slightly different form.
* http://issues.couchbase.com/browse/JVMCBC-[JVMCBC-]:
The circuit breaker now has a customizable completion callback.

==== Bug Fixes

The following list describes the API changes between 3.0.0 beta.2 and 3.0.0 GA.

* http://issues.couchbase.com/browse/JCBC-1550[JCBC-1550]:
The owned environment in the `Cluster` is now properly shutdown on disconnect.
* http://issues.couchbase.com/browse/JCBC-1517[JCBC-1517], http://issues.couchbase.com/browse/JCBC-1566[JCBC-1566]:
All reactive APIs are now deferred and will not execute I/O side effects when not subscribed to.
* http://issues.couchbase.com/browse/JCBC-1539[JCBC-1539]:
A bug has been fixed where the IoConfig.networkResolution could not be set through a system property.
* http://issues.couchbase.com/browse/JVMCBC-793[JVMCBC-793]:
Various fixes have been made around DNS SRV bootstrapping that make it more robust, including fixing a bug that prevented it from working properly.
* http://issues.couchbase.com/browse/JCBC-1524[JCBC-1524]:
The projections on `get` have been refactored, the test suite expanded, and a couple of issues fixed along the way.
* http://issues.couchbase.com/browse/JCBC-1531[JCBC-1531]:
The QueryIndexManager now only returns GSI indexes.
* http://issues.couchbase.com/browse/JVMCBC-802[JVMCBC-802]:
A bug has been fixed where a non-existing view in an existing design document would not cause an exception.
* http://issues.couchbase.com/browse/JCBC-1565[JCBC-1565]:
Views now use the right default View timeout instead of the Analytics one.
* http://issues.couchbase.com/browse/JVMCBC-789[JVMCBC-789]:
Performing operations while initially loading the collection map is now handled gracefully.

==== Known Issues

* http://issues.couchbase.com/browse/JVMCBC-805[JVMCBC-805]:
When bootstrapping against a non-KV node the KV socket is not cleaned up properly. As a workaround (an we recommend in general) please
only bootstrap against nodes which have the KV service enabled.

==== API Changes

The following list describes the API changes between 3.0.0 beta.2 and 3.0.0 GA. 
Since SDK 3 is a complete rewrite over SDK 2, the individual changes between them are not listed here. 
Please refer to the xref:project-docs:migrating-sdk-code-to-3.n.adoc[migration guide] for this.

* http://issues.couchbase.com/browse/JCBC-1533[JCBC-1533], http://issues.couchbase.com/browse/JCBC-1534[JCBC-1534], http://issues.couchbase.com/browse/JCBC-1535[JCBC-1535], http://issues.couchbase.com/browse/JCBC-1541[JCBC-1541], http://issues.couchbase.com/browse/JCBC-1542[JCBC-1542]:
Exceptions have been consolidated, renamed, and overall aligned with the latest RFC.
* http://issues.couchbase.com/browse/JCBC-1536[JCBC-1536]:
`SeedNodes` have been moved out of the `ClusterOptions` into a `Cluster#connect()` overload.
* http://issues.couchbase.com/browse/JCBC-1540[JCBC-1540]:
`MajorityAndPersistOnMaster` has been renamed to `MajorityAndPersistToActive` on the durability enum.
* http://issues.couchbase.com/browse/JCBC-1545[JCBC-1545]:
The diagnostics API has been reworked on all levels.
* http://issues.couchbase.com/browse/JCBC-1551[JCBC-1551]:
The `empty` constructors are gone from `JsonObject` and `JsonArray` since they duplicate `create`.


=== Pre-releases

Numerous _Alpha_ and _Beta_ releases were made in the run-up to the 3.0 release, and although unsupported, the release notes and download links are retained for archive purposes xref:3.0-pre-release-notes.adoc[here].


== Older Releases

Although https://www.couchbase.com/support-policy/enterprise-software[no longer supported], documentation for older releases continues to be available in our https://docs-archive.couchbase.com/home/index.html[docs archive].
// end::all[]
