= Couchbase Java SDK Release Notes and Archives
:description: Release notes, installation instructions, and download archive for the Couchbase Java Client.
:navtitle: Release Notes
:page-topic-type: project-doc
:page-partial:
:page-aliases: relnotes-java-sdk,ROOT:sdk-release-notes,ROOT:relnotes-java-sdk,ROOT:release-notes,ROOT:download-links

[abstract]
{description}

These pages cover the 3._x_ versions of the Couchbase Java SDK. 
For release notes, download links, and installation methods for 2.7 and earlier releases of the Couchbase Java Client, which will not work with Distributed Transactions, please see the xref:2.7@java-sdk::sdk-release-notes.adoc[2.x Java Release Notes & Download Archive].

Transactions is available as a separate library for the Java SDK.
Please see the xref:distributed-transactions-java-release-notes.adoc[Transaction Release Notes page].


== Installation

// tag::jdk-version[]
At least Java 8 is required for current releases;
see the xref:project-docs:compatibility.adoc#jdk-compat[Compatibility] section for details.
We recommend running the latest LTS version (i.e. at the time of writing JDK 17) with the highest patch version available.
Java 17 has various enhancements like sealed classes, pattern matching for switch expressions (in preview), and further updates and improvements on core libraries.

NOTE: JDK 17 is only supported from SDK version 3.2.4 onwards.
If you're using an SDK version earlier than 3.2.4, the recommended LTS version is JDK 11.
// end::jdk-version[]

[source,xml]
----
<dependencies>
    <dependency>
        <groupId>com.couchbase.client</groupId>
        <artifactId>java-client</artifactId>
        <version>3.2.7</version>
    </dependency>
</dependencies>
----

include::3.3@java-sdk:project-docs:page$sdk-release-notes.adoc[tag=all]
