= Couchbase Java SDK Release Notes and Archives
:description: Release notes, installation instructions, and download archive for the Couchbase Java Client.
:navtitle: Release Notes
:page-topic-type: project-doc
:page-partial:
:page-aliases: relnotes-java-sdk,ROOT:sdk-release-notes,ROOT:relnotes-java-sdk,ROOT:release-notes,ROOT:download-links

[abstract]
{description}

These pages cover the 3._x_ versions of the Couchbase Java SDK. 
For release notes, download links, and installation methods for 2.7 and earlier releases of the Couchbase Java Client, which will not work with Distributed Transactions, please see the https://docs-archive.couchbase.com/java-sdk/2.7/sdk-release-notes.html[2.x Java Release Notes & Download Archive].

== Installation

See the xref:project-docs:sdk-full-installation.adoc[Full Installation] guide for details.

// tag::all[]
== Version 3.3.1 (8 Jun 2022)

Version 3.3.1 is the second release of the 3.3 series, and is a maintenance release.

https://packages.couchbase.com/clients/java/3.3.1/Couchbase-Java-Client-3.3.1.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.3.1/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.3.1/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.3.1**
* com.couchbase.client:**core-io:2.3.1**
* io.projectreactor:**reactor-core:3.4.17**
* org.reactivestreams:**reactive-streams:1.0.3**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Version | Built Against              | API Stability
| `tracing-opentelemetry`   | 1.1.1   | OpenTelemetry 1.13.0       | Committed
| `tracing-opentracing`     | 1.1.1   | OpenTracing 0.33.0         | Committed
| `metrics-opentelemetry`   | 0.3.1   | OpenTelemetry 1.13.0-alpha | Volatile
| `metrics-micrometer`      | 0.3.1   | Micrometer 1.8.4           | Volatile
|=======================

=== Improvements

* https://issues.couchbase.com/browse/JVMCBC-1089[JVMCBC-1089]:
SDK users can now customize the `ConsoleLogger` format.
* https://issues.couchbase.com/browse/JVMCBC-1093[JVMCBC-1093]:
Fixed an issue where the DNS SRV lookup failed, due to a missing SRV record.
The SDK previously logged a `WARNING` with a stack trace.
The lookup failure is typically harmless, so the log message has been downgraded to `INFO` level without a stack trace.
* https://issues.couchbase.com/browse/JVMCBC-1088[JVMCBC-1088]:
Updated Netty to version `4.1.77.Final`.

== Version 3.3.0 (26 April 2022)

Version 3.3.0 is the first release of the 3.3 series.

The three headline changes in this release:

* Supports the new functionality of Couchbase Server 7.1.
* Directly integrates transactions into the SDK rather than requiring a separate library.  Existing users of the transactions library can refer to the xref:project-docs:distributed-acid-transactions-migration-guide.adoc[Distributed Transactions Migration Guide] to see the simple steps needed to migrate, which we recommend.
* Bundles the public server security certificates for Couchbase Capella, to make it easier for users to get started with Capella.

https://packages.couchbase.com/clients/java/3.3.0/Couchbase-Java-Client-3.3.0.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.3.0/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.3.0/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.3.0**
* com.couchbase.client:**core-io:2.3.0**
* io.projectreactor:**reactor-core:3.4.17**
* org.reactivestreams:**reactive-streams:1.0.3**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Version | Built Against              | API Stability
| `tracing-opentelemetry`   | 1.1.0   | OpenTelemetry 1.13.0       | Committed
| `tracing-opentracing`     | 1.1.0   | OpenTracing 0.33.0         | Committed
| `metrics-opentelemetry`   | 0.3.0   | OpenTelemetry 1.13.0-alpha | Volatile
| `metrics-micrometer`      | 0.3.0   | Micrometer 1.8.4           | Volatile
|=======================

=== Improvements
* https://issues.couchbase.com/browse/JCBC-1929[JCBC-1929]:
Integrated transactions library into SDK.
* https://issues.couchbase.com/browse/JVMCBC-1070[JVMCBC-1070]:
Bundled public Capella CA certificate.
* https://issues.couchbase.com/browse/JVMCBC-1074[JVMCBC-1074]:
If you try to connect to Capella without enabling TLS, now you'll get an exception that says TLS is required (instead of an `UnknownHostException`).
* https://issues.couchbase.com/browse/JVMCBC-1076[JVMCBC-1076]:
Deprecated `Event.createdAt()` in favor of a version that returns an `Instant`.
* https://issues.couchbase.com/browse/JVMCBC-1078[JVMCBC-1078]:
Made `schedulerThreadCount` customizable.
* https://issues.couchbase.com/browse/JVMCBC-1079[JVMCBC-1079]:
Added ConnectionString SDK 3 compatibility attributes.
* https://issues.couchbase.com/browse/JVMCBC-1082[JVMCBC-1082]:
Updated maintenance dependencies.
* https://issues.couchbase.com/browse/JVMCBC-1085[JVMCBC-1085]:
Exposed last connect attempt failure through `Diagnostics`.
* https://issues.couchbase.com/browse/JCBC-1886[JCBC-1886]:
Allow to list the number of currently available replicas for a document ID.
* https://issues.couchbase.com/browse/JCBC-1923[JCBC-1923]:
Added warning when ignoring connection string parameters or scheme.

=== Bugs
* https://issues.couchbase.com/browse/JCBC-1922[JCBC-1922]:
`NOT_STORED` when inserting a document will now correctly raise a `DocumentAlreadyExistsException` (rather than a `DocumentNotFoundException` as before).
* https://issues.couchbase.com/browse/JVMCBC-1077[JVMCBC-1077]:
Shutting down a ClusterEnvironment now correctly stops a `Meter` owned by the cluster. This plugs a resource leak where `LoggingMeter` worker threads would never be stopped.


== Version 3.2.7 (25 April 2022)

Version 3.2.7 is the eighth release of the 3.2 series.

https://packages.couchbase.com/clients/java/3.2.7/Couchbase-Java-Client-3.2.7.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.2.7/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.2.7/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.2.7**
* com.couchbase.client:**core-io:2.2.7**
* io.projectreactor:**reactor-core:3.4.17**
* org.reactivestreams:**reactive-streams:1.0.3**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Version | Built Against             | API Stability
| `tracing-opentelemetry`   | 1.0.7   | OpenTelemetry 1.9.1       | Committed
| `tracing-opentracing`     | 1.0.7   | OpenTracing 0.33.0        | Committed
| `metrics-opentelemetry`   | 0.2.7   | OpenTelemetry 1.7.1-alpha | Volatile
| `metrics-micrometer`      | 0.2.7   | Micrometer 1.7.5          | Volatile
|=======================

=== Bugs
* https://issues.couchbase.com/browse/JCBC-1922[JCBC-1922]:
The KeyValue error code `NOT_STORED` is now properly mapped to `DocumentExistsException` on `insert` and `mutateIn`.
* https://issues.couchbase.com/browse/JVMCBC-1077[JVMCBC-1077]:
The environment now properly shuts down the `Meter` if it is owned and not passed in externally.

=== Improvements
* https://issues.couchbase.com/browse/JVMCBC-1082[JVMCBC-1082]:
Updated internal and external dependencies.
 * Netty from 4.1.73 to 4.1.76
 * Jackson from 2.13.1 to 2.13.2 (and 2.13.2.2)
 * Reactor from 3.4.14 to 3.4.17 

== Version 3.2.6 (2 March 2022)

Version 3.2.6 is the seventh release of the 3.2 series.

https://packages.couchbase.com/clients/java/3.2.6/Couchbase-Java-Client-3.2.6.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.2.6/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.2.6/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.2.6**
* com.couchbase.client:**core-io:2.2.6**
* io.projectreactor:**reactor-core:3.4.14**
* org.reactivestreams:**reactive-streams:1.0.3**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Version | Built Against             | API Stability
| `tracing-opentelemetry`   | 1.0.6   | OpenTelemetry 1.9.1       | Committed
| `tracing-opentracing`     | 1.0.6   | OpenTracing 0.33.0        | Committed
| `metrics-opentelemetry`   | 0.2.6   | OpenTelemetry 1.7.1-alpha | Volatile
| `metrics-micrometer`      | 0.2.6   | Micrometer 1.7.5          | Volatile
|=======================

=== Bugs
* https://issues.couchbase.com/browse/JVMCBC-1060[JVMCBC-1060]:
Fixed an issue where rate limited exceptions were not thrown for `SearchIndexManager` errors.
* https://issues.couchbase.com/browse/JVMCBC-1071[JVMCBC-1071]:
The SDK now ensures that negative values are not sent to the `ValueRecorder`.
* https://issues.couchbase.com/browse/JCBC-1918[JCBC-1918]:
Executing a Full-Text Search query with an open-ended date range facet no longer results in a `NullPointerException`.
* https://issues.couchbase.com/browse/JCBC-1919[JCBC-1919]:
Index fields are now quoted in the analytics index manager.
* https://issues.couchbase.com/browse/JCBC-1921[JCBC-1921]:
QueryIndexManager `buildDeferredIndexes` no longer throws a `ParsingFailureException` against Couchbase Server 6.0.

=== New Features
* https://issues.couchbase.com/browse/JVMCBC-1057[JVMCBC-1057]:
Added core infrastructure for the Backup service. 
Users can now make custom HTTP requests to the Backup service.
* https://issues.couchbase.com/browse/JVMCBC-1064[JVMCBC-1064]:
When implementing a custom `RetryStrategy`, a new overload of `RetryAction.noRetry` lets you specify an exception translator for converting the default request cancellation exception into your preferred exception class.

=== Improvements
* https://issues.couchbase.com/browse/JVMCBC-1065[JVMCBC-1065]:
`RetryReason.allowsNonIdempotentRetry()` is now public, so you can call it from a custom `RetryStrategy`.
* https://issues.couchbase.com/browse/JVMCBC-1066[JVMCBC-1066]:
When `SecurityConfig.Builder.trustCertificate(Path)` is given a file containing more than one certificate, it now trusts all the certificates instead of just the first one.
Likewise, the result of `SecurityConfig.decodeCertificates(List<String>)` now includes all certificates in each string, not just the first certificate in each string.
* https://issues.couchbase.com/browse/JVMCBC-1068[JVMCBC-1068]:
Added explicit handling of `FeatureNotAvailable` for Magma on CE.
* https://issues.couchbase.com/browse/JVMCBC-1069[JVMCBC-1069]:
Added explicit handling of `FeatureNotAvailable` for Query CE.
* https://issues.couchbase.com/browse/JCBC-1916[JCBC-1916]:
Updated the Analytics Management API Javadocs.
* https://issues.couchbase.com/browse/JCBC-1917[JCBC-1917]:
You can now configure properties of the `ClusterEnvironment` without having to build and shut down the environment.
The new `ClusterOptions.environment(Consumer<ClusterEnvironment.Builder>)` method lets you configure properties of a `ClusterEnvironment` owned by the Cluster, so you don't need to manage the environment yourself.
Example usage:
[source,java]
----
Cluster cluster = Cluster.connect("localhost", clusterOptions(username, password)
    .environment(env -> env.ioConfig().captureTraffic(ServiceType.MANAGER)));
----

== Version 3.2.5 (2 February 2022)

Version 3.2.5 is the sixth release of the 3.2 series.

https://packages.couchbase.com/clients/java/3.2.5/Couchbase-Java-Client-3.2.5.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.2.5/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.2.5/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.2.5**
* com.couchbase.client:**core-io:2.2.5**
* io.projectreactor:**reactor-core:3.4.14**
* org.reactivestreams:**reactive-streams:1.0.3**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Version | Built Against             | API Stability
| `tracing-opentelemetry`   | 1.0.5   | OpenTelemetry 1.9.1       | Committed
| `tracing-opentracing`     | 1.0.5   | OpenTracing 0.33.0        | Committed
| `metrics-opentelemetry`   | 0.2.5   | OpenTelemetry 1.7.1-alpha | Volatile
| `metrics-micrometer`      | 0.2.5   | Micrometer 1.7.5          | Volatile
|=======================

=== API Impacting
* https://issues.couchbase.com/browse/JCBC-1901[JCBC-1901]:
Removed the Azure link type from the analytics management API, due to a change in the underlying server API.
(Note that this interface is marked @Stability.Volatile indicating that it can change.)

=== Bugs
* https://issues.couchbase.com/browse/JCBC-1895[JCBC-1895]:
Fixed an issue where `lookupInResult.contentAs(0, Boolean.class)` was throwing a `DecodingFailureException` on a Sub-Document exists operation.
* https://issues.couchbase.com/browse/JCBC-1896[JCBC-1896]:
Fixed an issue where `JsonValueSerializerWrapper` was unable to support decoding via TypeRef.
* https://issues.couchbase.com/browse/JCBC-1904[JCBC-1904]:
Fixed issues with constant and URL bindings and also introduced convenience methods to load a function from raw JSON.
* https://issues.couchbase.com/browse/JVMCBC-1046[JVMCBC-1046]:
Added fix to not load the global config if a node is not in the seed node list anymore.
* https://issues.couchbase.com/browse/JVMCBC-1058[JVMCBC-1058]:
The SDK now throws a more descriptive `FeatureNotAvailableException` for scopes and collections on memcached buckets.

=== Improvements
* https://issues.couchbase.com/browse/JCBC-1860[JCBC-1860]:
`ConflictResolutionType.CUSTOM` has now been added to the bucket management API.
* https://issues.couchbase.com/browse/JCBC-1864[JCBC-1864]:
FTS options now include `IncludeLocations` and `Operator`.
* https://issues.couchbase.com/browse/JCBC-1876[JCBC-1876]:
Query API now supports preserving TTL.
* https://issues.couchbase.com/browse/JCBC-1882[JCBC-1882]:
Index management API now supports managing indexes for a collection.
* https://issues.couchbase.com/browse/JCBC-1898[JCBC-1898]:
Added convenience method for getting raw bytes from `GetResult`.
* https://issues.couchbase.com/browse/JCBC-1902[JCBC-1902]:
The SDK now sends the configured user timeout to search.
* https://issues.couchbase.com/browse/JCBC-1905[JCBC-1905]:
Added convenience methods for loading eventing function JSON.
* https://issues.couchbase.com/browse/JCBC-1909[JCBC-1909]:
Added `scanWait` to `AnalyticsOptions`.
* https://issues.couchbase.com/browse/JCBC-1903[JCBC-1903]:
Added javadocs for bucket management API.
* https://issues.couchbase.com/browse/JCBC-1908[JCBC-1908]:
Added javadocs for query index management APIs.
* https://issues.couchbase.com/browse/JVMCBC-1055[JVMCBC-1055],
https://issues.couchbase.com/browse/JVMCBC-1047[JVMCBC-1047],
https://issues.couchbase.com/browse/JVMCBC-1051[JVMCBC-1051]:
Updated dependencies.
Netty goes from 4.1.72.Final to 4.1.73.Final.
Jackson from 2.13.0 to 2.13.1.
Reactor from 3.4.12 to 3.4.14.
log4j (an optional dependency) from 2.15.0 to 2.17.1.
* https://issues.couchbase.com/browse/JVMCBC-1037[JVMCBC-1037]:
Added a minor performance optimisation that avoids `whenComplete` closure for timeout cancellation.
* https://issues.couchbase.com/browse/JVMCBC-1045[JVMCBC-1045]:
Added an internal watchdog that updates the cluster configuration if the number of nodes changes.
* https://issues.couchbase.com/browse/JVMCBC-1048[JVMCBC-1048]:
Added change that ensures the SDK always sets `RequestContext` on `RequestSpan`.
* https://issues.couchbase.com/browse/JVMCBC-1056[JVMCBC-1056]:
Added more log information on unexpected endpoint disconnect.
* https://issues.couchbase.com/browse/JVMCBC-1059[JVMCBC-1059]:
The SDK now handles any `retry:true` field in a query error result by retrying it.


== Version 3.2.4 (9 December 2021)

Version 3.2.4 is the fifth release of the 3.2 series.

https://packages.couchbase.com/clients/java/3.2.4/Couchbase-Java-Client-3.2.4.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.2.4/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.2.4/[Core API Reference]

NOTE: This release introduces support for JDK 17.

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.2.4**
* com.couchbase.client:**core-io:2.2.4**
* io.projectreactor:**reactor-core:3.4.12**
* org.reactivestreams:**reactive-streams:1.0.3**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Version | Built Against             | API Stability
| `tracing-opentelemetry`   | 1.0.4   | OpenTelemetry 1.7.1       | Committed
| `tracing-opentracing`     | 1.0.4   | OpenTracing 0.33.0        | Committed
| `metrics-opentelemetry`   | 0.2.4   | OpenTelemetry 1.7.1-alpha | Volatile
| `metrics-micrometer`      | 0.2.4   | Micrometer 1.7.5          | Volatile
|=======================

=== Bugs
* https://issues.couchbase.com/browse/JCBC-1892[JCBC-1892]:
`EventingFunctionSettings` can now be empty - this fixes an issue with loading eventing functions from the cluster.

=== Improvements
* https://issues.couchbase.com/browse/JVMCBC-1033[JVMCBC-1033], https://issues.couchbase.com/browse/JVMCBC-1034[JVMCBC-1034]:
Updated internal and external dependencies to their latest bugfix versions. 
This also updates OpenTelemetry to 1.7.x.
* https://issues.couchbase.com/browse/JCBC-1881[JCBC-1881]:
Added (volatile) support for the `magma` storage backend when creating a bucket through the bucket manager.
* https://issues.couchbase.com/browse/JVMCBC-1035[JVMCBC-1035]:
The (internal) `subDocumentField` is now serializable - this is needed for apache spark integration.
* https://issues.couchbase.com/browse/JVMCBC-1032[JVMCBC-1032]:
Added (volatile) support for Rate/Quota Limits. 
This is needed for Couchbase Capella.
* https://issues.couchbase.com/browse/JVMCBC-1039[JVMCBC-1039]:
Included `httpStatus` in Query and Analytics Error Context, as well as the `vbucket` in the KV error context. 
This helps with debugging.


== Version 3.2.3 (2 November 2021)

Version 3.2.3 is the fourth release of the 3.2 series.

https://packages.couchbase.com/clients/java/3.2.3/Couchbase-Java-Client-3.2.3.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.2.3/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.2.3/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.2.3**
* com.couchbase.client:**core-io:2.2.3**
* io.projectreactor:**reactor-core:3.4.9**
* org.reactivestreams:**reactive-streams:1.0.3**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Version | Built Against             | API Stability
| `tracing-opentelemetry`   | 1.0.3   | OpenTelemetry 1.3.0       | Committed
| `tracing-opentracing`     | 1.0.3   | OpenTracing 0.33.0        | Committed
| `metrics-opentelemetry`   | 0.2.3   | OpenTelemetry 1.3.0-alpha | Volatile
| `metrics-micrometer`      | 0.2.3   | Micrometer 1.7.0          | Volatile
|=======================

=== Improvements
* https://issues.couchbase.com/browse/JVMCBC-1026[JVMCBC-1026]:
Support for error map v2 has been added to ensure the config can be parsed without failure.

== Version 3.2.2 (6 October 2021)

Version 3.2.2 is the third release of the 3.2 series.

https://packages.couchbase.com/clients/java/3.2.2/Couchbase-Java-Client-3.2.2.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.2.2/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.2.2/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.2.2**
* com.couchbase.client:**core-io:2.2.2**
* io.projectreactor:**reactor-core:3.4.9**
* org.reactivestreams:**reactive-streams:1.0.3**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Version | Built Against             | API Stability
| `tracing-opentelemetry`   | 1.0.2   | OpenTelemetry 1.3.0       | Committed
| `tracing-opentracing`     | 1.0.2   | OpenTracing 0.33.0        | Committed
| `metrics-opentelemetry`   | 0.2.2   | OpenTelemetry 1.3.0-alpha | Volatile
| `metrics-micrometer`      | 0.2.2   | Micrometer 1.7.0          | Volatile
|=======================

=== Improvements
* https://issues.couchbase.com/browse/JCBC-1872[JCBC-1872]:
Bring `NodeLocatorHelper` to SDK 3 from 2.
* https://issues.couchbase.com/browse/JCBC-1875[JCBC-1875]:
Document and polish Eventing Management API.
* https://issues.couchbase.com/browse/JVMCBC-1015[JVMCBC-1015]:
Improve client side error message when TLS is enforced on the server side.
* https://issues.couchbase.com/browse/JVMCBC-1016[JVMCBC-1016]:
Gracefully handle more invalid connection string cases.
* https://issues.couchbase.com/browse/JVMCBC-1022[JVMCBC-1022]:
Batch-Log messages in DefaultEventBus. 
Now events which are overflowing are not directly logged to stderr but rather batched up and logged at interval.
Note that this implies some "loss of precision", as not all dropped events are logged - one event per type is preserved.

=== Bugs
* https://issues.couchbase.com/browse/JVMCBC-1017[JVMCBC-1017]:
Fixed issue with Threshold Logging Tracing not working due to `RequestContext` not being set.
* https://issues.couchbase.com/browse/JCBC-1873[JCBC-1873]:
Rename EventingFunction to `validate_ssl_certificates` to conform to spec.
* https://issues.couchbase.com/browse/JVMCBC-1020[JVMCBC-1020]:
Added `target` property to `QueryRequest` and ensured it is honored for prepare and execute, so they are both run on the same node. 
This fix removes need for `TargetedQueryRequest`.


== Version 3.2.1 (1 September 2021)

Version 3.2.1 is the second release of the 3.2 series.

https://packages.couchbase.com/clients/java/3.2.1/Couchbase-Java-Client-3.2.1.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.2.1/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.2.1/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.2.1**
* com.couchbase.client:**core-io:2.2.1**
* io.projectreactor:**reactor-core:3.4.9**
* org.reactivestreams:**reactive-streams:1.0.3**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Version | Built Against             | API Stability
| `tracing-opentelemetry`   | 1.0.1   | OpenTelemetry 1.3.0       | Committed
| `tracing-opentracing`     | 1.0.1   | OpenTracing 0.33.0        | Committed
| `metrics-opentelemetry`   | 0.2.1   | OpenTelemetry 1.3.0-alpha | Volatile
| `metrics-micrometer`      | 0.2.1   | Micrometer 1.7.0          | Volatile
|=======================

=== Known Issues
* https://issues.couchbase.com/browse/JVMCBC-1017[JVMCBC-1017]:
The `ThresholdLoggingTracer` will not record any request and will not log them into the log file. 
If you rely on this functionality please use 3.1.7 as only 3.2.0 and 3.2.1 are affected. 
This issue will be addressed in 3.2.2.

=== Bug Fixes
* https://issues.couchbase.com/browse/JVMCBC-1002[JVMCBC-1002]:
Default log level reverted to INFO.
* https://issues.couchbase.com/browse/JVMCBC-1007[JVMCBC-1007]:
`LoggingMeter` was incorrectly marked as Volatile in SDK 3.2 -- now fixed.
* https://issues.couchbase.com/browse/JCBC-1850[JCBC-1850]:
Fixed `NullPointerException` with `OpenTracing`.

=== Improvements
* https://issues.couchbase.com/browse/JCBC-1732[JCBC-1732]:
Eventing Management API added.
* https://issues.couchbase.com/browse/JCBC-1852[JCBC-1852]:
FLE: Optionally read @Encrypted POJO properties from unencrypted JSON fields.
* https://issues.couchbase.com/browse/JCBC-1858[JCBC-1858]:
Added convenience method for getting raw JSON bytes from `LookupInResult`.
* https://issues.couchbase.com/browse/JCBC-1859[JCBC-1859]:
Allow to create `CollectionSpec` for default scope.
* https://issues.couchbase.com/browse/JCBC-1868[JCBC-1868]:
Make `JsonValueModule` compatible with Jackson < 2.8.
* https://issues.couchbase.com/browse/JVMCBC-1010[JVMCBC-1010]:
Maintenance dependency bump.
* https://issues.couchbase.com/browse/JVMCBC-990[JVMCBC-990]:
Fixed `WaitUntilReady` timing out with 6.0.x and unhealthy seed nodes.
* https://issues.couchbase.com/browse/JVMCBC-999[JVMCBC-999]:
Properly map server query timeout while streaming.
* https://issues.couchbase.com/browse/JVMCBC-1004[JVMCBC-1004]:
Configure and apply default log level for `ConsoleLogger`.
* https://issues.couchbase.com/browse/JVMCBC-1005[JVMCBC-1005]:
Allow to export Context as Map.
* https://issues.couchbase.com/browse/JVMCBC-1006[JVMCBC-1006]:
`ErrorContext` must be included in message.


== Version 3.2.0 (20 July 2021)

Version 3.2.0 is the first release of the 3.2 series.
It promotes to GA support for the scopes and collections provided by Couchbase Server 7.0, and also OpenTelemetry.

https://packages.couchbase.com/clients/java/3.2.0/Couchbase-Java-Client-3.2.0.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.2.0/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.2.0/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.2.0**
* com.couchbase.client:**core-io:2.2.0**
* io.projectreactor:**reactor-core:3.4.6**
* org.reactivestreams:**reactive-streams:1.0.3**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Version | Built Against             | API Stability
| `tracing-opentelemetry`   | 1.0.0   | OpenTelemetry 1.3.0       | Committed
| `tracing-opentracing`     | 1.0.0   | OpenTracing 0.33.0        | Committed
| `metrics-opentelemetry`   | 0.2.0   | OpenTelemetry 1.3.0-alpha | Volatile
| `metrics-micrometer`      | 0.2.0   | Micrometer 1.7.0          | Volatile
|=======================

=== Known Issues
* https://issues.couchbase.com/browse/JVMCBC-1017[JVMCBC-1017]:
The `ThresholdLoggingTracer` will not record any request and will not log them into the log file. 
If you rely on this functionality please use 3.1.7 as only 3.2.0 and 3.2.1 are affected. 
This issue will be addressed in 3.2.2.

=== Bug Fixes
* https://issues.couchbase.com/browse/JVMCBC-949[JVMCBC-949]:
Opening a non-default collection on an memcached bucket now fails fast.
* https://issues.couchbase.com/browse/JVMCBC-983[JVMCBC-983]:
Ignore slow subscribers on certain Flux intervals.
* https://issues.couchbase.com/browse/JCBC-1822[JCBC-1822]:
`BatchHelper` now supports MDS deployments.

=== Interface Changes
All interface changes are to interfaces that are currently in beta and marked `@Stability.Volatile` or `@Stability.Uncommitted`.

* https://issues.couchbase.com/browse/JVMCBC-978[JVMCBC-978]:
Rename `AggregatingMeter` to `LoggingMeter`.
* https://issues.couchbase.com/browse/JVMCBC-934[JVMCBC-934]:
Threshold and Orphan output is now in new format.
* https://issues.couchbase.com/browse/JVMCBC-979[JVMCBC-979]:
Rename `ThresholdRequestTracer` to `ThresholdLoggingTracer`.
* https://issues.couchbase.com/browse/JCBC-1823[JCBC-1823]:
Promote collection APIs from Volatile to Committed.
* https://issues.couchbase.com/browse/JCBC-1844[JCBC-1844]:
Promote `BatchHelper` from Volatile to Uncommitted.

=== Improvement
* https://issues.couchbase.com/browse/JVMCBC-980[JVMCBC-980]:
Add exception wrappers to Tracers and Meters.
* https://issues.couchbase.com/browse/JVMCBC-987[JVMCBC-987]:
Allow supplying an SDK2-compatible memcached hashing strategy.
* https://issues.couchbase.com/browse/JVMCBC-988[JVMCBC-988]:
Map Query Error 13014 to `AuthenticationException`.
* https://issues.couchbase.com/browse/JVMCBC-989[JVMCBC-989]:
Add timeout_ms to threshold logging tracer output.
* https://issues.couchbase.com/browse/JVMCBC-991[JVMCBC-991]:
Optimize metric dispatching.
* https://issues.couchbase.com/browse/JVMCBC-992[JVMCBC-992]:
Cache NodeIdentifier in NodeInfo.
* https://issues.couchbase.com/browse/JVMCBC-993[JVMCBC-993]:
Optimize early discard of events which are not going to be logged.
* https://issues.couchbase.com/browse/JVMCBC-996[JVMCBC-996]:
Throw `FeatureNotAvailableException` if scope level queries are not available.
* https://issues.couchbase.com/browse/JVMCBC-997[JVMCBC-997]:
Duplicate attributes from dispatch_to_server to improve tracing.
* https://issues.couchbase.com/browse/JVMCBC-998[JVMCBC-998]:
Performance: Do not set tracing spans if not needed.
* https://issues.couchbase.com/browse/JVMCBC-981[JVMCBC-981]:
Support CoreHttpClient requests to manager service.
* https://issues.couchbase.com/browse/JVMCBC-984[JVMCBC-984]:
Dependency bump: Netty 4.1.63 to 4.1.65, micrometer 1.6.6 to 1.7.0.
* https://issues.couchbase.com/browse/JCBC-1242[JCBC-1242],
https://issues.couchbase.com/browse/JCBC-1837[JCBC-1837]:
Add OSGi bundle.
* https://issues.couchbase.com/browse/JCBC-1787[JCBC-1787]:
Validate expiry instants.
* https://issues.couchbase.com/browse/JCBC-1838[JCBC-1838]:
Add support for SDK2-compatible `LegacyTranscoder`.
* https://issues.couchbase.com/browse/JCBC-1841[JCBC-1841]:
Update OpenTelemetry to 1.3.0.

== Version 3.1.8 (1 March 2022)

Version 3.1.8 is the ninth release of the 3.1 series, bringing stabilizations over 3.1.7.

https://packages.couchbase.com/clients/java/3.1.8/Couchbase-Java-Client-3.1.8.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.1.8/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.1.8/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.1.8**
* com.couchbase.client:**core-io:2.1.8**
* io.projectreactor:**reactor-core:3.4.15**
* org.reactivestreams:**reactive-streams:1.0.3**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Version | Built Against             | API Stability
| `tracing-opentelemetry`   | 0.3.8   | OpenTelemetry 1.2.0       | Volatile
| `tracing-opentracing`     | 0.3.8   | OpenTracing 0.33.0        | Volatile
| `metrics-opentelemetry`   | 0.1.8   | OpenTelemetry 1.2.0-alpha | Volatile
| `metrics-micrometer`      | 0.1.8   | Micrometer 1.6.6          | Volatile
|=======================

=== Bug Fixes

* https://issues.couchbase.com/browse/JVMCBC-1067[JVMCBC-1067]:
Internal and external maintenance dependencies are updated to their latest available bugfix releases (including Netty to 4.1.74.Final).
* https://issues.couchbase.com/browse/JVMCBC-1046[JVMCBC-1046]:
Added fix to not load the global config if a node is not in the seed node list anymore.
* https://issues.couchbase.com/browse/JVMCBC-1006[JVMCBC-1006]:
`ErrorContext` is now included in the message of a `CouchbaseException`.
* https://issues.couchbase.com/browse/JVMCBC-1895[JCBC-1895]:
Fixed an issue where `lookupInResult.contentAs(0, Boolean.class)` was throwing a `DecodingFailureException` on a Sub-Document exists operation.
* https://issues.couchbase.com/browse/JVMCBC-1896[JCBC-1896]:
Fixed an issue where `JsonValueSerializerWrapper` was unable to support decoding via TypeRef.

== Version 3.1.7 (11 August 2021)

Version 3.1.7 is the eigth release of the 3.1 series, bringing stabilizations and enhancements over 3.1.6.

https://packages.couchbase.com/clients/java/3.1.7/Couchbase-Java-Client-3.1.7.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.1.7/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.1.7/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.1.7**
* com.couchbase.client:**core-io:2.1.7**
* io.projectreactor:**reactor-core:3.4.6**
* org.reactivestreams:**reactive-streams:1.0.3**

Optional artifacts on top of this SDK version are tested for the following compatibilities:

.Optional Artifact Version Compatibility
[options="header"]
|=======================
| Artifact                  | Version | Built Against             | API Stability
| `tracing-opentelemetry`   | 0.3.7   | OpenTelemetry 1.2.0       | Volatile
| `tracing-opentracing`     | 0.3.7   | OpenTracing 0.33.0        | Volatile
| `metrics-opentelemetry`   | 0.1.7   | OpenTelemetry 1.2.0-alpha | Volatile
| `metrics-micrometer`      | 0.1.7   | Micrometer 1.6.6          | Volatile
|=======================

=== Bug Fixes

* https://issues.couchbase.com/browse/JVMCBC-949[JVMCBC-949]:
Opening a non-default collection on an memcached bucket now fails fast.
* https://issues.couchbase.com/browse/JVMCBC-983[JVMCBC-983]:
Ignore slow subscribers on certain Flux intervals.
* https://issues.couchbase.com/browse/JCBC-1822[JCBC-1822]:
`BatchHelper` now supports MDS deployments.
* https://issues.couchbase.com/browse/JCBC-1850[JCBC-1850]:
Ignore null values for attributed in OpenTelemetry and OpenTracing.
* https://issues.couchbase.com/browse/JVMCBC-990[JVMCBC-990]:
Gracefully handle cluster-level WaitUntilReady against clusters < 6.5.

=== Improvements

* https://issues.couchbase.com/browse/JVMCBC-996[JVMCBC-996]:
Throw `FeatureNotAvailableException` if scope level queries are not available.
* https://issues.couchbase.com/browse/JVMCBC-988[JVMCBC-988]:
Query error code 13014 is now mapped to `AuthenticationException`.
* https://issues.couchbase.com/browse/JCBC-1838[JCBC-1838]:
Add support for SDK2-compatible `LegacyTranscoder`.
* https://issues.couchbase.com/browse/JVMCBC-987[JVMCBC-987]:
Allow supplying an SDK2-compatible memcached hashing strategy.
* https://issues.couchbase.com/browse/JVMCBC-999[JVMCBC-999]:
Properly map server query timeout while streaming.

== Version 3.1.6 (4 June 2021)

Version 3.1.6 is the seventh release of the 3.1 series, bringing stabilizations and enhancements over 3.1.5.

https://packages.couchbase.com/clients/java/3.1.6/Couchbase-Java-Client-3.1.6.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.1.6/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.1.6/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.1.6**
* com.couchbase.client:**core-io:2.1.6**
* io.projectreactor:**reactor-core:3.4.6**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Bug Fixes
* https://issues.couchbase.com/browse/JCBC-1676[JCBC-1676]:
Bucket creation now succeeds against Community Edition 6.5 and above.
* https://issues.couchbase.com/browse/JVMCBC-972[JVMCBC-972]:
Only open one GCCCP connection per node.

=== Improvements
* https://issues.couchbase.com/browse/JCBC-1808[JCBC-1808]:
Updated tracing and metrics module dependencies.
* https://issues.couchbase.com/browse/JCBC-1649[JCBC-1649]:
Update analytics management API to support compound dataverse names.
* https://issues.couchbase.com/browse/JCBC-1815[JCBC-1815]:
Improve error context for BatchHelper.
* https://issues.couchbase.com/browse/JVMCBC-939[JVMCBC-939]:
Improve no collection access handling.
* https://issues.couchbase.com/browse/JVMCBC-974[JVMCBC-974]:
Restructure AggregatingMeter output format.
* https://issues.couchbase.com/browse/JVMCBC-975[JVMCBC-975]:
Further improve wait until ready diagnostics.
* https://issues.couchbase.com/browse/JVMCBC-977[JVMCBC-977]:
Improve bucket configuration handling (revEpoch).

== Version 3.1.5 (6 May 2021)

Version 3.1.5 is the sixth release of the 3.1 series, bringing stabilizations and enhancements over 3.1.4.

https://packages.couchbase.com/clients/java/3.1.5/Couchbase-Java-Client-3.1.5.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.1.5/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.1.5/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.1.5**
* com.couchbase.client:**core-io:2.1.5**
* io.projectreactor:**reactor-core:3.4.5**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Bug Fixes

* https://issues.couchbase.com/browse/JCBC-1804[JCBC-1804]:
Ensure `contentAsObject/Array()` works with a custom JsonSerializer.
* https://issues.couchbase.com/browse/JVMCBC-965[JVMCBC-965]:
Better error logging during bucket failures, which helps with troubleshooting.
* https://issues.couchbase.com/browse/JVMCBC-963[JVMCBC-963]:
Add better retry handling for local and global bucket config fetch failures, making it more resilient.
* https://issues.couchbase.com/browse/JVMCBC-967[JVMCBC-967]:
Work around and fix a `OverflowException` with `PersistTo`/`ReplicateTo`, caused by Reactor.

=== Improvements

* https://issues.couchbase.com/browse/JVMCBC-958[JVMCBC-958]:
Improve the performance of individual collection ID fetches, speeding up the time of bootstrap whan a lot of collections are opened.
* https://issues.couchbase.com/browse/JCBC-1756[JCBC-1756]:
Adds volatile support for preserving the expiry on certain mutation operations.
* https://issues.couchbase.com/browse/JVMCBC-959[JVMCBC-959]:
Allow `IoEnvironment` config to be overridden by system properties.
* https://issues.couchbase.com/browse/JCBC-1801[JCBC-1801]:
Allow to create a `SearchIndex` from a JSON definition.
* https://issues.couchbase.com/browse/JVMCBC-962[JVMCBC-962]:
Add (internal, volatile) request callback functionality.
* https://issues.couchbase.com/browse/JCBC-1733[JCBC-1733]:
Add support for collections to `SearchOptions`.

== Version 3.1.4 (7 April 2021)

Version 3.1.4 is the fifth release of the 3.1 series, bringing stabilizations and enhancements over 3.1.3.

https://packages.couchbase.com/clients/java/3.1.4/Couchbase-Java-Client-3.1.4.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.1.4/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.1.4/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.1.4**
* com.couchbase.client:**core-io:2.1.4**
* io.projectreactor:**reactor-core:3.4.4**
* org.reactivestreams:**reactive-streams:1.0.3**

WARNING: Due to protocol level changes, Java SDK 3.1.4 and later are not compatible with _pre-release_ versions of Couchbase Server 7.0.

=== Bug Fixes

* https://issues.couchbase.com/browse/JCBC-1798[JCBC-1798]:
Fixes ViewResult.metaData() throwing Exception when debug=true.
* https://issues.couchbase.com/browse/JVMCBC-940[JVMCBC-940]:
Better error handling of collection ID fetch failures.
* https://issues.couchbase.com/browse/JVMCBC-948[JVMCBC-948]:
CAS is only usable with Sub-Document when using StoreSemantics.REPLACE.
This server-side restriction is now also checked client-side, and a `InvalidArgumentException` raised.
* https://issues.couchbase.com/browse/JVMCBC-950[JVMCBC-950]:
waitUntilReady is now more resilient to just-created buckets.
* https://issues.couchbase.com/browse/JVMCBC-954[JVMCBC-954]:
More resilient handling of rebalances.

=== Improvements

* https://issues.couchbase.com/browse/JCBC-1786[JCBC-1786]:
Transcoders now allow contentAs(Object.class).
Java Map and List collections are used to represent JSON objects and arrays.
* https://issues.couchbase.com/browse/JCBC-1795[JCBC-1795]:
Allow `MutateInSpec.remove("")`, which removes the entire document.
* https://issues.couchbase.com/browse/JVMCBC-936[JVMCBC-936]:
Allow customizing TLS cipher list.
* https://issues.couchbase.com/browse/JVMCBC-941[JVMCBC-941]:
Support modified protocol for collections in Couchbase Server 7.0 (in beta).
* https://issues.couchbase.com/browse/JVMCBC-943[JVMCBC-943]:
Apply OpenTelemetry best practices.
* https://issues.couchbase.com/browse/JVMCBC-944[JVMCBC-944]:
Add implementation version to OpenTelemetry APIs.
* https://issues.couchbase.com/browse/JVMCBC-947[JVMCBC-947]:
Remove request counter metric.
* https://issues.couchbase.com/browse/JVMCBC-951[JVMCBC-951]:
Move GetAny/AllReplicas into core.
* https://issues.couchbase.com/browse/JVMCBC-955[JVMCBC-955]:
Distinguish between CAS mismatch and DML failure on query error.


== Version 3.1.3 (2 March 2021)

Version 3.1.3 is the fourth release of the 3.1 series, bringing stabilizations and enhancements over 3.1.2.

https://packages.couchbase.com/clients/java/3.1.3/Couchbase-Java-Client-3.1.3.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.1.3/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.1.3/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.1.3**
* com.couchbase.client:**core-io:2.1.3**
* io.projectreactor:**reactor-core:3.4.3**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Improvements

* https://issues.couchbase.com/browse/JCBC-1776[JCBC-1776],
https://issues.couchbase.com/browse/JVMCBC-924[JVMCBC-924],
https://issues.couchbase.com/browse/JVMCBC-925[JVMCBC-925]:
Updated dependencies: OpenTelemetry to 1.0.0, Netty dependency to 4.1.59, netty-tcnative-boringssl-static to 2.0.36, Reactor to 2.4.3, Jackson to 2.12.1.
* https://issues.couchbase.com/browse/JCBC-1774[JCBC-1774]:
Added pre-flight sanity check before using a JacksonJsonSerializer found on the classpath.
* https://issues.couchbase.com/browse/JVMCBC-919[JVMCBC-919]:
Support for Project Reactor BlockHound integration.
* https://issues.couchbase.com/browse/JVMCBC-926[JVMCBC-926]:
Performance: Replace new byte[] full copies with ByteBufUtil.getBytes.
* https://issues.couchbase.com/browse/JVMCBC-927[JVMCBC-927]:
Performance: Improve performance of metrics hot code path.

=== Bugs

* https://issues.couchbase.com/browse/JVMCBC-930[JVMCBC-930]:
Threshold and Orphan Reporting now report the correct time units.
* https://issues.couchbase.com/browse/JVMCBC-932[JVMCBC-932]:
Fixed a memory leak when OrphanReporter is disabled.
* https://issues.couchbase.com/browse/JVMCBC-933[JVMCBC-933]:
ThresholdRequestTracer and OrphanReporter now use bounded queues.

=== Internal Improvements

* https://issues.couchbase.com/browse/JVMCBC-912[JVMCBC-912]:
Refactor property loading.
* https://issues.couchbase.com/browse/JVMCBC-918[JVMCBC-918]:
Move ProjectionsApplier into core.
* https://issues.couchbase.com/browse/JVMCBC-920[JVMCBC-920]:
Move MutationState logic to core.
* https://issues.couchbase.com/browse/JVMCBC-921[JVMCBC-921]:
Add OpenTelemetry attributes for spans.
* https://issues.couchbase.com/browse/JVMCBC-929[JVMCBC-929]:
Retain stability annotations at runtime.


== Version 3.1.2 (2 February 2021)

Version 3.1.2 is the third release of the 3.1 series, bringing stabilizations and enhancements over 3.1.1.

https://packages.couchbase.com/clients/java/3.1.2/Couchbase-Java-Client-3.1.2.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.1.2/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.1.2/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.1.2**
* com.couchbase.client:**core-io:2.1.2**
* io.projectreactor:**reactor-core:3.4.1**
* org.reactivestreams:**reactive-streams:1.0.3**

=== API Affecting

* https://issues.couchbase.com/browse/JCBC-1763[JCBC-1763]:
CollectionManager::getScope is now deprecated, in favour of using getAllScopes.

=== Enhancements

* https://issues.couchbase.com/browse/JVMCBC-915[JVMCBC-915]:
As a performance optimization, loading a collection now only fetches the information required for that collection, rather than the full collection manifest.
* https://issues.couchbase.com/browse/JVMCBC-916[JVMCBC-916]:
Any send HTTP request will send a hostname if hostnames are used, rather than IP, leading to consistent hostname use across the system.


== Version 3.1.1 (12 January 2021)

Version 3.1.1 is the second release of the 3.1 series, bringing stabilizations and enhancements over 3.1.0.

https://packages.couchbase.com/clients/java/3.1.1/Couchbase-Java-Client-3.1.1.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.1.1/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.1.1/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.1.1**
* com.couchbase.client:**core-io:2.1.1**
* io.projectreactor:**reactor-core:3.4.1**
* org.reactivestreams:**reactive-streams:1.0.3**

=== API Affecting

* https://issues.couchbase.com/browse/JVMCBC-906[JVMCBC-906]:
Removed Tracer as a _mandatory_ argument from `OpenTelemetrySpan`.
(The OpenTelemetry module is marked `@Stability.Volatile`, indicating that there may be API-breaking changes.
The volatility arises from the underlying `OpenTelemetry` library itself being at a beta/volatile level.)

=== Bugs

* https://issues.couchbase.com/browse/JVMCBC-909[JVMCBC-909]:
Retry opening the bucket until timeout when it is not found, to allow for it not yet being created.
* https://issues.couchbase.com/browse/JVMCBC-910[JVMCBC-910]:
WaitUntilReady will now wait if bucket not present yet, before it starts to time out.
* https://issues.couchbase.com/browse/JVMCBC-911[JVMCBC-911],
https://issues.couchbase.com/browse/JCBC-1728[JCBC-1728]:
Certain collection-related error codes have changed.
* https://issues.couchbase.com/browse/JCBC-1730[JCBC-1730]:
Support for collections added to `BatchHelper`.
* https://issues.couchbase.com/browse/JCBC-1747[JCBC-1747]:
Prepared non-adhoc queries on scopes were failing, as query_context was not being passed to the individual prepare and/or execute statements.
This has now been fixed, and scope-level queries are working as expected. 

=== Enhancements

* https://issues.couchbase.com/browse/JVMCBC-907[JVMCBC-907]:
The Orphan Reporter can now be disabled.
* https://issues.couchbase.com/browse/JVMCBC-908[JVMCBC-908]:
Updated OpenTelemetry to 0.13.
* https://issues.couchbase.com/browse/JCBC-1749[JCBC-1749]:
Escape the scope for scope-level queries now enabled, as a fix in the server means that this works.
* https://issues.couchbase.com/browse/JCBC-1746[JCBC-1746]:
Expose partition information from the query management API on `QueryIndex` class.


== Version 3.1.0 (2 December 2020)

Version 3.1.0 is the first GA release of the 3.1 series, bringing stabilizations and enhancements over 3.0.10 and the 3.0 SDK, and adding features to support Couchbase Server 6.6 and 7.0β.

https://packages.couchbase.com/clients/java/3.1.0/Couchbase-Java-Client-3.1.0.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.1.0/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.1.0/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.1.0**
* com.couchbase.client:**core-io:2.1.0**
* io.projectreactor:**reactor-core:3.4.0**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Enhancements

* https://issues.couchbase.com/browse/JCBC-1731[JCBC-1731]:
Experimental support for Metrics (`Meter`) and the internals have been reworked around the `RequestTracer`. The new metrics implementation is disabled by default but will be enabled in the future. We encourage you to try it out and provide feedback, please see the documentation section on tracing and metrics for further information.
* https://issues.couchbase.com/browse/JCBC-1646[JCBC-1646]:
The minimum durability level can now be configured on the `BucketManager`.
* https://issues.couchbase.com/browse/JVMCBC-904[JVMCBC-904]:
Internal and external dependencies have been updated, including project reactor to `3.4.0`.
* https://issues.couchbase.com/browse/JVMCBC-905[JVMCBC-905]:
It is now possible to disable TLS hostname verification as part of the `SecurityConfig`.
* https://issues.couchbase.com/browse/JVMCBC-901[JVMCBC-901]:
Support for transactions with N1QL queries has been added to the core subsystem so that the upper transaction dependency can make use of it.

In addition to the tickets outlined below, different interfaces have been elevated from `Uncomitted` or `Volatile` to `Comitted`. These include:

* Expiry Key/Value read and write APIs that take an `Instant`.
* Geo-Polygon Search
* Search Flex-Index Option
* Search Disable-Scoring Option


== Version 3.0.10 (3 November 2020)

Version 3.0.10 is a maintenance release, bringing enhancements over the last stable release.

https://packages.couchbase.com/clients/java/3.0.10/Couchbase-Java-Client-3.0.10.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.10/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.11/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.10**
* com.couchbase.client:**core-io:2.0.11**
* io.projectreactor:**reactor-core:3.3.9.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Enhancements

* https://issues.couchbase.com/browse/JVMCBC-898[JVMCBC-898]:
Added fallback for lastDispatchedTo in context, to improve debuggability.
* https://issues.couchbase.com/browse/JVMCBC-899[JVMCBC-899]:
Updated OpenTelemetry to 0.9.1.


== Version 3.0.9 (7 October 2020)

Version 3.0.9 is a bugfix release of the 3.0 series, bringing enhancements and bugfixes over the last stable release.

https://packages.couchbase.com/clients/java/3.0.9/Couchbase-Java-Client-3.0.9.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.9/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.10/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.9**
* com.couchbase.client:**core-io:2.0.10**
* io.projectreactor:**reactor-core:3.3.9.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.3**

=== API Affecting
* https://issues.couchbase.com/browse/JCBC-1716[JCBC-1716]: The Analytics getPendingMutations API had a return value (`Map<String, Long>`) that did not reflect what was returned from the server.
The return value has been changed to `Map<String, Map<String, Long>>` accordingly.
As the getPendingMutations method was previously uncallable due to the resulting deserialization failure, we believe this API change - though technically breaking - will not impact any users, and we have kept the API version at 3.x.

=== Bug Fixes
* https://issues.couchbase.com/browse/JCBC-1713[JCBC-1713]: 
Improve LDAP auth failure handling.
* https://issues.couchbase.com/browse/JCBC-1718[JCBC-1718]: 
`Expiry` fixed for `touch` and `getAndTouch` methods.
* https://issues.couchbase.com/browse/JVMCBC-885[JVMCBC-885]: 
Allow overriding of `BestEffortRetryStrategy`.
* https://issues.couchbase.com/browse/JVMCBC-889[JVMCBC-889]: 
Make sure WaitUntilReady always times out.
* https://issues.couchbase.com/browse/JVMCBC-890[JVMCBC-890]: 
Enforce only negotiate PLAIN when using TLS with PasswordAuthenticator.
* https://issues.couchbase.com/browse/JVMCBC-892[JVMCBC-892]: 
Service pool idle time check must happen more often.
* https://issues.couchbase.com/browse/JVMCBC-894[JVMCBC-894]: 
BatchHelper: handle success case with no body gracefully.
* https://issues.couchbase.com/browse/JVMCBC-872[JVMCBC-872]: 
Subdoc 'no access' error code is now reported correctly.
This helps users to identify and fix permissions errors for system XATTRs.

=== Enhancements
* https://issues.couchbase.com/browse/JCBC-1651[JCBC-1651]: 
Geopolygon search support.
* https://issues.couchbase.com/browse/JCBC-1652[JCBC-1652]: 
Added Options To Use FTS Hints (Flex Index).
* https://issues.couchbase.com/browse/JCBC-1695[JCBC-1695]: 
Added support to pass Score as FTS parameter.
* https://issues.couchbase.com/browse/JCBC-1707[JCBC-1707]: 
Retrofited Geo Search Queries to allow Coordinate Usage.
* https://issues.couchbase.com/browse/JCBC-1709[JCBC-1709]: 
Allow to access ReactiveScope from Scope.
* https://issues.couchbase.com/browse/JCBC-1712[JCBC-1712]: 
Clarified Javadoc lockTime on getAndLock.
* https://issues.couchbase.com/browse/JCBC-1715[JCBC-1715]: 
Allow to provide custom http headers for the `RawManager`.
* https://issues.couchbase.com/browse/JCBC-1717[JCBC-1717]: 
Support for targeting requests to a given node.
This allows to always send QueryRequests related to a given transaction to the same query node.
* https://issues.couchbase.com/browse/JVMCBC-888[JVMCBC-888], 
https://issues.couchbase.com/browse/JVMCBC-893[JVMCBC-893]: 
Dependency bumps: Netty to 4.1.52.Final, OpenTelemetry to 0.8.
* https://issues.couchbase.com/browse/JVMCBC-886[JVMCBC-886]: 
Improve LDAP auth failure handling.
* https://issues.couchbase.com/browse/JVMCBC-896[JVMCBC-896]: 
Fast dispatch pooled requests.


== Version 3.0.8 (31 August 2020)

Version 3.0.8 is a bugfix release of the 3.0 series, bringing enhancements and bugfixes over the last stable release.

https://packages.couchbase.com/clients/java/3.0.8/Couchbase-Java-Client-3.0.8.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.8/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.9/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.8**
* com.couchbase.client:**core-io:2.0.9**
* io.projectreactor:**reactor-core:3.3.9.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Enhancements

* https://issues.couchbase.com/browse/JCBC-1705[JCBC-1705]:
A (uncomitted) API has been added which allows to very efficiently perform bulk fetch and bulk exists operations. See the `BatchHelper` class for more details.
* https://issues.couchbase.com/browse/JCBC-1684[JCBC-1684]:
The `PingOptions` services can now be configured through a vararg, making it easier to use.
* https://issues.couchbase.com/browse/JCBC-1691[JCBC-1691]:
A (uncomitted) API has been added which allows sending all kinds of requests to the cluster manager (called raw manager API).
* https://issues.couchbase.com/browse/JVMCBC-883[JVMCBC-883]:
The client is now a little less verbose when performing a DNS SRV request and the underlying JDK operation times out.
* https://issues.couchbase.com/browse/JVMCBC-879[JVMCBC-879]:
Updated internal and external dependencies to their latest maintenance releases.
* https://issues.couchbase.com/browse/JVMCBC-871[JVMCBC-871]:
On the `IoConfig` it is now possible to `captureTraffic()` with empty arguments, implying that all traffic will be captured.
* https://issues.couchbase.com/browse/JVMCBC-874[JVMCBC-874]:
When dealing with unknown collections, the SDK now returns a more user friendly retry reason when it can (outdated manifest vs. collection not found).
* https://issues.couchbase.com/browse/JVMCBC-875[JVMCBC-875]:
On the request timeout exception, the retry reasons are now accessible directly.
* https://issues.couchbase.com/browse/JCBC-1693[JCBC-1693]:
The `UserManager` API has been extended to support collections and scopes (needs at least Server 7.0 to be usable).
* https://issues.couchbase.com/browse/JCBC-1660[JCBC-1660]:
Support for scope-level N1QL queries has been added (needs at least Server 7.0 to be usable).
* https://issues.couchbase.com/browse/JCBC-1658[JCBC-1658]:
Support for scope-level analytics queries has been added (needs at least Server 7.0 to be usable).

=== Bug Fixes
* https://issues.couchbase.com/browse/JCBC-1696[JCBC-1696]:
When adding the option `withExpiry(true)` to `GetOptions`, it is now possible to use a custom transcoder which is JSON compatible.
* https://issues.couchbase.com/browse/JVMCBC-805[JVMCBC-805]:
The client now handles bootstrapping against nodes much better which do not have the data service enabled (in an MDS setup).
* https://issues.couchbase.com/browse/JVMCBC-882[JVMCBC-882]:
A bug has been fixed where when bootstrapping against a node with no data service enabled, the endpoint would not be cleaned up and would keep trying to reconnect.
* https://issues.couchbase.com/browse/JVMCBC-872[JVMCBC-872]:
The client now more explicitly handles an error response code (`NO_ACCESS`) when a subdocument request is performed against a system xattr.
* https://issues.couchbase.com/browse/JVMCBC-873[JVMCBC-873]:
Durability information is now properly unwrapped from an optional when exported and dumped (for example as part of an exception).
* https://issues.couchbase.com/browse/JVMCBC-880[JVMCBC-880]:
The client now trackes multiple parallel bucket open attempts (against different buckets) in a better way, making sure that an internal state is only switched when all those bucket open attempts have completed (and not just the first one).
* https://issues.couchbase.com/browse/JVMCBC-878[JVMCBC-878]:
`EndpointDiagnostics` had the local and remote hostnames mixed up, they now show up in the correct order.

== Version 3.0.7 (4 August 2020)

Version 3.0.7 is the eighth release of the 3.0 series, bringing enhancements and bugfixes over the last stable release.

https://packages.couchbase.com/clients/java/3.0.7/Couchbase-Java-Client-3.0.7.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.7/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.8/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.7**
* com.couchbase.client:**core-io:2.0.8**
* io.projectreactor:**reactor-core:3.3.8.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.3**

=== API Affecting
* https://issues.couchbase.com/browse/JCBC-1681[JCBC-1681]: 
Removed cas from `IncrementOptions` and `DecrementOptions`.  
CAS is not supported by the underlying protocol and should not have been exposed in these options.
* https://issues.couchbase.com/browse/JCBC-1625[JCBC-1625]: 
Deprecated `maxTTL` on BucketSettings in favor of `maxExpiry`.

=== Bug Fixes
* https://issues.couchbase.com/browse/JCBC-1647[JCBC-1647]: 
Deprecated `EjectionPolicy` in favor of `EvictionPolicyType`.
And added the "noEviction" and "nruEviction" policies used by ephemeral buckets.
This fixed a but where the BucketManager didn't recognize ephemeral bucket ejection values.
Users can now set a non-default ejection policy when creating an ephemeral bucket.
* https://issues.couchbase.com/browse/JCBC-1668[JCBC-1668]: 
Fixes an NPE when `toString` or `fieldsAs` is called when no fields are present in the result. 
In this case just null should now be returned, instead of a NPE deep down in the Jackson serializer stack.
* https://issues.couchbase.com/browse/JVMCBC-870[JVMCBC-870]: 
A bug in the chunk response parser prohibited responses meant that View reduce responses were never completed, and as a result timed out on the user side.
The completion of view results with reduce enabled has now been fixed.

=== Enhancements
* https://issues.couchbase.com/browse/JCBC-1661[JCBC-1661], https://issues.couchbase.com/browse/JCBC-1665[JCBC-1665]: 
Building on the expiry improvements in the previous release, this adds a new `expiryTime()` method that returns expiry as an `Instant`, which better expresses the concept than the `Duration` returned by `expiry()`.  
The latter will be deprecated in a future release.  
Similarly, everywhere a `Duration`-based expiry could be provided previously, an overload has been added to take an `Instant`-based expiry.
* https://issues.couchbase.com/browse/JCBC-1666[JCBC-1666]: 
Made `bucket.scope("_default").collection("_default")` behave just like `bucket.defaultCollection()`.
`AsyncScope.collection()` now no longer refreshes collection map for default collection.
* https://issues.couchbase.com/browse/JCBC-1670[JCBC-1670]: 
Added WaitUntilReadyOptions.serviceTypes() overload that accepts varargs.
* https://issues.couchbase.com/browse/JVMCBC-867[JVMCBC-867]: 
Performance improvement: do not grab ByteBuf slice when extracting server response time.
* https://issues.couchbase.com/browse/JVMCBC-869[JVMCBC-869]: 
Maintenance dependency bump: Netty -> 4.1.51, Jackson -> 2.11.1, Reactor -> 3.3.7, OpenTelemetry -> 0.6.0.

== Version 3.0.6 (14 July 2020)

Version 3.0.6 is the seventh release of the 3.0 series, bringing enhancements and bugfixes over the last stable release.

https://packages.couchbase.com/clients/java/3.0.6/Couchbase-Java-Client-3.0.6.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.6/index.html[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.7/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.6**
* com.couchbase.client:**core-io:2.0.7**
* io.projectreactor:**reactor-core:3.3.5.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Enhancements
* https://issues.couchbase.com/browse/JCBC-1645[JCBC-1645]:
Specifying document expiries has been made significantly easier.
Expiries are supplied as a `Duration`.  
The new behaviour is that if that duration is less than 50 years, then it will be interpreted as being a relative timestamp from the current time.
E.g. `Duration.ofDays(35)` will expire in 35 days time.
(Previously, a `Duration` longer than 30 days would be interpreted as being an epoch time.
Unless this epoch time occurred in the future then it would expire immediately.
In order to preserve compatibility for users that worked around this behaviour, any `Duration` longer than 50 years will continue to be interpreted as an epoch time.)
* https://issues.couchbase.com/browse/JCBC-1632[JCBC-1632]:
Bootstrapping is now fully pipelined for performance, building on the improvements in the previous release.
* https://issues.couchbase.com/browse/JVMCBC-865[JVMCBC-865]:
Changed the default idle timeout to 4.5s for http connections, to support performance improvements in query service.

=== Bug Fixes
* https://issues.couchbase.com/browse/JCBC-1662[JCBC-1662]:
`MutateInMacro` for CRC32 is fixed.
* https://issues.couchbase.com/browse/JCBC-1664[JCBC-1664]:
`viewQuery` with `ViewOptions.viewOptions().keys(keys)` was returning a bad_request error.
This is now fixed.
* https://issues.couchbase.com/browse/JVMCBC-849[JVMCBC-849]:
Redundant global loading exceptions no longer propagated -- now logged at `debug` level.
* https://issues.couchbase.com/browse/JVMCBC-856[JVMCBC-856]:
A just-opened connection in pool no longer gets cleaned up prematurely .
* https://issues.couchbase.com/browse/JVMCBC-858[JVMCBC-858]:
Channel writeAndFlush failures are no longer ignored.
* https://issues.couchbase.com/browse/JVMCBC-862[JVMCBC-862]:
Race condition with node identifier change on bootstrap identified.
New logic and some changes to the config provider code ensures that retry and resubscribe picks up fresh seed nodes.
* https://issues.couchbase.com/browse/JVMCBC-863[JVMCBC-863]:
Bucket-Level ping report no longer includes other view and KV services buckets.
* https://issues.couchbase.com/browse/JVMCBC-866[JVMCBC-866]:
Trailing : no longer added to IPv6 addresses without [].
'invalid IPv6 address' warnings now no longer produced when trying to connect to a valid Ipv6 address thus specified.


== Version 3.0.5 (2 June 2020)

Version 3.0.5 is the sixth release of the 3.0 series, bringing enhancements and bugfixes over the last stable release.

https://packages.couchbase.com/clients/java/3.0.5/Couchbase-Java-Client-3.0.5.zip[Download] |
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.5/[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.6/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.5**
* com.couchbase.client:**core-io:2.0.6**
* io.projectreactor:**reactor-core:3.3.5.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Enhancements

* http://issues.couchbase.com/browse/JVMCBC-852[JVMCBC-852]:
Bumped Reactor to 3.3.5, Netty to 4.1.50.Final, and Jackson to 2.11.0.
* https://issues.couchbase.com/browse/JVMCBC-693[JVMCBC-693]:
For performance, the KV bootstrap sequence is now partially pipelined.

In addition, there are internal revisions to support the forthcoming Field Level Encryption (FLE) support.
This will be available in a separate library for Enterprise Edition subscribers.

=== Bug Fixes

* http://issues.couchbase.com/browse/JVMCBC-851[JVMCBC-851]:
Reactive getAllReplicas methods will now honor a provided custom transcoder.
* http://issues.couchbase.com/browse/JVMCBC-849[JVMCBC-849]:
Duplicate global loading exceptions are now swallowed to remove redundant warnings from logging (this was a cosmetic-only issue).

== Version 3.0.4 (7 May 2020)

Version 3.0.4 is the fifth release of the 3.0 series, bringing enhancements and bugfixes over the last stable release.

https://packages.couchbase.com/clients/java/3.0.4/Couchbase-Java-Client-3.0.4.zip[Download] |
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.4/[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.5/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.4**
* com.couchbase.client:**core-io:2.0.5**
* io.projectreactor:**reactor-core:3.3.4.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.3**

=== Enhancements

* http://issues.couchbase.com/browse/JVMCBC-841[JVMCBC-841]:
Bumped Netty dependency to 2.0.30, and reactor to 3.3.4

=== Bug Fixes

* http://issues.couchbase.com/browse/JVMCBC-845[JVMCBC-845]:
If a rebalance is stopped in the middle, an edge case occasionally causes KV ops to time out as the fast forward map is chosen over the retry.
The behavior has now been changed so that the client will try the old and new servers to make sure the operation eventually gets dispatched to the right node.
* http://issues.couchbase.com/browse/JCBC-1626[JCBC-1626]:
If bucket is not flushable, a `BucketNotFlushableException` is now raised.

== Version 3.0.3 (7 April 2020)

Version 3.0.3 is the fourth release of the 3.0 series, bringing enhancements and bugfixes over the last stable release.

https://packages.couchbase.com/clients/java/3.0.3/Couchbase-Java-Client-3.0.3.zip[Download] |
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.3/[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.4/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.3**
* com.couchbase.client:**core-io:2.0.4**
* io.projectreactor:**reactor-core:3.3.3.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.2**

=== Enhancements

* http://issues.couchbase.com/browse/JCBC-1603[JCBC-1603], http://issues.couchbase.com/browse/JCBC-1606[JCBC-1606]:
Exposed API to set the CollectionsExample TTL.
CreateCollection CollectionSpec now includes `MaxTTL`.
* http://issues.couchbase.com/browse/JCBC-1617[JCBC-1617]:
Attempting to work with the collection manager on clusters where CollectionsExample are not available (or enabled as a DP) will now result in a `FeatureNotAvailable` failure.
* http://issues.couchbase.com/browse/JVMCBC-830[JVMCBC-830]:
Added more convenient overloads for SecurityConfig and CertAuth.
These overloads initialize both the SecurityConfig and the CertificateAuthenticator directly from a KeyStore or TrustStore.
* http://issues.couchbase.com/browse/JVMCBC-831[JVMCBC-831]:
Improves timeout for waitUntilReady -- the `waitUntilReady` helper should now throw a proper timeout exception.
* http://issues.couchbase.com/browse/JVMCBC-832[JVMCBC-832]:
Added support for multiple ports per hostname in the connection string -- without having to use the explicit SeedNode set overload.
* http://issues.couchbase.com/browse/JVMCBC-835[JVMCBC-835]:
Using "localhost:8091" as a connection string would set the kv bootstrap port to 8091, which is not desired behavior.
To prevent this from happening again, the code now checks for this condition, fails fast, and also provides guidance on what the connection string should look like instead.
* http://issues.couchbase.com/browse/JVMCBC-836[JVMCBC-836]:
Enabled Unordered Execution by Default.
* http://issues.couchbase.com/browse/JVMCBC-837[JVMCBC-837]:
Updates OpenTelemetry to 0.3 (beta).

=== Bug Fixes

* http://issues.couchbase.com/browse/JCBC-1618[JCBC-1618]:
Named fields in SearchRows results are now deserialized.
* http://issues.couchbase.com/browse/JVMCBC-834[JVMCBC-834]:
'CollectionNotFoundException' now triggers a retry, and if no collection refresh is currently in progress it will proactively trigger a new one.
Now Docs created under custom collection should no longer raise an exception when a collection has been created in the meantime, but the collection is not found as no refresh is in progress.
* http://issues.couchbase.com/browse/JVMCBC-826[JVMCBC-826]:
A NullPointerException was occuring when LDAP is enabled.
The code now explicitly fails the connection with a descriptive error message instructing the user what to do next (either use TLS which is preferred) or enable PLAIN on the password authenticator (insecure).
* http://issues.couchbase.com/browse/JVMCBC-827[JVMCBC-827]:
Search query results row_hit typo resulted in 0 being returned for total rows. 
This has now been fixed. 
* http://issues.couchbase.com/browse/JVMCBC-828[JVMCBC-828]:
Omit internal config request in orphan reporting.
* http://issues.couchbase.com/browse/JVMCBC-839[JVMCBC-839]:
Bootstrap will now correctly use the mapped port if alternate addr is present.


== Version 3.0.2 (3 March 2020)

Version 3.0.2 is the third release of the 3.0 series, bringing  enhancements and bugfixes over the last stable release.

https://packages.couchbase.com/clients/java/3.0.2/Couchbase-Java-Client-3.0.2.zip[Download] |
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.2/[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.3/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.2**
* com.couchbase.client:**core-io:2.0.3**
* io.projectreactor:**reactor-core:3.3.1.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.2**

=== Enhancements

* http://issues.couchbase.com/browse/JCBC-1588[JCBC-1588]:
Give TypeRef overload of JsonSerializer a default "unsupported" impl, making it easier for applications to implement custom JsonSerializers.
* http://issues.couchbase.com/browse/JVMCBC-813[JVMCBC-813]:
Improved error message for bucket is missing.
* http://issues.couchbase.com/browse/JVMCBC-815[JVMCBC-815]:
Check if key exceeds size limits.
* http://issues.couchbase.com/browse/JVMCBC-818[JVMCBC-818]:
Trimmed netty stack in connect failures for more readable output.
* http://issues.couchbase.com/browse/JVMCBC-819[JVMCBC-819]:
Distinguished bucket not found in select bucket failures.
* http://issues.couchbase.com/browse/JVMCBC-823[JVMCBC-823]:
Added a global component to the core id.
* http://issues.couchbase.com/browse/JVMCBC-825[JVMCBC-825]:
Support added for new VATTR HELLO flag.

=== Bug Fixes

* http://issues.couchbase.com/browse/JCBC-1587[JCBC-1587]:
Exists no longer returns wrong value if executed right after remove.
* http://issues.couchbase.com/browse/JCBC-1600[JCBC-1600]:
Using expiry together with document flags on a Sub-Document `mutateIn` no longer causes an incorrect flags field to be sent.
* http://issues.couchbase.com/browse/JCBC-1604[JCBC-1604]:
Properly clear cache when repreparing/retrying query.
* http://issues.couchbase.com/browse/JVMCBC-824[JVMCBC-824]:
Native Netty transports not included, resulting in fallback to default implementation.  Only affected 2.0.2 core release.

== Version 3.0.1 (5 February 2020)

Version 3.0.1 is the second release of the 3.0 series, bringing  enhancements and bugfixes over the last stable release.

https://packages.couchbase.com/clients/java/3.0.1/Couchbase-Java-Client-3.0.1.zip[Download] |
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.1/[API Reference] |
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.2/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.1**
* com.couchbase.client:**core-io:2.0.2**
* io.projectreactor:**reactor-core:3.3.1.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.2**

=== Enhancements

* http://issues.couchbase.com/browse/JCBC-1578[JCBC-1578]:
Added support for Java Object Serialization as a custom `Transcoder`.
* http://issues.couchbase.com/browse/JVMCBC-808[JVMCBC-808]:
The internal packaged `netty` dependency has been reduced to the minimum amount of artifacts needed, trimming the resulting jar size a little.

=== Bug Fixes

* http://issues.couchbase.com/browse/JCBC-1574[JCBC-1574]:
`JsonObject/Array.put(String,Object)` now supports writing generic Maps and Lists.
* http://issues.couchbase.com/browse/JCBC-1580[JCBC-1580]:
The code for get projections had an import for unbundled jackson which prevented it from working in an environment where no unbundled jackson is on the classpath.
This no longer occurs.
* http://issues.couchbase.com/browse/JCBC-1582[JCBC-1582]:
The client context ID is now propagated into the `PREPARE` query if needed.
* http://issues.couchbase.com/browse/JVMCBC-806[JVMCBC-806]:
TLS: remote hostname and port are passed down to the SSL engine, making sure that hostname validation works as expected.
* http://issues.couchbase.com/browse/JCBC-1575[JCBC-1575]:
Bucket Management: BucketSettings load does now recognize numReplicas properly.

=== Known Issues

* http://issues.couchbase.com/browse/JVMCBC-805[JVMCBC-805]:
When bootstrapping against a non-KV node the KV socket is not cleaned up properly. 
As a workaround (and as we recommend in general), please only bootstrap against nodes which have the KV service enabled.
Or maintain a list of KV nodes in xref:howtos:managing-connections.adoc#using-dns-srv-records[DNS SRV].

== Version 3.0.0 (10 January 2020)

This is the first GA release of the third generation Java SDK.

https://packages.couchbase.com/clients/java/3.0.0/Couchbase-Java-Client-3.0.0.zip[Download] |
http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.0/[API Reference] | 
http://docs.couchbase.com/sdk-api/couchbase-core-io-2.0.0/[Core API Reference]

The supported and tested dependencies for this release are:

* com.couchbase.client:**java-client:3.0.0**
* com.couchbase.client:**core-io:2.0.0**
* io.projectreactor:**reactor-core:3.3.1.RELEASE**
* org.reactivestreams:**reactive-streams:1.0.2**

=== Enhancements

The following list describes the API changes between 3.0.0 beta.2 and 3.0.0 GA.

* http://issues.couchbase.com/browse/JCBC-1563[JCBC-1563]:
Added the reactive API to the view index manager.
* http://issues.couchbase.com/browse/JVMCBC-776[JVMCBC-776]:
Added support for server-side KV tracing statistics.
* http://issues.couchbase.com/browse/JCBC-1522[JCBC-1522]:
All data commands have been instrumented to be included in RTO (Response Time Observability).
* http://issues.couchbase.com/browse/JCBC-1566[JCBC-1566], http://issues.couchbase.com/browse/JCBC-1568[JCBC-1568]:
The Search API has been slightly improved to align with the SDK RFC.
* http://issues.couchbase.com/browse/JCBC-1599[JCBC-1599]:
Bucket, Scope and Collection instances are now cached so repeated open attempts produce less garbage and happen quicker.
* http://issues.couchbase.com/browse/JVMCBC-785[JVMCBC-785], http://issues.couchbase.com/browse/JVMCBC-786[JVMCBC-786], http://issues.couchbase.com/browse/JVMCBC-675[JVMCBC-675]:
View, Search, Analytics, and Query retryable error codes are now retried as part of the configured retry strategy.
* http://issues.couchbase.com/browse/JCBC-1561[JCBC-1561], http://issues.couchbase.com/browse/JCBC-1562[JCBC-1562]:
Added Option overloads to collection and search index managers.
* http://issues.couchbase.com/browse/JVMCBC-787[JVMCBC-787], http://issues.couchbase.com/browse/JVMCBC-788[JVMCBC-788]:
View requests and KV collection requests are now short-circuited against unsupported clusters.
* http://issues.couchbase.com/browse/JCBC-1552[JCBC-1552]:
Added support for Java 9 automatic module names.

* http://issues.couchbase.com/browse/JCBC-1554[JCBC-1554]:
`JsonArry` and `JsonObject` now support `toArray` in addition to `toString`.
* http://issues.couchbase.com/browse/JCBC-1545[JCBC-1545]:
The `ping` command has been reintroduced to the cluster and bucket level APIs.
* http://issues.couchbase.com/browse/JCBC-1518[JCBC-1518]:
An internal server error from the KV engine is now properly mapped to the exception equivalent.
* http://issues.couchbase.com/browse/JVMCBC-779[JVMCBC-779]:
It is now possible to customize the event loop thread count instead of having to provide a new event loop itself.
* http://issues.couchbase.com/browse/JVMCBC-767[JVMCBC-767]:
A new `ConfigIdleRedialTimeout` has been introduced which recycles idle HTTP streaming connections.
* http://issues.couchbase.com/browse/JVMCBC-782[JVMCBC-782]:
The orphan response reporter (as part of RTO) has been ported to SDK 3 from SDK 2 and is now enabled by default.
* http://issues.couchbase.com/browse/JVMCBC-784[JVMCBC-784]:
Idle HTTP connections are now closed after 30 seconds.
* http://issues.couchbase.com/browse/JVMCBC-773[JVMCBC-773]:
SASL PLAIN is now not negotiated by default on non-TLS connections to prevent downgrade attacks out of the box.
* http://issues.couchbase.com/browse/JVMCBC-795[JVMCBC-795]:
Requests are now failed fast if it can be determined that the service is not available on the cluster.
* http://issues.couchbase.com/browse/JVMCBC-790[JVMCBC-790]:
The concept of backpressure has been re-introduced but in slightly different form.
* http://issues.couchbase.com/browse/JVMCBC-[JVMCBC-]:
The circuit breaker now has a customizable completion callback.

=== Bug Fixes

The following list describes the API changes between 3.0.0 beta.2 and 3.0.0 GA.

* http://issues.couchbase.com/browse/JCBC-1550[JCBC-1550]:
The owned environment in the `Cluster` is now properly shutdown on disconnect.
* http://issues.couchbase.com/browse/JCBC-1517[JCBC-1517], http://issues.couchbase.com/browse/JCBC-1566[JCBC-1566]:
All reactive APIs are now deferred and will not execute I/O side effects when not subscribed to.
* http://issues.couchbase.com/browse/JCBC-1539[JCBC-1539]:
A bug has been fixed where the IoConfig.networkResolution could not be set through a system property.
* http://issues.couchbase.com/browse/JVMCBC-793[JVMCBC-793]:
Various fixes have been made around DNS SRV bootstrapping that make it more robust, including fixing a bug that prevented it from working properly.
* http://issues.couchbase.com/browse/JCBC-1524[JCBC-1524]:
The projections on `get` have been refactored, the test suite expanded, and a couple of issues fixed along the way.
* http://issues.couchbase.com/browse/JCBC-1531[JCBC-1531]:
The QueryIndexManager now only returns GSI indexes.
* http://issues.couchbase.com/browse/JVMCBC-802[JVMCBC-802]:
A bug has been fixed where a non-existing view in an existing design document would not cause an exception.
* http://issues.couchbase.com/browse/JCBC-1565[JCBC-1565]:
Views now use the right default View timeout instead of the Analytics one.
* http://issues.couchbase.com/browse/JVMCBC-789[JVMCBC-789]:
Performing operations while initially loading the collection map is now handled gracefully.

=== Known Issues

* http://issues.couchbase.com/browse/JVMCBC-805[JVMCBC-805]:
When bootstrapping against a non-KV node the KV socket is not cleaned up properly. As a workaround (an we recommend in general) please
only bootstrap against nodes which have the KV service enabled.

=== API Changes

The following list describes the API changes between 3.0.0 beta.2 and 3.0.0 GA. 
Since SDK 3 is a complete rewrite over SDK 2, the individual changes between them are not listed here. 
Please refer to the xref:project-docs:migrating-sdk-code-to-3.n.adoc[migration guide] for this.

* http://issues.couchbase.com/browse/JCBC-1533[JCBC-1533], http://issues.couchbase.com/browse/JCBC-1534[JCBC-1534], http://issues.couchbase.com/browse/JCBC-1535[JCBC-1535], http://issues.couchbase.com/browse/JCBC-1541[JCBC-1541], http://issues.couchbase.com/browse/JCBC-1542[JCBC-1542]:
Exceptions have been consolidated, renamed, and overall aligned with the latest RFC.
* http://issues.couchbase.com/browse/JCBC-1536[JCBC-1536]:
`SeedNodes` have been moved out of the `ClusterOptions` into a `Cluster#connect()` overload.
* http://issues.couchbase.com/browse/JCBC-1540[JCBC-1540]:
`MajorityAndPersistOnMaster` has been renamed to `MajorityAndPersistToActive` on the durability enum.
* http://issues.couchbase.com/browse/JCBC-1545[JCBC-1545]:
The diagnostics API has been reworked on all levels.
* http://issues.couchbase.com/browse/JCBC-1551[JCBC-1551]:
The `empty` constructors are gone from `JsonObject` and `JsonArray` since they duplicate `create`.


== Pre-releases

Numerous _Alpha_ and _Beta_ releases were made in the run-up to the 3.0 release, and although unsupported, the release notes and download links are retained for archive purposes xref:3.0-pre-release-notes.adoc[here].


== Older Releases

Although https://www.couchbase.com/support-policy/enterprise-software[no longer supported], documentation for older releases continues to be available in our https://docs-archive.couchbase.com/home/index.html[docs archive].
// end::all[]
