= Data Structures Reference
:description: You can use complex data structures such as dictionaries and lists in Couchbase.
:page-aliases: 

[abstract]
{description}

Data structures in Couchbase are similar in concept to data structures in the Java Collections Framework:

See our xref:concept-docs:data-model.adoc[Data Model pages].

Here is a list of common operations:

.Data Structure Operations
[cols="25,94"]
|===
| |

| [.api]`mapAdd`
a|
Add a key to the map.

[source,java]
----
include::example$DataStructuresExample.java[tag=data_structures_1,indent=0]
----

| [.api]`mapRemove`
a|
Remove a key from a map.

[source,java]
----
include::example$DataStructuresExample.java[tag=data_structures_2,indent=0]
----

| [.api]`mapGet`
a|
Get an item from a map.

[source,java]
----
include::example$DataStructuresExample.java[tag=data_structures_3,indent=0]
----

If the key is not found, a [.api]`PathNotFoundException` is raised.

| [.api]`listAppend`
a|
Add an item to the _end_ of a list.

[source,java]
----
include::example$DataStructuresExample.java[tag=data_structures_4,indent=0]
----

| [.api]`listPrepend`
a|
Add an item to the _beginning_ of a list.

[source,java]
----
include::example$DataStructuresExample.java[tag=data_structures_5,indent=0]
----

| [.api]`listRemove`
a|
Remove a value from a list.

[source,java]
----
include::example$DataStructuresExample.java[tag=data_structures_6,indent=0]
----

| [.api]`listSet`
a|
Set an element at a specific index in the list.

[source,java]
----
include::example$DataStructuresExample.java[tag=data_structures_7,indent=0]
----

| [.api]`listGet`
a|
Get an item from a list by its index.

[source,java]
----
include::example$DataStructuresExample.java[tag=data_structures_8,indent=0]
----

If the index is out of range, a [.api]`PathNotFoundException` will be thrown.
Note that you can get the _last_ array element by specifying `-1` as the index.

| [.api]`setAdd`
a|
Add an item to a set, if the item does not yet exist in the set.

[source,java]
----
include::example$DataStructuresExample.java[tag=data_structures_9,indent=0]
----

Note that a _set_ is just a list.
You can retrieve the entire set by simply using a full-document [.api]`get` operation:

[source,java]
----
include::example$DataStructuresExample.java[tag=data_structures_10,indent=0]
----

NOTE: Currently, you can only store primitive values in sets, such as strings, ints, and booleans.

| [.api]`setContains`
a|
Check if a value exists in the set.

[source,java]
----
include::example$DataStructuresExample.java[tag=data_structures_11,indent=0]
----

| [.api]`setRemove`
a|
Remove an item from a set, if it exists.
An exception is not thrown if the item does not exist.
You can determine if an item existed or not by the return value.
If the item did not exist beforehand, `null` is returned.

[source,java]
----
include::example$DataStructuresExample.java[tag=data_structures_12,indent=0]
----

| [.api]`queuePush`
a|
Add an item to the beginning of the queue.

[source,java]
----
include::example$DataStructuresExample.java[tag=data_structures_13,indent=0]
----

Note that a queue is just a list.
You can retrieve items from the middle of the queue by using [.api]`listGet`

| [.api]`queuePop`
a|
Remove an item from the end of the queue and return it.

[source,java]
----
include::example$DataStructuresExample.java[tag=data_structures_14,indent=0]
----

If the queue is empty, then [.api]`null` is returned.

| [.api]`mapSize`, [.api]`listSize`, [.api]`setSize`, [.api]`queueSize`
a|
These methods get the length of the data structure.
For maps, this is the number of key-value pairs inside the map.
For lists, queues, and sets, this is the number of elements in the structure.

[source,java]
----
include::example$DataStructuresExample.java[tag=data_structures_15,indent=0]
----
|===

Note that there are only *two* basic types: map and list.
Types such as _queue_ and _set_ are merely derivatives of _list_.

== Data Structures and Key-Value APIs

Data structures can be accessed using key-value APIs as well.
In fact, the data structure API is actually a client-side wrapper _around_ the key-value and sub-document API.
Most of the data structure APIs wrap the sub-document API directly.

NOTE: Because the data structure API is just a wrapper around the various key-value APIs, you are free to switch between them in your code.

[#jcf]
== Collections Framework Integration

In addition to the [.api]`Bucket` level methods for working with data structures, the Java SDK provides implementations of the [.api]`Map`, [.api]`List`, [.api]`Set`, and [.api]`Queue` interfaces from the Java Collections Framework.
Instead of maintaining in-memory storage, these implementations are backed by JSON documents stored in Couchbase Server.
The implementations are thread-safe and suitable for concurrent use.
The [.api]`Map`, [.api]`List`, and [.api]`Queue` implementations may contain values of the following types:

* String
* Integer
* Long
* Double
* Boolean
* BigInteger
* BigDecimal
* JsonObject
* JsonArray

The [.api]`Set` implementation may contain values of all of the above types except [.api]`JsonObject` and [.api]`JsonArray`.

== CouchbaseMap

The CouchbaseMap<V> class implements Map<String, V>.
It allows null values, but does not allow null keys.

Example usage:

[source,java]
----
include::example$DataStructuresExample.java[tag=data_structures_16,indent=0]
----

== CouchbaseArrayList

The CouchbaseArrayList<V> class implements List<V>.
It allows null values.

Example usage:

[source,java]
----
include::example$DataStructuresExample.java[tag=data_structures_17,indent=0]
----

== CouchbaseArraySet

The CouchbaseArraySet<V> class implements Set<V>.
It allows null values.

Example usage:

[source,java]
----
include::example$DataStructuresExample.java[tag=data_structures_18,indent=0]
----

== CouchbaseQueue

The CouchbaseQueue<V> class implements Queue<V>.
It does not allow null values.

Example usage:

[source,java]
----
include::example$DataStructuresExample.java[tag=data_structures_19,indent=0]
----

