= Buckets and Clusters
:navtitle: Buckets & Clusters
:page-topic-type: concept
:page-aliases: managing-clusters

[abstract]
The Couchbase Java SDK provides an API for managing a Couchbase cluster programmatically.

The primary means for managing clusters is through the Couchbase Web UI which provides an easy to use interface for adding, removing, monitoring and modifying buckets. 
In some instances you may wish to have a programmatic interface. 
For example, if you wish to manage a cluster from a setup script, or if you are setting up buckets in test scaffolding.

The Java SDK also comes with some convenience functionality for common Couchbase management requests.
Management operations in the Java SDK may be performed through several interfaces depending on the object.


== Creating and Removing Buckets

To create or delete a bucket, call the bucket manager with the `buckets()` call on the cluster:

[source,java]
----
Cluster cluster = Cluster.connect("127.0.0.1", "Administrator", "123456");
BucketManager manager = cluster.buckets();
manager.createBucket(bucketSettings);
----

// The `BucketSettings` can be created via a builder, [.api]`DefaultBucketSettings.builder()`.
This class is also used to expose information about an existing bucket (`manager.getBucket(string)`) or to update an existing bucket (`manager.updateBucket(bucketSettings)`). 

The default Collection & Default Scope will be used automatically.


include::6.5@sdk:shared:partial$flush-info-pars.adoc[tag=update-bucket-warning]

////
Only `name` and `type` parameters are mandatory for the `BucketSettings`.
Here is the list of parameters available:

* `name`: The name of the bucket (mandatory to create one, cannot be updated).
* `type`: The type of the bucket (mandatory to create one, cannot be changed).
Defaults to `BucketType.COUCHBASE`, but can also be `BucketType.MEMCACHED` to create a cache bucket.
* `quota`: How much memory should each node use for the bucket.
This number is specified in megabytes.
* `password`: If specified, makes this bucket password protected, forcing future connects (using the [.api]`Bucket`) class to specify the `password` parameter.
* `enableFlush`: Enables the [.api]`BucketManager#flush()` operation to be performed on this bucket (see the <<flushing>> section below).
* `replicas`: The number of replicas to use for the bucket.
* `indexReplicas`: Wether or not to replicate indexes.
* `port`: The optional proxy port.
////


////
The following example updates an existing "hello" bucket (notice how all parameters are set):

----
BucketSettings bucketSettings = new DefaultBucketSettings.Builder()
    .type(BucketType.COUCHBASE)
    .name("hello")
    .password("")
    .quota(120) // megabytes
    .replicas(1)
    .indexReplicas(true)
    .enableFlush(true)
    .build();

manager.updateBucket(bucketSettings);
----

Once you no longer need to use the bucket, you may delete the bucket using the [.api]`ClusterManager#removeBucket(string)` method:

----
clusterManager.removeBucket("new_bucket");
----
////

////
[#flushing]
== Flushing Buckets

include::6.0@sdk:shared:partial$flush-info-pars.adoc[tag=flush-intro]

You may flush a bucket in the Java SDK by using the [.api]`BucketManager#flush()` method:

----
bucket.bucketManager().flush()
----

The [.api]`flush` operation may fail if the bucket does not have flush enabled:

....
com.couchbase.client.java.error.FlushDisabledException: Flush is disabled for this bucket.
    at com.couchbase.client.java.bucket.BucketFlusher$6.call(BucketFlusher.java:145)
    at com.couchbase.client.java.bucket.BucketFlusher$6.call(BucketFlusher.java:140)
    ...
....
////