= Documents
:description: Couchbase supports CRUD operations, various data structures, and binary documents.
:nav-title: Documents & Doc Ops
:page-topic-type: concept
// :page-aliases: ROOT:documents.adoc,ROOT:documents-basics.adoc,ROOT:documents-atomic.adoc,ROOT:core-operations.adoc,7.6@server:developer-guide:expiry.adoc,7.6@server:developer-guide:creating-documents.adoc


include::project-docs:partial$attributes.adoc[]

[abstract]
{description}

Although query and path-based (Sub-Document) services are available, the simplicity of the document-based key-value (kv) interface is the fastest way to perform operations involving single documents.


// use the simplicity of https://developer.couchbase.com/documentation/server/3.x/developer/dev-guide-3.0/read-write.html possibly?
// don't forget https://docs-staging.couchbase.com/dotnet-sdk/2.7/datastructures.html - and Java equiv?

////
== Documents

== Input and Output Types

== Counters

== Data Structures

== Raw Byte Concatenation
////





include::{version-common}@sdk:shared:partial$documents.adoc[tag=document]

== Primitive Key-Value Operations

[source,java]
----
upsert(String docid, Object document)
insert(String docid, Object document)
replace(String docid, Object document)
get(String docid)
remove(String docid)
----

include::{version-common}@sdk:shared:partial$documents.adoc[tag=crud-overview]

include::{version-common}@sdk:shared:partial$documents.adoc[tag=store-update]

[NOTE]
====
If you wish to only modify certain parts of a document, you can use xref:subdocument-operations.adoc[sub-document] operations which operate on specific subsets of documents:

[source,java,indent=0]
----
include::example$DocumentsExample.java[tag=mutate-in]
----

or xref:7.1@server:n1ql:n1ql-language-reference/update.adoc[N1QL UPDATE] to update documents based on specific query criteria:

[source,sql]
----
update `travel-sample`.inventory.airline SET sale_price = msrp * 0.75 WHERE msrp < 19.95;
----
====

include::{version-common}@sdk:shared:partial$documents.adoc[tag=get_generic]

[source,sql]
----
SELECT * FROM `travel-sample`.inventory.airport USE KEYS ["airport_1254"];
----

or

[source,sql]
----
SELECT * FROM `travel-sample`.inventory.airport WHERE META().id = "airport_1254";
----

You can also retrieve _parts_ of documents using xref:subdocument-operations.adoc[sub-document operations], by specifying one or more sections of the document to be retrieved

[source,java,indent=0]
----
include::example$DocumentsExample.java[tag=lookup-in]
----

// Counters

include::{version-common}@sdk:shared:partial$documents.adoc[tag=counters1]

[source,java,indent=0]
----
include::example$DocumentsExample.java[tag=counters]
----

You can simplify by importing `decrementOptions()` statically:

[source,java]
----
collection.binary().decrement(counterDocId, decrementOptions().delta(5));   
----

include::{version-common}@sdk:shared:partial$documents.adoc[tag=counters2]

[source,java,indent=0]
----
include::example$DocumentsExample.java[tag=counter-increment]
----

include::{version-common}@sdk:shared:partial$documents.adoc[tag=counters3]


=== Use Cases

The SDK provides a high-level abstraction over the simple `incr()`/`decr()` of Couchbase Server's memcached binary protocol, using `collections.binary()`. 
This enables you to work with counters using `get()` and `upsert()` operations -- allowing, _inter alia_, the use of durability options with the operations.
You will find several ways of working with counters https://docs.couchbase.com/sdk-api/couchbase-java-client/com/couchbase/client/java/kv/CounterAccessor.html#increment(com.couchbase.client.core.Core,com.couchbase.client.core.msg.kv.IncrementRequest,java.lang.String,com.couchbase.client.java.kv.PersistTo,com.couchbase.client.java.kv.ReplicateTo)(java.lang.String,long)[in the API docs].


// Expiry
include::{version-common}@sdk:shared:partial$documents.adoc[tag=expiration]


////
include::{version-common}@sdk:shared:partial$documents.adoc[tag=]


include::{version-common}@sdk:shared:partial$documents.adoc[tag=]

include::{version-common}@sdk:shared:partial$documents.adoc[tag=]

include::{version-common}@sdk:shared:partial$documents.adoc[tag=]

include::{version-common}@sdk:shared:partial$documents.adoc[tag=]

include::{version-common}@sdk:shared:partial$documents.adoc[tag=]

include::{version-common}@sdk:shared:partial$documents.adoc[tag=]
////
