= Document 
:nav-title: Documents & Doc Ops
:page-topic-type: concept
//:page-aliases: ROOT:core-operations.adoc
:page-aliases: ROOT:documents.adoc,ROOT:documents-basics.adoc,ROOT:documents-atomic.adoc

[abstract]
Couchbase supports CRUD operations, various data structures, and binary documents.

Although query and path-based (Sub-Document) services are available, the simplicity of the document-based key-value (kv) interface is the fastest way to perform operations involving single documents.


// use the simplicity of https://developer.couchbase.com/documentation/server/3.x/developer/dev-guide-3.0/read-write.html possibly?
// don't forget https://docs-staging.couchbase.com/dotnet-sdk/2.7/datastructures.html - and Java equiv?

////
== Documents

== Input and Output Types

== Counters

== Data Structures

== Raw Byte Concatenation
////





include::6.5@sdk:shared:partial$documents.adoc[tag=document]

== Primitive Key-Value Operations

[source,python]
----
upsert(docid, document)
insert(docid, document)
replace(docid, document)
get(docid)
remove(docid)
----

include::6.5@sdk:shared:partial$documents.adoc[tag=crud-overview]

include::6.5@sdk:shared:partial$documents.adoc[tag=store-update]

[NOTE]
====
If you wish to only modify certain parts of a document, you can use xref:subdocument-operations.adoc[sub-document] operations which operate on specific subsets of documents:

[source,python]
----
collection.mutate_in("customer123", [SD.upsert("fax", "311-555-0151")])
----

or xref:6.0@server:n1ql:n1ql-language-reference/update.adoc[N1QL UPDATE] to update documents based on specific query criteria:

[source,sql]
----
update `default` SET sale_price = msrp * 0.75 WHERE msrp < 19.95;
----
====

include::6.5@sdk:shared:partial$documents.adoc[tag=get_generic]

[source,sql]
----
SELECT * FROM default USE KEYS ["docid"];
----

or

[source,sql]
----
SELECT * FROM default WHERE META(default).id = "docid";
----

You can also retrieve _parts_ of documents using xref:subdocument-operations.adoc[sub-document operations], by specifying one or more sections of the document to be retrieved

[source,python]
----
name, email = cb.retrieve_in('user:kingarthur', 'contact.name', 'contact.email')
----

// Counters

include::6.5@sdk:shared:partial$documents.adoc[tag=counters1]

[source,java]
----
String counterDocId = "counter-doc";
// Increment by 1, creating doc if needed
collection.binary().increment(counterDocId);
// Decrement by 1
collection.binary().decrement(counterDocId);
// Decrement by 5
collection.binary().decrement(counterDocId,
DecrementOptions.decrementOptions().delta(5));
----

You can simplify by importing `decrementOptions()` statically:

[source,java]
----
collection.binary().decrement(counterDocId, decrementOptions().delta(5));   
----

include::6.5@sdk:shared:partial$documents.adoc[tag=counters2]

[source,python]
----
# Python example:
rv = cb.get('counter_id')
value, cas = rv.value, rv.cas
if should_increment_value(value):
  cb.upsert('counter_id', value + increment_amount, cas=cas)
----

include::6.5@sdk:shared:partial$documents.adoc[tag=counters3]


=== Use Cases

The SDK provides a high-level abstraction over the simple `incr()`/`decr()` of Couchbase Server's memcached binary protocol, using `collections.binary()`. 
This enables you to work with counters using `get()` and `upsert()` operations -- allowing, _inter alia_, the use of durability options with the operations.
You will find several ways of working with counters https://docs.couchbase.com/sdk-api/couchbase-java-client/com/couchbase/client/java/kv/CounterAccessor.html#increment(com.couchbase.client.core.Core,com.couchbase.client.core.msg.kv.IncrementRequest,java.lang.String,com.couchbase.client.java.kv.PersistTo,com.couchbase.client.java.kv.ReplicateTo)(java.lang.String,long)[in the API docs].


// Expiry
include::6.5@sdk:shared:partial$documents.adoc[tag=expiration]


////
include::6.5@sdk:shared:partial$documents.adoc[tag=]


include::6.5@sdk:shared:partial$documents.adoc[tag=]

include::6.5@sdk:shared:partial$documents.adoc[tag=]

include::6.5@sdk:shared:partial$documents.adoc[tag=]

include::6.5@sdk:shared:partial$documents.adoc[tag=]

include::6.5@sdk:shared:partial$documents.adoc[tag=]

include::6.5@sdk:shared:partial$documents.adoc[tag=]
////
