= Querying with N1QL
:nav-title: Querying with N1QL
:page-topic-type: concept
:page-aliases: ROOT:n1ql-query,ROOT:prepared-statements,ROOT:querying

[abstract]
Parallel data management for complex queries over many records, using a familiar SQL-like syntax.


include::6.5@sdk:shared:partial$n1ql-queries.adoc[tag=intro]


// Prepared Statements for Query Optimization
include::6.5@sdk:shared:partial$n1ql-queries.adoc[tag=prepared]

The maximum client-side query cache size is 5000 entries.

[source,java]
----
QueryResult result = cluster.query(
        "select count(*) from `travel-sample` where type = \"airports\" and country = ?",
        queryOptions().adhoc(false).parameters(JsonArray.from("France"))
);
----


== Indexes

The Couchbase query service makes use of xref:6.5@server:learn:services-and-indexes/indexes/indexes.adoc[_indexes_] in order to do its work.
Indexes replicate subsets of documents from data nodes over to index nodes, 
allowing specific data (for example, specific document properties) to be retrieved quickly, 
and to distribute load away from data nodes in xref:6.5@server:learn:services-and-indexes/services/services.adoc[MDS] topologies.

[IMPORTANT]
In order to make a bucket queryable, it must have at least one index defined.

You can define a _primary index_ on a bucket.
When a _primary_ index is defined you can issue non-covered (see below) queries on the bucket as well.
This includes using the `META` function in the queries.

[source,n1ql]
----
CREATE PRIMARY INDEX ON `users`
----

You can also define indexes over given document fields and then use those fields in the query:

[source,n1ql]
----
CREATE INDEX ix_name ON `users`(name);
CREATE INDEX ix_email ON `users`(email);
----

This would allow you to query the _users_ bucket regarding a document's `name` or `email` properties, thus:

[source,n1ql]
----
SELECT name, email FROM `users` WHERE name="Monty Python" OR email="monty@python.org";
----

Indexes help improve the performance of a query.
When an index includes the actual values of all the fields specified in the query, 
the index _covers_ the query, and eliminates the need to fetch the actual values from the Data Service.
An index, in this case, is called a _covering index_, and the query is called a _covered_ query.
For more information, see xref:6.5@server:n1ql:n1ql-language-reference/covering-indexes.adoc[Covering Indexes].

You can also create and define indexes in the SDK using:

[source,java]
----
QueryIndexManager indexManager = cluster.queryIndexes();

indexManager.createPrimaryIndex("users");
indexManager.createIndex("users", "ix_name", Collections.singletonList("name"));
indexManager.createIndex("users", "ix_email", Collections.singletonList("email"));
----


== Index Building

Creating indexes on buckets with many existing documents can take a long time.
You can build indexes in the background, creating _deferred_ indexes.
The deferred indexes can be built together, rather than having to re-scan the entire bucket for each index.

[source,sql]
----
CREATE PRIMARY INDEX ON `users` WITH {"defer_build": true};
CREATE INDEX ix_name ON `users`(name) WITH {"defer_build": true};
CREATE INDEX ix_email ON `users`(email) WITH {"defer_build": true};
BUILD INDEX ON `users`(`#primary`, `ix_name`, `ix_email`);
----

The indexes are not built until the `BUILD INDEX` statement is executed.
At this point, the server scans all of the documents in the `users` bucket, 
and indexes it for all of the applicable indexes (in this case, those that have a `name` or `email` field).

Building deferred indexes can also be done via the SDK:

[source,java]
----
QueryIndexManager indexManager = cluster.queryIndexes();

indexManager.createPrimaryIndex("users", createPrimaryQueryIndexOptions().deferred(true));
indexManager.createIndex("users", "ix_name", Collections.singletonList("name"), createQueryIndexOptions().deferred(true));
indexManager.createIndex("users", "ix_email", Collections.singletonList("email"), createQueryIndexOptions().deferred(true));
indexManager.buildDeferredIndexes("users");
indexManager.watchIndexes("users", Arrays.asList("ix_name", "ix_email"), Duration.ofMinutes(5));
----


// Index Consistency
include::6.5@sdk:shared:partial$n1ql-queries.adoc[tag=index-consistency]

The following options are available:

include::6.5@server:learn:page$services-and-indexes/indexes/index-replication.adoc[tag=scan_consistency]

Consider the following snippet:

[source,java]
----
String id = "user::" + UUID.randomUUID().toString();
collection.insert(
  id,
  JsonObject.create().put("value", true)
);

cluster.query(
  "select * from bucket where META().id = $id", 
  queryOptions()
    .parameters(JsonObject.create().put("id", id))
);
----

The above query may not return the newly inserted document because it has not yet been indexed.
The query is issued immediately after document creation, and in this case the query engine may process the query before the index has been updated.

If the above code is modified to use _REQUEST_PLUS_, query processing will wait until all updates have been processed and recalculated into the index from the point in time the query was received:

[source,java]
----
cluster.query(
  "select * from bucket where META().id = $id",
  queryOptions()
    .parameters(JsonObject.create().put("id", id))
    .scanConsistency(QueryScanConsistency.REQUEST_PLUS)
);
----

This gives the application developer more control over the balance between performance (latency) and consistency,
and allows optimization on a case-by-case basis.
