= Couchbase Java SDK 3.1
:page-type: landing-page
:page-layout: landing-page-top-level-sdk
:page-role: tiles
:!sectids:
// :page-aliases: ROOT:dotjavanet-sdk.sdoc


++++
<div class="card-row two-column-row">
++++


[.column]
====== {empty}
[.content]
The Couchbase Java client allow Java applications to access a Couchbase cluster. 
It offers synchronous APIs as well as reactive and asynchronous equivalents to maximize flexibility and performance.

[.column]
[.content]
[source,java]
----
MutationResult result = collection.mutateIn(
    "airport_1254",
    Collections.singletonList(MutateInSpec.upsert("foo", "bar")),
    mutateInOptions().durability(DurabilityLevel.MAJORITY)
);
----

++++
</div>
++++



[.column]
====== {empty}

== Couchbase Java SDK 3.1

++++
<div class="card-row three-column-row">
++++


[.column]
====== {empty}
.Getting Started

[.content]
* Dive right in with a xref:start-using-sdk.adoc[quick install and Hello World].
* Try out our xref:sample-application.adoc[Travel Sample Application].
* Take a look at the xref:howtos:working-with-collections.adoc[developer preview of Collections].
////
[]
[source,xml]
----
<dependencies>
    <dependency>
        <groupId>com.couchbase.client</groupId>
        <artifactId>java-client</artifactId>
        <version>3.1.5</version>
    </dependency>
</dependencies>
----
////

[.column]
====== {empty}
.Practical Howto Docs

[.content]
Connect to our services -- xref:howtos:kv-operations.adoc[data (KV)]; 
xref:howtos:n1ql-queries-with-sdk.adoc[Query]; 
xref:howtos:full-text-searching-with-sdk.adoc[Search]; 
xref:howtos:analytics-using-sdk.adoc[Analytics]; 
xref:howtos:view-queries-with-sdk.adoc[Views] -- 
and the xref:howtos:subdocument-operations.adoc[Sub-Document API].

[.column]
====== {empty}
.Reference Guides

[.content]
The documentation supplements the practical Howto docs with references and xref:concept-docs:concepts.adoc[concept guides], for those who prefer a broader understanding before diving in and coding.

https://docs.couchbase.com/sdk-api/couchbase-java-client/[API Docs^]


[.column]
====== {empty}
.What's Hot?

[.content]
The Couchbase Java SDK 3.0 is a complete rewrite of the 2.x API, providing a simpler surface area and adding support for future Couchbase Server features like Collections and Scopes (available in Couchbase Server 6.5 and 6.6 as a developer preview). 
The (reactive) API also migrated from RxJava to Reactor, along with other improvements to performance, logging, debugging and timeout troubleshooting.

Introducing xref:howtos:distributed-acid-transactions-from-the-sdk.adoc[Distributed ACID Transactions from the Java SDK].

[.column]
====== {empty}
.About

[.content]
Those useful nuts-and-bolts guides to 
xref:project-docs:compatibility.adoc[compatibility tables]; 
xref:project-docs:sdk-release-notes.adoc[release notes]; 
xref:project-docs:get-involved.adoc[contribution guide]; and the 
xref:project-docs:migrating-sdk-code-to-3.n.adoc[migration guide] for moving to the 3.0 API.

[.column]
====== {empty}
.Community

[.content]
For community help, visit the https://forums.couchbase.com/c/java-sdk/5[Couchbase forums^].
The Java SDK can be combined with many other projects in the broader Java and JVM ecosystem and beyond.
This includes xref:project-docs:compatibility.adoc#spring-compat[Spring Data] and xref:spark-connector::getting-started.adoc[Spark].
//  -- in the https://blog.couchbase.com/[Couchbase Blog^] there are examples covering everything from ????
[]
xref:project-docs:third-party-integrations.adoc[Integrations & Ecosystem]; 

++++
</div>
++++
