= Couchbase Java SDK 3.2
:page-type: landing-page
:page-layout: landing-page-top-level-sdk
:page-role: tiles
:!sectids:


++++
<div class="card-row two-column-row">
++++


[.column]
====== {empty}
[.content]
The Couchbase Java client allows Java applications to access a Couchbase cluster.
It offers synchronous APIs as well as reactive and asynchronous equivalents to maximize flexibility and performance.

[.column]
[.content]
[source,java]
----
include::hello-world:example$Overview.java[tag=overview,indent=0]
----

++++
</div>
++++



[.column]
====== {empty}

== Couchbase Java SDK 3.2

++++
<div class="card-row three-column-row">
++++


[.column]
====== {empty}
.Getting Started

[.content]
* Dive right in with a xref:start-using-sdk.adoc[quick install and Hello World].
* Try out our xref:sample-application.adoc[Travel Sample Application].
* Take a look at the xref:howtos:working-with-collections.adoc[Collections feature].
////
[]
[source,xml]
----
<dependencies>
    <dependency>
        <groupId>com.couchbase.client</groupId>
        <artifactId>java-client</artifactId>
        <version>3.1.6</version>
    </dependency>
</dependencies>
----
////

[.column]
====== {empty}
.Practical Howto Docs

[.content]
Connect to our services -- xref:howtos:kv-operations.adoc[data (KV)]; 
xref:howtos:n1ql-queries-with-sdk.adoc[Query]; 
xref:howtos:full-text-searching-with-sdk.adoc[Search]; 
xref:howtos:analytics-using-sdk.adoc[Analytics]; 
xref:howtos:view-queries-with-sdk.adoc[Views] -- 
and the xref:howtos:subdocument-operations.adoc[Sub-Document API].

[.column]
====== {empty}
.Reference Guides

[.content]
The documentation supplements the practical Howto docs with references and xref:concept-docs:concepts.adoc[concept guides], for those who prefer a broader understanding before diving in and coding.

https://docs.couchbase.com/sdk-api/couchbase-java-client/[API Docs^]


[.column]
====== {empty}
.What's Hot?

[.content]
The Couchbase Java SDK 3.x is a complete rewrite of the 2.x API, providing a simpler surface area and adding support for Couchbase Server features like Collections and Scopes (available in Couchbase Server 7.0).
The (reactive) API also migrated from RxJava to Reactor, along with other improvements to performance, logging, debugging and timeout troubleshooting.

Introducing xref:howtos:distributed-acid-transactions-from-the-sdk.adoc[Distributed ACID Transactions from the Java SDK].

[.column]
====== {empty}
.About

[.content]
Those useful nuts-and-bolts guides to 
xref:project-docs:compatibility.adoc[compatibility tables]; 
xref:project-docs:sdk-release-notes.adoc[release notes]; 
xref:project-docs:get-involved.adoc[contribution guide]; and the 
xref:project-docs:migrating-sdk-code-to-3.n.adoc[migration guide] for moving to the 3.x API.

[.column]
====== {empty}
.Community

[.content]
For community help, visit the https://forums.couchbase.com/c/java-sdk/5[Couchbase forums^].
The Java SDK can be combined with many other projects in the broader Java and JVM ecosystem and beyond.
This includes xref:project-docs:compatibility.adoc#spring-compat[Spring Data] and xref:spark-connector::getting-started.adoc[Spark].
//  -- in the https://blog.couchbase.com/[Couchbase Blog^] there are examples covering everything from ????
[]
xref:project-docs:third-party-integrations.adoc[Integrations & Ecosystem]; 

++++
</div>
++++
