= Start Using the Java SDK
:description: A quick start guide to get you up and running with Couchbase and the Java SDK.
:page-partial:
:page-aliases: ROOT:getting-started,ROOT:start-using,ROOT:hello-couchbase,ROOT:start-using-sdk,ROOT:java-intro,ROOT:tutorial
:page-toclevels: 2
:page-pagination: next
:page-topic-type: tutorial

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}

The Couchbase Java client allows applications to access a Couchbase cluster.
It offers synchronous APIs as well as reactive and asynchronous equivalents to maximize flexibility and performance.

In this guide, you will learn:

* How to xref:connect[connect to Couchbase Capella or Couchbase Server].

* How to xref:add-and-retrieve-documents[add and retrieve Documents].

* How to xref:sql-lookup[lookup documents] with the {sqlpp_url}[{sqlpp} (formerly N1QL)] query language.

== Hello Couchbase

We will go through the code sample step by step, but for those in a hurry, here's the complete code:

[{tabs}]
==== 
Couchbase Capella Sample::
+
--
If you are connecting to https://docs.couchbase.com/cloud/index.html[Couchbase Capella], you'll need to know the endpoint address, as well as a username and password.

This example requires the Travel Sample Bucket.
The Couchbase Capella free tier version comes with this bucket, and its Query indexes, loaded and ready.

[source,java]
----
include::devguide:example$StartUsingCapella.java[tag=cloud-connect,indent=0]
----
--

Local Couchbase Server::
+
--
Before running this example, you will need to install the Travel Sample Bucket
using either the xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-ui[Web interface]
or the xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-cli[command line].

[source.try-it,java]
----
include::example$StartUsing.java[tags=start-using,indent=0]
----
--
====

== Quick Installation

We recommend running the latest Java LTS version (i.e. at the time of writing JDK 21) with the highest patch version available.
// Other supported Java versions will work, too.
Couchbase publishes all stable artifacts to https://central.sonatype.com/namespace/com.couchbase.client[Maven Central].

The latest version (as of January 2024) is https://central.sonatype.com/artifact/com.couchbase.client/java-client/3.5.3/jar[3.5.3].

You can use your favorite dependency management tool to install the SDK.

[{tabs}] 
==== 
Maven::
+
--
[source,xml]
----
<dependencies>
    <dependency>
        <groupId>com.couchbase.client</groupId>
        <artifactId>java-client</artifactId>
        <version>3.5.3</version>
    </dependency>
</dependencies>
----
--

Gradle::
+
--
[source,groovy]
----
implementation 'com.couchbase.client:java-client:3.5.3'
----
--
====

See the xref:project-docs:sdk-full-installation.adoc[installation page] for more detailed instructions.


== Prerequisites

The following code samples assume:

[{tabs}]
====
Couchbase Capella::
+
--
* You have signed up to https://cloud.couchbase.com/sign-up[Couchbase Capella].

* You have created your own bucket, or loaded the Travel Sample dataset.
Note, the Travel Sample dataset is installed automatically when deploying a Capella free tier cluster.

* A user is created with permissions to access the cluster (at least Application Access permissions).
See the xref:cloud:get-started:cluster-and-data.adoc#credentials[Capella connection page] for more details.

IMPORTANT: Couchbase Capella uses xref:cloud:organizations:organization-projects-overview.adoc[Roles] to control user access to cluster resources.
For the purposes of this guide, you can use the *Organization Owner* role automatically assigned to your account during installation of the Capella cluster.
In a production scenario, we strongly recommend setting up users with more granular access roles as a best practice.
--

Local Couchbase Server::
+
--
* xref:{version-server}@server:getting-started/do-a-quick-install.adoc[Couchbase Server] is installed and accessible locally.

* You have created your own bucket, or loaded the Travel Sample dataset using the xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-ui[Web interface].

* A user is created with permissions to access your cluster (at least Application Access permissions).
See xref:{version-server}@server:manage:manage-security/manage-users-and-roles.adoc[Manage Users, Groups and Roles] for more details.

IMPORTANT: Couchbase Server uses xref:{version-server}@server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
In this guide we suggest using the *Full Admin* role created during setup of your local Couchbase Server cluster.
For production client code, you will want to use more appropriate, restrictive settings.
--
====

== Step by Step

Here are all the imports needed to run the sample code:

[source,java]
----
include::devguide:example$StartUsingCapella.java[tags=imports,indent=0]
----

If you haven't already, create an empty class and add a `main()` method.

[source, java]
----
public class YourClassName {
    public static void main(String... args) {}
}
----

Make sure to replace `YourClassName` with your own class name.

Above the `main()` method, add the following variables and update them accordingly:

[{tabs}]
====
Couchbase Capella::
+
--
[source,java]
----
include::devguide:example$StartUsingCapella.java[tags=connect-info,indent=0]
----
--

Local Couchbase Server::
+
--

[source,java]
----
include::example$StartUsing.java[tags=connect-info,indent=0]
----
--
====

In the following sections we will populate the `main()` method.

=== Connect

Connect to your cluster by calling the `Cluster.connect()` method and pass it your connection details.
The basic connection details that you’ll need are given below -- for more background information, see xref:howtos:managing-connections.adoc[].

[{tabs}]
==== 
Couchbase Capella::
+
--
From version 3.3, the Java SDK includes Capella’s standard Certificate Authority (CA) certificates by default, so you don't need any additional configuration.
Capella requires TLS, which you can enable by using a connection string that starts with `couchbases://` (note the final 's').

This example shows how to connect and customize the xref:howtos:managing-connections.adoc#cluster-environment[Cluster Environment] settings.

[source,java]
----
include::devguide:example$StartUsingCapella.java[tags=connect-env,indent=0]
----

When accessing Capella from a different Wide Area Network or Availability Zone, you may experience latency issues with the default connection settings.
SDK 3.4 introduces a `wan-development` Configuration Profile, which provides pre-configured timeout settings suitable for working in high latency environments.
Basic usage is shown in the example above, but if you want to learn more see xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments].

CAUTION: The Configuration Profiles feature is currently a xref:java-sdk:project-docs:compatibility.adoc#interface-stability[Volatile API] and may be subject to change.
--

Local Couchbase Server::
+
--
For developing locally on the same machine as Couchbase Server, your connection string can be `couchbase://127.0.0.1` as shown here.
For production deployments, you will want to enable TLS by using `couchbases://` (note the final 's') instead of `couchbase://`.

This example shows how to connect and customize the xref:howtos:managing-connections.adoc#cluster-environment[Cluster Environment] settings.

[source,java]
----
include::example$StartUsing.java[tags=connect-env,indent=0]
----
--
====

[TIP]
.Simpler Connection
====
There's also a simpler version of `Cluster.connect()` for when you don't need to customize the cluster environment:

[source,java]
----
include::devguide:example$SimpleConnect.java[tags=connect-string,indent=0]
----
====

Now that you have a `Cluster`, add this code snippet to access your `Bucket`:

[source,java]
----
include::devguide:example$StartUsingCapella.java[tag=bucket,indent=0]
----



////
[TIP]
.Connecting to Cloud Native Gateway, for Kubernetes or OpenShift
====
Couchbase's large number of ports across the URLs of many services can be proxied by using a `couchbase2://` endpoint as the connection string -- read more on the xref:howtos:managing-connections.adoc#cloud-native-gateway[Connections] page.
====
////




=== Add and Retrieve Documents

The Java SDK supports full integration with the xref:{version-server}@server:learn:data/scopes-and-collections.adoc[Collections] feature introduced in Couchbase Server 7.0.
*Collections* allow documents to be grouped by purpose or theme, according to a specified *Scope*.

Here we refer to the `users` collection within the `tenant_agent_00` scope from the Travel Sample bucket as an example, but you may replace this with your own data.

[source,java]
----
include::devguide:example$StartUsingCapella.java[tag=collection,indent=0]
----

xref:howtos:kv-operations.adoc[Data operations], like storing and retrieving documents, can be done using simple methods on the `Collection` class such as `Collection.get()` and `Collection.upsert()`.

Add the following code to create a new document and retrieve it:

[source,java]
----
include::devguide:example$StartUsingCapella.java[tag=upsert-get,indent=0]
----

=== {sqlpp} Lookup

Couchbase {sqlpp} queries can be performed at the `Cluster` or `Scope` level by invoking `Cluster.query()` or `Scope.query()`.

Cluster level queries require you to specify the fully qualified keyspace each time (e.g. `travel-sample.inventory.airline`).
However, with a Scope level query you only need to specify the Collection name -- which in this case is `airline`:

[source,java]
----
include::devguide:example$StartUsingCapella.java[tag=n1ql-query,indent=0]
----

You can learn more about {sqlpp} queries on the xref:howtos:n1ql-queries-with-sdk.adoc[] page.

=== Execute!

Now that you've completed all the steps, run the example via your IDE or through the command line.
You should expect to see the following output:

[source, console]
----
mike
[{"airline":{"country":"United States","iata":"Q5","name":"40-Mile Air","callsign":"MILE-AIR","icao":"MLA","id":10,"type":"airline"}}]
----

== Next Steps

Now you're up and running, try one of the following:

* Our xref:hello-world:sample-application.adoc[Travel Sample Application] demonstrates all the basics you need to know;
* Explore xref:howtos:kv-operations.adoc[] against a document database;
* Or xref:howtos:n1ql-queries-with-sdk.adoc[] with our {sqlpp} query language;
// * Try longer-running queries with our xref:howtos:analytics-using-sdk.adoc[Analytics Service];
// * A xref:howtos:full-text-searching-with-sdk.adoc[Full Text Search];
* Or read up on xref:concept-docs:data-services.adoc[which service fits your use case].

=== Additional Resources

The API reference is generated for each release and the latest can be found http://docs.couchbase.com/sdk-api/couchbase-java-client/[here].
Older API references are linked from their respective sections in the xref:project-docs:sdk-release-notes.adoc[Release Notes].

Couchbase welcomes community contributions to the Java SDK.
The Java SDK source code is available on https://github.com/couchbaselabs/couchbase-jvm-clients[GitHub].

If you are planning to use Spring Data Couchbase, see the xref:project-docs:compatibility.adoc#spring-compat[notes on version compatibility].

=== Troubleshooting

* Couchbase Server is designed to work in the same WAN or availability zone as the client application.
If you're running the SDK on your laptop against a Capella cluster, see further information on:
** Notes on xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments].
** xref:project-docs:compatibility.adoc#network-requirements[Network Requirements].
** If you have a consumer-grade router which has problems with DNS-SRV records review our xref:howtos:troubleshooting-cloud-connections.adoc#troubleshooting-host-not-found[Troubleshooting Guide].
* Our https://forums.couchbase.com/c/java-sdk/5[community forum] is a great source of help.
