= Install and Start Using the Java SDK with Couchbase Server
:description: Installing the Couchbase Java SDK & a Hello World example program.
:navtitle: Start Using the SDK
:page-partial:
:page-aliases: ROOT:getting-started,ROOT:start-using,ROOT:hello-couchbase,ROOT:start-using-sdk,ROOT:java-intro,ROOT:tutorial

== Hello Couchbase

On this page we show you how to quickly get up and running --  installing the Couchbase Java SDK, and trying out the Hello World code example against Couchbase Capella, or against a local Couchbase cluster.

We will go through the code sample step by step, but for those in a hurry to see it, here it is:

[{tabs}] 
==== 
Couchbase Capella Sample::
+
--
If you are connecting to https://docs.couchbase.com/cloud/index.html[Couchbase Capella], be sure to get the correct endpoint as well as user, password  -- and see the <<cloud-connections, Cloud section>>, below.

[source,java]
----
include::devguide:example$CloudConnect.java[tag=cloud-connect,indent=0]
----

The Couchbase Capella free trial version comes with the Travel Sample Bucket, and its Query indexes, loaded and ready.
--

Local Couchbase Server::
+ 
-- 
[source.try-it,java]
----
include::example$StartUsing.java[tags=start-using,indent=0]
----

As well as the Java SDK (see below), and a running instance of Couchbase Server, you will need to load up the Travel Sample Bucket
using either the xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-ui[Web interface]
or the xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-cli[command line].
--
====


== Quick Installation

We recommend running the latest Java LTS version (i.e. at the time of writing JDK 17) with the highest patch version available.
// Other supported Java versions will work, too.
Couchbase publishes all stable artifacts to https://search.maven.org/search?q=com.couchbase.client[Maven Central].

The latest version (as of April 2022) is https://search.maven.org/artifact/com.couchbase.client/java-client/3.3.0/jar[3.3.0].

You can use your favorite dependency management tool to install the SDK.

[{tabs}] 
==== 
Maven::
+
--
[source,xml]
----
<dependencies>
    <dependency>
        <groupId>com.couchbase.client</groupId>
        <artifactId>java-client</artifactId>
        <version>3.3.0</version>
    </dependency>
</dependencies>
----
--

Gradle::
+
--
[source,groovy]
----
implementation 'com.couchbase.client:java-client:3.3.0'
----
--
====

See the xref:project-docs:sdk-full-installation.adoc[installation page] for more detailed instructions.


== Step by Step

Once you have the Java client installed, open your IDE, and try out the following:

[{tabs}] 
==== 
Couchbase Capella Connection::
+
--
[source,java]
----
include::devguide:example$CloudConnect.java[tags=connect,indent=0]
----

From 3.3, the Java SDK includes Capella's standard certificates by default, so you do not need to additional configuration.
You do need to enable TLS, which can be done by simply using `couchbases:` in the Connection String as in this example.
See xref:howtos:managing-connections.adoc[Managing Connections] for full configuration details.
--
Local Server Connection::
+
--
[source,java]
----
include::example$StartUsing.java[tags=connect,indent=0]
----
--
====

Couchbase uses xref:{version-server}@server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
Here we suggest using the _Full Admin_ role created during setup of   Couchbase Capella, or a local Couchbase Server cluster.

For production client code, you will want to use more appropriate, restrictive settings -- but here we want to get you up and running quickly.
If you're developing client code on the same VM or machine as the Couchbase Server, your connection string can be just `localhost`.

The `Cluster` provides access to cluster-level operations like N1Ql queries, analytics or full-text search. You will also find different management APIs on it.

To access the KV (Key/Value) API or to query views, you need to open a `Bucket`:

[source,java]
----
include::example$StartUsing.java[tag=bucket,indent=0]
----

If you installed the `travel-sample` data bucket, substitute _travel-sample_ for _bucketName_.

The 3.3 SDK supports full integration with the xref:concept-docs:collections.adoc[Collections] feature introduced in Couchbase Server 7.0.
This brings complete support of Collections, allowing Documents to be grouped by purpose or theme, according to a specified _Scope_.
Here we will use the `users` collection within the `tenant_agent_00` scope from `travel-sample` bucket as an example.

[source,java]
----
include::example$StartUsing.java[tag=collection,indent=0]
----

KV Operations are described in detail on the xref:howtos:kv-operations.adoc[KV Operations page], but to get you started the following code creates a new document and then fetches it again, printing the result.

[source,java]
----
include::example$StartUsing.java[tag=upsert-get,indent=0]
----

You can also perform a N1QL query at the cluster level:

[source,java]
----
include::example$StartUsing.java[tag=n1ql-query,indent=0]
----

You can learn more about N1QL queries on the xref:howtos:n1ql-queries-with-sdk.adoc[Query page]. 
Other services (like analytics, search or views) work very similar to the two shown above. 
Please refer to their respective documentation sections to learn more.


== Cloud Connections

For developing on Capella, if you are not working from the same _Availability Zone_, refer to the following:

* Notes on xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments]
* xref:project-docs:compatibility.adoc#network-requirements[Network Requirements]
* If you have a consumer-grade router which has problems with DNS-SRV records review our xref:howtos:troubleshooting-cloud-connections.adoc#troubleshooting-host-not-found[Troubleshooting Guide].


== Additional Resources

The API reference is generated for each release and the latest can be found http://docs.couchbase.com/sdk-api/couchbase-java-client/[here].
Older API references are linked from their respective sections in the xref:project-docs:sdk-release-notes.adoc[Release Notes].

Couchbase welcomes community contributions to the Java SDK.
The Java SDK source code is available on https://github.com/couchbaselabs/couchbase-jvm-clients[GitHub].

If you are planning to use Spring Data Couchbase, see the xref:project-docs:compatibility.adoc#spring-compat[notes on version compatibility].
