= Hello World
:page-aliases: ROOT:getting-started.adoc,ROOT:start-using.adoc,ROOT:hello-couchbase.adoc,ROOT:start-using-sdk.adoc,ROOT:java-intro.adoc,ROOT:tutorial.adoc
:page-toclevels: 3
:description: Install, connect, try. A quick start guide to get you up and running with Couchbase and the {name-sdk}.
:forum-link: https://www.couchbase.com/forums/c/java-sdk/5
:complete-code-include: include::devguide:example$java/StartUsingCapella.java[]
// implementation 'com.couchbase.client:java-client:{sdk_current_version}'
:page-partial:

// Note to editors
// 
// This page pulls in content from
// https://github.com/couchbase/docs-sdk-common/blob/api/3.10/modules/shared/partials/start-using-sdk.adoc
//
// and code samples from
// https://github.com/couchbase/docs-sdk-java/tree/release/3.12/modules/devguide/examples/java
// 
// It can be seen built at
// https://docs.couchbase.com/java-sdk/3.12/hello-world/start-using-sdk.html



[abstract]
{description}

// intro
include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=intro]



// upsert snippet
.Upsert with Replication set to xref:concept-docs:data-durability-acid-transactions.adoc#durable-writes[Majority Durablity]:
[source,java]
----
collection.upsert("my-document", JsonObject.create().put("doc", true),
    upsertOptions().durability(DurabilityLevel.MAJORITY));
----


// intro-upsert
include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=intro-upsert]


// TIP - DEE tutoral & Student record tutorial
include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=other-tutorials]



== Before You Start

include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=before]



// Script the docs!
// Can any of the SDK installations be scripted?



=== Prerequisites

* The Java SDK is tested against LTS versions of OpenJDK --
see the xref:project-docs:compatibility.adoc#jdk-compat[compatibility docs].
+
https://adoptium.net/[OpenJDK {java_latest_lts_version} with HotSpot JVM] is recommended.


// self-managed + Capella pre-reqs
include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=prereq]



== Installation

We recommend running the latest Java LTS version (i.e. at the time of writing JDK {java_latest_lts_version}) with the highest patch version available.
// Other supported Java versions will work, too.
Couchbase publishes all stable artifacts to https://central.sonatype.com/namespace/com.couchbase.client[Maven Central].

The latest version of {sdk_dot_minor}.x is https://central.sonatype.com/artifact/com.couchbase.client/java-client/{sdk_current_version}/jar[{sdk_current_version}].

// tag::quick-install[]
More details of the installation process are in the 
xref:project-docs:sdk-full-installation.adoc[full installation guide].
In most cases, given the above prerequisites, use your favorite dependency management tool to install the SDK.

[{tabs}] 
==== 
Maven::
+
--
[source,xml,subs="+attributes"]
----
<dependencies>
    <dependency>
        <groupId>com.couchbase.client</groupId>
        <artifactId>java-client</artifactId>
        <version>{sdk_current_version}</version>
    </dependency>
</dependencies>
----
--

Gradle::
+
--
[source,groovy,subs="+attributes"]
----
implementation 'com.couchbase.client:java-client:{sdk_current_version}'
----
--
====
// end::quick-install[]


=== IDE Plugins

include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=ide]


=== Grab the Code

include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=complete-code]


== Connect to your Database

Connect to your Couchbase Capella operational cluster (or your local Couchbase Cluster, if you are trying out self-managed Couchbase).


[tabs,sync-group-id="Couchbase Capella|Self-Managed Couchbase Server"]
==== 
Couchbase Capella::
+
--
[source,java]
----
include::devguide:example$java/StartUsingCapella.java[tags=connect,indent=0]
----
--

Self-Managed Couchbase Server::
+
--

[source,java]
----
include::devguide:example$java/StartUsing.java[tags="connect-info",indent=0]
----
[source,java]
----
include::devguide:example$java/StartUsing.java[tags="connect-env",indent=0]
----
--

Cloud Native Gateway (CNG)::
+
--
Couchbase's large number of ports across the URLs of many services can be proxied by using a `couchbase2://` endpoint as the connection string --
currently only compatible with recent versions of xref:operator:ROOT:concept-cloud-native-gateway.adoc[Couchbase Autonomous Operator]:

[source,java]
----
Cluster cluster = Cluster.connect(
  "couchbase2://10.12.14.16",
  ClusterOptions
    .create(username, password)
    .environment(env)
)
----

Read more on the xref:howtos:managing-connections.adoc#cloud-native-gateway[Connections] page.
--

Quarkus::
+
--
Our  xref:quarkus-extension:ROOT:overview.adoc[Couchbase Quarkus Java Extension docs] cover installing and connecting with the Quarkus extension in detail,
but if you already have Quarkus installed and a project ready (with `quarkus-couchbase` in your `pom.xml` or `build.gradle`),
then your `src/main/resources/application.properties` file needs to contain:

[source,properties]
----
quarkus.couchbase.connection-string=localhost
quarkus.couchbase.username=username
quarkus.couchbase.password=password
----
--
====

include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=deeper-conn]


The `ClusterEnvironment.Builder` is covered more fully on the xref:ref:client-settings.adoc#the-environment-builder[Client Settings] page.

[TIP]
.Simpler Connection
====
There's also a simpler version of `Cluster.connect()` for when you don't need to customize the cluster environment:
[source,java]
----
include::devguide:example$java/SimpleConnect.java[tags=connect-string,indent=0]
----
====


=== Opening a Bucket

Following successful authentication, open the bucket with:

[source,java]
----
include::devguide:example$java/StartUsingCapella.java[tag=bucket,indent=0]
----



////
client has not yet completed bootstrapping (connecting to the cluster, getting the configuration, connecting to the nodes).
////


`waitUntilReady` is an optional call,
but it is good practice to use it.
Opening resources such as buckets is asynchronous --
that is, the `cluster.bucket` call returns immediately and proceeds in the background.
`waitUntilReady` ensures that the bucket resource is fully loaded before proceeding.
If not present, then the first key-value (KV) operation on the bucket will wait for it to be ready.
As with the earlier `Cluster.connect`, we use `.get` on the result here for simplicity.

*Collections* allow documents to be grouped by purpose or theme, according to a specified *scope* -- see data modeling, <<data-modeling,below>>.
Here we will use the `airport` collection within the `inventory` scope from `travel-sample` bucket as an example.

[source,java]
----
include::devguide:example$java/StartUsingCapella.java[tag=collection,indent=0]
----


== Create, Read, Update, Delete

include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=crud]


=== JSON

We'll create a snippet of JSON to work with, using the client's own JSON library,
but you can read about the {name-sdk}'s support for other JSON libraries on the
xref:howtos:json.adoc[] page.

[source,java]
----
include::devguide:example$java/StartUsingCapella.java[tag=json,indent=0]
----

=== Insert (Create) and Upsert

`insert` and `upsert` will both create a new document.
The difference between the two is that if a document with that key already exists, the `insert` operation will fail,
// throwing `DocumentExistsException` --
while the `upsert` operation will succeed, replacing the content.

We need to provide a unique ID as the key, and we'll use a UUID here:

.Creating a new document
[source,java]
----
include::devguide:example$java/StartUsingCapella.java[tag=upsert,indent=0]
----

=== Get (Read)

The `get` method reads a document from a collection.
// If the collection does not have a document with this ID, the `get` method also throws `DocumentNotFoundException`.

Wrapping the method in a `try` / `catch` is a good way to handle exceptions:

[source,java]
----
include::devguide:example$java/StartUsingCapella.java[tag=get,indent=0]
----

////
Here we're fetching the value for the key `docId`,
converting that value to a `JsonObjectSafe`
(a simple wrapper around `JsonObject` that returns `Try` results -- see
xref:howtos:json.adoc#error-handling-and-jsonobjectsafe[JsonObjectSafe] for details),
and then accessing the value of the *status* key as a String.
////

////
==== Better Error Handling

All three of these operations could fail, so there's quite a lot of error handling code here to do something quite simple.
One way to improve on this is by using `flatMap`, like this:

[source,java]
----
include::devguide:example$java/StartUsingCapella.java[tag=get-map,indent=0]
----

Alternatively, you can use a for-comprehension, like so:

[source,java]
----
include::devguide:example$java/StartUsingCapella.java[tag=get-for,indent=0]
----

Either of these methods will stop on the first failed operation.  So the final returned `Try` contains either 
a) `Success` and the result of the final operation, indicating that everything was successful, or 
b) `Failure` with the error returned by the first failing operation.
////

=== Replace (Update) and Overloads

////
You'll notice that most operations in the Scala SDK have two overloads.
One will take an Options builder, which provides all possible options that operation takes.
For instance:
////

.The replace method updates the value of an existing document
[source,java]
----
include::devguide:example$java/StartUsingCapella.java[tag=replace-options,indent=0]
----

////
These options blocks are implemented as Scala case classes:
they are immutable data objects that return a copy of themselves on each change.

The other overload is provided purely for convenience.
It takes named arguments instead of an Options object, and provides only the most commonly used options:

[source,java]
----
include::devguide:example$java/StartUsingCapella.java[tag=replace-named,indent=0]
----
////

CAUTION: When you replace a document, it's usually good practice to use xref:howtos:kv-operations.adoc#optimistic-locking[optimistic locking].
Otherwise, changes might get lost if two people change the same document at the same time.

=== Remove (Delete)

The remove method deletes a document from a collection:

[source,java]
----
try {
  collection.remove("my-document");
} catch (DocumentNotFoundException ex) {
  System.out.println("Document did not exist when trying to remove");
}
----

Like `replace`, `remove` also optionally takes the xref:howtos:kv-operations.adoc#what-is-cas[CAS value] if you want to make sure you are only removing the document if it hasn’t changed since you last fetched it.


== Data Modeling

include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=data-model]



== What Next?

////
Query and KV -
both
- but different emphasis on modelling objects....
////


include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=what-next]
