= Install and Start Using the Java SDK with Couchbase Server
:navtitle: Start Using the SDK

[abstract]

The Couchbase Java SDK allows Java applications to access a Couchbase cluster. It offers traditional synchronous APIs as well as reactive and asynchronous APIs to maximize flexibility and performance.

WARNING: These pages cover the first _Developer Preview_ of the Couchbase Java SDK 3.0 (DP1).
As such they are likely to change without notice.
The DP1 code _should not_ be used in production.

== Installing the SDK

The SDK requires Java 8 or later to be installed, earlier versions will not work. Most of the flavors available will do, although we might only provide support for OpenJDK and Oracle JDK going forward.

You can use your favorite dependency management tool to install the SDK. The following snippet shows how to do it with maven.

[source,xml]
----
<dependency>
    <groupId>com.couchbase.client</groupId>
    <artifactId>java-client</artifactId>
    <version>3.0.0-dp1</version>
</dependency>
----

== Hello Couchbase

Once you have the Java client installed, open your IDE, and try out the following:

[source,java]
----
Cluster cluster = Cluster.connect("localhost", "username", "password");
----

Couchbase uses xref:server:learn/security:roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
Here we will use the _Full Admin_ role created during installation of the Couchbase Data Platform.
For production client code, you will want to use xref:3.0dp1@net-sdk:howtos:managing-connections.adoc#rbac[more appropriate, restrictive settings], but here we want to get you up and running quickly.
If you're developing client code on the same VM or machine as the Couchbase Server, your URI can be _localhost_.

Connection to the cluster is initialized by

[source,java]
----
// get a bucket reference
Bucket bucket = cluster.bucket("bucket-name");
----

If you installed the travel sample data bucket, substitute _travel-sample_ for _bucket-name_.

[source,java]
----
// get a collection reference
Collection collection = bucket.defaultCollection();
----

The 3.0 SDK is ready for the introduction of xref:#[Collections] in an upcoming release of the Couchbase Data Platform.
The latest release, Mad Hatter, brings a limited _Developer Preview_ of Collections, allowing Documents to be grouped by purpose or theme, according to specified _Scope_.
Here we will use the `DefaultCollection`, which covers the whole Bucket.

[source,java]
----
// Upsert Document
MutationResult upsertResult = collection.upsert(
    "my-document", 
    JsonObject.create().put("name", "mike")
);

// Get Document
Optional<GetResult> getResult = collection.get("my-document");
----

KV Operations are described in detail on the xref:howtos:kv-operations.adoc[KV Operations page].
Now that you know the basics, you may wish to go straight to that page.
// -- or first see a complete worked example of using the Couchbase Java client, our xref:3.0dp1@sample-application.adoc[Travel Sample Application].

== Additional Resources

The API reference is generated for each release and can be found xref:http://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.0/[here].

// xref:migrating-sdk-code-to-3.n.adoc[The Migrating from SDK2 to 3 page] highlights the main differences to be aware of when migrating your code.

Couchbase welcomes community contributions to the Java SDK.
The Java SDK source code is available on xref:https://github.com/couchbase/couchbase-java-client[GitHub].
