name: Test Code Samples (Dev)

on:
  push:
    branches: [ release/3.* ]

env:
  REGISTRY: registry.gitlab.com/cb-vanilla/server
  CB_EDITION: 7.0.0
  CB_BUILD: 5295

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      working-directory:
        ./modules

    steps:
      - name: Checkout actions
        uses: actions/checkout@v2

      # Because the job is a "required" status check, GitHub will block merging
      # if the file filters don't apply to the changeset.
      # We use this Github action to skip these steps when the changes made don't match the required
      # file filters. By doing this the status check can be marked as "successful" and users can merge the PR.
      # See https://github.community/t/feature-request-conditional-required-checks/16761/23 for some background.
      - name: Check file changes
        uses: getsentry/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/workflows/file-filters.yml

      - name: Docker Login
        if: steps.changes.outputs.filters == 'true'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PSWD }}

      - name: Build Couchbase Docker image
        if: steps.changes.outputs.filters == 'true'
        run: CB_EDITION=${{ env.REGISTRY }}:${{ env.CB_EDITION }} CB_BUILD=${{ env.CB_BUILD }} make cb-build
        working-directory: ${{ env.working-directory }}

      - name: Run Couchbase Server+SDK container
        if: steps.changes.outputs.filters == 'true'
        run: make cb-start
        working-directory: ${{ env.working-directory }}

      - name: Test code samples
        if: steps.changes.outputs.filters == 'true'
        run: make tests
        working-directory: ${{ env.working-directory }}

      - name: Cleanup
        if: steps.changes.outputs.filters == 'true'
        run: make cb-stop
        working-directory: ${{ env.working-directory }}

      - name: Notify slack on failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Docs Bot Automation
          fields: repo,workflow,job,commit,author
          mention: here
          if_mention: failure
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
